thin-edge/thin-edge.io

.github/workflows/hosted-post-merge_version_update.yml, release.toml
This will automatically bump version of all crates in the workspace by patch, create tag with `crate_name-x.x.x` and push it back to the main.
This will be triggered only on merged pull request to main.
TODO: Bump version of only the changed crate.
=> [CIT-308] Automate versioning

.github/workflows/hosted-post-merge_version_update.yml, release.toml
This will create single commit for each version bump instead of for each crate.
=> [CIT-308] Create single commit when versioning

ci/ci_smoke_test.sh, ci/roundtrip_local_to_c8y.py, common/mqtt_client/examples/sawtooth_publisher.rs
This will fix the integration test for the self-hosted rpi (after manual intervention).
There is also a slight extension to the sawtooth publisher.
This PR is identical to https://github.com/thin-edge/thin-edge.io/pull/129 it needed re-creation after the switch to the public
=> Adopt user model and timezone for integration-test 2

Cargo.lock, Cargo.toml, tedge/Cargo.toml, tedge_config/Cargo.toml, tedge_config/src/config_setting.rs, tedge_config/src/error.rs, tedge_config/src/lib.rs, tedge_config/src/models/connect_url.rs, tedge_config/src/models/mod.rs, tedge_config/src/settings.rs, tedge_config/src/tedge_config.rs, tedge_config/src/tedge_config_dto.rs, tedge_config/src/tedge_config_location.rs, tedge_config/src/tedge_config_repository.rs, tedge_config/tests/test_tedge_config.rs
- Move configuration into `tedge_config` crate.
- Add `ConfigSetting` trait. Each "thing" that we want to make
configurable will have it's own struct-type. For example `struct
DeviceIdSetting` or `C8yUrlSetting`.
- The `ConfigSetting` trait does not provide any means of how to
read/write/unset a configuration setting. It only provides the key,
description and the value type of the setting, but no implementation. It's just "meta-data".
- Use trait `ConfigSettingAccessor` to implemenent `query`, `update` and
`unset`. TODO: rename to `ConfigSettingAccess`, `ConfigSettingImpl`?
- `TEdgeConfigRepository` implements functionality to read/write a
`TEdgeConfig`. The `TEdgeConfig` struct itself just holds data. Note that it wraps around `TEdgeConfigDto` to make a clear distinction between the type …
=> Refactor TEdge config

ci/ci_smoke_test.sh
Use the certificate uploading feature with a password given as environment variable.
Not an issue but a failing workflow:
https://github.com/thin-edge/thin-edge.io/actions/runs/726331194
=> Auto upload certificate

.github/workflows/integration-test-workflow.yml, ci/roundtrip_local_to_c8y.py, tests/PySys/pysysproject.xml
Improve roundtrip test to be more flexible 
- Add optional command line parameters for size, timeslot size and delay
- Increase c8y page size
- Adopt user model and use sudo
- Add more checks for the c8y response
- Remove timezone management and use UTC instead
=> Improve roundtrip test script

ci/roundtrip_local_to_c8y.py, tests/pytest/test_roundtrip_local_to_c8y.py
With this we switch to timezone-aware timestamps when using thin-edge JSON. When C8y generates the timestamps itself (when we publish via SmartREST), there is still a Z appended - we just replace that with +00:00 to use the utc timestamps.
Since there is again a plus sign in the code that needs to be encoded, we rely on the requests package to do that.
In addition, some unit-tests with pytest were added to ensure that timestamp validation works right.
- [] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
=> Hotfix after switch to timezone aware timestamps

README.md
Add status badges for workflows in the repository
=> Add status badges for repository workflows

tests/PySys/smoketest_smartrest_400_samples_20ms/run.py
Actually use 20ms delay in the test named with 20ms delay.
Extend time slot to download values from c8y from 20s to 30s (35s is heuristic).
=> [CIT-279] Fix smartrest system-test to 20ms 

.github/workflows/commit-workflow.yml
This adds a workaround for failing `tarpaulin` build due to change in the latest toolchain (1.52), alternative is to use experimental version of tarpaulin 0.18alpha3.
- [z] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
=> Fix workflow toolchain version

Cargo.lock, Cargo.toml, common/flockfile/Cargo.toml, common/flockfile/src/lib.rs, mapper/tedge_mapper/Cargo.toml, mapper/tedge_mapper/src/main.rs
This introduces crate `flockfile` which allows for only single mapper running on the system.
=> [CIT-293] Add lock to allow only one mapper running

mapper/dm_agent/src/batcher.rs, mapper/dm_agent/src/collectd.rs
If an invalid collectd message is received during batching, it shouldn't result in the batch getting split. The failure should only be logged.
<br/>
=> Avoid message batch split with invalid messages during batching

tests/PySys/mapper_awaits_before_reconnect/run.py, tests/PySys/runtime_start_two_mappers/run.py
Now `tedge-mapper` runs by `tedge_mapper c8y` or `tedge_mapper az`. This change broke the existing system tests. This commit adds the missing argument for `tedge_mapper`.
<br/>
=> Add `c8y` argument for tedge_mapper system tests after merging Azure Mapper

tedge_config/src/tedge_config_dto.rs, tedge_config/tests/test_tedge_config.rs
By this patch, tedge will accept `[azure]` in tedge.toml file.
How it works?
case 1) Read old configs -> [azure] stays in tedge.toml file unless user sets a new az keys.
case 2) Set az.xxx configs -> tedge will overwrite [azure] to [az] in tedge.toml file.
case 3) No old configs -> tedge will write [az] in tedge.toml file.
#265 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> [CIT-391] Accept the old configuration using azure

tedge/src/cli/connect/command.rs, tedge/src/cli/connect/error.rs
Add a timeout for MQTT publish while testing connections to c8y or az.
This PR is just a temporary fix inside the `check_connection` functions as the root of the problem is inside the client in publish method.
The root of the defect lies in `mqtt_client` `publish` method which does wait indefinitely for a connection to a broker. To fix the defect a small change to the API of the method and the client is proposed (details to follow) along …
=> [CIT-392] Add timeout to publish on connection test for c8y and az

tedge/src/cli/connect/cli.rs, tedge/src/cli/connect/command.rs, tedge/src/cli/disconnect/cli.rs, tedge/src/cli/disconnect/disconnect_bridge.rs, tedge/src/cli/disconnect/error.rs, tedge/src/command.rs, tedge/src/main.rs, tedge/src/utils/paths.rs
- This information is already available through `TEdgeConfigLocation`.
- Inject `TEdgeConfigLocation` to commands that depend on this.
- While there, refactor some `String`'s to `PathBuf` and dedup some
other code.
=> Remove use of "build_path_for_sudo_or_user"

tedge_config/src/tedge_config.rs, tedge_config/src/tedge_config_defaults.rs, tedge_config/tests/test_tedge_config.rs
1) I completely forgot to add unit test cases for `az.mapper.timestamp`. Added those tests.
2) Did small refactoring for the key `az.mapper.timestamp`. Basically, the implementation should be the same with `mqtt.port`, however, there was inconsistency whether adding the key to `TEdgeConfigDefaults` struct. I decided to add `az.mappaer.timestamp` to there.
3) Did refactoring the existing unit tests in config. Some tests should be renamed, some tests should be merged to other tests, something was missing. I consulted with @albinsuresh.
<br/>
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> [CIT-408] Add az.mapper.timestamp unit tests and refactoring in config tests

common/json_writer/src/lib.rs, mapper/cumulocity/c8y_translator_lib/src/serializer.rs, mapper/thin_edge_json/src/serialize.rs
* Simplifies the serializers.
* Less room for bugs.
=> Move logic related to JSON separation into JsonWriter

tests/PySys/environments/environment_c8y.py
Always check if c8y bridge is working in system tests.
<br/>
comment
=> Always check if c8y bridge is working

tedge/src/cli/mqtt/publish.rs
* The first call to `has_pending()` would under almost all situations
return `true`, which added a 500ms delay.
* This 500ms delay accumulated and broke integration tests.
* Reduce the sleep to 50ms. This should mitigate breakage.
* The better solution would be to use signals / semaphores.
<br/>
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …
=> Reduce sleep from 500ms to 50ms

tests/PySys/apt-plugin/apt-list-format/run.py
Relaying on the fact that `systemd` is not listed by `apt list --manual-installed` is fragile.
This test has been simply removed, the list feature being tested by the install and remove tests.
<br/>
If this is a relatively large or complex …
=> Remove unstable test

mapper/cumulocity/c8y_translator_lib/src/serializer.rs, mapper/tedge_mapper/src/collectd_mapper/batcher.rs, mapper/tedge_mapper/src/collectd_mapper/monitor.rs, mapper/thin_edge_json/examples/tej_example.rs, mapper/thin_edge_json/src/group.rs, mapper/thin_edge_json/src/json.rs, mapper/thin_edge_json/src/measurement.rs, mapper/thin_edge_json/src/serialize.rs
* Remove FlatMeasurementVisitor in favour of GroupedMeasurementVisitor.
Either one can be implemented by the other. Rename to just MeasurementVisitor.
Grouping semantics (whether or not a group can be reopened for instance) depends on the concrete implementation not on the Visitor trait.
* Split MeasurementGrouper according to separation of concerns principle.
* Prefix visitor methods with "visit_". `serde` visitors use that pattern and generally, methods should name an "action".
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
=> Refactor measurement visitors

tedge/src/cli/certificate/error.rs, tedge_config/src/models/file_path.rs
When creating the certificate and it already exists, the error included:
```
Existing file: FilePath("/etc/tedge/device-certs/tedge-certificate.pem")
```
it's changed to:
```
Existing file: "/etc/tedge/device-certs/tedge-certificate.pem"
```
https://cumulocity.atlassian.net/browse/CIT-437
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> CIE-437: Use Display for the path in the certificate exists message rather than Debug

mapper/tedge_mapper/src/main.rs, tedge/src/cli/certificate/cli.rs, tedge/src/cli/certificate/create.rs, tedge/src/cli/certificate/remove.rs, tedge/src/cli/certificate/show.rs, tedge/src/cli/certificate/upload.rs, tedge/src/cli/config/commands/get.rs, tedge/src/cli/config/commands/list.rs, tedge/src/cli/config/commands/set.rs, tedge/src/cli/config/commands/unset.rs, tedge/src/cli/connect/command.rs, tedge/src/cli/disconnect/disconnect_bridge.rs, tedge/src/cli/mqtt/publish.rs, tedge/src/cli/mqtt/subscribe.rs, tedge/src/command.rs, tedge/src/main.rs
* The proper way is to inject dependencies through `BuildContext` in
`build_command`. There is no need for an `ExecutionContext`.  All
dependencies are now explicitly passed through the command structure.
* While there, convert `Result<T, anyhow::Error>` to just
`anyhow::Result<T>`.
=> Remove ExecutionContext - Inject UserManager where required

Cargo.lock, sm/json_sm/Cargo.toml, sm/json_sm/src/lib.rs, sm/json_sm/src/messages.rs
* Change the type of request ids from usize to string.
* Introduce two constructors per request type:
* `::new()` use nanoid to generate the id of the request
* `::new_with_id()` use the given id.
* The responses are built after a request re-using the request id
<br/>
=> [CIT-506] Use nanoid to generate request ids

.github/workflows/commit-workflow.yml, .github/workflows/hosted-post-merge_version_update.yml, BUILDING.md
=> Bump MSRV to 1.54.0

.github/workflows/commit-workflow.yml
Make the workflow (temporarily) continue even when tarpaulin fails.
Without that we have four failing tests that fail in tarpaulin but not in cargo test.
https://cumulocity.atlassian.net/browse/CIT-551
=> Make the workflow (temporarily) continue even when tarpaulin fails

tedge/src/cli/mqtt/error.rs, tedge/src/cli/mqtt/publish.rs, tedge/src/cli/mqtt/subscribe.rs, tests/PySys/local_mqtt_pub_fail/local_mqtt_pub_fail_qos0/run.py, tests/PySys/local_mqtt_pub_fail/local_mqtt_pub_fail_qos1/run.py, tests/PySys/local_mqtt_pub_fail/local_mqtt_pub_fail_qos2/run.py
* On error, `tedge mqtt pub` must return an exit code of 1.
* This is a fix of an error introduced by https://github.com/thin-edge/thin-edge.io/pull/418.
* Some tests have also been fixed : the were triggering a systemic error independent of the MQTT errors under test.
<br/>
=> Fix the exit status of `tedge mqtt pub` on error

Cargo.lock, Cargo.toml, mapper/cumulocity/c8y_smartrest/Cargo.toml, mapper/cumulocity/c8y_smartrest/src/error.rs, mapper/cumulocity/c8y_smartrest/src/lib.rs, mapper/cumulocity/c8y_smartrest/src/smartrest_deserializer.rs, mapper/cumulocity/c8y_smartrest/src/smartrest_serializer.rs, mapper/tedge_mapper/Cargo.toml, mapper/tedge_mapper/src/sm_c8y_mapper/error.rs, mapper/tedge_mapper/src/sm_c8y_mapper/mapper.rs, mapper/tedge_mapper/src/sm_c8y_mapper/mod.rs
This moves c8y_smartrest module from mapper to a separate.
This is part of `CIT-571` work and PR as `get_jwt_token` is now also required to be used in `tedge_agent` and smartrest parsing is required to use that function.
=> [CIT-571] Move smartrest to separate crate

.github/workflows/integration-test-workflow.yml
Turns out that we are not always disconnected when we start a test run.
Why we are still connected is another question, that we need to solve.
This PR adds a tedge disconnect for c8y and az in the integration test.
<br/>
=> Bugfix: Always disconnect before starting an integration test

.github/workflows/integration-test-workflow.yml
Stop the collectd mapper before we de-install tedge.
<br/>
=> Stop the collectd mapper before we deinstall tedge

.github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml
Stop the collect-mapper everywhere and continue if service is not there
<br/>
=> Stop the collect-mapper everywhere and continue if service is not there

common/mqtt_client/tests/mqtt_pub_sub_test.rs
Due to the recent random fails of `mqtt_pub_sub_test`, mark two tests ignored.
- sending_and_receiving_a_message
- subscribing_to_many_topics
Link to #588 
<br/>
=> Ignore mqtt_pub_sub_test since they fail randomly on GitHub Actions

.github/workflows/commit-workflow.yml
Fix #590.
Changes:
- Add steps to print the version of `cargo`; `cargo test` and `cargo build`.
- Add steps to print the version of plugins; all others, e.g. `cargo-msrv`.
- Add a step `cargo install cargo-outdated`. This brings the latest version to the workflow.
Future:
- The step `cargo install cargo-outdated` should be removed. Unfortunately, as of today, without install, the version `0.10.0` of `cargo-outdated` is used. That version panics.
<br/>
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
=> Fix cargo outdated issue temporarily

.github/workflows/commit-workflow-optional.yml, .github/workflows/commit-workflow.yml
Move cargo outdated to optional
<br/>
=> Move cargo outdated to optional

.github/workflows/build-workflow.yml
Temporarily disable build for musl due to cross compilation issue
<br/>
=> Temporarily disable build for musl due to cross compilation issue

.github/workflows/build-workflow.yml, Cargo.lock, mapper/cumulocity/c8y_smartrest/Cargo.toml, mapper/cumulocity/c8y_smartrest/src/smartrest_deserializer.rs
C8y smartrest payload returns datetime as follows:
```shell
c8y result: 2021-10-23T19:03:26+0100
```
However, chrono expects the following datetime:
```shell
rfc3339 expected: 2021-10-23T19:03:26+01:00
```
The only difference being the colon (:) at the end. This fix allows both types of date formats to be parsed.
https://cumulocity.atlassian.net/browse/CIT-612
=> [CIT-697] Allowing colon in datetime deserialisation

.github/workflows/integration-test-workflow.yml
Due to new directory struct the caches have been invalidated, we need to build dummy_plugin for tests.
=> Fix for cargo test features cache being invalidated

.github/workflows/integration-test-workflow.yml
Works manually but not from workflows anymore
Temporarily disable Azure roundrip
<br/>
=> Temporarily disable Azure roundrip

crates/core/tedge_mapper/src/sm_c8y_mapper/json_c8y.rs
Avoid nesting of `url` JSON fragment inside the `url` field of a `c8y_SoftwareList` object.
This is the least invasive change. The "right" fix would have been to have a dedicated struct for software list sent from the device to the cloud that doesn't even have a `url` field as it doesn't make any sense for a device to send a url to the cloud.
(https://github.com/thin-edge/thin-edge.io/issues/640)
=> Fix #640: Fix url field formatting in c8y software list

ci/ci_run_all_plugin_tests.sh, ci/ci_run_all_sm_tests.sh, ci/ci_run_all_tests.sh, tests/PySys/pysysproject.xml
Enable recording for all invocations of PySys.
Avoid to stop when the execution fails (wrap around set +e & -e).
Move report folder, so that it won't be overridden.
This is part one of CIT-623 that only enables reporting but not postprocessing.
https://github.com/thin-edge/thin-edge.io/issues/623
=> [CIT-623] Enable recording for all PySys calls

configuration/debian/tedge_agent/postinst
commands (#683)
Currently, tedge_agent can only use commands defined in /etc/tedge/sm-plugins. 
The restart operation requires it to use `sync` and `init`. This PR is to give access to tedge_agent to use those commands. 
<br/>
=> updated tedge agent post install to have access to sync and init

.github/workflows/integration-test-workflow.yml
After switching the IoT Hub to the new official one, it works and we can remove that continue-on-error.
https://github.com/thin-edge/thin-edge.io/issues/669
=> [CIT-669] Avoid continue on error for Azure smoke test

ci/ci_run_all_plugin_tests.sh
Cherry-picked from CI branch
Set the executable bit for the plugin when we copy it to its destination.
<br/>
=> Bug: Fix permissions of docker plugin

crates/core/tedge_agent/src/agent.rs
There is no point for `tedge_agent` to publish capabilities on start. These messages are used nowhere, corresponding to an idea that has never been fully implemented.
<br/>
=> Remove capabilities messages on tedge agent start

.github/workflows/build-workflow.yml
Observation is that preinst postinst and prerm scripts are missing in the tedge debian package.
Hotfix: Switch back to a older version : 1.29.0. This is at least one version where we know it works.
Furhter investigation necessary!
https://github.com/thin-edge/thin-edge.io/issues/765
=> [#765] Switch to current cargo-deb version

.github/workflows/system-test-offsite.yml
Use correct artifact location for new sawtooth_publisher
Aftermath of: https://github.com/thin-edge/thin-edge.io/pull/778
=> Use correct artifact location for new sawtooth_publisher

crates/common/mqtt_channel/src/config.rs, crates/common/mqtt_channel/src/connection.rs, crates/common/mqtt_channel/src/errors.rs, crates/common/mqtt_channel/src/lib.rs, crates/common/mqtt_channel/src/session.rs, crates/common/mqtt_channel/src/tests.rs, crates/common/mqtt_channel/src/topics.rs
Improve the `mqtt_chanel` crate with two functions:
* `mqtt_channel::init_session(&mqtt_config)` create an MQTT session with the provided session name.
* `mqtt_channel::clear_session(&mqtt_config)` clear an MQTT session previously created.
* Issue: [The sm-c8y and the agent should not expect the other to start first](https://github.com/thin-edge/thin-edge.io/issues/699)
* Related PR: [init/clear agent and mapper sessions](https://github.com/thin-edge/thin-edge.io/pull/797)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …
=> Add functions to init/clear mqtt session

crates/common/download/src/download.rs, crates/core/tedge_mapper/src/az_mapper.rs, crates/core/tedge_mapper/src/c8y_converter.rs, crates/core/tedge_mapper/src/c8y_mapper.rs, crates/core/tedge_mapper/src/converter.rs, crates/core/tedge_mapper/src/main.rs, crates/core/tedge_mapper/src/mapper.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs, crates/core/tedge_mapper/src/tests.rs, crates/tests/mqtt_tests/src/test_mqtt_client.rs, crates/tests/mqtt_tests/src/test_mqtt_server.rs
Detect and reconcile any alarms that the mapper may have missed while it was down, on its restart. The mapper needs to detect any newly raised  alarms as well as the ones that were cleared while it was down.
<br/>
=> [#735] Detect and reconcile alarms updated while mapper was down

crates/common/mqtt_channel/src/connection.rs, crates/common/mqtt_channel/src/errors.rs, crates/common/mqtt_channel/src/session.rs, crates/common/mqtt_channel/src/tests.rs
* Remove useless unsubscribe calls on clear_session
* Improve error handling on connect
* Improve error handling on subscription errors
* There is still a point to clarify with subscription errors on topics name `test`.
* [Code review comment on error handling](https://github.com/thin-edge/thin-edge.io/pull/819#discussion_r799419180)
* [Code review comment on cleared subscriptions](https://github.com/thin-edge/thin-edge.io/pull/819#discussion_r799124260)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
=> Improve MQTT error handling

crates/core/tedge_mapper/src/sm_c8y_mapper/tests.rs, crates/core/tedge_mapper/src/tests.rs, crates/tests/mqtt_tests/Cargo.toml, crates/tests/mqtt_tests/src/lib.rs, crates/tests/mqtt_tests/src/test_mqtt_client.rs, crates/tests/mqtt_tests/src/test_mqtt_server.rs
The motivation is to ease testing with the [`StreamExt`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html) extension
* In the mqtt test helper crate, use [`futures::channel::mpsc`](https://docs.rs/futures/latest/futures/channel/mpsc/index.html) instead of [`tokio::sync::mpsc`](https://docs.rs/tokio/latest/tokio/sync/mpsc/index.html).
If this is a relatively large or complex change, kick off the discussion by explaining …
=> Use `futures` channels instead of `tokio` channels

Cargo.lock, crates/common/certificate/Cargo.toml, crates/common/certificate/src/lib.rs, crates/core/tedge/Cargo.toml
This is third in a series (part 1 #850 and part 2 #851) of changes to remove `chrono` from dependencies.
To replace #629.
Partial fix for #625.
This removes `chrono` in favour of `time ^0.3` in `certificate` and all dependents crates.
Caused by RUSTSEC-2020-0159 - no movement on the issue in the `chrono` crate since ~10.2020
=> Use 'time' instead of 'chrono' due to CVE for certificate and all dependent crates [3/3]

crates/common/json_writer/src/lib.rs
This is part of #825 - my patches to fix the clippy warnings in the `json_writer` crate.
=> Clippy fixes for: json_writer

crates/core/plugin_sm/src/log_file.rs, crates/core/plugin_sm/src/plugin_manager.rs
There's no need in the codebase to convert this to a `&str`. This patch ensures that we return `&Path` and use it appropriately.
~~Please merge this only after squash and rebase requirements have been removed (see the discussion).~~
=> Change return type of LogFile::path to &Path

crates/common/download/src/download.rs
This is part of #825 - my patches to fix the clippy warnings in the `download` crate.
=> Clippy fixes for: download

Cargo.lock, crates/common/batcher/Cargo.toml, crates/common/batcher/src/batch.rs, crates/common/batcher/src/batchable.rs, crates/common/batcher/src/batcher.rs, crates/common/batcher/src/config.rs, crates/common/batcher/src/driver.rs, crates/common/clock/Cargo.toml, crates/common/clock/src/lib.rs, crates/core/c8y_smartrest/src/smartrest_deserializer.rs, crates/core/c8y_translator/Cargo.toml, crates/core/c8y_translator/src/json.rs, crates/core/c8y_translator/src/serializer.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/az_converter.rs, crates/core/tedge_mapper/src/collectd_mapper/batcher.rs, crates/core/tedge_mapper/src/collectd_mapper/collectd.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs, crates/core/thin_edge_json/Cargo.toml, crates/core/thin_edge_json/benches/parsing.rs, crates/core/thin_edge_json/examples/validate.rs, crates/core/thin_edge_json/src/builder.rs, crates/core/thin_edge_json/src/data.rs, crates/core/thin_edge_json/src/group.rs, crates/core/thin_edge_json/src/measurement.rs, crates/core/thin_edge_json/src/parser.rs, crates/core/thin_edge_json/src/serialize.rs, crates/core/thin_edge_json/tests/fixtures/invalid/reject_invalid_timestamp.expected_error, crates/core/thin_edge_json/tests/fixtures/invalid/reject_partial_timestamp.expected_error, crates/core/thin_edge_json/tests/fixtures/invalid/reject_timestamp_missing_time_separator.expected_error
This is first in a series (part 2 #851 part 3 #852) of changes to remove `chrono` from dependencies.
To replace #629.
Partial fix for #625.
This removes `chrono` in favour of `time ^0.3` in `thin-edge-json` and all dependents crates.
Caused by RUSTSEC-2020-0159 - no movement on the issue in the `chrono` crate since ~10.2020
=> Use 'time' instead of 'chrono' due to CVE for thin_edge_json and all dependent crates [1/3]

plugins/tedge_apt_plugin/src/main.rs, plugins/tedge_apt_plugin/src/module_check.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_apt_plugin` crate.
=> Clippy fixes for: tedge_apt_plugin

Cargo.lock, crates/common/clock/Cargo.toml, crates/common/clock/src/lib.rs, crates/common/clock/src/serde/mod.rs, crates/common/clock/src/serde/rfc3339.rs, crates/core/thin_edge_json/Cargo.toml, crates/core/thin_edge_json/src/alarm.rs, crates/core/thin_edge_json/src/event.rs
Minor findings while browsing the source code.
- Remove unneeded dependencies
- Hide `serde` support behind feature flag to reduce dependency creep for consumers that don't need this feature
- Reuse (de-)serialization facilities from the `time`crate (requires v0.3.6)
The `serde` dependencies are now disabled by default and must be enabled explicitly with this feature flag. Alternatively the flag could be enabled by default at your choice. My recommendation is to keep `serde` support optional.
The prefix `with-` was chosen for disambiguation in Cargo.toml where dependencies and features share a single namespace. Just a personal habit, still looking for a consistent and commonly accepted solution across projects. Another option for naming this flag could be by prefixing it with the project …
=> clock: Hide serde support behind feature flag `with-serde`

crates/core/c8y_smartrest/src/smartrest_deserializer.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs
This is part of #825 - my patches to fix the clippy warnings in the `c8y_smartrest` crate.
=> Clippy fixes for: c8y_smartrest

.github/workflows/system-test-offsite.yml, ci/configure_bridge.sh
Fix the name of a GitHub secret (emergency workaround was to temporarily create the secret).
Fix the a misleading echo statement.
[
#835](https://github.com/thin-edge/thin-edge.io/issues/835)
=> [#835] Aftermath: Fix GitHub secret name

Cargo.lock, crates/core/plugin_sm/Cargo.toml, crates/core/plugin_sm/tests/plugin.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/config/cli.rs, crates/core/tedge/src/cli/connect/cli.rs, crates/core/tedge/src/cli/disconnect/cli.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/cli/mqtt/cli.rs, crates/core/tedge/src/command.rs, crates/core/tedge/src/main.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/main.rs, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apama_plugin/src/main.rs, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_apt_plugin/src/main.rs, plugins/tedge_dummy_plugin/Cargo.toml, plugins/tedge_dummy_plugin/src/main.rs
Closes #806 
This is implemented in one patch, as I see very little benefit in splitting this per crate. The changes are absolutely minimal, only replacing each instance of `structopt` with `clap`. No other code is touched.
=> Replace structopt with clap 3

tests/PySys/software_management_end_to_end/environment_sm_management.py
Fix Python method signature.
Will fix test SoftwareManagement.sm_apt_install_remove if rolldice was installed before.
Seems like nobody used the method yet, as the reference to self was missing. 
<br/>
=> Fix method signature

plugins/log_request_plugin/src/smartrest.rs
This is part of #825 - my patches to fix the clippy warnings in the `log_request_plugin` crate.
=> Clippy fixes for: log_request_plugin

crates/common/tedge_utils/src/paths.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/tedge/src/cli/certificate/upload.rs
This patchset removes the `pathbuf_to_string()` helper function, which is only used to convert pathes to strings and then using these strings in APIs that want pathes as arguments :laughing:
=> Remove pathbuf_to_string()

crates/core/c8y_smartrest/src/event.rs, crates/core/thin_edge_json/src/event.rs
Cumulocity-mapper to treat the `message` field as optional in Thin Edge JSON events. When it's not provided, the `event-type` will be substituted as message as well, as Cumulocity mandates a message for events.
<br/>
=> Make message field optional in Thin Edge JSON events

crates/core/c8y_smartrest/src/smartrest_deserializer.rs
Removes the manual cloning of the modules vector.
=> Remove unecessary manual clone

CONTRIBUTING.md
Changes the wording in the CONTRIBUTING file, that we only need one approval right now.
I just found this while browsing over the repository.
=> Fix: We only need one approval right now

Cargo.lock, crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_api/src/json_c8y.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/az/converter.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/core/size_threshold.rs
Cumulocity has a 16K limit for events that can be sent over MQTT. So, if the thin-edge event size is more than that limit, it must be sent via HTTP. This PR implements that switching mechanism based on event payload size.
<br/>
=> [#809] Cumulocity mapper to send large events > 16K size with HTTP

crates/common/tedge_config/src/tedge_config.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_config` crate.
This seems to have slipped in the first iteration.
=> Clippy fixes for: tedge_config

crates/core/tedge/src/cli/mod.rs
Just a small fix I found while browsing the codebase
=> Fix: Remove unused "use"

Cargo.lock, crates/common/certificate/Cargo.toml
Bump zeroize version used by rcgen.
<br/>
=> Fix cargo audit warning: zeroize 1.5.2 is yanked

Cargo.toml
The v2 resolver allows for more fine-grained inclusion of dependency
features. Previously dev-dependency features got merged with 'normal'
dependency features. This may not always be desirable.
For more information see
https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
This should be a non-breaking change as, as far as I could tell no crates had 'hidden' feature dependencies. However, since it is the default since the 2021 edition it makes sense to enable it now so as to reduce potential future workload.
=> Enable Resolve v2 for workspace

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/doc_improvement.md, .github/ISSUE_TEMPLATE/feature_improvement.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
This changes the github issue template and the pull request template so that the notes about what to fill in are HTML comments. For example this section:
```
```
Would still be in the template, but as soon as one creates a issue/PR, it wouldn't be shown anymore, reducing the noise one has to read over when browsing issues/PRs.
I'm not yet 100% positive that the desired effect is applied by this change, but as far as I remember, that's the way it used to be with github templates, am I right @TheNeikos ?
---
**Asking for review from all, as this effects all of us!** Of course I am open to …
=> GitHub templates comments

CONTRIBUTING.md
This patch adds a note about "fixup-commits".
I noticed that we still see some commits that are addressing review comments that could potentially be squashed into other commits before merging a PR.
Right now, this is not yet that much of an issue because these PRs are still squash-merged. As soon as we move fully away from squash merging, these kind of commits can be squashed away by the author of the PR as soon as a PR passes review (and CI of course).
This patch adds to the `CONTRIBUTING` documentation for this to be documented.
This is probably a bit controversial, so I'm opening this as a draft for now, opening up for discussion here. :smiley: :sunny:
=> Add note about fixup commits

.github/workflows/block-fixup-commits.yml
This patch adds a workflow that blocks merging commits that were made with
`git commit --fixup` or `git commit --squash` during the development of
a PR.
For example as happened from https://github.com/thin-edge/thin-edge.io/pull/934 (no offense of course)!
=> Add workflow to block fixup commits

Cargo.lock, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/error.rs
- Closes #937
Fixing error message when the `sm-plugins` directory exists **but** it is empty. 
```shell
mkdir /tmp/sm-plugins
./target/debug/tedge_agent --config-dir /tmp
```
- #937 
=> #937 fixing sm plugins path error message

plugins/tedge_apt_plugin/src/main.rs
This PR addresses the apt plugin exit code when the plugin fails due to no args or wrong args.
`Clap` returns `exit code 2` on failure when there are wrong args, but this has to be `1` as per the plugin specification.
So, we overwrite the exit code to `1`.
<br/>
=> [955] over write the apt plugin exit code

crates/core/tedge_agent/src/agent.rs
- Closes #997
- fixing logs path 
-  this was causing the software list operation to fail with permission denied
#997
=> appending tedge/agent to logs.path key (#997)

.github/workflows/integration-test-workflow.yml
These tests rely on a working tedge apt plugin.
However, in the current integration-test-workflow.yml the plugin is not installed (currently on purpose).
Until the release, I propose to run the tests manually and disable them temporarily to avoid issues in CI.
Afterwards, we should prepare the right environment for the tests afterwards.
Soon after the release should do one of these:
a) Install the plugin in the workflow
b) Move the tests to a test-job where we have tedge installed (yet to be created) (e.g. a integration- or system-test crate)
https://github.com/thin-edge/thin-edge.io/issues/1000
=> Temporarily disable integration tests that need the apt plugin

crates/core/c8y_smartrest/src/operations.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/error.rs
- Closes #983 
- tedge-mapper was previously leaving operations hanging dead in the
cloud if the wrong command path was set inside the template file
in /etc/tedge/operations/<cloud>/operation_name
- this will fix handles the error, (removing the unwrap)
- it also ensures that operation status is updated to executing and
then to failed.
=> fixing panic when wrong command set in template #983

.github/workflows/integration-test-workflow.yml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, plugins/log_request_plugin/Cargo.toml
This PR fixes this [issue](https://github.com/thin-edge/thin-edge.io/runs/5691998305?check_suite_focus=true)
Since the thin-edge Debian package dependency is broken, the packages have to be installed individually rather than with wild card `*.deb`.
Also, for example, the `tedge-mapper` Debian package depends on the `tedge` package. The dependency is defined in the Cargo.toml as below `depends = tedge`.
This will not strictly check the dependency. Because of this `tedge-mapper` Debian package will go ahead and try to copy the artifacts. During that it creates the `/etc/tedge/contrib/collectd/` and copy the `configuration/contrib/collectd/collectd.conf` file.
In this process, it creates the `/etc/tedge` directory as a root instead of as a `tedge` user. This will not allow other packages to …
=> Install individual packages on integration workflow

.github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml
Fix package installation and deinstallation in the integration test workflow.
Probably a side effect of installing collectd on that Pis earlier
<br/>
=> Fix workflows: Add collectd to purge and to install again

tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_packet_threshold_size/run.py
Adjust mqtt message threshhold in test to the value that is actually supported by C8y
<br/>
=> Fix mqtt message threshhold in test

docs/src/supported-platforms.md
The first step to update our supported platform described in https://github.com/thin-edge/thin-edge.io/issues/1024.
To add Raspberry Pi OS 11 (bullseye) as level 2 support.
https://github.com/thin-edge/thin-edge.io/issues/1024
=> Add Raspberry Pi OS 11 to level 2 support

crates/common/tedge_config/src/settings.rs, crates/common/tedge_config/src/tedge_config.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/main.rs
While I was implementing to get the query of `tmp.path`, I got confused by the name `TmpPathDefaultSetting` because the default is `/tmp`, but I use the variable because I don't want to hardcode `/tmp`. I believe that it's wrongly named.
This PR just removes "Default" from 
* TmpPathDefaultSetting
* LogPathDefaultSetting
* RunPathDefaultSetting
Note) SoftwarePluginDefaultSetting should stay as it is, as this is meant to have what the "default" plugin.
<br/>
=> Remove "default" from the name of some tedge config settigs

Cargo.lock, crates/common/logged_command/Cargo.toml, crates/common/logged_command/src/lib.rs, crates/common/logged_command/src/logged_command.rs, crates/core/plugin_sm/Cargo.toml, crates/core/plugin_sm/src/lib.rs, crates/core/plugin_sm/src/plugin.rs
Extract `logged_command` to a crate as it is now used by other components.
<br/>
=> #759 Move 'logged_command' to a crate as it going to be used by other components

Cargo.lock, configuration/contrib/tedge_upgrade/upgrade_tedge_0.6.sh, configuration/debian/tedge/postinst, configuration/debian/tedge/postrm, configuration/debian/tedge_agent/postinst, configuration/debian/tedge_agent/postrm, configuration/debian/tedge_mapper/postinst, configuration/debian/tedge_mapper/postrm, configuration/init/systemd/tedge-agent.service, configuration/init/systemd/tedge-mapper-az.service, configuration/init/systemd/tedge-mapper-c8y.service, configuration/init/systemd/tedge-mapper-collectd.service, crates/common/tedge_users/src/lib.rs, crates/core/c8y_translator/fuzz/Cargo.lock, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, docs/src/howto-guides/002_installation.md
This PR captures code changes for
- Removing the `tedge-agent` and tedge-mapper` users and groups
- Now all the directories and files that are required by the `thin-edge.io` services are owned by `tedge` user.
- The `thin-edge.io services tedge-agent, tedge-mapper az/c8y/collectd` will run under `tedge` user.
<br/>
=> Have a single unix user used for all the thin-edge daemons

.github/workflows/ci_pipeline.yml, ci/ci_run_all_plugin_tests.sh, ci/ci_run_all_sm_tests.sh, ci/ci_run_all_tests.sh, ci/report/build.sh, ci/report/build_local.sh, ci/report/download_workflow_artifact.py, ci/report/final_result.py, ci/report/report_builder.py
Switch to all in one workflow strategy for GitHub Actions.
See  https://github.com/thin-edge/thin-edge.io/issues/1038
Note: Docu is still missing (Runners, configuration, etc)
Note: The configuration of Runners is not finalized yet
**Note: I'll present this in the next arch rampup**
Here is an example how it would look on Michaels CI:
https://github.com/abelikt/thin-edge.io/actions/runs/2108411912
This is the report that is automatically generated from it:
https://abelikt.github.io/thin-edge.io/report-matrix.html
https://github.com/thin-edge/thin-edge.io/issues/1038
comment
=> Switch to all in one workflow strategy for GitHub Actions

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/tedge_mapper/src/core/error.rs
The code changes include checking the `c8y JSON measurement message size`, If the message size exceeds the threshold size, (16K) then it will not be sent to Cumulocity and an error message will be returned.
<br/>
=> Publishing many measurements and series at once to c8y

crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs, crates/core/tedge/src/cli/disconnect/error.rs
Return non zero exit code when one or more service component fails to stop or get disabled during `tedge disconnect` call.
#759
=> #759 tedge disconnect falsely returns exit code 0 when disabling or stopping of a component fails

configuration/debian/tedge/postinst, configuration/debian/tedge/postrm, configuration/debian/tedge/preinst, configuration/debian/tedge_agent/postrm, configuration/debian/tedge_mapper/postrm
- Create `tedge` user in `preinst` script rather than in `postinst` script.
- Remove `tedge` user only during `purge` not on `remove`, because the files/directories created using `tedge` user are deleted only on `purge`.
<br/>
=> tedge preinst script uses tedge user that doesn't exist yet

tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/run.py
- the test was still using tedge-mapper user but #1085 renamed all users to `tedge`
- Closes #1124
=> #1124 runtime_start_two_mappers pysys test fix

.github/workflows/gh-pages.yml
Idea: Select only the html folder and upload it  to the same place as before.
Will not upload the linkcheck folder, but that one seems not to be needed anyway.
Works for me, our uploaded html folder with the docu will stay at the same place:
https://abelikt.github.io/thin-edge.io/html/
https://abelikt.github.io/thin-edge.io/results/report-matrix.html
Fixes: "Some deploy mechanism is overriding our rest results on github pages 1106"
https://github.com/thin-edge/thin-edge.io/issues/1106
=> Fix depoy mechanism for github pages #1106

docs/src/references/c8y-configuration-management.md
Update the reference documentation accordingly to https://github.com/thin-edge/thin-edge.io/pull/1145:
* Optional configuration `type`
* Changes of the notification topic.
* Ownership of new configuration file. 
<br/>
=> Finalize config management reference documentation

ci/ci_smoke_test_c8y.sh, ci/configure_bridge.sh, ci/find_device_id.py, tests/requirements.txt
Increase CI stability by retrying a few times to when retrieving the C8Y ID.
<br/>
//comment
=> Retry when retrieving the C8Y ID fails

plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
Fix the style of `c8y-log-plugin.toml` content style as below.
`files = [
{ type = "software-management", path = "/var/log/tedge/agent/software-*" },
]`
The `toml::toml!()` outputs the content as `[[files]]`. So, to avoid this syntax replace the `toml::toml!` with `format!`.
(https://github.com/thin-edge/thin-edge.io/issues/1209)
=> .toml format for c8y-log-plugin and c8y-configuration-plugin is different

crates/common/tedge_utils/src/fs.rs
This _may_(!!!) solve #1241.
#1241
=> Fix: Flush the file buffer after writing to the file

.github/dependabot.yml
The thin-edge.io project has quite a lot of dependencies - I counted 73
from the current commit, via this very un-scientific method:
```console
cargo tree --depth 1 | \
grep -v "^[a-z]"  | \
grep -v "^$" | \
grep -v "dev-dependencies" | \
cut -d " " -f 2 | \
sort -u | \
wc -l
```
And because they might only get more in the future rather than less,
this patch disables the dependabot pull request limit, letting
dependabot open as many pull requests as necessary to keep our
dependencies up to date.
=> Disable the pull request limit for dependabot

crates/common/clock/Cargo.toml, crates/common/clock/src/lib.rs, crates/common/clock/src/serde/mod.rs, crates/common/clock/src/serde/rfc3339.rs, crates/core/thin_edge_json/Cargo.toml, crates/core/thin_edge_json/src/alarm.rs, crates/core/thin_edge_json/src/event.rs
I found that the "serde" module was only a reexport of the "serde" module of the "time" crate which did not add any further functionality.
Thus, its usage can be replaced by using the "time" crate directly. As the functionality was only used in the "thin_edge_json" crate, and that crate already imports "time", I consider this PR a reduction in code-complexity.
=> Remove "serde" module in "clock" crate

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/pull-request-checks.yml
As actions-rs/toolchain is unmaintained, switch over to dtolnay/rust-toolchain for our workflow implementation.
=> Replace actions-rs/toolchain with dtolnay/rust-toolchain

Cargo.lock, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_utils/Cargo.toml
Removes unused dependencies from `tedge_utils` and `mqtt_channel`.
Followup for #1313
=> Remove unused deps

crates/core/tedge_watchdog/src/dummy_watchdog.rs, crates/core/tedge_watchdog/src/error.rs, crates/core/tedge_watchdog/src/main.rs
Following the discussion in #1278 and as suggested by @albinsuresh:
This patch ensures that the systemd watchdog backend is only used when
building for linux.
Right now, there is no other watchdog implementation. Thus, there is a
"dummy_watchdog" module introduced that does nothing. This might be
removed and replaced by something specific, if we ever build
thin-edge.io for other targets, such as Apple, FreeBSD or others.
---
I'm going to request review by multiple people, so everyone knows about this and has the chance of saying something if this is not the right approach (because we might possibly need more like this in the future).
=> Make systemd watchdog backend only build for linux

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs
With the existing logic, when the `tedge-mapper-c8y` is restarted, the `child/external` device creation message is formed and pushed into the vector even during the sync logic as well, because the sync logic receives messages from `tedge/alarms`.  This will create the devices that were not requested now but were part of the previous requests.
As a fix, Create an `external/child device` only after the alarm messages are synced if the device is not created already.
https://github.com/thin-edge/thin-edge.io/issues/1340
=> Restart of tedge-mapper-c8y is recreating deleted child devices

crates/core/tedge_agent/src/agent.rs
* the log directory configured in tedge config set logs.path
is now used in --init
#1070
=> make log directory configurable during init

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/hosted-post-merge_version_update.yml, .github/workflows/pull-request-checks.yml, .github/workflows/update-tedge-ref-docs.yml, crates/common/mqtt_channel/src/messages.rs
In #1279 we had a brief discussion whether to update rustc in our CI or not.
IMO there's no reason why we shouldn't, so here goes a PR to update rustc in all workflows.
=> Update rustc: 1.58.1 -> 1.63.0

crates/core/tedge_mapper/src/c8y/alarm_converter.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mod.rs
Refactor the `c8y alarms` code and move the `alarms` code to a separate file.
<br/>
=> Move alarms converter code to a separate file

ci/installation_scripts/clean_up_rpi.sh, ci/installation_scripts/install_for_amd64.sh, ci/installation_scripts/install_for_arm.sh
I messed up b3f1da8cf607cb1c6668d30ae1121a19305cf9e9, 12912211adc50d6ea99d4e2d1c4c1bf71a3cb5c0 and c147d91f6aedfcef6574fd105557e6661220ee3d as reported by @PradeepKiruvale in [here](https://github.com/thin-edge/thin-edge.io/commit/a2c58baddcf685cde414fb66847e6e981921d6c7).
This fixes it (hopefully).
@PradeepKiruvale please test these patches whether they fix your issue!
=> Fix install array expansion

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, docs/src/howto-guides/022_c8y_fragments.md
This PR includes the code to create the `/etc/tedge/device` directory when the `tedge-mapper-c8y` is initialized.
It also fixes some issues related to reading the fragment `inventory.json` file from the custom path when config files are stored in the `custom config` direction.
- [x ] Documentation Update (if none of the other choices apply)
https://github.com/thin-edge/thin-edge.io/issues/1365
=> Directory for custom fragments /etc/tedge/device does not exist

Cargo.lock, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/fs_notify.rs, crates/core/tedge_mapper/Cargo.toml, crates/tests/tedge_test_utils/src/fs.rs, plugins/c8y_configuration_plugin/src/main.rs
This PR fixes the issue related to raising the events for the wrong `directory` when  `watching multiple directories`.
Uses the `inotify` fix that helps to extract the exact path on which the event has been raised.
https://github.com/thin-edge/thin-edge.io/issues/1453
=> fs_notify generates events on wrong directory paths

configuration/debian/tedge_agent/postrm, configuration/init/systemd/tedge-agent.service, crates/core/tedge_agent/src/http_rest.rs, docs/src/references/tedge-file-transfer-service.md, plugins/c8y_configuration_plugin/src/main.rs
Change default HTTP port of `tedge-agent` from 80 to 8000 so that it doesn't always have to run as root.
<br/>
=> Closes #1486 Set port 8000 as default HTTP port for tedge-agent

configuration/debian/tedge_agent/postrm, crates/common/tedge_utils/src/file.rs
When `tedge-agent` starts, the `/var/log/tedge/agent` directory is first created as `root` by the `operations_log` manager in `SmAgent::try_new` which is later changed to `tedge` in `SmAgent::init`. This fix makes such ownership changes of existing files possible.
The log directory could have been created as `tedge` at the beginning itself. Avoiding that for now, just to minimize the changes required for this bug fix. This will be fixed properly after the 0.7.6 release.
<br/>
=> File permission API to change ownership of directory even if it already exists

plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/main.rs
=> Issue #1480: Prevent c8y-config-plugin crashing on bad input

Cargo.lock, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/c8y/fragments.rs, crates/core/tedge_mapper/src/c8y/tests.rs
This test was passing because the pipeline did not have tedge installed. But when tedge is installed, locally, the version field defaults to the version of tedge on your system. This tests fixes this issue to use tedge from cargo_bin. Additionally env! is used to get the current version of the binaries, which can be used to compare to tedge --version.
<br/>
=> Fix fragments tests to work with `tedge` installed

configuration/debian/tedge_agent/postinst
`tedge_agent --init` must run as root, introduced by https://github.com/thin-edge/thin-edge.io/commit/fe705ffdf2b18e09492df0ab613a69f8b5bca72f.
However, my commit https://github.com/thin-edge/thin-edge.io/commit/ccf9bf2f626caec5d303980b02432535f5896d66 brought back it to run as `tedge`. This PR fixes it.
#1466
=> Fix --init of tedge_agent run by root

.typos.toml, docs/src/references/c8y-configuration-management.md
Signed-off-by: reubenmiller <reuben.miller@softwareag.com>
* Fix small typo of `tedge` in the Cumulocity Device Configuration Management docs
* Add `typos` rule to automatically detect common `tedge` typo
=> fix tedge typo in docs

design/thin-edge-core.md
Here a proposal for a vision statement for the core of thin-edge. 
The purpose of this statement is to set a frame around the discussions on what has been [our vision so far](https://github.com/thin-edge/thin-edge.io/tree/main/docs/src/architecture), [how to improve it](https://github.com/thin-edge/thin-edge.io/discussions/801) and the [direction proposed by @TheNeikos and @matthiasbeyer](https://github.com/thin-edge/thin-edge.io/pull/948).
The focus is on what and why, letting the how to other discussions.
* Up to now, the focus has been set on flexibility and openness with a large set of features. Do we have to move to a smaller and statically defined core? Where is the balance point?
* What are the criteria to decide for an approach …
=> Vision statement for thin-edge core

crates/tests/mqtt_tests/src/test_mqtt_server.rs
Increase the `connection_timeout_ms` setting of the `rumqttd` broker. 
Before it was set to `1ms` as observed that the tests were failing because the `rumqttd` broker was closing the client connection if the connection was idle for 1ms.
Now increased it to `10ms` the tests are not failing anymore. Now the broker will close the client connection only if the connection is idle for 10ms.
Ran the tests in the loop for 500 iterations, and found that the tests are not failing anymore.
<br/>
=> Sporadic test failures in c8y tests

crates/common/tedge_config/src/tedge_config_defaults.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/restart_operation_handler.rs
tedge_agent creates `tedge_agent_restart` file in order to keep the timestamp of restart operation executed. However, the file was supposed to be created /run/tedge_agent directory, which is created by systemd.
In addition, to create a file directly under /run requires root.
To remove the implicit dependency on systemd, change the directory to create the file from /run/tedge_agent to /tmp.
#975
=> Change the restart temporary file location from /run/tedge_agent to /tmp

crates/core/tedge_agent/src/error.rs
Fix the following compiler warning about a format string used in an error for `tedge_agent`:
```
Compiling tedge_agent v0.8.1 (/workspaces/fork/crates/core/tedge_agent)
warning: named argument `timestamp` is not used by name
--> crates/core/tedge_agent/src/error.rs:50:13
|
50 |     #[error("Could not convert {timestamp:?} to unix timestamp. Error message: {}")]
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--^
|             |                                                                  |
|             |                                                                  this formatting argument uses named argument `timestamp` by position
```
=> fix string formatting warning

crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
When `tedge connect c8y` makes a direct connection to c8y, if there is an issue regarding certificate, the verbose output of errors is not helpful for end-users to understand what is the actual issue. This commit improves the printing error messages.
https://github.com/thin-edge/thin-edge.io/issues/1458
=> Improve the error messages when certificates having issues for c8y

crates/core/c8y_api/src/http_proxy.rs
Address the two root causes of [Unauthorized request](https://github.com/thin-edge/thin-edge.io/issues/1562):i
* Re-open the MQTT connection for each JWT token request.
* When an HTTP request to Cumulocity is rejected as unauthorized, then renew the JWT token and retry.
Do this only once, since there is no point to get yet another fresh token if rejected twice in a row.
For the first point, the alternative is to keep the MQTT connection open and to have a background task that consumes all the JWT token - requested by the process or not, and to cache the latest one. However, this alternative introduces more complexity and opening an MQTT connection before each HTTP request should not be a performance issue for the current use-cases.
See …
=> Retry unauthorized HTTP request with a renewed JWT token

plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/config_manager.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/tests.rs, plugins/c8y_configuration_plugin/src/upload.rs
If a child device does not respond to a config management operation request, fail that operation in the cloud with a timeout.
This PR is split into two parts:
[x] Make the plugin stateful so that the request-response mappings can be tracked
[] Timeout unacknowledged config management operation requests 
#1544
=> Issue #1544 Timeout unacknowledged config management operation requests

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml
The job for arm architecture with cache can fail sporadically. Stop using cache for those builds.
You can see the trial build: https://github.com/thin-edge/thin-edge.io/actions/runs/3498740838
<br/>
=> Remove cache from the job to build for arm architecture

crates/core/tedge/src/cli/connect/c8y_direct_connection.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/connect/jwt_token.rs
Signed-off-by: Pradeep Kumar K J <pkj@softwareag.com>
On `yocto` the `tedge connect c8y` was failing because the MQTT connections were timing out.
So, the `MQTT connection timeout` has been increased in the below MQTT client's connection.
- Direct connection to create the device in the c8y cloud
- Jwt token retrieval for verification of the connection
The default value was `5sec` now increased to `60sec`.
https://github.com/thin-edge/thin-edge.io/issues/1595
=> tedge connect c8y fails to connect to cumulocity cloud on yocto

crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
Fixed a bug where only positive timezone offset (UTC+n) was formatted to rfc3339 expected format.
- #1633
=> Parse timezone with negative offset

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, ci/build_scripts/build.sh, crates/core/tedge/build.rs, crates/core/tedge_agent/build.rs, crates/core/tedge_mapper/build.rs, crates/core/tedge_watchdog/build.rs, plugins/c8y_configuration_plugin/build.rs, plugins/c8y_log_plugin/build.rs, plugins/tedge_apama_plugin/build.rs, plugins/tedge_apt_plugin/build.rs, plugins/tedge_dummy_plugin/build.rs
Support an automatic versioning based on git describe. It provides a way to generate binaries/packages with a unique version number between official releases (e.g. as soon as it is merged into `main`). 
**Versioning overview**
* Version is determined from the distance from the last git tag
* if commit is tagged, then the version will be the tag (eg. `0.9.0`). For official releases the `Cargo.toml` should still be updated, but the file should be updated and committed, then tagged!
* if commit is 2 commits passed the last tag, then the version will be `0.9.0-2-gabcdef10`, where it follows the schema `<tag>-<distance>-g<commit_sha>`
* support setting a custom version (for dev and testing purposes only)
```sh
export …
```
=> support auto git semver versioning of packages

Cargo.lock, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/lib.rs, crates/common/tedge_utils/tedge-derive/Cargo.toml, crates/common/tedge_utils/tedge-derive/src/lib.rs, crates/common/tedge_utils/tedge-derive/tests/test.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/main.rs
This PR:
-  adds a new crate inside an existing crate: "tedge-derive" behind a feature flag
-  uses this crate to catch unknown serde values, and stores them under a new field named `other`.
-  adds a new declarative macro to generate warnings when any toml fields have unknown values.
- turns on logging for the `tedge` binary  
- #1623
=> Gracefully handle unknown config

CODING_GUIDELINES.md, ci/az_upload_device_cert.py, ci/roundtrip_local_to_az.py, docs/src/BUILDING.md, docs/src/architecture/mapper.md, docs/src/howto-guides/003_registration.md, docs/src/howto-guides/004_connect.md, docs/src/howto-guides/010_add_self_signed_trusted.md, docs/src/howto-guides/011_retrieve_jwt_token_from_cumulocity.md, docs/src/howto-guides/024_smartrest_templates.md, docs/src/references/c8y-configuration-management.md, docs/src/references/c8y-log-management.md, docs/src/references/plugin-api.md, docs/src/references/thin-edge-config-files.md, docs/src/tutorials/connect-azure.md, docs/src/tutorials/connect-c8y.md, docs/src/tutorials/device-monitoring.md, docs/src/tutorials/getting-started.md, docs/src/tutorials/send-events.md, docs/src/tutorials/send-thin-edge-data.md, docs/src/tutorials/supported_operations.md, docs/src/tutorials/write-my-software-management-plugin.md, tests/PySys/software_management_end_to_end/dummy_plugin_configuration/Info.md
Improves the usefulness of the code blocks by separating the command to the output of the commands. `$` command prefixes are also removed. These changes make it easier for the user to copy/paste the command when they are following steps in the documentation.
Related to https://github.com/thin-edge/thin-edge.io/issues/1616
<br/>
=> remove $ prefix in shells

configuration/debian/tedge-agent/postinst, configuration/debian/tedge-mapper/postinst, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, get-thin-edge_io.sh, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
PR #1625 broke the upgrade path (installing from older versions). The installation of some packages (namely `tedge-mapper` and `tedge-agent`) would fail in the `postinst` maintainer scripts due to the flocks not being released. Upon further investigation it was found out that the maintainer scripts from the previous package were not being run which resulted in the related services not being stopped before the new `postinst` script from the renamed packages were executed.
The following changes were done to address the installation errors:
* Add `Breaks` and `Conflicts` Debian package relationships to the old renamed package to prevent both versions from being **installed** at the same time. This way all the maintainer scripts are …
=> fix debian upgrade path

Cargo.lock, crates/core/c8y_api/src/smartrest/message.rs, crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs, crates/core/c8y_api/src/utils.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/error.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/tedge_mapper/src/core/error.rs
When deleting a child device from the cloud representation the supported operations logic would re-create this child device but fail to notice it is not available on the cloud any longer. Thus resulting in a child device name prefixed by "MQTT Device".
This fix, changes the logic of initialising supported operations on startup, to first requesting the cloud representation of child devices, computing a diff between cloud and local, initialising as new child devices anything that is available locally but is not seen on the cloud and then proceeds to add supported operations for the child devices.
- #1569
=> Declare child devices again if deleted in cloud

crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/remove.rs, docs/src/howto-guides/003_registration.md, docs/src/references/thin-edge-config-files.md, docs/src/tutorials/connect-azure.md, docs/src/tutorials/connect-c8y.md
Added output to `tedge cert create` and `tedge cert remove` commands:
- `tedge cert create`
- `Certificate was successfully created.` if certificate was successfully created
- `tedge cert remove`
- `Certificate was successfully removed.` if certificate was removed
- `There is no certificate to remove.` if there is no certificate
The documentation was also updated to include the added output.
<br/>
The change was made because I think it would be good for all the CLI commands that could possibly be invoked by the human, to print human-readable output describing what happened, even if just one sentence, it's better than nothing.
E.g. `tedge cert remove` returned `Ok` for both `cert removed` and `no cert` cases, but it had no output, so the user wouldn't know what actually happened. …
=> Add output to `tedge cert create` and `tedge cert remove` commands

crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs, crates/core/tedge/src/cli/common.rs, crates/core/tedge/src/cli/connect/cli.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/disconnect/cli.rs, crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs, crates/core/tedge/src/cli/disconnect/mod.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/cli/reconnect/cli.rs, crates/core/tedge/src/cli/reconnect/command.rs, crates/core/tedge/src/cli/reconnect/mod.rs
Added a new command to tedge - `tedge reconnect {cloud}`. This command
simply combines `tedge disconnect` and `tedge connect`.
- #1638
=> tedge reconnect command

plugins/tedge_apt_plugin/src/main.rs
When upgradable version is available, the plugin took the upgradable version instead of the actual installed version.
This implementation relies on the output format of `apt list --manual-installed`
#1664
=> Fix tedge-apt-plugin list to show the correct version

crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/collectd/monitor.rs
Code changes include updating the status of the `az` and `collectd` mapper.
When mapper starts it publishes `up` status
and `down` status when it stops.
<br/>
=> Update health status of az and collectd mapper

crates/core/c8y_api/src/smartrest/message.rs, crates/core/tedge_mapper/src/c8y/converter.rs
When receiving multiline SmartREST messages, splitting simply by `\n` is not a right approach because a SmartREST message can also contain `\n`, e.g. an argument of c8y_Command.
Also, in case of an operation failure, giving only the last line of stderr is not easy enough for users to understand why the operation failed. It should give also the whole context as much as possible.
#1687
=> Fix a method to split SmartREST messages and improve failure reason

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, docs/src/developer/DEV_CONTAINER.md, docs/src/developer/INSTALLING_DOCKER.md
Add a (VSCode) [dev container](https://code.visualstudio.com/docs/devcontainers/containers) definition which makes it easier for developers to develop by providing all of the project dependencies.
The dev container is an optional feature which enables VSCode users to start developing quickly as the dev containers includes all of the dependencies required to build/debug/run the project. It is currently only applicable for VSCode users, however the dev container definition contains a plain `Dockerfile` and `docker-compose.yml` that lists the dependencies making it easier for other IDE users to read and replicate in their applicable environments.
To use a dev container locally on your machine, the following dependencies are …
=> feat: add vscode devcontainer definition

Cargo.lock, crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/json_c8y.rs, crates/core/c8y_api/src/smartrest/alarm.rs, crates/core/tedge_api/Cargo.toml, crates/core/tedge_api/src/alarm.rs, crates/core/tedge_mapper/src/c8y/alarm_converter.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs
Create an alarm with custom fragments
Supports for both `thin-edge` devices as well as for the `child` devices.
For example, if an alarm message is published with a custom fragment as below a child device it must create an alarm with the custom message.
```
tedge mqtt pub tedge/alarms/critical/myCustomAlarmType/child_device_example '{ "text": "Some test alarm", "someOtherCustomFragment": {"nested":{"value": "extra info"}} }'
```
https://github.com/thin-edge/thin-edge.io/issues/1682
=> Support custom fragments in alarm creation

crates/core/tedge_mapper/Cargo.toml
Disable the `tedge-mapper az/c8y/collectd` on installation
Also, start the mappers only if bridge config file exists
https://github.com/thin-edge/thin-edge.io/issues/1631
=> tedge_mapper az/collectd services start running when the thin-edge device restarts

Cargo.lock, docs/src/howto-guides/002_installation.md
Fix typo of the uninstall script name in the install doc
<br/>
=> Fix uninstall script name in the doc

.github/workflows/build-workflow.yml, ci/build_scripts/build.sh, ci/build_scripts/publish_debian.sh, docs/src/developer/DEBIAN_PACKAGE_HOSTING.md
This PR is a bit cross cutting as there are three topics wrapped into one, but all of them relate to the building/publishing of the artifacts. I would like to push the topics in one go, rather than having 3 dependent PRs (but I am happy to change this if there are objections).
The following changes are included:
* Use [cargo-zigbuild](https://github.com/rust-cross/cargo-zigbuild) for building artifacts as it makes it easier to cross compile on various sources and targets (e.g. MacOS M1, Linux x86_64 etc.) 
* Checkout out the [blog post](https://actually.fyi/posts/zig-makes-rust-cross-compilation-just-work/) describing some of the motivation and challenges with cross compiling in rust
* Build `musl` variants (see next section for more details on why)
* Simplify the `build-workflow` to use …
=> Build/publish artifacts - musl, zigbuild and cloudsmith

crates/core/c8y_api/src/smartrest/alarm.rs, crates/core/tedge_api/src/alarm.rs, crates/core/tedge_mapper/src/c8y/tests.rs, docs/src/tutorials/raise-alarm.md
This PR addresses
- Adding tests for custom fragments
- Updating the documents related to the `custom` fragments.
https://github.com/thin-edge/thin-edge.io/issues/1710
=> tedge alarm does not transform message fragment to text in the tedge-mapper-c8y

tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot, tests/RobotFramework/tests/cumulocity/software.robot, tests/images/debian-systemd/files/mosquitto.conf
Extend software tests to wait for the `tedge-mapper-c8y` health message to be published locally before checking if the software list is installed. The software list check already has a default timeout of 30 seconds, however since the device is created in Cumulocity IoT during the connection phase, the full initialization sequence can take longer, so the cloud side software list check timer should not start until the mapper is fully up and running.
A ticket has been created referring to ticket which the workarounds were created for: https://github.com/thin-edge/thin-edge.io/issues/1731
<br/>
=> Wait for mapper health message before starting software list assertion

crates/core/tedge_api/src/health.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/c8y/mod.rs, crates/core/tedge_mapper/src/c8y/service_monitor.rs, crates/core/tedge_mapper/src/c8y/tests.rs, docs/src/SUMMARY.md, docs/src/howto-guides/028_c8y_service_monitoring.md, docs/src/howto-guides/howto-guides.md
These code changes support monitoring of the `thin-edge` device service as well as the `child` devices service on c8y.
The `tedge-mapper-c8y` receives the health status from the thin-edge c8y services (tedge-agent, c8y-log-plugin, etc) or any child device service and translates into a smart rest (102) message, and sends it to c8y.
- The thin-edge device services must publish health status on `tedge/health/<service-name>` topic 
- The child device services must publish the health status on `tedge/health/<child-id>/<service-name>` topic
The health status will be published to c8y only on state change.i.e on start (up) or stop(down).
https://github.com/thin-edge/thin-edge.io/issues/1353
- [x ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) …
=> Adapt monitoring of daemons to new Service Monitoring Feature in 10.14

crates/bin/c8y-device-management/src/main.rs, crates/extensions/tedge_http_ext/src/actor.rs, crates/extensions/tedge_http_ext/src/lib.rs, crates/extensions/tedge_http_ext/src/messages.rs, crates/extensions/tedge_http_ext/src/tests.rs
Derive actor configs from TEdgeConfig
=> Issue #1724 Derive actor configs from TEdgeConfig

.github/workflows/pull-request-checks.yml
=> Fix clippy warning almost_swapped

crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/core/tedge_actors/src/tests.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/credentials.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_http_proxy/src/tests.rs, crates/extensions/tedge_http_ext/src/actor.rs, crates/extensions/tedge_http_ext/src/lib.rs, crates/extensions/tedge_http_ext/src/tests.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_script_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/actor.rs, crates/extensions/tedge_timer_ext/src/builder.rs, crates/extensions/tedge_timer_ext/src/tests.rs
- Rename ServiceProvider and ServiceConsumer the former Socket/Plug traits
- Rename Server the former Service trait
- Rename ServerMessageBox the former ServiceMessageBox trait
- Rename ServerClientMessageBox the former RequestResponseHandler struct
=> Improve naming for message box builder traits

.github/workflows/integration-tests.yml, Cargo.lock, crates/core/tedge_actors/Cargo.toml, crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/errors.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/runtime.rs, crates/extensions/c8y_config_manager/Cargo.toml, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/download.rs, crates/extensions/c8y_config_manager/src/error.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_config_manager/src/upload.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/tedge_file_system_ext/src/lib.rs, crates/extensions/tedge_http_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_script_ext/src/lib.rs, crates/extensions/tedge_signal_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/actor.rs
A library crate should not depend on anyhow
- Remove tedge_actors dependency on anyhow
- Remove c8y_config_manager dependency on anyhow
- Extends RuntimeError with a case for any std::error::Error
- Change the signature of Actor::run to raise RuntimeError
=> Remove tedge_actors dependency on anyhow

configuration/init/systemd/tedge-mapper-aws.service, crates/core/tedge_mapper/src/aws/converter.rs, crates/core/tedge_mapper/src/aws/mapper.rs, docs/src/architecture/mapper.md, docs/src/references/bridged-topics.md, docs/src/tutorials/connect-aws.md, docs/src/tutorials/supported_operations.md
This PR fixes some bugs and inaccuracies concerning AWS support:
- It fixes a wrong binary name used in the unit file
- Maps `tedge/measurements` to `aws/td/measurements` instead of `aws/td`
- Corrects mentions of previous AWS topic mappings used in the documentation
<br/>
=> Aws topic mapping

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs
This PR fixes the flaky alarm tests
- Run tests in `serial`
- Fix the issues `in the way the results validated`
<br/>
=> Fix the flaky alarms tests

crates/common/tedge_config/src/system_services/log_config.rs, crates/core/tedge/src/cli/config/commands/get.rs, crates/core/tedge/tests/main.rs, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/tedge/tedge_config_get.robot, tests/images/debian-systemd/files/bootstrap.sh
Move `tedge config` user directed messages to stderr so actual data output and user-directed messages can be more easily told apart and parsed as described in #1721.
<br/>
=> Output tedge config control messages to stderr

crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/runtime.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/tedge_http_ext/src/test_helpers.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_signal_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/actor.rs, crates/extensions/tedge_timer_ext/src/tests.rs
=> Combine message box receivers

crates/bin/c8y-device-management/src/main.rs, crates/common/tedge_config/src/tedge_config_cli/config_setting.rs, crates/common/tedge_config/src/tedge_config_cli/models/ipaddress.rs, crates/common/tedge_config/src/tedge_config_cli/settings.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/mqtt/cli.rs, crates/core/tedge/tests/mqtt.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/core/tedge_mapper/src/core/component.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs, crates/extensions/c8y_config_manager/src/config.rs, crates/extensions/c8y_log_manager/src/config.rs, plugins/c8y_configuration_plugin/src/config_manager.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/tests.rs, plugins/c8y_firmware_plugin/src/firmware_manager.rs, plugins/c8y_firmware_plugin/src/main.rs, plugins/c8y_firmware_plugin/src/tests.rs, plugins/c8y_log_plugin/src/main.rs
As described in #1773, config settings for addresses and port numbers were made separate for MQTT clients and brokers, as often connect and bind addresses are different. This change will help in scenarios where the MQTT broker is located outside of the local network, e.g. when using containers or when using a hostname.
Additionally c8y_configuration_plugin, c8y_firmware_plugin, and c8y_log_plugin, which didnt's use any MQTT address/host config settings, and were hardcoded to default to localhost, now use MqttClientAddressSetting and MqttClientPortSetting settings.
- #1773
=> Add address/port config settings for crates using MQTT clients

crates/bin/c8y-device-management/src/main.rs, crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/core/tedge_actors/src/tests.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_http_proxy/src/credentials.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/tedge_http_ext/src/actor.rs, crates/extensions/tedge_http_ext/src/lib.rs, crates/extensions/tedge_http_ext/src/tests.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/tests.rs, crates/extensions/tedge_script_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/builder.rs, crates/extensions/tedge_timer_ext/src/tests.rs
WIP
So a ServiceConsumer can be connected to a ServiceProvider
without any knowledge of the config used by the former to connect the latter.
=> Simplify Actor Builders

tests/RobotFramework/tests/cumulocity/firmware/firmware1.txt, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot, tests/images/debian-systemd/files/bootstrap.sh
Create a new test file for c8y-firmware-plugin. Prepared two scenarios:
1. Happy path with file download.
2. Happy path without file download (hitting the file cache).
Note:
* `c8y-firmware-plugin` must be installed after `tedge-agent`, otherwise the installation of `c8y-firmware-plugin` will fail due to the failure to create directories under `/var/tedge` by `c8y-firmware-plugin --init`. That's why the change on the bootstrap script looks a bit strange.
#1696
=> Add a RobotFramework test for c8y-firmware-plugin

crates/common/mqtt_channel/src/config.rs, crates/common/mqtt_channel/src/connection.rs, crates/core/c8y_api/src/smartrest/monitor.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_api/src/health.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/monitor.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, plugins/c8y_configuration_plugin/src/config_manager.rs, plugins/c8y_firmware_plugin/src/firmware_manager.rs, plugins/c8y_log_plugin/src/main.rs, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
When the MQTT broker restarts, the registered will messages that are registered to send out the health status `(down)` will be published. The connections will be restored after a while, still, the status remains `down`.
To address this issue an updated health status `up`  message has to be sent. For this to work, need to register an `initial message` when the `mqtt` client is created. This message will be sent out when the connection is restored.
So added an option to add the initial message `with_initial_message` function. Using this API, one can register the `initial message`.
https://github.com/thin-edge/thin-edge.io/issues/1774
=> All service statuses are set to down and remain down after restarting mosquitto

tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/cumulocity/jwt/jwt_request.robot
=> Add test for jwt request

crates/core/tedge_actors/src/errors.rs, crates/core/tedge_actors/src/runtime.rs
Wrapped tasks.run() in a spawn so I can map the JoinErrors from that spawn into RuntimeErrors so that the runtime can do appropriate cleanup.
<br/>
=> Handle panicking actors

ci/build_scripts/build.sh
When building the binaries/packages via the `ci/build_scripts/build.sh` script, it now detects the appropriate target (linux/musl variant) based on your current host architecture if the user does not provide a target triple.
For example executing the `ci/build_scripts/build.sh` script with no arguments will choose the following targets:
* `aarch64-unknown-linux-musl` on MacOS M1 natively (aarch64)
* `aarch64-unknown-linux-musl` on MacOS M1 running inside a linux vm (aarch64)
* `x86_64-unknown-linux-musl` on amd64/x86_64
* `armv7-unknown-linux-musleabihf` on amv7
* `arm-unknown-linux-musleabihf` on amv6
<br/>
This change was brought on from several discussions with core team members about how the integration tests was not detecting the correct binaries for their host machine. Since the …
=> build linux/musl target by default for host arch

crates/common/tedge_config/src/tedge_config_cli/settings.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/c8y/service_monitor.rs, crates/core/tedge_mapper/src/c8y/tests.rs, docs/src/howto-guides/028_c8y_service_monitoring.md, tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
This PR adds a feature to configure the `service_type` that is required for the `service monitoring` feature.
Set service type : 
```
sudo tedge config set service.type <service-type> 
sudo tedge config unset service.type
```
The default value is `service`.
(https://github.com/thin-edge/thin-edge.io/issues/1769)
=> tedge command for updating the service type

crates/common/tedge_config/src/tedge_config_cli/settings.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/main.rs
This commit adds a configuration option to disable lock file creation by running the `tedge config` command or editing the `tedge.toml` file. More information in #1802 
#1802
<br/>
=> Add configuration option to disable lock file creation

tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot, tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot, tests/RobotFramework/tests/cumulocity/software.robot
Corrected spell check errors in the .robot files
<br/>
=> Correct spell check errors

crates/common/flockfile/src/unix.rs
This commit adds PID inside lock files that are located under `/run/lock`. More information in #1746
#1746 
<br/>
=> Add support for PID files

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Added examples to keywords which was used in tests so far
<br/>
=> Added examples to keywords

tests/RobotFramework/tests/configuration/lock_file.robot
Added test that is checking the lock file creation set/unset
<br/>
=> Add test for checking the lock file creation set/unset

Cargo.lock, crates/common/download/Cargo.toml, crates/common/download/src/download.rs, crates/common/download/src/error.rs, crates/common/tedge_utils/src/file.rs, crates/core/c8y_api/src/http_proxy.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/messages.rs
Downloader to download directly to target location instead of first downloading to temp location and then moving it. This eliminated the need to move the downloaded file between file systems.
<br/>
=> Downloader to download directly to target location

crates/core/tedge_mapper/src/c8y/tests.rs, crates/extensions/tedge_file_system_ext/src/lib.rs
Temporary fix: wait a bit before updating the file system to give to the watching actor a chance to be ready.
See https://github.com/thin-edge/thin-edge.io/issues/1879
=> Fix flaky test: test_fs_events

docs/src/tutorials/write-my-software-management-plugin.md
Documentation styling improvements to avoid the false positive "potential incomplete link" warnings.
For example, previously the docs were generating the following warnings (which are now removed):
```sh
warning: Potential incomplete link
┌─ tutorials/write-my-software-management-plugin.md:72:28
│
72 │ |update-list| COMMAND NAME [--module-version VERSION] [--file FILE] | - |Executes the list of `install` and `remove` commands.|
│                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you forget to define a URL for `--module-version VERSION`?
│
= hint: declare the link's URL. For example: `[--module-version VERSION]: http://example.com/`
```
<br/>
=> docs: use inline code blocks to avoid warnings

tests/RobotFramework/tests/configuration/lock_file.robot
1. Adding Step to check the PID number stored in the lock file is the actual PID number of the running service
2. Checking if after restarting the services the new PID number is stored in the lock files
<br/>
=> Add steps to check PID in lock file

crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/channels.rs, crates/core/tedge_actors/src/converter.rs, crates/core/tedge_actors/src/messages.rs, crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs
Add a Config type parameter to MessageSink, so a message sink can provides its config to connect the source.
Now a source and sink can be connected with `source.add_sink()` without any knowledge of the config nor the internal sender used by the sink (as it was the case with `sink.register_peer(config,&mut sender).
<br/>
=> Add a Config type parameter to MessageSink 

ci/build_scripts/build.sh, justfile
=> Add just file support

configuration/debian/tedge/postinst
Use awk to put `include_dir /etc/tedge/mosquitto-conf` before `include_dir /etc/mosquitto/conf.d` so that `per_listener_settings` that appears in `tedge-mosquitto.conf` appears first.
Fixes #1852.
- #1852
This is a quick workaround, perhaps `per_listener_settings true` line should be included in the top level `mosquitto.conf` file?
=> mosquitto.conf: put `per_listener_settings` first

configuration/init/systemd/c8y-configuration-plugin.service, configuration/init/systemd/c8y-firmware-plugin.service, configuration/init/systemd/c8y-log-plugin.service, configuration/init/systemd/tedge-agent.service, configuration/init/systemd/tedge-mapper-aws.service, configuration/init/systemd/tedge-mapper-az.service, configuration/init/systemd/tedge-mapper-c8y.service, configuration/init/systemd/tedge-mapper-collectd.service
Increase the systemd auto restart delay from the default 100ms to 5s. This results in the services from breaching the burst rate-limiting state (e.g. systemd's message `Start request repeated too quickly`) allowing the service to potential start successfully once the error has been resolved. For example the `c8y-configuration-plugin` will fail if the `c8y.url` setting is not configured. This causes the service to activate the systemd rate limiting within seconds which prevents the service from auto-starting when the `c8y.url` is set by the user, thus requiring the user to manually start the service.
One downside is that technically it will cause more CPU usage as the service will continuously try to restart, however the additional load is minimal and remove manual steps required by the …
=> Delay systemd automatic service restarts by 5 sec

Cargo.lock
`cargo-audit` tool in PR check reported a vulnerability in h2 crate, used as a dependency by reqwest and hyper crates, which were in turn used by almost all the crates in our workspace. `cargo update` bumped patch versions of our dependencies, resolving the audit failure.
<br/>
=> Run `cargo update` to pass `cargo audit`

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/file.rs, crates/common/tedge_utils/src/fs.rs, crates/core/tedge_agent/src/state.rs, crates/extensions/c8y_config_manager/src/upload.rs
Replace rename with copy and delete where necessary. Calculate tmp path inside atomically write functions. More in #1899
#1899
<br/>
=> Fix rename

tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/configuration/c8y-configuration-plugin-updated.toml, tests/RobotFramework/tests/cumulocity/configuration/c8y-configuration-plugin.toml, tests/RobotFramework/tests/cumulocity/configuration/config1-version2.json, tests/RobotFramework/tests/cumulocity/configuration/config1.json, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
Add Cumulocity configuration management integration tests (for the main device)
Add test cases to cover the following:
<br/>
=> Test configuration management on main device

tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot, tests/images/debian-systemd/files/mqtt-logger
Add test coverage for configuring a connecting to a remote mqtt broker. #1773
To support this test, the following test framework modifications were also included:
* Added support to the integration test's `mqtt-broker` service to detect the mqtt broker address via the `tedge` command (if it is present)
<br/>
#1773
=> Test configuration of tedge services to use a remote MQTT broker

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, docs/src/howto-guides/029_mqtt_local_broker_authentication.md
There was a typo in `tedge config set mqtt.client.auth.key` which sneaked past the MQTT client authentication review.
<br/>
This highlights one more place where `tedge_config` could use some deduplication.
=> Fix typo in mqtt.client.auth.key set error message

crates/common/tedge_utils/src/file.rs, crates/core/tedge/src/main.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_firmware_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs, plugins/c8y_remote_access_plugin/src/main.rs
Small improvement to the error messages created by tedge init commands that was mentioned in #1795. Issue only happened when we wanted to change the owner/group of the file. The problem was with chown that handled errors by itself but did not provide any information about directory, file etc. 
#1795
<br/>
=> extend error message for chown function

configuration/debian/tedge-agent/postinst
The tedge-agent init. logic should still run when being installed on other linux OSs without systemd.
Previously the installation of c8y-firmware-plugin was failing because the tedge-agent was not running `tedge-agent --init` (and therefore not creating the /var/tedge folder) if systemd was not installed. This is common in container environments.
Summary of changes:
* Check if process is running rather than a service (to be service manager agnostic)
* Ignore any --init errors so install does not fail
* Simplify lock file logic by using `rm -f` which ignores files if they don't exist
<br/>
=> fix: tedge-agent init on non-systemd installs

tests/RobotFramework/tests/cumulocity/firmware/firmware_operation.robot
Allow enough time to retry fetching the jwt token if it fails the first time.
<br/>
Found during a PR check failure on:
* https://github.com/thin-edge/thin-edge.io/actions/runs/4873733875/attempts/1
=> fix(test): increase operation assertion timeouts

.github/workflows/pull-request-checks.yml, Cargo.lock
CI broke again because clippy was not included in rust 1.70-beta.4 version. Fortunately, clap backported fixes in versions 3.2.24 and 3.2.25 for their macro code, so we're able to avoid a clap major version bump and can return to stable clippy.
<br/>
=> update to clap 3.2.25, move back to stable clippy

crates/common/tedge_config/src/tedge_config_cli/models/connect_url.rs, crates/common/tedge_config/src/tedge_config_cli/models/host_port.rs, crates/common/tedge_config/src/tedge_config_cli/models/mod.rs, crates/common/tedge_config/src/tedge_config_cli/settings.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/upload.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge/src/cli/connect/bridge_config_c8y.rs, crates/core/tedge/src/cli/connect/command.rs, crates/extensions/c8y_config_manager/src/config.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/src/config.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/config.rs, crates/extensions/c8y_mapper_ext/src/config.rs, plugins/c8y_remote_access_plugin/src/main.rs
This PR adds `c8y.http` and `c8y.mqtt` config options intended to override `c8y.url` option in HTTP and MQTT contexts respectively. This is necessary for when HTTP and MQTT servers are present under different domain names. These settings are optional and are derived from `c8y.url` if not present.
In code, settings `C8yHttpSetting` and `C8yMqttSetting` were added. Their `query()` methods were made to look whether `c8y.http/mqtt` option was defined first, and if not, they use the value of `c8y.url`. The old `C8yUrlSetting` accessor was left as it is because changing its behaviour would break setting/listing config options, in the future it should be made deprecated and phased out.
Previously used for deserializing `ConnectUrl` type does not allow specifying ports in host strings. To allow …
=> Add separate HTTP and MQTT endpoints for Cumulocity

tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
This PR adds integration tests to verify the thin-edge device's telemetry data, that includes
- Measurement
- Measurement with custom type
- Alarm
- Event
<br/>
=> telemetry test for thin-edge device

crates/core/c8y_api/src/smartrest/operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/operation/c8y_Command_1, tests/RobotFramework/tests/cumulocity/operation/c8y_Command_2, tests/RobotFramework/tests/cumulocity/operation/command_1.sh, tests/RobotFramework/tests/cumulocity/operation/command_2.sh, tests/RobotFramework/tests/cumulocity/operation/dynamically_reload_operation.robot, tests/RobotFramework/tests/cumulocity/shell/c8y_Command
The issue here is, if there is any change to the `custom operation` file content, then these changes are not reflected in the operation list that is present with the `tedge-mapper-c8y`. To get it reflected the mapper has to be restarted.
On the code path, on the file change notification, the mapper is wrongly updating the child device operations list.
The proposed fix is
- Dynamically update/populate the `thin-edge` device operation list of `tedge-mapper-c8y` when there is a change in the operation file.
- Added integration test to verify the fix.
https://github.com/thin-edge/thin-edge.io/issues/1705
=> tedge-mapper-c8y service restart is required after a change of supported operation file contents

crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/restart_manager/actor.rs, crates/core/tedge_agent/src/restart_manager/error.rs, crates/core/tedge_agent/src/state_repository/state.rs
The restart actor must specifically await a shutdown request to check that the restart has been successfully triggered without consuming subsequent requests.
Use the `recv_signal()` method instead of the `recv_message` method. The former consumes only runtime requests while the latter primary purpose is to consume regular messages (while being alerted of any high-priority signal sent by the runtime).
https://github.com/thin-edge/thin-edge.io/issues/1964
=> Await for a shutdown request when a restart is triggered

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/error.rs, crates/extensions/c8y_config_manager/src/config.rs, crates/extensions/c8y_log_manager/src/config.rs, crates/extensions/tedge_file_system_ext/Cargo.toml, crates/extensions/tedge_file_system_ext/src/lib.rs
The issue here is in `tedge_file_system_ext` in the `FsWatchActor` `run` function, the errors are not handled, and using `unwrap`, Because of this when there are no directories to add `fs watch` it panics.
The proposed solution is to handle these panics gracefully by removing unwrap.
https://github.com/thin-edge/thin-edge.io/issues/1955
=> c8y-configuration-plugin panics when required folder/s are missing

crates/common/mqtt_channel/src/connection.rs, crates/core/c8y_api/src/http_proxy.rs, crates/extensions/c8y_http_proxy/src/actor.rs
This is not a fix. Just misc small improvements to reduce the likelihood of the issue and improve debugability.
https://github.com/thin-edge/thin-edge.io/issues/1972
=> Improve debugability of JWT failures

crates/common/mqtt_channel/src/connection.rs
The MQTT connections were actually not closed on drop, letting the event loop still running in the background.
Simply break the MQTT event loop on Outgoing::Disconnect.
https://github.com/thin-edge/thin-edge.io/issues/1981
=> Quit the MQTT event loop on Outgoing::Disconnect

Cargo.lock, crates/extensions/tedge_http_ext/Cargo.toml, crates/extensions/tedge_http_ext/src/tests.rs
The request to httpbin service was failing with a 504 for me, so I replaced it with a mock.
The mock is unfortunately HTTP only, so if the intent was to test HTTPS as well, then this PR removes it.
<br/>
=> http_ext: Replace request to httpbin with mock

.typos.toml, crates/common/tedge_config/src/tedge_config_cli/new.rs, crates/common/tedge_config_macros/examples/macro.rs, crates/common/tedge_config_macros/impl/src/input/parse.rs, crates/common/tedge_config_macros/impl/src/lib.rs, crates/common/tedge_config_macros/src/define_tedge_config_docs.md, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
The tests were broken because of two conflicting merges:
- Adding tests for misc settings: https://github.com/thin-edge/thin-edge.io/pull/1976
- Changing setting names: https://github.com/thin-edge/thin-edge.io/pull/1936
This clash is a call for https://github.com/thin-edge/thin-edge.io/issues/1393
<br/>
=> Fix setting names to match the new tedge-config

Cargo.lock
Compiling crate value-bag, which is used by crate log, fails on nightly. This makes all our CI jobs using nightly fail. Updating it fixed the problem.
<br/>
~~If we don't want to update all the dependencies, we could alternatively only update `log`.~~
Updating all the dependencies caused some tests to fail, so only updating `log` for the time being.
=> update deps to fix failing check on nightly

Cargo.lock, crates/extensions/c8y_mapper_ext/Cargo.toml, crates/extensions/c8y_mapper_ext/build.rs, crates/extensions/c8y_mapper_ext/src/fragments.rs, tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
The `tedge-mapper` was using this to get publish the current "tedge" version to Cumulocity, for example it was producing the publishing the following fragment to Cumulocity on startup.
```json
{
"c8y_Agent": {
"name": "thin-edge.io",
"url": "https://thin-edge.io",
"version": "0.11.0-38-g246db7dd"
}
}
```
This PR is to change where the `c8y_Agent.version` value is populated from.
The agent version now returns the value from the Rust build environment variable (package version) instead of calling the `tedge --version` binary. This removes the dependency to `tedge` and means that the `tedge-mapper` can be run in an environment where `tedge` is not installed and still report back the correct agent version to Cumulocity.
<br/>
#1991
=> feat(tedge-mapper): retrieve agent version from cargo package version instead of calling the tedge cli

crates/core/c8y_api/src/smartrest/operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs
Issue:
Removing an operation file using the `mv` command does not remove it from the tedge-mapper's operations list.
The reason for this is when a file is moved, a `file modified` event gets generated and this will be considered as an `add` operation. So, the mapper tries to access the file and fails to read the file and add it to the list, instead of removing the operation from the list.
Proposed solution:
- So, the proposed solution is when a `file is modified` and a `modified/Add` event is generated, and if the operation file does not exist then remove the operation from the list.- 
- Also replaced the operation list, with a map to store the operations. A single map is used to store the operation.- 
- Populate the operations map every time there is an event, irrespective of add/remove …
=> Removing an operation with mv command does not remove the operation

.github/workflows/pull-request-checks.yml
Replace the usage of [actions-rs/toolchain@v1](https://github.com/actions-rs/toolchain) as it is no longer maintained and it uses deprecated GitHub Actions API.
The PR switches to using [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) provides similar functionality, however requires an additional step when using the nightly toolchain because it does not support the override option.
**Warning**
This does not solve all of the deprecation notices, but reduces any coming from `actions-rs/toolchain@v1`.
**References**
* [actions-rs/toolchain usage of deprecated GHA API](https://github.com/actions-rs/toolchain/issues/219)
* [dtolnay/rust-toolchain override option workaround](https://github.com/dtolnay/rust-toolchain/issues/29#issuecomment-1412903426)
<br/>
An example of the …
=> ci: remove usage of actions-rs/toolchain@v1 as it is not actively maintained

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/new.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/plugin_sm/Cargo.toml, crates/core/plugin_sm/src/plugin.rs, docs/src/howto-guides/012_install_and_enable_software_management.md, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_apt_plugin/src/main.rs, tests/RobotFramework/tests/plugin_apt/filter_packages_list_output.robot
This PR adds two features:
- option to filter packages by name and maintainer in apt plugin. User have to set filters manually using `tedge.toml`.
- limit of software list output to given number of lines using `tedge config`. Default value is set to 1000 and 0 means no limit to the output (STC).
#1926 
<br/>
=> Filtering criteria in apt-sm-plugin output

crates/core/tedge/src/cli/certificate/mod.rs, crates/core/tedge/src/cli/connect/c8y_direct_connection.rs, crates/core/tedge/src/cli/connect/mod.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/command.rs, crates/core/tedge/src/lib.rs, crates/core/tedge/src/main.rs
In order to enable thick-edge remote connectivity, we would like to connect thin-edge to Cumulocity programmatically, and we would like to do this without going via the tedge binary, as that makes error handling more tricky (than calling a Rust function), and it means we are forced into running logic that doesn't make sense in Kubernetes, such as ensuring mosquitto is connected when we run `tedge connect c8y` (mosquitto is run in a separate container, and is only started after we have connected the device).
This PR modifies the tedge crate to be a library crate, which allows other crates to import functions from `tedge`. I have exported the direct connection logic so our code can call that directly, and tweaked `main.rs` to import from the library. I have also added a case to the direct …
=> Export tedge features via a library crate

crates/common/tedge_config/src/mqtt_config.rs, crates/common/tedge_config/src/tedge_config_cli/new.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/core/tedge_mapper/src/core/component.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/core/tedge_mapper/src/main.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_mapper_ext/src/config.rs
For #1969, I need to add new tedge config keys to the new tedge config API in order to use them in tedge-mapper. However, to proceed it, firstly I need to refactor tedge-mapper by replacing the old tedge config API by the new one. Otherwise, it's impossible to load the new API keys from the old tedge config API object.
This PR is compilable, but there is still questionable point if I used the new tedge config API in a designed manner. Feel free to add comments!
Part of #1969
=> Refactor tedge-mapper by using new tedge config API

.github/codecov.yml, .github/workflows/head_coverage.yml
Codecov guides suggest uploading coverage for push and pull_request events. `pull-request-checks.yml` only runs on PRs though, and when coverage upload only happens there, it has an effect of codecov patch reports not picking up the latest HEAD and displaying coverage changes that have already been made in previous PRs. To fix this, we upload report every time we push to main, which also happens when a PR gets merged.
Also, because coverage data that we get from llvm-cov is somewhat noisy and unrelated changes can randomly increase or decrease coverage, failing PR checks, we disable blocking checks for the time being. Once we tune codecov to a sufficient degree, we can reenable them.
<br/>
https://docs.codecov.com/docs/commit-status#informational
=> Add workflow to upload coverage report on pushes to main

crates/common/download/src/download.rs, crates/common/tedge_utils/src/file.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/upload.rs, crates/extensions/c8y_firmware_manager/src/actor.rs
This PR makes ConfigManager actor no longer unsuccessfully exit if there's an error processing event, instead it just logs it and continues processing events. Previous behaviour was not optimal for e.g. processing config snapshot messages, where an error doesn't really put the actor in an unrecoverable state, so IMO there's no reason to exit. The new behaviour was applied to all possible errors when processing events, so if there are any event-related errors where it is crucial to terminate the actor, please let me know.
Also the error message was improved when we try to copy the child device configuration file from file transfer directory to the `/etc/tedge/c8y/` directory. If the configuration file was not uploaded via HTTP (`PUT …
=> Don't exit ConfigManager if error processing event and improve config snapshot error message

crates/extensions/aws_mapper_ext/src/converter.rs, crates/extensions/az_mapper_ext/src/converter.rs
As I discovered during different work, https://github.com/thin-edge/thin-edge.io/pull/2033#discussion_r1235795859, aws-mapper and az-mapper should not stop converter actor when it fails to deserialize JSON.
This PR fixes the bug.
Publish invalid JSON payload to `tedge/measurements` topic in both mappers.
You will see Converter Actor died from the mapper log.
Part 3 of #1969
=> Fix AwsConverter and AzConverter not being killed by JSON parse error

crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/plugin_sm/tests/plugin.rs, crates/core/plugin_sm/tests/plugin_manager.rs, crates/core/tedge_agent/src/software_manager/actor.rs
This is follow up PR to #1961 that solve the issue with tedge config. Previously it was assumed that tedge config is in default location, now it is delivered from agent. 
#1961
<br/>
=> pass config location to plugin-sm from agent

crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
Problem:
When the `tedge-mapper-c8y` starts, it will publish the `tedge-agent` supported operation to c8y and also sends a `software list` request to `tedge-agent`. If the `tedge-agent` is not up, then the `software list request` will be lost.
Proposed solution:
- Check the `tedge-agent` status (either up or down)
- Create the `c8y_SoftwareUpdate` & `c8y_Restart`  supported operations files
- Send the software list request to tedge-agent
Added an integration test as well
https://github.com/thin-edge/thin-edge.io/issues/1201
https://github.com/thin-edge/thin-edge.io/issues/1731
=> tedge-mapper-c8y sync with tedge-agent

crates/common/tedge_config/src/tedge_config_cli/new.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/extensions/aws_mapper_ext/src/converter.rs, crates/extensions/az_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, docs/src/operate/configuration/config-mapper-mqtt-topics.md, tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot, tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-az.robot, tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-c8y.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot, tests/RobotFramework/tests/tedge/tedge_config_get.robot
This PR introduces 3 new tedge config keys:
- c8y.topics
- az.topics
- aws.topics
The default values of them are the topics that currently the mapper subscribes. So, by default, user will find no difference.
If you want to subscribe limited topics, try something like this.
```
sudo tedge config c8y.topics tedge/measurements,tedge/measurements/+
```
Then, c8y-mapper will subscribe the only configured topics. 
Currently, 
- c8y-mapper subsribes to `tedge/health/+` and `tedge/health/+/+`.
- az-mapper subscribes no health topics.
- aws-mapper subscribes to `tedge/health` and `tedge/health/+`
Source:
c8y: https://github.com/thin-edge/thin-edge.io/blob/main/crates/extensions/c8y_mapper_ext/src/config.rs#L80-L81
az: https://github.com/thin-edge/thin-edge.io/blob/main/crates/extensions/az_mapper_e …
=> Support configurable tedge-mapper MQTT topics

crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/restart_manager/config.rs, crates/core/tedge_agent/src/software_manager/actor.rs, crates/core/tedge_agent/src/software_manager/config.rs, crates/core/tedge_agent/src/software_manager/error.rs, crates/core/tedge_agent/src/software_manager/tests.rs
Refactor `tedge-agent` to use the new `tedge-config` APIs to parse the configurations.
https://github.com/thin-edge/thin-edge.io/issues/2019
=> tedge-agent must use new tedge-config

crates/core/tedge_actors/src/servers/message_boxes.rs
The bug in ConcurrentServerMessageBox::await_idle_processor caused runtime shutdown requests to not have intended effect (closing the actor) when the message box was processing in-progress requests.
This fix works for this specific case, but the message box can still block in other places, e.g. when sending a response if the channel is full. When this happens, if the receiver is not freed before the sender, we block.
<br/>
=> Fix bug in ConcurrentServerMessageBox

crates/common/download/src/download.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_agent/src/software_manager/actor.rs, crates/core/tedge_api/src/error.rs, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/cumulocity/software.robot
This PR is a follow-up to #1966, improving on some things that came up during the partial download demo.
- added more logging statements to keep track of what the downloader is doing
- fixed mistakenly lowered backoff delay and added a method to customize the backoff for testing
- tweaked error handling in plugin_sm to print error causes
- made SoftwareManager immediately process shutdown requests, even if an operation is in progress.
<br/>
=> Improve downloader logging behaviour and make SoftwareManager exit immediately on ^C

design/decisions/0002-mqtt-topic-schema.md, docs/src/contribute/design/index.md, docs/src/contribute/design/mqtt-topic-design.md, docs/src/references/mappers/c8y-mapper.md, docs/src/references/mappers/index.md, docs/src/references/mqtt-api.md
Guidelines for MQTT topics
<br/>
#2005
=> Guidelines for MQTT topics

Cargo.lock, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_api/src/json_c8y.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_config_manager/src/upload.rs, crates/extensions/c8y_firmware_manager/src/config.rs, crates/extensions/c8y_http_proxy/Cargo.toml, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/messages.rs, crates/extensions/c8y_http_proxy/src/tests.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
When an HTTP interaction with `Cumulocity` fails with 
- status code 401 or 403, then get the renewed `JWT` token and retry the HTTP request.
- status code 404 then get the new `internal-id` and retry the HTTP request.
- use map inside the `C8yEndPoint` to cache `child_internal_id` and `main_device_internal id`. Also, cache the `token` in `C8yEndPoint`
https://github.com/thin-edge/thin-edge.io/issues/1201
=> Retry http requests to c8y fails with the response status code 401,403 and 404

docs/src/references/tedge-log-management.md
This is a PR for `tedge-log-plugin` specification.
* States. Need to sync with the state machine spec later.
#2048
=> tedge-log-plugin specification

tests/RobotFramework/tests/installation/install_tedge.robot, uninstall-thin-edge_io.sh
Change the uninstall script to not make any assumptions about the dependencies between thin-edge.io packages. The script already handles the case if the package is not installed, so at worst it is a no-op.
Otherwise, if the dependencies between the packages changes it will not remove all of them.
Integration tests were also added to cover the uninstall script in the current branch, so that any changes to the uninstall script can be validated in the PR before merging to main.
<br/>
=> refactor(uninstall): explicitly remove all packages to avoid problems when dependencies are changed

tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot, tests/RobotFramework/tests/MQTT_health_check/health_c8y-configuration-plugin.robot, tests/RobotFramework/tests/MQTT_health_check/health_c8y-log-plugin.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-agent.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot, tests/RobotFramework/tests/configuration/lock_file.robot
Reduce false positives when getting the Process ID (PID) in integration tests. Previously the pgrep command could match additional processes (such as the pgrep command itself). Now a more exact matching is used to only check processes starting with `/usr/bin/` etc.
<br/>
https://github.com/thin-edge/thin-edge.io/issues/2087
=> tests(lock): improve pid detection logic by using more precise matches

ci/build_scripts/build.sh
A newly released version of zig (used to build the project) causes build errors (unsure of it is a zig issue or a cargo-zigbuild issue).
For now enforcing a fixed version, 0.10.1.
**Example of error**
The error can be view on this [run](https://github.com/thin-edge/thin-edge.io/actions/runs/5760900709)
And an extert from a local build (using ziglang 0.11.0) is shown below.
```
Compiling c8y-device-management v0.12.0 (/Users/reubenmiller/dev/projects/tedge/code/fork-docs/thin-edge.io/crates/bin/c8y-device-management)
error: linking with `/Users/reubenmiller/Library/Caches/cargo-zigbuild/0.17.0/zigcc-aarch64-unknown-linux-musl.sh` failed: exit status: 1
|
= note: LC_ALL="C" PATH="/Users/reubenmiller/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/re …
```
=> fix(build): use fixed ziglang 0.10.1 due to build issue with 0.11.0

get-thin-edge_io.sh
Improve the get thin-edge.io install script to avoid rate limiting enforced by GitHub. Sometimes the install script was failing due to the latest version detection logic which relied on the `api.github.com` endpoint which has fairly low limits for unauthenticated requests.
For example, if a user does too many requests, then the following response is returned by GitHub.
```
{"message":"API rate limit exceeded for 80.133.228.217. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
The error was mostly occurred in the integration test runs in GitHub as the rate limiting would be hit due to parallel workflow runs which …
=> fix(install): improve reliability of latest version detection by using non rate limited api

docs/src/references/tedge-configuration-management.md
Spec of `tedge-configuration-plguin`.
* Notification mechanism. State machine will do most probably. See the thread https://github.com/thin-edge/thin-edge.io/pull/2097#discussion_r1275096672
* File deletion. Mapper will do. See the thread https://github.com/thin-edge/thin-edge.io/pull/2097#discussion_r1275108499
#2098
=> tedge-configuration-plugin specification

.github/workflows/integration-tests.yml
The full report is still visible in the test runner, but hiding the passed tests helps reduce the noise in PRs.
For example, the "Passed tests" section will be left out of the comment posted after the integration tests have passed. Below shows an example of how the section was previously included by default, and with ~240 tests, it made scrolling through the PR very difficult.
<br/>
=> test(ci): reduce PR test report output by hiding passed tests

Cargo.lock, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_agent/src/tedge_to_te_converter/converter.rs, crates/core/tedge_agent/src/tedge_to_te_converter/mod.rs, crates/core/tedge_agent/src/tedge_to_te_converter/tests.rs, tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
This new actor translates the `tedge/#` topics to `te/#` topics.
| tedge topic | te topic | other updates
|---|---|---|
|tedge/measurements| te/device/main///m/ ||
| tedge/measurements/child | te/device/child///m/ ||
| tedge/alarms/severity/alarm_type|te/device/main///a/alarm_type|add severity into payload|
|tedge/alarms/severity/child/alarm_type|te/device/child///a/alarm_type|add severity into payload|
|tedge/events/event_type|te/device/main///e/event_type||
|tedge/events/child/event_type|te/device/child///e/event_type||
| tedge/health/service-name | te/device/main/service/service-name/status/health||
|tedge/health/child/service-name| te/device/child/service/service-name/status/health||
https://github.com/thin-edge/thin-edge.io/issues/2079
=> Implement a converter that bridges the old MEA topics to the new ones

crates/core/tedge_agent/src/tedge_to_te_converter/converter.rs, crates/core/tedge_agent/src/tedge_to_te_converter/tests.rs, tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- Enforce the retain flag when the `tedge` messages are republished on `te` topics 
- integration tests 
https://github.com/thin-edge/thin-edge.io/issues/2147#
=> tedge legacy health messages are not being republished on the te/ topic with the retained flag

crates/core/tedge/src/cli/init.rs, tests/RobotFramework/tests/customizing/tedge_init.robot
Fix/add group permissions on the config dir (e.g. `/etc/tedge`) creation when calling the `tedge init` command.
<br/>
=> fix(tedge init): add missing group permissions on base config_dir

justfile
Make it easier for users to run the `just check` by using cargo-zigbuild if available. This allows users using MacOS m1 (aarch64 darwin) to run the code checks without having to build in a linux environment (running `just release` to build natively on MacOS m1 for LInux is already possible).
If `cargo-zigbuild` is not installed, then `cargo` will be used (this is auto detected in the justfile. The user can also override the setting by using:
```sh
just CARGO=cargo check
```
**Other changes*
* Remove deprecated docs tasks for the just file.
<br/>
=> dev(checks): use zigbuild to run just check task if it is available

crates/core/tedge_agent/src/tedge_to_te_converter/converter.rs, crates/core/tedge_agent/src/tedge_to_te_converter/tests.rs, tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
The `tedge-to-te` topic converter was not properly handling the `alarm` clear message. This PR addresses this issue.
Also, added the tests that cover all the missing topic conversion cases like empty messages, empty topics, Unsupported topics, etc.
https://github.com/thin-edge/thin-edge.io/issues/2151
=> Clearing an alarm causes an EOL error

crates/extensions/c8y_log_manager/src/actor.rs, tests/RobotFramework/tests/cumulocity/log/c8y-log-plugin.toml, tests/RobotFramework/tests/cumulocity/log/example.log, tests/RobotFramework/tests/cumulocity/log/log_operation.robot
This PR consists of two parts:
1. Adding missing Robot framework tests for c8y-log-plugin.
2. Fixing bug in log manager: It returns error message instead of Ok(()) which cause mqtt actor termination
<br/>
=> Adding missing tests for c8y-log-manager and fixing a bug that causes mqtt actor termination

Cargo.lock, crates/common/download/src/download.rs, crates/common/flockfile/src/unix.rs, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/system_services/log_config.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/src/main.rs, crates/core/tedge_watchdog/src/main.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, docs/src/references/c8y-configuration-management.md, docs/src/references/c8y-firmware-management.md, docs/src/references/c8y-log-management.md, docs/src/references/tedge-configuration-management.md, docs/src/references/tedge-log-management.md, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_firmware_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
`--debug` flag used to increase log verbosity is very noisy, as it enables `trace` (lowest level) logs from all modules, as well as dependencies.
On the contrary, `RUST_LOG` environment variable can be used to set different logging levels on a per-module basis, allowing to e.g. set `trace` for a module one is currently working on and `info` on the rest, or limiting logging only to the current crate.
As such, `set_log_level` function was modified to not overide a `$RUST_LOG` filter if it is present. If this variable is not present, it sets log level globally as usual.
<br/>
=> Allow log filtering with $RUST_LOG

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge_api/src/entity.rs, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/topic.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/json.rs, crates/extensions/c8y_mapper_ext/src/serializer.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot, tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-c8y.robot, tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
__The main point of this PR is to implement a concrete use-case of the EntityStore and  be in a better position to evaluate and improve this new API.__
Update the c8y-mapper to translate the measurements received on the `te/+/+/+/+/m/+` topics.
https://github.com/thin-edge/thin-edge.io/issues/2082
=> Update c8y-mapper to consume `te` measurements

crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/messages.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
As the `tedge-agent` can't request the `new jwt` token, a new `jwt` token has to be sent to the `tedge-agent` with the `software update`  request.
https://github.com/thin-edge/thin-edge.io/issues/2175
=> The mapper must not forward expired JWT tokens to the agent

crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/connect/error.rs
This PR fixes an issue of returning exit code 0 when the connection test for any cloud fails. Additionally, I removed redundant messages, which will now be covered by returned error messages.
#2170
<br/>
=> Fix the wrong exit code after the cloud connection test failure

ci/build_scripts/build.sh, ci/build_scripts/package.sh, ci/build_scripts/version.sh, configuration/package_manifests/nfpm.c8y-configuration-plugin.yaml, configuration/package_manifests/nfpm.c8y-firmware-plugin.yaml, configuration/package_manifests/nfpm.c8y-log-plugin.yaml, configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml, configuration/package_manifests/nfpm.sawtooth-publisher.yaml, configuration/package_manifests/nfpm.tedge-agent.yaml, configuration/package_manifests/nfpm.tedge-apt-plugin.yaml, configuration/package_manifests/nfpm.tedge-dummy-plugin.yaml, configuration/package_manifests/nfpm.tedge-mapper.yaml, configuration/package_manifests/nfpm.tedge-watchdog.yaml, configuration/package_manifests/nfpm.tedge.yaml, configuration/package_manifests/virtual/nfpm.tedge-full.yaml, configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml, justfile
Update version scheme used in packages to align with best practices.
**General**
* Use 7 letters to represent the commit hash to align with GitHub's default used in the UI
* Refactor version scripts to a single version.sh script which is sourced in the relevant scripts
**apk**
* Use version schema `x.x.x_rcN+gabcdef0-r0` to align with [Alpine Linux format](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#pkgver)
**tarball**
* Use version schema `x.x.x-rcN+gabcdef0` so that cloudsmith sorts packages built on the main branch correctly
<br/>
=> packaging: align version schema used in packaging

Cargo.lock, Cargo.toml
Limit `clap` dependency to 4.1.x as anything higher enforces a minimum supported rust version (MSRV) of 1.70 (where as the current MSRV version of the project is 1.67). The version is limited to 4.1.x by using the [tilde-requirement](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements) syntax.
clap released a new version, [4.4.0](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#440---2023-08-24), however it seems the dependency within 4.3.x includes a dependency to `clap_lex` where the bump in MSRV was coupled only with a patch version bump (and not a minor version bump). This causes the 4.3.x versions to automatically pull in the more recent `clap_lex` package via Rusts default
<br/>
Some additional context:
* …
=> build: limit clap version to 4.2.x to prevent MSRV bump to 1.70

crates/common/flockfile/src/unix.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/main.rs
This PR disable lock file mechanism when `{run.path}/lock` does not exist or directory is not writable.
#2131
<br/>
=> Disable lock file if directory does not exist or no permissions

crates/core/tedge/src/cli/connect/command.rs
By using a persistent session, `tedge connect c8y --test` might return false positive, telling the connection with c8y is okay, while the received tokens were simply stalled and persisted by mistake. => All MQTT connections used to retrieve JWT token must set the clean session flag to true.
Start as for https://github.com/thin-edge/thin-edge.io/issues/2207, *but* on a device that is actively connected for a while and where `tedge connect c8y --test.` has not been run during this period.
1. Ensure that the used network interface is up.
2. Run the command tedge connect c8y. 
3. Bring down the network interface `sudo up link set wlan down` or just disconnect your network cable.
4. Run the command `tedge connect c8y --test.`
5. __Unexpectedly, the previous command tells everything is fine …
=> Fix: tedge connect c8y --test must not use a persistent MQTT session

crates/core/tedge/src/cli/connect/command.rs
This PR changes exit code to `0` and prevents from running tedge components if service manager is not present.
#2172
<br/>
=> Exit with code 0 if service manager not present

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, plugins/tedge_log_plugin/src/main.rs
Fix some inconsistencies with the tedge-log-plugin
* Use the mqtt client settings instead of the bind settings when creating the mqtt client
* Use DEBUG log level when starting the plugin with `--debug` (to align with other plugins)
* Build the mqtt client's session name using the plugin name, root and identifier topics to avoid conflicts between multiple tedge-log-plugin instances running as different child devices all on the same broker
<br/>
=> fix: align tedge-log-plugin settings

docs/src/references/tedge-configuration-management.md, docs/src/references/tedge-log-management.md
See the comment here. https://github.com/thin-edge/thin-edge.io/pull/2108#discussion_r1310712532
During the work of c8y-mapper, we decided to use the device name inside `tedgeUrl` instead of using "main". So, this PR updates the specs to align with the implementation.
#2048
=> Update tedge plugin specs after c8y-mapper change

.github/workflows/pull-request-checks.yml, crates/common/download/src/download.rs, crates/extensions/tedge_downloader_ext/src/tests.rs
By removing SDKs for other languages that we don't need, about 15GB of disk space was freed. `download` crate tests should no longer fail due to lack of disk space. As such, the tests have been reenabled.
- #2208
<br/>
=> CI: Free some disk space by deleting unneeded SDKs

crates/common/tedge_config_macros/impl/src/lib.rs
`#[tedge_config(rename = "name-with-hyphens")]` panicked because of hyphens in the rename field. This occured because a test that was being generated to test that field did not remove hyphens from the identifier name, e.g:
> error: proc macro panicked
> ...
>     = help: message:
`"example_value_can_be_deserialized_for_run_name-with-hyphens_example_0"` is not a valid identifier
Was fixed by replacing hyphens with underscores in identifier name.
<br/>
=> Fix panic in tedge_config macro when `-` present in field name

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/json_c8y.rs, crates/core/tedge_api/src/event.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot, tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-c8y.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Events for **c8y** should be consumed from the mqtt topic `te/+/+/+/+/e/+` instead of `tedge/events/#`. 
#2214
=> Events for c8y are consumed from te/+/+/+/+/e/+

plugins/c8y_remote_access_plugin/src/input.rs, plugins/c8y_remote_access_plugin/src/main.rs
This PR add support for `config-dir` flag in c8y-remote-access-plugin
#2112
<br/>
=> Add support for `config-dir` flag

Cargo.lock, crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/plugin_sm/tests/plugin.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/restart_manager/actor.rs, crates/core/tedge_agent/src/software_manager/actor.rs, tests/RobotFramework/tests/cumulocity/restart/on_shutdown.sh, tests/RobotFramework/tests/cumulocity/restart/restart_device.robot, tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
This PR add improvements to `tedge agent` modules that run `command`. They run the `sudo` command only if it is available. If it is not, module try to run command without `sudo` and pass error if occurred. More in #2096 
* #2096 
<br/>
=> Check if sudo is available when using tedge agent operations

Cargo.lock, crates/extensions/c8y_http_proxy/Cargo.toml, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/tests.rs
While retrying the HTTP call on the expired jwt token, use the freshly retrieved token for authentication in the subsequent HTTP calls.
https://github.com/thin-edge/thin-edge.io/issues/2222
=> c8y-log-plugin fails to upload binary due to 401 error

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/extensions/tedge_log_manager/src/config.rs, crates/extensions/tedge_log_manager/src/tests.rs, plugins/tedge_log_plugin/src/main.rs, tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
Settings `mqtt.topic_root` have been `mqtt.device_topic_id` added to tedge-config and used inside tedge-agent, enabling the agent to be run on a child device and connect to a parent's MQTT broker.
Also `--mqtt-topic-root` and `--device-topic-id` flags have been added to `tedge-agent`, which can be used to override these values if taken from a configuration file.
`tedge-log-manager` was updated to use new `mqtt.topic_root` and `mqtt.device_topic_id` config options, still allowing them to be overridden by cli flags. The naming of the flags was made consistent with `tedge-agent` and some code was cleaned up.
#2018
This PR completes the _Make tedge-agent running on any device_ section of [this TODO list](https://github.com/thin-edge/thin-edge.io/issues/2018#issuecomment-1705325553)
=> Add `mqtt.topic_root` and `mqtt.device_topic_id` options

crates/core/tedge/src/cli/mqtt/mod.rs, crates/core/tedge/src/cli/mqtt/publish.rs, crates/core/tedge/src/cli/mqtt/subscribe.rs, crates/extensions/c8y_http_proxy/src/actor.rs, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Fix the tedge device's internal ID lookup while sending large events over HTTP, when the payload doesn't contain the `source` field.
A small adjustment was also included to increase the max packet size in the `tedge mqtt pub|sub` commands as these are used in the tests to verify the fix. Before the the `tedge mqtt pub` was using the default package size. Now the `tedge mqtt pub|sub` have aligned the default packet size with the tedge-agent, to 10MB.
https://github.com/thin-edge/thin-edge.io/issues/2234
=> Fix device_id lookup while sending large events over HTTP #2234

Cargo.lock, crates/common/mqtt_channel/Cargo.toml, crates/common/mqtt_channel/src/config.rs, crates/common/mqtt_channel/src/connection.rs
PR #2233 introduced some `info!` logging statements to MQTT connection code, so that the user could see what's happening.
However, this code printed out the contents of the AuthenticationConfig struct which contained root certificate store and a client private key if client authentication option was used.
The intent was to print out the certificate paths, but what was printed was the contents, potentially including secrets.
Fortunately it was caught quickly by @reubenmiller.
I think the biggest factor that contributed to this mistake was keeping secrets together with other safe-to-print fields, without using any marker type to denote that `ClientAuthConfig.key` is a secret, disabling it's `Debug` implementation so that it can't be accidentally printed out in the first place. Crates like …
=> Don't log authentication configuration when connecting to MQTT broker

crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/actor.rs, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/cumulocity/configuration/config2.json, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
Fix the problem of not updating the internal representation of config files. This applies to all plugins that use `FsFileWatcher`: 
-  `tedge-log-plugin`
-  `c8y-log-plugin`
- `c8y-configuration-plugin`
Additionally this PR fixes unsafe `unwrap` while sending mqtt message inside the  `c8y-configuration-plugin` (that could lead to rust panic if there was any problem with MQTT actor)
The integration tests were also extended to cover these scenarios to ensure it functions as expected (taken from https://github.com/thin-edge/thin-edge.io/pull/2260):
* add library function to check service status of child devices and switch to new tedge interface
* use recent timestamp instead of 1970 as this is more aligned to how the UI behaves
* fix timestamp bug where the tests were using a fixed timezone …
=> Fix: plugins don't update their internal representation of config files on file change

crates/common/tedge_utils/src/paths.rs, crates/core/tedge/src/cli/connect/command.rs
This PR extends `DraftFile` with `mode` option that allows setting the permission of the target file after `persist` operation. It is then used to set tedge mosquitto configuration file permissions to 644.
* #2154
<br/>
=> Change tedge mosquitto configuration file permissions to 644

configuration/package_manifests/virtual/nfpm.tedge-full.yaml, configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
Fixing a problem with the rpm virtual packages `tedge-full` and `tedge-minimal` version requirement which caused a mismatch in the expected and actual versions.
Changes to nfpm v2.33.1 enforced the usage of the release suffix for rpm packages causing the mismatch.
Unfortunately this fix is not the cleanest, but is in place to quickly fix the rpm packages in cloudsmith. Whilst it is not critical to have this fix, once a more reliable way to determine the rpm specific version number prior to building the package, it should be used in place of hard coding the suffix.
<br/>
https://github.com/thin-edge/thin-edge.io/issues/2285
=> fix(packaging): use release suffix in version dependency to avoid version mismatches

crates/extensions/c8y_auth_proxy/src/server.rs, crates/extensions/c8y_auth_proxy/src/tokens.rs
Refactor the handler to make it more idiomatic axum code, and fix the handling of query strings (i.e. pass them through to Cumulocity) in `c8y_auth_proxy`.
https://github.com/thin-edge/thin-edge.io/issues/2282
=> Improve error handling and fix query string handling

crates/extensions/az_mapper_ext/src/converter.rs, crates/extensions/az_mapper_ext/src/error.rs
Issue:
Azure mapper converter was failing to translate the service health message `timestamp`, because it's an integer number.
Proposed solution/fix:
Forward the health status message payload to Azure Cloud without translating.
As a followup tasks
https://github.com/thin-edge/thin-edge.io/issues/2256
=> azure tedge mapper fails to translate health status messages

crates/core/tedge_agent/src/restart_manager/tests.rs, crates/core/tedge_agent/src/tedge_operation_converter/tests.rs, crates/core/tedge_api/src/messages.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_config_manager/src/tests.rs, crates/extensions/tedge_log_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/tests.rs
As suggested by @Bravo555 with https://github.com/thin-edge/thin-edge.io/pull/2245#discussion_r1332923226, the reason field makes sense only for a Failed command.
Attached the `reason` field to the only case where it makes sense: a `Failed` command.
```
#[derive(Debug, Deserialize, Serialize, PartialEq, Eq, Clone)]
#[serde(rename_all = "camelCase", tag = "status")]
pub enum CommandStatus {
Init,
Executing,
Successful,
Failed { reason: String },
}
```
<br/>
=> Use serde tag enum representation for CommandStatus

Cargo.lock, plugins/c8y_remote_access_plugin/Cargo.toml, plugins/c8y_remote_access_plugin/src/main.rs
This PR changes the executable path in child process from default one: `/usr/bin/c8y-remote-access-plugin` to one that was used to call itself. More in #2132.
* #2132 
<br/>
=> Run remote access plugin with correct executable path in child process

crates/extensions/tedge_downloader_ext/src/actor.rs, crates/extensions/tedge_downloader_ext/src/tests.rs
This change is required for c8y-mapper's enhancement to download a file per an operation. For example, if the key is only string, it's difficult to distinguish which operation (software, firmware, config_update) fires the download request.
So, this kind of example usage will be possible with this change, sending `DownloadRequest`:
```rust
struct DownloadKey {
op_type: OperationType,
id: String
}
self.message_box
.download_sender
.send((DownloadKey{ op_type: OperationType::ConfigUpdate, id: "abcd1234".into() }, download_request))
.await?;
```
#2292
=> Accept any type as the key of the downloader actor

Cargo.lock, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/file_transfer_server/actor.rs, crates/core/tedge_agent/src/file_transfer_server/http_rest.rs, crates/core/tedge_api/Cargo.toml, crates/core/tedge_api/src/lib.rs, crates/core/tedge_api/src/path.rs, crates/extensions/c8y_config_manager/src/config.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/Cargo.toml, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_firmware_manager/src/config.rs, crates/extensions/c8y_firmware_manager/src/lib.rs, crates/extensions/c8y_firmware_manager/src/operation.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
This directory was introduced by c8y-firmware-plugin, however, now cloud mappers need to download files from remote. The cache directory must be used also by cloud mappers to avoid multiple file downloads for the same file.
The directory usage will be covered by robot tests during #2292 work.
In addition, to solve this comment https://github.com/thin-edge/thin-edge.io/pull/2293#discussion_r1338429388, I introduced `DataDir`(crates/core/tedge_api/src/path.rs) struct, which is a wrapper of `Utf8PathBuf` with refactoring codes.
#2292
=> tedge-agent creates /var/tedge/cache directory on start-up

Cargo.toml, crates/core/tedge_api/src/mqtt_topics.rs
In a typical case of a fencepost error, segments were confused with segment separators and thus in topics with 4 slashes erroneously passed the "topic has max of 4 segments" check. This would later cause an underflow when generated missing topic segments, leading to a string of size near `usize::MAX` being allocated.
<br/>
As for the error itself, I can identify 3 potential causes:
1. No overflow checks in release mode. This is addressed in this PR by enabling overflow checks in release profile. thin-edge isn't really math-heavy, so I doubt it will impact performance, but it can provide additional safety.
2. Lacking test coverage. The error conditions producing `Result::Error` variants were not sufficiently tested. This is also addressed by this PR.
3. And i think the one we should think …
=> Fix integer underflow in EntityTopicId parsing

Cargo.lock, Cargo.toml
Affected tungstenite crate was bumped to the latest version 0.20.1
<br/>
=> Resolve RUSTSEC-2023-0065

crates/core/tedge_api/src/entity_store.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs
To solve the issue, registration message conversion was changed to only convert if the registration message affected any entities. An update is considered to affect an entity if the entity was previously registered and the update changes any part of entity metadata (i.e. is different from a previous one) or adds or removes children of a device.
As part of the fix, it was necessary to change the `EntityRegistrationMessage::payload` field. It was renamed to `other` and made to not include `@id`, `@type`, `@parent`, etc. fields that are already direct fields of `EntityRegistrationMessage`.
A test `does_not_duplicate_global_registration_2311` was added to ensure the fix had intended effect. The fix was confirmed to turn the test from red to green.
One non-intuitive part is that the …
=> Fix 2311: don't publish c8y register message twice

Cargo.lock, crates/extensions/tedge_log_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/config.rs, crates/extensions/tedge_log_manager/src/tests.rs, plugins/tedge_log_plugin/Cargo.toml, plugins/tedge_log_plugin/src/lib.rs
Replace previous log plugin topics parsing with the Mqtt schema. Additionally this PR removes `current_operations` field that is not used after #2108 changes.
<br/>
=> Parse log plugin topics using new mqtt schema

Cargo.lock, crates/core/c8y_api/src/json_c8y.rs, crates/core/tedge_api/Cargo.toml, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot, tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot, tests/RobotFramework/tests/cumulocity/restart/restart_device_child.robot, tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/customizing/data_path_config.robot
The XIDs (external IDs) of devices created using the operations directory file watcher mechanism were changed in #2266 breaking backward compatibility. So, reverting those changes. As the file watcher mechanism was a lower level API specifically designed for C8y, it makes sense to keep the directory name and XID the same.
<br/>
=> Do not change XIDs of child devices created via ops dir watcher

crates/core/tedge_api/src/health.rs, crates/core/tedge_watchdog/src/error.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs
To unify the timestamps that are used across `thin-edge`, Update the `health_status_up_message` API to use RFC3339 time format rather than `unix` timestamp.
https://github.com/thin-edge/thin-edge.io/issues/2237
=> tedge-mapper-aws health message uses two different timestamp formats for up and down messages

crates/common/tedge_config/Cargo.toml, crates/common/tedge_config_macros/Cargo.toml, crates/common/tedge_config_macros/impl/src/input/parse.rs, crates/common/tedge_config_macros/impl/src/input/validate.rs, crates/common/tedge_config_macros/impl/src/lib.rs, crates/common/tedge_config_macros/impl/src/query.rs, crates/common/tedge_config_macros/src/define_tedge_config_docs.md, crates/common/tedge_config_macros/tests/arc.rs
Add support for `Arc<str>` in the `define_tedge_config!` macro.
#2259
=> Support `Arc<str>` for fields in `tedge_config`

Cargo.lock, crates/common/tedge_utils/src/futures.rs, crates/common/tedge_utils/src/lib.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/tedge_mqtt_ext/Cargo.toml, crates/extensions/tedge_mqtt_ext/src/lib.rs, tests/RobotFramework/tests/cumulocity/benchmarks/benchmark.py, tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
If tedge-mapper is overwhelmed with messages, this causes a deadlock, preventing any further processing of MQTT messages until the mapper is restarted. The root cause of the deadlock is detailed in https://github.com/thin-edge/thin-edge.io/issues/2326#issuecomment-1753214566, but the pertinent information here is that the MQTT actor blocks itself, waiting on outgoing messages to be processed before it can process incoming messages, but stuck in the middle of processing an incoming message.
This PR spawns a task to process outgoing messages, which allows the mapper to process incoming and outgoing messages concurrently. This avoids the deadlock scenario that is the root cause of the bug.
Running this change locally, I can reliably send 20,000 messages to the mapper running on my laptop …
=> Enable concurrent processing of incoming and outgoing MQTT messages

crates/core/tedge_api/src/entity_store.rs, crates/extensions/c8y_mapper_ext/src/config_operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs
As commented in https://github.com/thin-edge/thin-edge.io/pull/2303#discussion_r1356364285, we have many patterns using `get()` or `get_by_external_id()` and map them `None` to `Err`. We should stop the same mapping every time.
The new API methods return `Error::UnknownEntity` instead of `None`.
#2303
=> Add try_get() and try_get_by_external_id() to entity_store

crates/extensions/c8y_auth_proxy/src/server.rs, docs/src/references/tedge-cumulocity-proxy.md
This PR adds some public facing documentation for c8y_auth_proxy, so customers know it exists and can make use of it if they wish. It also improves the proxy's handling of large bodies, proactively checking the JWT is valid before making the real request.
#2174
=> Add reference documentation for `c8y_auth_proxy`

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/inventory.rs, crates/extensions/c8y_mapper_ext/src/lib.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, docs/src/references/mappers/c8y-mapper.md, docs/src/references/mqtt-api.md, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
PR to communicate the proposed mapping of the `/twin/` topics including integration tests. This PR can be used for the actual implementation.
<br/>
https://github.com/thin-edge/thin-edge.io/issues/2279
=> feat(mqtt): add docs for tedge data/inventory topic

tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
System test for clearing inventory fragments via twin/ topic
<br/>
=> System test for clearing inventory fragments via twin/ topic

tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Fixing a git merging error after merging https://github.com/thin-edge/thin-edge.io/pull/2356 into main (due to the PR not being up to date with the main branch prior to merging).
<br/>
=> fix placement of assertions due to a git merging error

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge/src/cli/connect/bridge_config_aws.rs, crates/core/tedge/src/cli/connect/bridge_config_azure.rs, crates/core/tedge_api/src/health.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/extensions/aws_mapper_ext/src/converter.rs, crates/extensions/az_mapper_ext/src/converter.rs, crates/extensions/c8y_firmware_manager/src/config.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot, tests/RobotFramework/tests/aws/aws_telemetry.robot, tests/RobotFramework/tests/azure/azure_telemetry.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
This PR completes the migration to new health topics. Besides switching over AWS and Azure mappers to new health status topics, some leftovers of old health check topics were also removed.
`tedge/health/` and `tedge/health-check` topics now no longer appear in the integration test log (besides the test checking upgradability from previous version, which is expected).
- #2351
Next step will be to change or add relevant documentation related to health status/check messages and the health checking mechanism, as described in #2348.
=> Health status on AWS and Azure mappers

crates/core/tedge_api/src/entity_store.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/inventory.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/tedge_health_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/test_helpers.rs, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
The bug was caused by the mapper not removing the cleared fragment from its local inventory cache, when a clear twin data message is received. When the old value existed in the cache, the duplicate message that came after the clear message was getting ignored, because it is the same as the existing value.
Support setting twin property after it has been cleared.
Tasks:
https://github.com/thin-edge/thin-edge.io/issues/2365
=> fix: support sending previously cleared twin property value

docs/src/operate/c8y/c8y_service_monitoring.md, docs/src/operate/configuration/config-mapper-mqtt-topics.md, docs/src/operate/monitoring/enable_tedge_watchdog_using_systemd.md, docs/src/operate/troubleshooting/monitor_tedge_health.md, docs/src/references/mappers/c8y-mapper.md, docs/src/references/mqtt-api.md
This PR updates the markdown documentation regarding health statuses and health checks.
- #2348
=> Health status documentation

crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/c8y_mapper_ext/Cargo.toml, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs, crates/extensions/tedge_health_ext/src/lib.rs, tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Some additions:
1. A C8y converter test was added to make sure that the emitted service creation message is valid if `service.type` is empty.
2. `c8y_api::inventory` functions which created C8y smartrest messages were changed to return `Result`. Currently we only check if values marked as mandatory in [SmartREST reference documentation][1] are not empty, but we could do more validation in the future.
3. Added `ConversionError::UnexpectedError` variant, which can be constructed from an `anyhow::Error`.
_Unexpected_ part is supposed to denote that the error was not related due to invalid input, or the user doing something wrong, but some unexpected conditions occured that makes it so that the request cannot be completed. Like a `panic!`, it can be used when there is a logic error on part of …
=> fix #2383: Use "service" if service type missing

crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
If the child device directory the child device operation directories follow the default external id naming scheme, they are auto-registered with the right topic id and name derived from that external id.
https://github.com/thin-edge/thin-edge.io/issues/2389
=> Fix auto-registration of child device op dirs #2389

crates/extensions/tedge_config_manager/src/lib.rs, crates/extensions/tedge_log_manager/src/lib.rs, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/configuration/backward_compatibility.robot, tests/RobotFramework/tests/cumulocity/configuration/c8y-configuration-plugin.toml, tests/RobotFramework/tests/cumulocity/log/backward_compatibility.robot
The `tedge-config-plugin` and `tedge-log-plugin` will migrate their legacy counterparts' configuration files, if found during initialization.
<br/>
=> Tedge operation plugins to migrate legacy config file contents

crates/common/download/examples/simple_download.rs, crates/common/download/src/lib.rs, tests/RobotFramework/README.md, tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot, tests/RobotFramework/tests/installation/install_tedge.robot, tests/RobotFramework/tests/tedge/call_tedge.robot, tests/images/debian-systemd/files/bootstrap.sh
Updating tests to align with new 0.13.0 release which broken some tests which used the latest official released version.
* Replace usage of the now deprecated `get-thin_edge_io.sh` script in place of the newer `thin-edge.io/install.sh` script (hosted in https://github.com/thin-edge/thin-edge.io-website)
* Updated assertions which relied on the older clap cli formatting (e.g. `USAGE:` => `Usage:`)
Notes:
* There is still one test which relies on the older `get-thin_edge_io.sh` script as this script allows installing a specific version but the new version is not (but this is planned)
<br/>
=> tests: update tests after latest 0.13.0 release

crates/common/tedge_config_macros/impl/src/input/parse.rs, crates/common/tedge_config_macros/impl/src/lib.rs
https://github.com/thin-edge/thin-edge.io/pull/2398/files/313cc0efaac938fe47b1267d63a3d89cbb31c312..954da3d0246b6e6db4b5cd3d41421f5864ad9088#r1380338718 highlighted a usability issue with `define_tedge_config` and default values, which can either be provided using `default(value = true)` or `default(variable = "Ipv4Addr::LOCALHOST")`. The distinction between these two formats is important, but subtle.
This PR adds a custom error message for the case which caused confusion, pointing the user towards a suggested solution. See the screenshot below (or the added test) for the error that appears:
<br/>
=> Add a custom error message for invalid use of `default(value = ...)` in `define_tedge_config!`

crates/extensions/tedge_config_manager/src/lib.rs, crates/extensions/tedge_config_manager/src/tests.rs, crates/extensions/tedge_log_manager/src/lib.rs, crates/extensions/tedge_log_manager/src/tests.rs, plugins/tedge_configuration_plugin/src/lib.rs, plugins/tedge_log_plugin/src/lib.rs
Follow-up of #2399 to use async `tedge_utils::file::move_file` API instead if `std::fs::rename` to move config files.
<br/>
=> Tedge ops plugins init use async move_file

docs/src/contribute/design/mqtt-topic-design.md, docs/src/contribute/writing-documentation/markdown-components.md, docs/src/operate/c8y/child_device_config_management_agent.md, docs/src/operate/c8y/retrieve_jwt_token_from_cumulocity.md, docs/src/operate/configuration/child-device-config-management.md, docs/src/operate/monitoring/enable_tedge_watchdog_using_systemd.md, docs/src/operate/telemetry/pub_sub.md, docs/src/operate/troubleshooting/monitor_tedge_health.md, docs/src/operate/troubleshooting/trouble_shooting_monitoring.md, docs/src/references/agent/device-management-api.md, docs/src/references/agent/restart-operation.md, docs/src/references/agent/software-management.md, docs/src/references/agent/tedge-configuration-management.md, docs/src/references/agent/tedge-log-management.md, docs/src/references/mappers/c8y-mapper.md, docs/src/references/mqtt-api.md, docs/src/start/connect-aws.md, docs/src/start/connect-azure.md, docs/src/start/connect-c8y.md, docs/src/start/device-monitoring.md, docs/src/start/getting-started.md, docs/src/start/raise-alarm.md, docs/src/start/send-events.md, docs/src/start/send-thin-edge-data.md, docs/src/understand/tedge-mapper.md, docs/src/understand/thin-edge-json.md
Enforce the display of the new MQTT v1 format in all te2mqtt code blocks, as currently the 0.13.0 docs still show the legacy MQTT api when the `formats=` is missing on the directive.
The global default needs to be kept at legacy so it does not break the older doc implementation, or at least until the setting can be made to auto detect which version is being shown.
<br/>
=> docs: enforce/normalize v1 format on all te2mqtt code blocks

crates/common/tedge_config/src/tedge_config_cli/models/auto.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
Simple follow up task suggested here https://github.com/thin-edge/thin-edge.io/pull/2398#discussion_r1380463768
- Use default(variable = "AutoFlag::Auto") for `c8y.bridge.include.local_cleansession`
- Remove `impl From<&str> for AutoFlag` as no more required.
<br/>
=> Use default(variable = "AutoFlag::Auto")

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Include a more readable version of the mqtt messages received during a system test by including a separate mqtt log output section in the Robot Framework `Get Logs` keyword.
The benefits are:
* Easier to read and see errors by only including the timestamp, topic and message (don't included any additional meta information that is store in the mqtt-logger output, .e.g. hex into.)
The same detailed information is still provided within the journald output (to see the interactions of the mqtt messages with the service log entries), however the messages are more difficult to read and isolate from the log entries for cases where the tester only cares about the mqtt messages being sent.
**Example**
The logs can easily be copied/pasted from the system test report for detailed analysis.
<br/>
=> tests: include more readable mqtt logs in Get Logs keyword

tests/RobotFramework/tests/configuration/lock_file.robot
Improving flaky system test:
```
Check PID number in lock file after restarting the services
```
Suspected root cause:
[systemctl restart](https://man7.org/linux/man-pages/man1/systemctl.1.html) does not wait for all file descriptors to be flushed before returning which is most likely the reason why some pid information is still being detected via pgrep -f. Using stop/start does not suffer from this problem.
flake-finder was used to run the suite of tests 200 times and all passed:
```
Overall: PASSED
Results: 200 iterations, 200 passed, 0 failed
Elapsed time: 9:20:38.046294
```
And a second run of 300 iterations all passed except for 1 unrelated error due to a loss of connectivity during the system test run:
```
Overall: FAILED
Results: 300 iterations, 299 passed, 1 failed
Elapsed time: …
```
=> tests: use stop/start over restart for service to improve flaky system test

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
system test improvement which hides the `c8y/s/dat` message payload from the log output so that the reports can be published to github issues to assist with debugging of flaky system tests.
Note: the implementation is not ideal as it is fairly fragile in nature as the mqtt messages use journald to provide time bases querying...however this introduces some complexity in parsing the log entries. Most likely a different way to handle this will be required in the future.
<br/>
=> tests: hide cumulocity iot token message from the test log output

crates/extensions/c8y_mapper_ext/src/config_operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs
Disable operation support for:
* nested child devices
* services on any device
This is just a temporary fix for #2409 to avoid nested child devices and services from messing up the mapper's `operations` directory, which only supports immediate child devices. A proper fix will be coming in a later PR.
https://github.com/thin-edge/thin-edge.io/issues/2409
=> Disable nested child device operation support #2409

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, docs/src/contribute/BUILDING.md, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/images/debian-systemd/debian-systemd.dockerfile, tests/images/debian-systemd/files/bootstrap.sh
Update dependencies (dev container and system test image):
* update to Debian 12 (bookworm)
* install mosquitto >= 2.0.18 as it fixes some bugs with the bridge that thin-edge.io is reliant on
* bump `robotframework-devicelibrary` version (for system tests)
<br/>
=> chore: update dev and system test images

crates/extensions/c8y_http_proxy/Cargo.toml, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/messages.rs, crates/extensions/c8y_http_proxy/src/tests.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
c8y-mapper should create an event for a child device via HTTP when the event size exceeds the MQTT threshold. However, it was created for the main device instead. This PR fixes the issue.
The root cause how to get the `device_id` (= c8y's **internal** device ID) in this part of the code.
https://github.com/thin-edge/thin-edge.io/blob/9dea122c94be8c50ea81f122a3d11548353703ac/crates/extensions/c8y_http_proxy/src/actor.rs#L310-L314
`c8y_event.source` needs to hold an internal ID, however, it's too early to expect to have an internal ID as `source`. If we have to use the current implementation, one has to get the device's internal ID in the mapper's converter level (= the `c8y_event` object in the the below code has to have its internal ID as `source`). Querying an internal ID should be …
=> Fix send_event() in c8y_http_proxy to create events under child devices

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/extensions/c8y_config_manager/src/config.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/src/config.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/config.rs, crates/extensions/c8y_mapper_ext/src/config.rs, docs/src/operate/c8y/child_device_config_management_agent.md, docs/src/operate/configuration/child-device-config-management.md, docs/src/references/tedge-file-transfer-service.md, tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
This commit introduces new `http.client.host` and `http.client.port` setting options. Similarly to the `mqtt.client.*` options, there is a significant difference between an address used to bind, e.g. "0.0.0.0" and an address used to connect.
`http.client.host` is now a string, which makes it possible to use DNS names where previously only IP address could be used.
https://github.com/thin-edge/thin-edge.io/issues/2391
=> add http.client.host/port setting options

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/extensions/c8y_auth_proxy/src/url.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, docs/src/references/tedge-cumulocity-proxy.md
This PR adds `c8y.proxy.client.host` and `c8y.proxy.client.port` used to connect to running C8y HTTP proxy.
- #2445
=> fix(#2445): add c8y proxy config settings

Cargo.lock, crates/common/log_manager/Cargo.toml, crates/common/log_manager/src/log_utils.rs, crates/core/tedge_agent/src/agent.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/config.rs, crates/extensions/tedge_log_manager/src/tests.rs, plugins/tedge_log_plugin/src/lib.rs
The temporary aggregated log file created by the log_manager actor will be created at the temp directory instead of the target file directory, to avoid permission issues when the log manager is not running as root.
#2443
=> Create aggregated log file in temp dir #2443

Cargo.lock, crates/extensions/tedge_script_ext/Cargo.toml, crates/extensions/tedge_script_ext/src/lib.rs
Add two optional timeouts to script execution:
- If the script is still running after the graceful_timeout, the process is sent a SIGTERM
- If the script is still running after the forceful_timeout, the process is sent a SIGKILL
<br/>
=> Kill scripts still running after a timeout

Cargo.lock, Cargo.toml, crates/core/tedge_api/src/entity_store.rs, crates/extensions/c8y_mapper_ext/Cargo.toml, crates/extensions/c8y_mapper_ext/src/converter.rs
When using a topic that is not covered by auto registration, `topic schema` the `auto_register_entity` must not return an error but it must log the message at the `debug` level.
https://github.com/thin-edge/thin-edge.io/issues/2426
=> log entry erroneously set to ERROR when handling device/services registered with custom topic schema

crates/core/tedge_api/src/messages.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs
Without giving the default reason, mappers will parse an error when command status is failed but no "reason" is given. However, "reason" filed should be optional in command payloads.
This bug was found during writing a unit test for firmware_update support.  
```
[te/device/main///cmd/firmware_update/c8y-mapper-2023-11-16T14:02:31.419901262Z] {
"status":"failed",
"remoteUrl":"https://speed.hetzner.de/10GB.bin",
"name":"10GB",
"version":"2.0.0"
}
[te/errors] missing field `reason` at line 6 column 1
```
The bahaviour is covered by the unit test `handle_log_upload_executing_and_failed_cmd_for_main_device()`.
Maybe worth adding a robot test?
<br/>
=> Give the default failure "reason" when commands failed

Cargo.lock, Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/notify.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/actor.rs
This fix consists of 2 parts:
1. `NotifyStream` impl was changed to make use of a `notify-debouncer-full` crate to delay and debounce fs events. This should also impact other consumers of `NotifyStream`.
2. Watch parameters of `tedge-log-plugin` were changed to only listen to `Modified` events, no longer listening to `FileCreated` events.
This fix was confirmed to produce only 1 reload when using following editors:
- nano
- vim
- neovim
More details regarding both parts can be found in their respective commit messages.
- #2451
=> Stop duplicate messages being sent by `tedge-log-plugin` and `tedge-configuration-plugin` on file reload

crates/core/tedge/src/cli/certificate/error.rs, crates/core/tedge/src/cli/certificate/upload.rs, tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
While uploading the certificate, if the `root` certificate path does not exist, the error message must be more verbose, providing the info about which `path` or `directory` does not exist. The error must be as below.
```
Error: failed to upload root certificate
Caused by:
Root certificate path /etc/ssl/certssaa does not exist
```
https://github.com/thin-edge/thin-edge.io/issues/2419
=> tedge cert upload c8y: ambiguous file/folder not found error - missing path in error message

crates/core/tedge/src/cli/init.rs
This PR changes `tedge init` to create:
* `<config_dir>/sm-plugins` directory with `root:root` and `755`
* `<config_dir>/operations/c8y` directory with `tedge:tedge` and `755`
The directory `sm-plugins` gets created by the `tedge-apt-plugin` package installation, therefore, keeping the same permission as it is now.
The directory `operations` is already created by `tedge init`, however, `operations/c8y` gets created on the start-up of `tedge-mapper-c8y`. From the description of #2452, the user may create the directory before they run `tedge-mapper-c8y`, so this PR changes it to create by `tedge init`.  
```
root@2749a49fbbcc:/etc/tedge/operations# ls -ltr
total 4
drwxr-xr-x 2 tedge tedge 4096 Nov 21 13:44 c8y
```
```
root@2749a49fbbcc:/etc/tedge# ls -ltr
total 32
-rw-r--r-- 1 root  root …
```
=> Create sm-plugins and operations/c8y directories by tedge init

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge_api/src/messages.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/config_operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/lib.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs
Implement `firmware_update` support to c8y-mapper as described in #2453.
#2453
=> Add firmware_update support to c8y mapper

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge_agent/src/restart_manager/actor.rs, crates/core/tedge_agent/src/restart_manager/config.rs, crates/core/tedge_agent/src/restart_manager/tests.rs, crates/core/tedge_agent/src/software_manager/actor.rs, crates/core/tedge_agent/src/software_manager/config.rs, crates/core/tedge_agent/src/software_manager/tests.rs, crates/core/tedge_agent/src/state_repository/state.rs
- A new tedge-config setting has been added: `agent.state.path`
- This path is used to store the __tedge-agent__ state across restarts.
- If for some reasons this directory cannot be used (doesn't exist or is not writable),
then  the __tedge-agent__ use `/etc/tedge/.agent` as a fallback.
- The default value for `agent.state.path` is `/data/tedge/agent`.
```
agent.state.path
The directory where the tedge-agent persists its state across restarts. 
Note: If the given directory doesn't exists, `/etc/tedge/.agent` is used as a fallback irrespective of the current setting.
Example: /data/tedge/agent
```
https://github.com/thin-edge/thin-edge.io/issues/2488
=> Add tedge config agent.state.path setting

Cargo.lock, crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/smartrest/alarm.rs, crates/core/c8y_api/src/smartrest/csv.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/message.rs, crates/core/c8y_api/src/smartrest/mod.rs, crates/core/c8y_api/src/smartrest/operations.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/c8y_api/src/smartrest/topic.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/download.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_config_manager/src/upload.rs, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_firmware_manager/src/message.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config_operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/log_upload.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_mqtt_ext/src/test_helpers.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot
This PR simplifies the CSV serialization logic for `SmartRestSetOperationToFailed`, allowing quotes inside the `failure_reason` field to be preserved.
It also makes a small tweak to an error message modified as part of #2474 to make it more generic, referring to `config-manager` instead of `tedge-configuration-plugin` as suggested by @albinsuresh. 
#2487
=> Support quotes in Cumulocity failureReason field

configuration/contrib/system/bsd/system.toml, configuration/contrib/system/openrc/system.toml, configuration/contrib/system/systemd/system.toml, crates/common/tedge_config/src/system_services/manager.rs, crates/common/tedge_config/src/system_services/manager_ext.rs, crates/common/tedge_config/src/system_services/managers/config.rs, crates/common/tedge_config/src/system_services/managers/general_manager.rs, crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs, docs/src/references/init-system-config.md, tests/PySys/misc_features/custom_init_system/system.toml, tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot, tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot, tests/images/debian-systemd/files/system.toml
This changes `tedge connect` and `tedge reconnect` to merely start `tedge-agent`, and prevents `tedge disconnect c8y` from stopping `tedge-agent` since there is no longer any cloud-specific functionality in tedge-agent.
~In order to make the feature work, a new `start` field in `system.toml`'s `init` section is required, hence this is a breaking change.~ The new `start` field is now optional as per @didier-wenzek's suggestion, so this is no longer a breaking change.
#2494
=> Don't restart tedge-agent on (re)connect

crates/core/tedge/src/cli/connect/bridge_config_azure.rs
This fixes broken mosquitto configuration generation for Azure when running `tedge connect az`. The generated configuration looked like
```
topic mesages/devicebound/# in 1 az/ devices/alpha/
topic topic methods/POST/# in 1 az/ $iothub/
//      ^^^ extra topic keyword here
```
- #2514
The unit tests for this should probably generate the configuration and do some checking of the actual output, that would have made the error here more obvious. I haven't spent any real time creating this PR beyond just fixing the bug, and my time is probably better spent elsewhere, but it seems like there's definitely a gap here.
=> Fix broken mosquitto config generation for Azure

.github/workflows/build-workflow.yml, .gitignore, ci/build_scripts/version.sh, containers/tedge/Dockerfile, containers/tedge/system.toml, justfile
Publish a container image with the multi-call thin-edge.io binary to Github container registry (ghcr.io). The container image can be used to start any of the thin-edge.io binaries, e.g. tedge-agent, tedge-mapper etc.
By default, tedge-agent will be started if no command line arguments are provided when running the container.
**Additional Notes**
The PR does not include a full end-to-end user example as there still other dependencies required (e.g. a container with mosquitto setup with thin-edge.io specific configuration etc.). This end-to-end example (including documentation will be added at a later point in time)
Once the PR is merged, then you can use the container using one of the following commands:
**Start (default) tedge-agent**
You can use the following to connect to a mosquitto …
=> feat(packaging) publish container image to ghcr

tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
In https://github.com/thin-edge/thin-edge.io/pull/2474#issuecomment-1833515269, I discussed a minor bug with the mapper's handling of operations that I found while writing robot tests. After some investigation including manual testing, I couldn't reproduce the bug, and then discovered that the issue was my understanding of the robot test code. I have now added the corrected test, as well as correcting the negative case (as due to the same misunderstanding, there was an entirely redundant assertion).
<br/>
=> Add a robot test to cover the case where mapper doesn't supply client cert

crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/lib.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/core/tedge_api/src/pending_entity_store.rs, crates/core/tedge_api/src/ring_buffer.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, design/decisions/0003-c8y-mapper.md, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
=> Ordered processing of entity registration messages before any other messages

configuration/init/systemd/c8y-firmware-plugin.service, configuration/init/systemd/tedge-agent.service, configuration/init/systemd/tedge-mapper-aws.service, configuration/init/systemd/tedge-mapper-az.service, configuration/init/systemd/tedge-mapper-c8y.service, configuration/init/systemd/tedge-mapper-collectd.service, configuration/init/systemd/tedge-watchdog.service, tests/RobotFramework/tests/customizing/data_path_config.robot, tests/RobotFramework/tests/customizing/log_path_config.robot
Run `tedge init` using root user to setup the service before starting the main process. This allows folders to be created on startup rather than during installation time (see linked ticket for further details).
**Notes**
* `+` is only used on services where the main process is run under a non-root user, e.g. `tedge` - see [systemd.service docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines)
* `-` is used when running the `tedge init` so that any initialization failure does not block attempting to start the main process (to avoid errors in non critical actions run in `tedge init` from blocking the starting of the main process)
* support for systemd versions < 231 is dropped with this PR, though the linux distributions that use systemd < 231 …
=> feat: run initializations before starting main process

Cargo.lock, crates/common/certificate/src/lib.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/renew.rs
This PR changes the behaviour of `tedge cert renew`. The work on #2502 defines that `renew` = `remove` + `create`, however, as #2512 is created, `renew` should reuse the private key and create only a new certificate.
At first, I thought I should have changed the robot tests regarding `tedge cert renew`, but I changed my mind. Indeed, the tests pass and they test the validity of the new certificate. So, I decided not to change them.
tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
- Renew the certificate
- Renew certificate fails
#2512
=> tedge cert renew uses the existing key to create a new certificate

tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Make the "Trigger Agent Restart" is flaky for two reasons:
- a reboot might take longer than expected
- the same message can be received twice
- https://github.com/thin-edge/thin-edge.io/actions/runs/7219433666
- https://github.com/thin-edge/thin-edge.io/actions/runs/7220547814
=> Make more robust a test detecting restart

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/lib.rs, crates/core/tedge_agent/src/operation_file_cache/mod.rs, crates/core/tedge_api/src/messages.rs, crates/extensions/c8y_auth_proxy/src/url.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/operations/config_update.rs, crates/extensions/tedge_config_manager/src/actor.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/configuration/generate_certificates.sh
This PR moves file download from cloud - which needs to happen when handling `config_update` operation - from the mapper to the tedge-agent, in order to simplify the mapper. However, the complexity is not eliminated and is merely moved into tedge-agent, which now needs to have special handling for Cumulocity. However, this is accepted for now, because it enables tedge-agent and tedge-mapper-c8y to be run on different containers, and eliminates the implicit dependency on File Transfer Service (a part of tedge-agent) in tedge-mapper-c8y.
The updated operation works like this:
1. The [`Download configuration type with type`](https://cumulocity.com/guides/reference/smartrest-two/#download-configuration-file-with-type-524) Smartrest message is received by the mapper
2. tedge-mapper-c8y …
=> Move `config_update` file download from tedge-mapper-c8y to tedge-agent

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml
`fail-fast` can cause the half successful state, which cause another issue in the next attempt.  
See this attempt. https://github.com/thin-edge/thin-edge.io/actions/runs/7251106688/attempts/1
This PR adds `fail-fast false` to matrix jobs. This option is `true` by default.
<br/>
=> Mark fail-fast false to matrix jobs

Cargo.lock, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/tedge_operation_converter/actor.rs, crates/core/tedge_agent/src/tedge_operation_converter/builder.rs, crates/core/tedge_agent/src/tedge_operation_converter/config.rs, crates/core/tedge_agent/src/tedge_operation_converter/mod.rs, crates/core/tedge_agent/src/tedge_operation_converter/tests.rs, crates/core/tedge_api/src/messages.rs, crates/core/tedge_api/src/workflow/error.rs, crates/core/tedge_api/src/workflow/mod.rs, crates/core/tedge_api/src/workflow/on_disk.rs, crates/core/tedge_api/src/workflow/state.rs, crates/core/tedge_api/src/workflow/supervisor.rs, crates/core/tedge_api/src/workflow/toml_config.rs, docs/src/references/agent/operation-workflow.md, tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot, tests/RobotFramework/tests/tedge_agent/workflows/native-reboot.toml
Change the way MQTT is used to trigger state updates along an operation workflow
- https://github.com/thin-edge/thin-edge.io/issues/2495
=> Improve operation workflow concurrency model

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
The tests were failing due to a time precision problem while validating MQTT messages with a `date_from` range and not because there was a duplicate message. The `date_from` value takes a UNIX timestamp without milli-second precision. But in the failing test case, the following was happening (note the time precision):
1. Entity registration message published at `10:10:35.513002` 
2. Converted message received by the logger at `10:10:36.198326`
3. The timestamp to be used in the `date_from` for the assertion was generated using `Get Unix Timestamp` API at `10:10:36.756000`. But, the `Get Unix Timestamp` returns the time: `1703067036` without millisecond precision.
When that timestamp without precision, which is  `10:10:36.000000` is used as the `date_from` in the assertion, it covers the …
=> Fix flaky entity store persistence test

crates/core/tedge_api/src/workflow/error.rs, crates/core/tedge_api/src/workflow/mod.rs, crates/core/tedge_api/src/workflow/toml_config.rs
Simply forbid scripts to be attached to the terminal states in order to avoid unexpected behavior such as:
- infinite loop if a script fails on the failed state (see https://github.com/thin-edge/thin-edge.io/issues/2484)
- race condition where the action is executed or not depending on the requester clear the state before it is observed by the agent.
This is more a workaround rather than the definitive solution.
https://github.com/thin-edge/thin-edge.io/issues/2484
=> Forbid scripts to be attached to the terminal states

ci/build_scripts/version.sh
Support release candidate info in the version (e.g. `1.0.0-rc.1`).
And adding support for auto incrementing from the previous release candidate version after merging into main (instead of bumping just the patch version)
Below shows the version numbers in different scenarios:
**Main branch - 231 commits past tag 0.13.1**
```sh
$ just version
GIT_SEMVER: 0.13.2~231+g141c1d0
APK_VERSION: 0.13.2_rc231+g141c1d0
DEB_VERSION: 0.13.2~231+g141c1d0
RPM_VERSION: 0.13.2~231+g141c1d0
CONTAINER_VERSION: 0.13.2-231-g141c1d0
TARBALL_VERSION: 0.13.2-rc231+g141c1d0
```
**Tag 1.0.0-rc.1**
```sh
$ just version
GIT_SEMVER: 1.0.0-rc.1
APK_VERSION: 1.0.0_rc.1
DEB_VERSION: 1.0.0-rc.1
RPM_VERSION: 1.0.0-rc.1
CONTAINER_VERSION: 1.0.0-rc.1
TARBALL_VERSION: 1.0.0-rc.1
```
**Main branch - 2 commits past tag …
=> build: support a release candidate version

crates/core/tedge/src/cli/connect/bridge_config_c8y.rs, crates/extensions/c8y_mapper_ext/src/compatibility_adapter.rs
The reverted PR #2482 contains the changes which should not have to be reverted. This PR is the collection of such commits. 
Two commits are cherry-picked from #2482 and changed the hash (important to have different hash to merge them again).
- (original commit) => (new commit in this branch)
- 31e07a871216df105284215ea66f510793df8af6 => 566124f017b7af5b97400d7a309b4295881f3a65
- e7fc294c3a914492fa66ac04eb33e0a9b40d205d => d4d9568608ec8cf09fda2518e098205c27407b54
<br/>
=> Follow-up: Extract useful changes from the reverted #2482 PR

tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Testing that a successful device restart is properly notified to Cumulocity even in the subtle case where the running version of tedge-agent it not the installed version, this version-mismatch situation being the result of the tedge software update from the cloud. 
<br/>
=> Restart the device after a self-update

crates/core/c8y_api/src/smartrest/operations.rs
Add a warning log message when an invalid custom operation filename is encountered to warn the user that the file will be ignored.
This helps users understand why their custom operation definition is not being used. Previously the user would not receive any indication that thin-edge.io was actively ignoring the file.
<br/>
=> feat: add user warning when an invalid custom operation filename is used

tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Refactor service system tests to remove unnecessary logic in an attempt to make the tests more stable.
The tests are passing reliably when using the [instructions in #2423](https://github.com/thin-edge/thin-edge.io/issues/2423#issuecomment-1796385473)
* https://github.com/thin-edge/thin-edge.io/issues/2427
* https://github.com/thin-edge/thin-edge.io/issues/2423
=> test: refactor service tests by removing unnecessary logic

tests/images/debian-systemd/files/bootstrap.sh
Configuring the repo is unnecessary when installing via local deb packages and can fail due to connectivity issues when run under the CI.
Example of failed CI run due to the repo configuration failing:
* https://github.com/thin-edge/thin-edge.io/actions/runs/7472331384
=> test: don't configure repos when installing thin-edge.io via local deb packages

crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
This PR introduces a limit to the size of the message that is sent when the operation fails. If the failure reason is longer than 200 characters, it is truncated from the end, and the user gets a warning message about truncation. 
* #2567
<br/>
=> Limit the length of the message for failed operation

tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
Improve system tests which used a fixed service name which would cause failures if another system test instance is running the same test (or the service is not cleaned up by the test).
Instead use a randomly generated service name to reduce risk of name clashes.
<br/>
=> test: use random service name in tests to avoid side effects from concurrent runs

docs/src/operate/security/device-certificate.md
Fix documentation about the order of certificates in the cert chain (when using a signing cert). The first cert in the chain must be the device cert.
<br/>
=> docs: correct note about certificate chain order

.github/workflows/integration-tests.yml, tests/RobotFramework/README.md, tests/RobotFramework/devdata/env.template, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot, tests/RobotFramework/tests/tedge/tedge_upload_cert.robot, tests/images/debian-systemd/files/bootstrap.sh
Use a local CA to generate the device certificates used in each test. This should improve overall performance, and avoid creating large amounts of device certificates in Cumulocity IoT
* Generate device certificate during bootstrap.sh script using a local CA provided  via environment variables (if `CA_KEY` and `CA_PUB` are present, which are base64 encoded values), otherwise continue using self signed certificate
* Only run "delete cert" logic in the cleanup of tests if a self-signed device certificate is detected
* Decouple the certificate deletion and the device deletion to avoid problems where the device is not cleaned up if the cert deletion fails
<br/>
=> test: use local ca to generate device certificates

crates/core/tedge_api/src/entity_store.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/dynamic_discovery.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, tests/RobotFramework/tests/cumulocity/bootstrap.robot
Added a workaround for #2584 by changing status update smartrest message to 102.
Also fixed #2606 by properly checking in the fs event handler if the path of the event is actually inside the c8y operations path.
- #2584
Note that changing `104` to `102` in this case is only a workaround, because, fundamentally, Cumulocity maintains a certain state, and depending on this state, we either can or can't send certain messages, e.g. `104` can't be sent before a `102` or it will create a child device, but I assume this is only a single example and there are many more. To be able to use certain messages, we need to actually maintain the state for entities in cumulocity - if they're registered, if they're child devices or services, etc. So ultimately we may need to change our model a bit from "map …
=> fixed services shown as child devices #2584

Cargo.lock, crates/common/logged_command/Cargo.toml, crates/common/logged_command/src/logged_command.rs, crates/core/plugin_sm/src/plugin.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, docs/src/operate/c8y/supported_operations.md, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_multiple_args/c8y_Command_1, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_multiple_args/command_1.sh, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_multiple_args/operation_multiple_arguments_in_command.robot
This PR adds support for arguments/subcommands when running command in custom operation. Command accepts string with arguments separated by whitespaces, e.g:
```
command = "python /etc/tedge/operations/command.py"
```
More in #2568.
* #2568
=> Add support for commands with multiple arguments in custom operations

Cargo.lock, Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/certificate/src/lib.rs
Update Rust crates to versions which use the newer ring 0.17.x release. ring 0.17.x makes it possible to compile thin-edge.io for different target triples (though it is still not possible via cargo-zigbuild).
Whilst the build tooling has not been updated to support building for the additional targets, it at least opens the possibility for users to build the project on the native architectures, or use their own setup which uses clang (an example can be seen from the [ring workflow](https://github.com/briansmith/ring/blob/main/.github/workflows/ci.yml) which shows how to build for multiple targest on a linux x86_64 host).
The following targets can now be enabled (see example of how to build [here](https://github.com/reubenmiller/thin-edge.io/blob/experiment-clang/.github/workflows/ci.yml)) …
=> dependencies: update Rust crates to use ring 0.17.x

docs/src/overview.md, docs/src/start/index.md
Refactor the overview and start pages to reduce maintain by linking to other parts of the docs rather than listing individual pages within each section.
In addition the following minor tweak were made to improve the links within the pages:
* Use fixed anchor ids
* Use thin-edge.io name placeholder
https://github.com/thin-edge/thin-edge.io/issues/2628
=> docs: refactor overview and start pages

crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, docs/src/operate/c8y/supported_operations.md, tests/RobotFramework/tests/cumulocity/bootstrap.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot, tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot, tests/RobotFramework/tests/customizing/data_path_config.robot
1. Add operations support for nested child devices by keeping their supported operations in the same `/etc/tedge/operations/c8y` directory where the main device and immediate child devices keep their operation files.
2. Stop interpreting all directories under the operations directory as immediate child devices, and registering them on startup, resulting in the reported bug.
3. Limit the dynamic update of the supported operations list via file updates to this directory only to the main device. The supported list of child devices are updated only when they declare their supported operations via MQTT.
#2409
=> Limit dynamic operation dir APIs to main device #2409

crates/core/tedge/src/cli/init.rs, crates/core/tedge_api/src/entity_store.rs, tests/RobotFramework/tests/cumulocity/mapper_recovery/recover_and_publish_software_update_message.robot
Fix entity store file permission using the `tedge init` command that is always executed before mapper startup.
https://github.com/thin-edge/thin-edge.io/issues/2598
=> Fix entity store file permission on mapper startup #2598

crates/core/c8y_api/src/json_c8y.rs, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot, tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot, tests/RobotFramework/tests/cumulocity/software_management/software.robot
Software type is reported as "type" in the PR #2613, however, it should have been "softwareType" according to c8y's document. Refer to here. https://cumulocity.com/guides/reference/device-management-library/#software
* #2613
* https://github.com/thin-edge/thin-edge.io/issues/2653
=> Fix software type should be reported as "softwareType", not "type"

docs/src/start/getting-started.md, docs/src/start/raise-alarm.md, docs/src/start/send-events.md
remove explicit timestamps in example commands in the Getting Started section.
Removing the timestamps improves the user experience as it ensures the alarms/events are created at the time of execution and not in the past (which results in the data not being displayed in the c8y UI as it is too far in the past)
https://github.com/thin-edge/thin-edge.io/issues/2641
=> docs(getting started): remove explicit timestamps from example commands

Cargo.lock, crates/core/tedge_agent/src/agent.rs, crates/extensions/tedge_config_manager/src/lib.rs, crates/extensions/tedge_config_manager/src/tests.rs, crates/extensions/tedge_log_manager/Cargo.toml, crates/extensions/tedge_log_manager/src/config.rs, crates/extensions/tedge_log_manager/src/lib.rs, crates/extensions/tedge_log_manager/src/tests.rs, plugins/tedge_log_plugin/src/lib.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot
Provide default plugin configurations for `tedge-config-plugin` and `tedge-log-plugin` that'll work with both main and child devices.
https://github.com/thin-edge/thin-edge.io/issues/2447
=> Default configuration for tedge operation plugins

crates/core/tedge_actors/src/channels.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_agent/src/tedge_operation_converter/actor.rs, crates/core/tedge_agent/src/tedge_operation_converter/builder.rs, crates/core/tedge_api/src/message_log.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, tests/RobotFramework/tests/tedge_agent/main_tedge_agent.robot
Introduce unbounded receivers. Given a cycle of actors (say A sending messages to B, B to C and C to A), at least one of these actors must use such an unbounded receiver.
https://github.com/thin-edge/thin-edge.io/issues/2639
=> Fix tedge-agent stuck on too many pending operations

tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
Use unique names within the system test which registers devices using an explicit `@id` field to avoid name clashes when running multiple tests or if the device is not cleaned up in Cumulocity IoT (as the `@id` is used as the External Id which must be unique within the whole tenant, and can only have 1 owner).
This is the same issue fixed in other tests in https://github.com/thin-edge/thin-edge.io/pull/2618
<br/>
=> test: use unique child names when creating devices with an explicit @id field

crates/core/tedge_agent/src/software_manager/actor.rs, crates/core/tedge_agent/src/state_repository/state.rs
This PR replaces error log levels with warnings and prevents exiting with error code in such cases.
* #2634
=> Replace error log levels with warnings in tedge agent

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/json_c8y.rs, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/message_log.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
=> Bypass duplicate message filtering on mapper startup with config flag

plugins/tedge_apt_plugin/src/lib.rs
Disable debian frontends whilst running apt commands in **tedge-apt-plugin**
This avoids packages failing due to interactive frontend.
https://github.com/thin-edge/thin-edge.io/issues/2671
=> fix(apt): disable debian frontend when running apt commands

tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-agent.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-aws.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot, tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot, tests/RobotFramework/tests/configuration/lock_file.robot, tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Due to some flake-finder runs, it was found that the assertions which rely on getting a service's main PID can suffer from race conditions if there is a delay between starting a service and getting the pid via `pgrep`. Instead the `Service Should Be Running` keyword also returns the PID of the running service, so it does not assume that the service is running "now", but will wait if necessary if the service is not already running.
<br/>
=> test: use a more reliable service pid detection

docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
Update rugpi image building instrustions after refactoring the tedge-rugpi-image repo to use new Rugpi features (layers and repositories) introduced in 0.6.
* https://github.com/thin-edge/tedge-rugpi-image (image)
* https://github.com/thin-edge/tedge-rugpi-core (recipes)
* Rugpi release notes:  https://oss.silitics.com/rugpi/blog/releases/0.6
<br/>
=> docs: update rugpi instructions to align with rugpi v0.6

plugins/tedge_apt_plugin/src/lib.rs, tests/RobotFramework/tests/plugin_apt/install_overwrite_config_files.robot
Refactor tedge-apt-plugin to move logic to a common area. It solves the linked tickets.
The systems tests were updated to improve coverage for the keep config options which was previously erroneously passing due to using manual `tedge-apt-plugin install` commands rather than installing packages from the cloud which uses a different code path to install packages.
* https://github.com/thin-edge/thin-edge.io/issues/2669
* https://github.com/thin-edge/thin-edge.io/issues/2671
* https://github.com/thin-edge/thin-edge.io/issues/2670
=> tedge-apt-plugin update list missing keep config options

.github/workflows/pull-request-checks.yml
Pin nightly version so cargo-udeps keeps working. After our dependencies are updated and don't use the incompatible ahash version, the pin can be removed.
- #2686
=> cargo-udeps: pin nightly version to fix "unknown feature `stdsimd`" error

docs/src/extend/firmware-management/building-image/rugpi/tutorial.md, docs/src/extend/firmware-management/device-onboarding.md
Fix a broken anchor in the rugpi onboarding instructions.
<br/>
=> docs: fix broken anchor to rugpi instructions

crates/core/c8y_api/src/http_proxy.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_http_proxy/src/tests.rs
Even if the internal ID lookup fails on the initial attempt (presumably because of delays in the creation of the device), retry a few more times before failing.
<br/>
=> Retry internal id lookup when not found #2533

Cargo.lock, Cargo.toml, crates/common/tedge_config/src/lib.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/main.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/lib.rs, crates/core/tedge_mapper/src/main.rs
Log memory usage of the agent and the mapper. 
The default interval is of 60 seconds.
This can be changed using the` --log-memory-interval` flag which sets the logging interval in seconds.
```
$ target/debug/tedge-mapper --log-memory-interval 5 c8y
$ sudo target/debug/tedge-agent --log-memory-interval 5
```
https://github.com/thin-edge/thin-edge.io/issues/2692#issuecomment-1934466228
=> Log memory usage of the agent and the mapper

.github/workflows/autotag.yml, .github/workflows/build-workflow.yml, .github/workflows/hosted-post-merge_version_update.yml
Improve release workflow by automating more steps
* Use PAT when creating a PR (so that github actions checks will also be run)
* Trigger tedge-docs workflow on tags to create a new doc snapshot PR
* Create a tag when detecting a change in the Cargo.toml package.version (result of triggering the `hosted-post-merge_version_update.yml` workflow)
=> ci: improve release workflow

crates/common/tedge_config/src/system_services/log_config.rs
Only enable ansi colours/codes when standard error is writing to a terminal (tty).
Previously ansi colours were enabled by default leading to journald log entries being created with the ansi escape sequences (causing problems when reading from the journald using the json output):
**Example**
Previously the `.MESSAGE` field is encoded as a JSON array (of integers/chars) as the message contained non unicode characters (e.g. ansi escape codes) and journald does not try to render it as a string.
```
journalctl -fu tedge-agent -o json -n 100 -u tedge-agent
```
**Before**
```json
{"_GID":"992","PRIORITY":"6","_SYSTEMD_SLICE":"system.slice","_BOOT_ID":"d22c4e29863542fc9405091fe2b3664c","_SYSTEMD_UNIT":"tedge-agent.service","_COMM":"tedge-agent","__REALTIME_TIMESTAMP":"1708940884913851","__MONOTON …
```
=> feat(logs): only enable ansi colors in logs when stderr is a terminal

crates/common/tedge_utils/src/notify.rs
Use the generic [RecommendedWatcher](https://docs.rs/notify/latest/notify/) notify type to remove OS specific types, as `INotifyWatcher` is generally only supported on linux targets.
There should be no functional difference.
<br/>
=> refactor: use generic RecommendedWatcher type over platform specific type

crates/common/download/src/download.rs
Move an import which is only used in a test which is run on linux targets to avoid problems when running tests on other target os's.
<br/>
=> tests: move import into test which is only run on linux targets

crates/common/tedge_utils/src/notify.rs, crates/extensions/tedge_file_system_ext/src/lib.rs, crates/tests/tedge_test_utils/src/fs.rs
Use canonical path (e.g. resolving symlinks etc.) when watching a directory.
On some platforms like MacOS, the watcher path and the paths in the notify messages can differ if the watcher path is a symlink. Most notably this occurs during testing as the default tmp directory is a symlink under MacOS (e.g. the temp folder is given as`/var/folders`, however this is actually a symlink to `/private/var/folders`).
<br/>
=> feat(watcher): use canonical path when watching a directory

.github/workflows/build-workflow.yml
Build `riscv64gc-unknown-linux-gnu` target using minimum Rust 1.73, otherwise the produced binary crashes with a "segmentation fault".
Rust 1.73 upgraded the internal use of llvm to version 17 (which includes some other improvements) which 
* [PR Upgrade to llvm 17](https://github.com/rust-lang/rust/pull/114048/) is mentioned in the [Rust 1.73 release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1730-2023-10-05)
Rust versions 1.70 through to 1.76 were tested on a Star Vision2 device (with a riscv processor) - where "Segmentation fault" is observed whilst initialising the c8y-remote-access-plugin (though it is not limited to this command):
```sh
user@starfive:~$ uname -a
Linux starfive 5.15.0-starfive #1 SMP Fri Nov 24 07:22:28 UTC 2023 riscv64 GNU/Linux …
```
=> fix(riscv): building using Rust 1.73 to avoid segmentation fault in release mode

crates/common/tedge_config/src/tedge_config_cli/models/c8y_software_management.rs, crates/common/tedge_config/src/tedge_config_cli/models/mod.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/inventory.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/software_management/software.robot, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Since c8y 10.14, advanced software management feature is supported together with the microservice "Advanced-software-mgmt". This PR enables users to use the feature. For more details about the feature, please read the [c8y user doc](https://cumulocity.com/docs/2024/device-integration/fragment-library/#installed-software). 
Introduced two tedge configs:
1. **c8y.software_management.api**
To switch legacy software management (= sending list via HTTP) and advanced one (= sending list via SmartREST).
By default, it is set to `legacy`. To enhance the detection, the ticket #2778 is created.
2. **c8y.software_management.with_types**
If mapper publishes `c8y_SupportedSoftwareTypes` to the inventory or not. If the type is set in its managed object, c8y stop using `c8y_SoftwareList` fragment to …
=> c8y-mapper sends software list to advanced software management endpoint

crates/common/certificate/src/lib.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_utils/src/file.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/error.rs, crates/core/tedge/src/cli/certificate/mod.rs, crates/core/tedge/src/cli/certificate/renew.rs, docs/src/operate/security/certificate-signing-request.md, docs/src/references/cli/tedge-cert.md, tests/RobotFramework/tests/tedge/certificate_signing_request.robot
This PR is introducing new `tedge cert` command: `create-csr` along with new config option `device.csr_path`. This allow to create a certificate signing request which later can be used to create device certificate using CA. The Syntax for the command is following:
```sh
tedge cert create-csr --device-id mydevice001
tedge cert create-csr
```   
Command will reuse existing public certificate to use its `CommonName`. 
Moreover, the command will reuse private key if it already exists. Same goes for `tedge cert create`. 
* #2760
=> feat(cert): Create a Certificate signing request using `tedge cert create-csr`

.typos.toml
- ignore 2 hexa digits numbers to accept e.g. ` a3:d5:ec:9b:5c:65:7a:ba:7d:92:20:a1:80:9b:d6:`
<br/>
=> Fix false negative typos: ignoring hexa literals

crates/common/tedge_config/src/tedge_config_cli/error.rs, crates/common/tedge_config/src/tedge_config_cli/models/host_port.rs, crates/common/tedge_config/src/tedge_config_cli/models/port.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge/src/bridge/aws.rs, crates/core/tedge/src/bridge/azure.rs, crates/core/tedge/src/bridge/c8y.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge/src/cli/certificate/upload.rs, crates/core/tedge/src/cli/connect/c8y_direct_connection.rs, crates/core/tedge/src/cli/connect/command.rs, tests/RobotFramework/README.md
* https://github.com/thin-edge/thin-edge.io/issues/2787
=> fix: Honor c8y.mqtt setting on tedge connect

tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-az.robot, tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
The cause of the flake was `Should Have MQTT Messages` keyword finding a message from the previous test case, because of the default 1s precision in the `messages_from` timestamp, so the proper timestamp had to be rounded down, which leads to issues when test cases are short and execute in less than 1 second.
Closes #2799
- #2799
=> fix: flaky custom_sub_topics_tedge-mapper-az test

Cargo.lock, crates/common/logged_command/src/logged_command.rs, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/lib.rs, crates/common/tedge_config/src/sudo.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/plugin_sm/tests/plugin.rs, crates/core/plugin_sm/tests/plugin_manager.rs, crates/core/tedge_agent/src/restart_manager/actor.rs, crates/core/tedge_agent/src/restart_manager/config.rs, crates/core/tedge_agent/src/restart_manager/tests.rs, crates/core/tedge_agent/src/software_manager/actor.rs, crates/core/tedge_agent/src/software_manager/config.rs, crates/core/tedge_agent/src/software_manager/tests.rs, crates/core/tedge_write/Cargo.toml, crates/core/tedge_write/src/api.rs, crates/core/tedge_write/tests/main.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_config_manager/src/config.rs
Check `sudo.enable` config setting before using sudo in software and restart managers. If `sudo.enable` is `true` but isn't found in `$PATH`, a warning is emitted.
- #2749 
I'll also probably add a test, once I figure out where to put it.
=> fix(#2749): Check sudo.enable in software and restart managers

tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot, tests/RobotFramework/tests/tedge/certificate_signing_request.robot
Fix the test [Generate CSR without an existing certificate and private key](https://github.com/thin-edge/thin-edge.io/actions/runs/8566493225?pr=2813)
- Trim spaces before comparing openssl output with the expected CSR
<br/>
=> Fix broken test checking CSR content

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/utils.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/renew.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/tedge_mqtt_bridge/src/lib.rs, tests/RobotFramework/tests/cumulocity/shell/shell_operation_built-in_bridge.robot, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
These are some of the changes discussed in #2794, specifically:
- Ensure custom templates work (this was just a check I performed, no code changes were made)
- Modifying the bridge healthcheck message to use thin-edge json, rather than 0/1 like mosquitto
- Fix connectivity check in `tedge connect c8y` so new devices connect successfully
- #2794
=> Initial follow up tasks for built-in bridge

Cargo.lock, Cargo.toml, crates/common/upload/Cargo.toml, crates/common/upload/src/lib.rs, crates/common/upload/src/upload.rs, crates/extensions/c8y_mapper_ext/src/operations/config_snapshot.rs, crates/extensions/c8y_mapper_ext/src/operations/log_upload.rs, crates/extensions/tedge_uploader_ext/src/actor.rs, crates/extensions/tedge_uploader_ext/src/lib.rs, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot, tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
With this change, now you can download log files with file name such as `rina0005_software-management-c8y-mapper-5369.txt`.
Technical changes:
- Use async client to support multipart/form-data
- Expand Uploader to support both PUT and POST method
- Add MIME auto-detection based on file extension
I added a half working content-type auto detection mechanism to this PR. Stories behind:
* It is nice to have auto-detection of `Content-Type` header. 
* The `reqwest` feature `multipart` adds a dependency on the `mime_guess` crate. So, using `mime_guess` crate shouldn't give any new dependency to thin-edge.
* However, their function gives a guess based on a file extension without file access. Read [this](https://docs.rs/mime_guess/latest/mime_guess/struct.MimeGuess.html#method.from_path).
For …
=> Uploader supports multipart/form-data and attaches filename

crates/common/mqtt_channel/src/connection.rs
Instead of retrying MQTT connection immediately for some errors, apply delay before retrying connection by default for all errors.
One could argue that for errors where we know we're going to receive it again, e.g. misconfiguring certificates, we should exit instead of retrying, but because rumqttc doesn't organize its errors very well, it would be hard to ensure that every variant is covered, whereas this is simple and works.
- https://github.com/thin-edge/thin-edge.io/issues/2728
=> fix: apply delay to mqtt connect errors by default

design/decisions/0004-entity-dregister-api.md
Entity deregistration API proposals with pros and cons of each approach.
<br/>
=> Entity deregistration API proposals

crates/core/tedge_agent/src/operation_file_cache/mod.rs, crates/core/tedge_api/src/commands.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_log_manager/src/actor.rs
Use the `Command<Payload>` representation for log, config and firmware commands
This is required for:
- https://github.com/thin-edge/thin-edge.io/pull/2833
- https://github.com/thin-edge/thin-edge.io/pull/2844
<br/>
=> Use Command<Payload> for log, config and firmware commands

crates/core/tedge/src/cli/connect/command.rs, tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Fix false negative where a warning was being printed during `tedge connect c8y` due to comparing two urls where one would have the port defined, and the other would not. The port number is now ignored during the comparison.
https://github.com/thin-edge/thin-edge.io/issues/2863
=> fix(cli): ignore port when comparing cloud urls

Cargo.lock, Cargo.toml, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/smartrest/topic.rs, crates/core/tedge/src/bridge/aws.rs, crates/core/tedge/src/bridge/azure.rs, crates/core/tedge/src/cli/common.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/disconnect/cli.rs, crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs, crates/core/tedge/src/cli/reconnect/command.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/operations/config_snapshot.rs, crates/extensions/c8y_mapper_ext/src/operations/config_update.rs, crates/extensions/c8y_mapper_ext/src/operations/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/operations/log_upload.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, crates/extensions/tedge_mqtt_bridge/Cargo.toml, crates/extensions/tedge_mqtt_bridge/src/config.rs, crates/extensions/tedge_mqtt_bridge/src/health.rs, crates/extensions/tedge_mqtt_bridge/src/lib.rs, crates/extensions/tedge_mqtt_bridge/src/topics.rs, crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
This adds support for AWS and Azure to the built-in bridge, as well as some clean session configuration to ensure we don't lose messages.
Previously the rules were Cumulocity rules, where all we needed to do was remove and add local prefixes, so a large section of the changes are around supporting more complex mapping logic, so a `BridgeRule` struct has been added to support the same configurations as mosquitto.
<br/>
=> Support different clouds in built-in bridge

crates/core/tedge/src/cli/connect/command.rs
Avoid to panic when running `tedge connect c8y` on a device where there is no `mosquitto` user.
https://github.com/thin-edge/thin-edge.io/issues/2867
https://github.com/thin-edge/thin-edge.io/issues/2867
=> Do not panic changing ownership of device cert to unknown user

plugins/c8y_remote_access_plugin/src/lib.rs
This switches from `current_exe()` to `env::args()` as `current_exe` resolves the symlink on Linux (so the plugin was calling `tedge` rather than `c8y-remote-access-plugin` when calling itself).
- #2890
=> Switch to env::args for establishing the executable name

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/plugin_sm/tests/plugin.rs, crates/core/tedge_api/Cargo.toml, crates/core/tedge_api/src/error.rs, docs/src/references/agent/software-management.md, tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
This PR introduce two new tedge configs: `software.plugin.include` and `software.plugin.exclude`. This allows to filter packages list output in `sm-plugin` using include pattern and exclude pattern.  When both patterns are provided in config, include pattern takes precedence over exclude pattern. 
#2848
=> feat(sm-plugin): filter packages output list with exclude/include pattern

crates/common/download/src/download.rs, crates/core/tedge_api/src/commands.rs, crates/core/tedge_api/src/software.rs, tests/RobotFramework/tests/cumulocity/software_management/software.robot
This PR adds an extra check in `software_update` to skip the download process if the payload contains an empty url. A system test was added to prove that the error no longer exists when an empty url is provided in the local command.
* #2857
<br/>
=> feat(sm-plugin): skip package download if the url is empty

Cargo.lock, crates/core/c8y_api/src/utils.rs, crates/core/tedge_api/src/health.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, crates/extensions/tedge_mqtt_bridge/Cargo.toml, crates/extensions/tedge_mqtt_bridge/src/lib.rs, crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
Refactor health status refactoring code, including addressing review comments from #2903 
<br/>
=> refactor: Refactor health status code

tests/RobotFramework/requirements/requirements.txt
Update the `robotframework-c8y` library (used in system tests), to improve the logging of the "smart retry" feature. This should help improve debugging of tests to show an assertions number of attempts, and the output of each failed attempt.
**Example**
The following snippet shows the new info log entries showing that `Managed Object Should Have Fragment Values` assertion was attempted a few times before it passed.
<br/>
=> test(system): update c8y system test lib to improve retry logging

configuration/package_scripts/_generated/tedge/apk/postrm, configuration/package_scripts/_generated/tedge/apk/preinst, configuration/package_scripts/_generated/tedge/deb/postrm, configuration/package_scripts/_generated/tedge/deb/preinst, configuration/package_scripts/_generated/tedge/rpm/postrm, configuration/package_scripts/_generated/tedge/rpm/preinst, configuration/package_scripts/tedge/postrm, configuration/package_scripts/tedge/preinst
Improve the compatibility across different linux/bsd distributions when checking for the existence of users or groups during the installation and remove of thin-edge.io.
The new logic will checks for the existence of the dependent tool before using it, and if not found will continue to the next tool, the order is as follows:
1. `id`
2. `getent`
3. `grep /etc/passwd` (user) or `grep /etc/group` (groups) - Though this is only a last resort and will not work reliably on distributions that use some exotic NSS setup, like Fedora IoT, however in the majority of cases, `id` SHOULD be installed.
There is another related PR regarding the thin-edge.io/install.sh script which also used `getent` by default:
* https://github.com/thin-edge/thin-edge.io-website/pull/59 …
=> fix: improve compatibility of user/group existence check in package maintainer scripts

crates/extensions/tedge_config_manager/src/lib.rs, crates/extensions/tedge_config_manager/src/tests.rs
Use linux permissions `644` instead of `444` as the latter is unexpected for most users as it does not allow users to edit the file, and give that it is the `tedge-log-plugin` file, then it should be editable for the owner.
This change was initiated after a customer interaction.
<br/>
=> feat: avoid using 444 permissions in example tedge-configuration file

crates/core/tedge/src/cli/mqtt/mod.rs, crates/core/tedge/src/cli/mqtt/subscribe.rs
As rumqttc doesn't trigger a client disconnect when the connection is not established,
one has to combine a client disconnect with the use of an `AtomicBool` to break the event loop
if for some reason the connection is not established when the user hits ctrl-c. 
https://github.com/thin-edge/thin-edge.io/issues/2949
=> fix: tedge mqtt ignoring ctrl-c when connection fails

configuration/contrib/collectd/collectd.conf, crates/common/axum_tls/test_data/_regenerate_certs.sh, crates/common/mqtt_channel/src/config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config_macros/examples/macro.rs, crates/core/tedge/src/bridge/common_mosquitto_config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/tedge_mqtt_bridge/src/config.rs, crates/extensions/tedge_mqtt_bridge/tests/bridge.rs, crates/tests/mqtt_tests/src/test_mqtt_client.rs, crates/tests/mqtt_tests/src/test_mqtt_server.rs, tests/RobotFramework/tests/cumulocity/configuration/generate_certificates.sh, tests/RobotFramework/tests/mqtt/gen_certs.sh, tests/RobotFramework/tests/tedge/call_tedge_config_list.robot, tests/images/debian-systemd/files/bootstrap.sh
Some Linux distributions installations where the `/etc/hosts` file is not defined, the loopback address (`127.0.0.1`), the `localhost` alias does not get resolved to `127.0.0.1`. And devices which have a read-only rootfs, can't even add a manual entry to the list, so the only option is to change the `tedge.toml` values (which is not ideal for such basic settings).
Changing the defaults from `localhost` to `127.0.0.1` improves the out of the box compatibility.
<br/>
=> feat: use loopback ip address instead of alias to improve compatibility

crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/tedge_http_ext/src/actor.rs, crates/extensions/tedge_http_ext/src/messages.rs, crates/extensions/tedge_http_ext/src/test_helpers.rs
Add information to the HTTP status code error messages, specifically the path (e.g. `/inventory/managedObjects/12345`) and method (e.g. `PUT`). Previously the error messages just quoted the status code, which meant that without further context it was near enough impossible to work out what tedge was trying to do when it encountered the error.
This also adds a small bit of context to the specific case I encountered testing the mapper against a fake Cumulocity.
<br/>
=> feat: add path and method used to HTTP error messages to improve debugability

Cargo.lock, Cargo.toml, crates/extensions/c8y_auth_proxy/Cargo.toml, crates/extensions/c8y_auth_proxy/src/server.rs
Improve the host header tests introduced in #2946 by actually parsing the headers instead of simply checking for the presence of a string in the incoming request. Additionally simplify the logic for obtaining the websocket host.
<br/>
=> test: use more robust http parsing in the c8y-proxy host header tests

crates/extensions/tedge_config_manager/src/lib.rs, crates/extensions/tedge_config_manager/src/tests.rs
All of our other examples use octal when declaring the file permissions for the tedge-configuration-plugin.toml file, so we should also use it when generating the default `tedge-configuration-plugin.toml` file if it does not already exist.
<br/>
=> fix: use octal format for file permission in generated example file

.github/workflows/build-workflow.yml
This PR bumps MSRV in the workflow.  Version 1.78 introduced [diagnostic_attribute](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#diagnostic-attributes) that will be used in #2943.
<br/>
=> chore: bump MSRV in the workflow to 1.78

crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/upload.rs, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
Small usability improvements around the `tedge cert upload c8y` command:
* Support reading the username from the env variable via `C8Y_USER` (if provided)
* If user is not provided by the `--user` flag, or the `C8Y_USER`, then the user will be prompted to enter their username => **Reason:** Users generally don't know that they have to provide the `--user` flag, so it is more intuitive to prompt them for the missing information rather than throwing an error about the missing `--user` flag
* Password can also be set via the more common env variable, `C8Y_PASSWORD`, though `C8YPASS` is still supported, but it has been deprecated and a warning is printed to the console => **Reason:** other Cumulocity tooling (like go-c8y-cli) uses C8Y_PASSWORD which means the tools work well with each other …
=> feat: tedge cert upload usability improvements

crates/common/tedge_config/src/tedge_config_cli/error.rs, crates/common/tedge_utils/src/fs.rs, crates/core/tedge_agent/src/restart_manager/error.rs, crates/core/tedge_agent/src/state_repository/error.rs, crates/extensions/tedge_config_manager/src/error.rs
This PR adds extra info to error messages when atomically writing to file.
#2959
=> feat(fs): add extra context to errors when atomically writing to file

docs/src/operate/c8y/software-management.md
These config keys were not described anywhere, so I would add a short explanation.
```sh
sudo tedge config set c8y.software_management.api advanced
sudo tedge config set c8y.software_management.with_types true
```
<br/>
=> docs: add advanced software mgmt descriptions

tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot
The step:
`Should Not Contain    ${MQTT_PUB}    Error` 
from the test:
`tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot`
has to be commented out because this validation is causing unstable test runs, if needed can be included again when (and if) we find the reason for it
<br/>
=> test: remove OpenSSL Error check because of flakiness

.github/workflows/build-workflow.yml, tests/images/debian-systemd/files/bootstrap.sh
The root cause to the problem that prompted the change in https://github.com/thin-edge/thin-edge.io/pull/2979 has been identified. Previously the debian `sid` repository was being used to install mosquitto 2.0.18, then around 2024-07-05, the usage of the `sid` repository also resulted in the systemd version being upgraded to 256 where support for cgroup v1 has been deprecated (see the [systemd news](https://github.com/systemd/systemd/blob/main/NEWS)). The Github runner ubuntu-20.04 was being used to run the system tests which uses cgroup v1 resulting in some system test failures due to some systemctl commands not functioning as expected. Using the Github runner `ubuntu-22.04` fixes the issue as the OS uses cgroup v2 by default.
In addition to using switching to the Github runner …
=> tests: improve debugging of bootstrap script and include systemd/cgroup compat check

tests/RobotFramework/tests/cumulocity/log/workflow/log_upload.sh, tests/RobotFramework/tests/cumulocity/log/workflow/log_upload.toml, tests/RobotFramework/tests/cumulocity/log/workflow/log_workflow.robot, tests/RobotFramework/tests/cumulocity/log/workflow/tedge-log-plugin.toml
Add a system tests which can demonstrate how to handle command based log_upload commands by overriding the default log_upload workflow, and add a pre-processing step which will generate the log file when called (the command could do something like talk to a database etc.)
It shows a working example that can be referenced to customers.
<br/>
=> test: add a custom command based log_upload workflow

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/models/c8y_software_management.rs, crates/common/tedge_config/src/tedge_config_cli/models/mod.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_auth_proxy/src/url.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_mapper_ext/Cargo.toml, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/lib.rs, crates/extensions/c8y_mapper_ext/src/operations/config_snapshot.rs, crates/extensions/c8y_mapper_ext/src/operations/config_update.rs, crates/extensions/c8y_mapper_ext/src/operations/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/operations/log_upload.rs, crates/extensions/c8y_mapper_ext/src/operations/mod.rs, crates/extensions/c8y_mapper_ext/src/operations/restart.rs, crates/extensions/c8y_mapper_ext/src/operations/software_list.rs, crates/extensions/c8y_mapper_ext/src/operations/software_update.rs, crates/extensions/c8y_mapper_ext/src/operations/upload.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
This PR is a 2nd attempt at simplifying operation control flow. I found that the top-down approach in #2881 of spawning a task for every main actor message would be too tedious to get working, because to remove the lock on the converter would require to change `convert` method to `&self`, which at this moment is infeasible because of how many things it does/how many other functions it calls.
Instead, the approach taken here was a bottom-up one:
1. It was identified that the operation handling and its properties do not fit into `convert` method's assumptions:
- `convert()` needs to convert MQTT messages in both directions without blocking
- but operation handling can block, and it can take some time before MQTT response is ready
2. As such, some operations (not all) were pulled out of …
=> Simplify the operation handling code by replacing fragmented control flow with regular async/await - attempt #2

Cargo.lock, crates/common/log_manager/Cargo.toml, crates/common/log_manager/src/log_utils.rs, tests/RobotFramework/tests/cumulocity/log/log_operation.robot
Currently the log manager is filtering logs by date no matter whether provided path is static or containing wildcard. With this PR log manager will return log path if it is fixed. Explanation why this feature is needed can be found in #2966.
* #2966 
<br/>
=> feat(log manager): skip filtering by date when a static path is used

crates/core/tedge/src/bridge/aws.rs, crates/core/tedge/src/bridge/azure.rs, crates/core/tedge/src/bridge/c8y.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge/src/cli/connect/command.rs, tests/RobotFramework/resources/common.resource, tests/RobotFramework/tests/aws/aws_connect.robot
Add simple cloud specific retry mechanism when running `tedge connect xxx`. At the moment, only `aws` uses a retries > 0, as AWS has a [Just In Time Provisioning](https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html) feature which creates the "Thing" on first connection, but this leads to the first connection check failing, so retrying the connection leads to a higher success of passing.
A on-demand system test has also been added to support testing the AWS connection manually, as some infrastructure and automation scripts needs to be created before the tests can be included in the standard build-workflow runs (e.g. a script to delete the device(thing) and certificate from AWS after the test has completed). This automation will be done in a subsequent PR.
**Note** …
=> feat: retry aws connection check when establishing initial connection

Cargo.lock, plugins/c8y_remote_access_plugin/Cargo.toml, plugins/c8y_remote_access_plugin/src/auth.rs, plugins/c8y_remote_access_plugin/src/lib.rs, plugins/c8y_remote_access_plugin/src/proxy.rs, tests/RobotFramework/bin/setup.sh, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
Remove the c8y-remote-access-plugin connection dependency on the c8y local proxy which is launched by the **tedge-mapper-c8y** service. This is part one of the large ticket (#2859) which looks at creating the remote access connection which is fully independent to the **tedge-mapper-c8y** service, thus allowing the user to execute `tedge reconnect c8y` without the remote access connection from being dropped.
**Note**
Prior to the c8y local proxy feature, the c8y-remote-access-plugin did use a direct connection to Cumulocity IoT, however the implementation was switch to use the local proxy which adds an additional connection dependency on the tedge-mapper-c8y (e.g. if you restart the tedge-mapper-c8y, the local proxy will also restart thus stopping the connection). This PR does not change …
=> feat: use direct c8y connection for c8y-remote-access-plugin

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, tests/RobotFramework/tests/cumulocity/software_management/software.robot
Change the default value of `c8y.operations.auto_log_upload` from `never` to `on-failure`, so that the failed operations will automatically have their associated log files uploaded to Cumulocity IoT.
* https://github.com/thin-edge/thin-edge.io/issues/2761
* Original PR which introduced the `c8y.operations.auto_log_upload` setting: https://github.com/thin-edge/thin-edge.io/pull/2833
=> feat: upload c8y log file on failure by default

tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Prevent an inadvertent change of the `mqtt.bridge.built_in` setting at the end of a test by unsetting the value instead of setting it to an explicit value (and using an official `[Teardown]` hook so it is always executed regardless if the test passes or fails).
Technically the test flaky is present due to an unknown issue in the builtin bridge, however this issue will be addressed in another PR, https://github.com/thin-edge/thin-edge.io/pull/2911.
* https://github.com/thin-edge/thin-edge.io/issues/3022
=> test: reset mqtt.bridge.built_in setting to default value

.config/nextest.toml, .github/workflows/pull-request-checks.yml, .gitignore, justfile
Switch to using cargo-nextest to run the test on the CI Runner. cargo-nextest is already being used in the `just test` task definition.
Using cargo-nextest will enable individual tests to be configured to automatically retry (e.g. on flaky tests).
<br/>
=> ci: run tests using cargo-nextest

.config/nextest.toml
Mark the following unit tests as flaky:
* `bridge_reconnects_successfully_after_cloud_connection_interrupted` - similar to https://github.com/thin-edge/thin-edge.io/pull/3027
* `uploaded_file_can_be_downloaded_from_the_api`
The failed run was seen in the following CI runs:
* uploaded_file_can_be_downloaded_from_the_api
* https://github.com/thin-edge/thin-edge.io/actions/runs/10180472337
* https://github.com/thin-edge/thin-edge.io/actions/runs/10181924590
* uploaded_file_can_be_downloaded_from_the_api
* https://github.com/thin-edge/thin-edge.io/actions/runs/10181924590/job/28163263896
* https://github.com/thin-edge/thin-edge.io/issues/3021
* https://github.com/thin-edge/thin-edge.io/issues/3030
=> test: mark sporadically failing unit tests as flaky

crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/connect/jwt_token.rs, tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Send MQTT `DISCONNECT` on local MQTT connections (in normal operation) in the `tedge connect` and `tedge reconnect` commands.
* https://github.com/thin-edge/thin-edge.io/issues/3024
=> fix: disconnect cleanly from local MQTT broker in tedge connect

crates/extensions/tedge_mqtt_bridge/src/lib.rs, tests/RobotFramework/tests/cumulocity/bridge_config/builtin_bridge.robot
Messages with packet id 0 should be handled differently as they won't receive a PubAck or PubRec control messages hence it will never be removed from the hashmap and future messages with packet id 0 are ignored.
This should resolve the [last incident](https://github.com/thin-edge/thin-edge.io/issues/2960#issuecomment-2249874311) seen on the OSADL slot 2 device, as the tedge mapper went unresponsive after requesting a file from the device, which most likely invoked a JWT request, which never was answered. Note, that the problem is limited to publishing messages directly to the cloud topic with QoS 0, as publishing a message to the `te/#` topics will be republished to the `c8y/#` topics with QoS > 0 (something automatically done by the bridge, to ensure reliable cloud communication).
* …
=> fix: built-in MQTT bridge handling of QoS 0 messages published to the cloud topic

crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/operation_workflows/config.rs, tests/RobotFramework/tests/tedge_agent/tedge_agent_as_child.robot
The tedge-agent now respects the root topic value when passed via the `--mqtt-topic-root` flag.
* https://github.com/thin-edge/thin-edge.io/issues/3031
=> fix: tedge-agent use the root topic when provided by the cli flag

cliff.toml
Minor improvements to the formatting and classification rules used in the changelog generation (done by git-cliff):
* Limit scope of matching a message against a group by matching against `<scope>(.+)?:` to prevent matching against the description
* Add PR number check before returning the link to the PR
<br/>
=> ci: changelog formatting and classification improvements

plugins/c8y_remote_access_plugin/src/input.rs
Fix the issue of a unit test reported in https://github.com/thin-edge/thin-edge.io/pull/3007#discussion_r1699906163
<br/>
=> test: fix unit test to pass when the unit socket file exists

Cargo.lock, Cargo.toml
Reverting the version bump due to spotting an addition bug which should be fixed before the release thin-edge/thin-edge.io#3042. Reverting the version bump is required as if another PR is merged, then the "autotag" workflow will create the release tag again (which we want to prevent until we're ready for the official release).
=> Revert "minor version bump"

crates/extensions/c8y_mapper_ext/src/operations/handler.rs
When receiving multiple MQTT messages on a command topic, `OperationHandler::handle` method spawned extra tokio tasks, because `.unwrap_or` and not `.unwrap_or_else` was used when checking if a task for that topic already existed. Fortunately because returned object, and along it the sender to the task, was immediately dropped, the task exited and so we weren't leaking anything.
<br/>
=> fix: stop OperationHandler spawning extra tasks

.github/workflows/build-workflow.yml, ci/changelog/changelog.sh
A problem with the changelog from/to version detection prevented the release pipeline from completing. As a result the following changes are proposed:
* Option to detect the changelog from/to (e.g. previous release and current release) from git tags.
* Don't fail the pipeline if the changelog generation fails (as this is not strictly required for a release and can be run locally). This logic could be removed in the future once the changelog generation has been verified in production
<br/>
=> ci: changelog generation from tags and don't fail on errors

crates/extensions/c8y_mapper_ext/src/operations/handlers/config_snapshot.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/restart.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/software_update.rs
Unlike other c8y operations that we support so far, `c8y_DeviceProfile` operation requires a inventory update MQTT message after `EXECUTING` message. Refer to the [doc](https://cumulocity.com/docs/device-integration/fragment-library/#device-profile).
This PR changes `CommandStatus::Executing` to take extra MQTT messages after sending `EXECUTING` message to c8y.
P.S.
If we have a requirement that extra messages need to be send right **before** the `EXECUTING` message, this API need to be changed again. It will probably look like `CommandStatus::Executing {messages: Vec<MqttMessage>}` and all operation handlers need to add `501,<op_type` message to the vector explicitly. Since there is no such a requirement as of now, I prefer to hide `501` message creation inside the API as it is.
<br/>
=> refactor: CommandStatus::Executing takes extra MQTT messages

crates/extensions/c8y_mapper_ext/src/operations/handler.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
Avoid processing operations on a sub-workflow operation topic in OperationHandler.
To verify the fix I created two unit tests:
- one for OperationHandler to test its public interface
- one more permanent test in c8y_mapper_ext::tests to make sure it still
holds even if OperationHandler implementation changes
As this check could easily be done in c8y mapper unit tests, I didn't create an integration test.
- #3048 
To avoid similar problems in the future, we should distinguish sub-workflow command ids on a type level.
=> fix(#3048): don't send status update for sub-workflow operations

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/json_c8y_deserializer.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/tedge_api/src/commands.rs, crates/core/tedge_api/src/device_profile.rs, crates/core/tedge_api/src/lib.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/lib.rs, crates/extensions/c8y_mapper_ext/src/operations/convert.rs, crates/extensions/c8y_mapper_ext/src/operations/handler.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
=> feat: add operation mapping for device profile

crates/extensions/c8y_mapper_ext/src/operations/handler.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
If c8y mapper receives operation message with the same status again, don't send smartrest operation status message again.
It's still not clear what should be done if operation is cleared while processing or if some component publishes a previous status (e.g. c8y mapper received operation message with status SUCCESSFUL, but later received operation with the same ID with status EXECUTING).
<br/>
=> don't process operation status duplicates

crates/extensions/c8y_mapper_ext/src/operations/convert.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/software_update.rs
This PR solves two issues with mapping device profile operation:
- Mapper does not map `tenant_url` to `proxy_url` for device profile.
- Mapper does not update software list after finished operation.
* #2920 
<br/>
=> fix: mapper does not convert url to proxy_url and does not update the software list for the device profile operation

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/extensions/tedge_mqtt_bridge/src/lib.rs, crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
- Increase the max packet size of the built-in bridge to the same value as is used by `tedge mqtt pub`
- Document the feature flag for the built-in bridge
- Refactor the logic from #3028 
<br/>
=> fix: increase max packet size for built-in bridge

crates/core/plugin_sm/src/plugin.rs, tests/RobotFramework/tests/cumulocity/software_management/dummy-plugin.sh, tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
This small PR fixes issue with software artifacts being downloaded twice when `update-list` is not available. Extra validation step was introduced to check if artifact is downloaded.
* #3062 
<br/>
=> fix: software artifacts are downloaded twice when the `update-list` feature is not available

crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/core/tedge_mapper/src/core/component.rs, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
When the topic prefix is customised for the bridge, use that prefix in the mapper service name. If the topic prefix is set to e.g. `c8y-edge`, the resulting service name (in Cumulocity/the entity store, not systemd) will be `tedge-mapper-c8y-edge`. 
<br/>
=> feat: use custom topic prefix in mapper service name

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/extensions/c8y_firmware_manager/src/message.rs, crates/extensions/c8y_firmware_manager/src/worker.rs, crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/operations/handler.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/config_snapshot.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/restart.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/software_update.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/log/log_operation.robot, tests/RobotFramework/tests/cumulocity/restart/restart_device.robot, tests/RobotFramework/tests/cumulocity/software_management/software.robot
Cumulocity 10.18 version added [504-506](https://cumulocity.com/docs/smartrest/mqtt-static-templates/#504) SmartREST static templates, which enables users to update operation status with its operation ID. This PR adds a new tedge config to switch either 501-503 or 504-506 for operation status updates.
One can change the setting by `tedge config`. `true` (504-506), `false` (501-503). Ideally making `auto` option, however, this is out of scope of this PR.
```sh
tedge config set c8y.smartrest.use_operation_id true
```
Note: for the naming decision, see this [thread](https://github.com/thin-edge/thin-edge.io/pull/3076#discussion_r1732377605).
This change **excludes** the supports for below since they react to SmartREST operation messages, not JSON over MQTT. This means it's not possible to …
=> feat: add an option to use c8y operation ID to update its status

Cargo.lock, crates/common/tedge_config/src/sudo.rs, crates/core/tedge_write/src/api.rs, crates/extensions/tedge_config_manager/Cargo.toml, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_config_manager/src/error.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- Only use `tedge-write` for privilege elevation after normal copy fails due to `PermissionDenied` error and tedge-write is enabled
- Put more details into warn and error logs when deploying configuration files using `tedge-write`:
```
before: "WARN: `sudo.enable` set to `true`, but sudo not found in $PATH"
after:  "WARN: `sudo.enable` set to `true`, but sudo not found in $PATH, using tedge-write directly"
before: "ERROR: config-manager failed writing updated configuration file: Starting tedge-write process failed"
after:  "ERROR: config-manager failed writing updated configuration file: failed to start process '/usr/bin/tedge-write': No such file or directory (os error 2)"
before: "ERROR: config-manager failed writing updated configuration file: sudo: /usr/bin/tedge-write: command not …
```
=> config-manager: Only use tedge-write after normal copy fails due to permissions and improve tedge-write logging

crates/core/tedge/src/cli/connect/mod.rs, crates/core/tedge/src/cli/mod.rs
Thick edge depends on a few parts of the `tedge` crate library that were previously public but have since been made private in a refactoring PR. The goal of this is so thick edge can only do the parts of the connection process it cares about (e.g. the direct connection and mosquitto configuration) for connecting to c8y in an automated fashion. This PR restores the public visibility of those items.
<br/>
=> refactor: restore visibility of tedge api relied upon by thick edge

crates/extensions/tedge_config_manager/src/actor.rs
If tedge-failed, process error code and stderr were printed 2 times like this:
```
failed to deploy configuration file: process '/usr/bin/sudo' returned non-zero exit code (1); stderr="sudo: a password is required": process '/usr/bin/sudo' returned non-zero exit code (1); stderr="sudo: a password is required"
```
Now it doesn't contain a duplicate:
```
failed to deploy configuration file: process '/usr/bin/sudo' returned non-zero exit code (1); stderr="sudo: a password is required"
```
This was due to unnoticed wrapping of the error types: all the functions returned `ConfigManagementError`, but we still wanted to attach context, so we had the following nesting, which screwed up anyhow's error causes formatting:
ConfigManagementError::Other(anyhow::Error(source: …
=> Fix process exit code and stderr printing 2 times

crates/core/tedge_agent/src/agent.rs, tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot, tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_initialization.robot, tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Run the device profile manager builder before the loading the workflows, otherwise the newly created device_profile workflow will not be detected until the service is restarted.
The problem was being masked in the existing system test as the test restarted the tedge-agent in the setup due to adding an additional workflow (firmware_update). The system test to check the supported operation has been moved to an independent test which does not restart the tedge-agent in the test setup.
Partially solves https://github.com/thin-edge/thin-edge.io/issues/3088
**Note** installing thin-edge.io via the install.sh script will still require the tedge-agent to be restarted, however this is less of an issue
=> fix: create device_profile workflow before loading workflows from disk

crates/common/tedge_config/src/sudo.rs, crates/core/tedge_write/src/api.rs, crates/core/tedge_write/src/lib.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
API for spawning a tedge-write process no longer uses a hardcoded `/usr/bin/tedge-write` path.
The path was hardcoded because of the wrong assumption of how `sudo` works: when provided with a command without the full path, e.g. `sudo tedge-write /etc/config1`, `sudo` will internally look for `tedge-write` in $PATH and then compare path with its sudoers entry, so it's not necessary to use full path for binaries used with `sudo`.
- #3073
=> fix: tedge write remove hardcoded path

crates/core/tedge_mapper/src/c8y/mapper.rs
Change the MQTT client ID for `last_will_c8y_mapper` to use the topic prefix in place of `c8y`, so multiple mappers can connect to the same mosquitto.
<br/>
=> refactor: include topic prefix in c8y last-will service name

plugins/c8y_remote_access_plugin/src/lib.rs, tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
Avoid using an explicit path in the c8y_RemoteAccessConnect operation definition to allow c8y-remote-access-plugin to be installed in custom locations (e.g. anything other than `/usr/bin/c8y-remote-access-plugin`).
https://github.com/thin-edge/thin-edge.io/issues/3111
=> feat: avoid using explicit path to the c8y-remote-access-plugin binary

crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge_agent/src/lib.rs, crates/core/tedge_mapper/src/lib.rs, crates/core/tedge_watchdog/src/lib.rs, docs/src/legacy/child-device-firmware-management.md, docs/src/operate/configuration/index.md, docs/src/references/cli/index.md, docs/src/references/cli/tedge-cert.md, docs/src/references/cli/tedge-config.md, docs/src/start/getting-started.md, plugins/c8y_firmware_plugin/src/lib.rs, plugins/c8y_remote_access_plugin/src/input.rs, plugins/tedge_apt_plugin/src/lib.rs, tests/RobotFramework/tests/customizing/config_dir.robot
Support setting the tedge `--config-dir` flag via an environment variable, `TEDGE_CONFIG_DIR`
This makes it much easier for users which are installing thin-edge.io in custom locations, as they can just set an environment variable and all of the binaries will respect the config dir path without having to add `--config-dir` everywhere.
**Implementation Note:** Clap's `.env(key)` function as it does not ignore empty environment variables, e.g. if an empty env variable is defined`export TEDGE_CONFIG_DIR=''`, then clap's logic will set the value to an empty string instead of falling back to the default value. Hence why the `default_value` logic was used instead, but that has a downside that the doc string needs to be manually provided (since the .env and .default_value functions are not used). …
=> feat: support setting config dir via env variable

containers/tedge/Dockerfile
Use explicit user/group ids in the docker image to enable more predicatable behaviour across different build systems and images.
**References**
* https://www.docker.com/blog/understanding-the-docker-user-instruction/
<br/>
=> feat: use explicit user/group id in container image

crates/extensions/c8y_auth_proxy/src/server.rs, crates/extensions/c8y_auth_proxy/src/tokens.rs
This PR replace `unwrap()` with `anyhow` error handling when `c8y_auth_proxy` is trying to retrive JWT token.
* #3019 
<br/>
=> fix: handle error when jwt token could not be retrieved

crates/core/tedge_agent/src/operation_workflows/actor.rs, crates/core/tedge_agent/src/operation_workflows/builder.rs, crates/core/tedge_agent/src/operation_workflows/tests.rs, crates/core/tedge_api/src/commands.rs, crates/core/tedge_api/src/workflow/error.rs, crates/core/tedge_api/src/workflow/mod.rs, crates/core/tedge_api/src/workflow/script.rs, crates/core/tedge_api/src/workflow/state.rs, crates/core/tedge_api/src/workflow/supervisor.rs, crates/core/tedge_api/src/workflow/toml_config.rs, docs/src/references/agent/operation-workflow.md, tests/RobotFramework/tests/cumulocity/log/workflow/log_upload.sh, tests/RobotFramework/tests/cumulocity/log/workflow/log_upload.toml, tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot, tests/RobotFramework/tests/tedge_agent/workflows/init-software-list.sh, tests/RobotFramework/tests/tedge_agent/workflows/software_list.toml, tests/RobotFramework/tests/tedge_agent/workflows/software_update.toml
This is an alternative PR to [improve the way builtin operations are customized](https://github.com/thin-edge/thin-edge.io/issues/3014).
- For the first attempt, see https://github.com/thin-edge/thin-edge.io/pull/3070
- For the motivations for a second proposal, see  https://github.com/thin-edge/thin-edge.io/pull/3070#discussion_r1728933530
- For a description of this proposal, see:  https://github.com/thin-edge/thin-edge.io/issues/3014#issuecomment-2317687695
Improve the definition of operation workflows, so one can trigger a builtin operation the same way as for a sub operation. The aim is to make things easier to understand with less concepts, more consistent (while a single way to trigger an operation) and more flexible (ability to define specific state on success and on error). …
=> Feat: improve workflow builtin actions

crates/extensions/tedge_mqtt_bridge/src/health.rs, crates/extensions/tedge_mqtt_bridge/src/lib.rs
When a large amount of messages has to be published from the device to the cloud (say after a network outage),
the builtin bridge fails to cope with the load and reaches a point where no more progress is made. After a while, the local  MQTT broker closes the builtin bridge connection, with an error:
```
1725524939: Client tedge-mapper-bridge-c8y has exceeded timeout, disconnecting.
```
The root cause is a dead lock inside the builtin bridge. The two main tasks (one publishing local messages to the remote MQTT endpoint, the other forwarding the remote message acknowledgements to the local broker) are blocked waiting for the other to make progress.
What makes the issue not so easy to fix is that the MQTT library used by thin-edge (`rumqttc`) provides no way to reduce the pressure. When a …
=> fix: builtin bridge disconnected when under heavy load

crates/common/axum_tls/src/config.rs, justfile, tests/RobotFramework/tasks.py, tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot, tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Run `just format` to apply the formatting to the code base due to:
* Latest Rustfmt nightly results in new formatting
* Some Robotframework tests weren't formattinged before
To avoid committing unformatted Robotframework tests, the `format-check` was extended to also check the formatting of the Robotframework tests as well which is run on PR checks.
<br/>
=> ci: format code and add ci check for robotframework formatting

crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/mqtt_topics.rs, tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
The mapper panics when receiving a registration message such as `'te/device/child02//' '{"@type":"service"}'`.
The issue is that:
- the entity is seen as a child device i.e. matching `device/+//`
- but its registration message pretends that this is a service.
- the mapper tries then to register the entity as its own parent.
When the type of entity is explicitly set to be a service, but the topic id is attached to a child device (according to the default scheme), then this entity must be considered as non-following the default scheme.
https://github.com/thin-edge/thin-edge.io/issues/2986
=> fix: c8y mapper panics on unexpected registration message

crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/mqtt_topics.rs
Introduce a new function `mqtt_topic::default_topic_schema::parse()` taking an entity topic id and returning the registration messages matching the auto-registration behavior.
Using this `parse` function simplifies the auto-registration logic which has no more to parse again and again the entity topic id to extract registration info.
<br/>
=> Refactor: Simplify entity auto-registration

plugins/c8y_remote_access_plugin/src/input.rs, plugins/c8y_remote_access_plugin/src/lib.rs, tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
This PR add two new flags to `c8y-remote-access-plugin`: `--user` and `--group` that can be used only with `--init` flag. Plugin will now create directory with custom permissions provided by user or change the permissions if file/directory already exists.
* #2886
<br/>
=> feat: allow to init remote access plugin with non-standard user/group

Cargo.lock, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_downloader_ext/Cargo.toml, crates/extensions/tedge_downloader_ext/src/actor.rs, crates/extensions/tedge_downloader_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/configuration/config-root.json, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin-updated.toml, tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin.toml
Stop setting file ownership in tedge-agent, which runs as `tedge` user. Also added a missing test for a case when a file is owned by root.
Setting file ownership is a privileged operation, which should be done by tedge-write. It's also unnecessary to change permissions on a temporary file which is atomically moved into destination by config-manager anyway.
- #3143
This change should resolve the issue and is small, so it'd be good to merge it ASAP. It resolves first 2 points of https://github.com/thin-edge/thin-edge.io/issues/3143#issuecomment-2383833471, i.e. adds missing test case and removes the usage of `chown` while running as `tedge`.
We still unnecessarily leave temporary files, but that will be done in a follow-up PR.
=> fix: Stop chowning in tedge-agent

crates/extensions/c8y_mapper_ext/src/operations/upload.rs
The tedge-mapper-c8y feature controlled by `c8y.operations.auto_log_upload=on-failure`, uploads an operation log based on the given condition. This PR just adds an additional check to only do the upload if the log file exists to avoid scenarios where an event is created with no attachment...this typically occurs when running the tedge-agent on a child device, and the mapper does not yet have access to the related operation log.
<br/>
=> fix: check if log exists before trying to upload it

crates/common/tedge_config_macros/impl/src/reader.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
Fix some minor typos in the Rust source code (detected by running `typo` locally)
<br/>
=> chore: fix typos

tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation.robot
Format Robotframework system tests using robotframework-tidy.
<br/>
=> test: format robotframework system tests

.github/workflows/pull-request-checks.yml
Fail PR checks if typos are found to avoid merging any typos into main.
<br/>
=> ci: fail on detection of typos in PR check

crates/common/download/Cargo.toml, crates/common/download/src/download.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/messages.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_downloader_ext/src/actor.rs
Replace manually created tempfiles with `.tmp` suffixes that didn't properly get clean up on errors with `tempfile` which delete on drop.
Downloader and config manager should no longer leave temporary files if respective functions did not complete successfully.
<br/>
=> Use `tempfile` in config-manager and downloader to ensure tmpfiles are always deleted

crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, tests/RobotFramework/tests/cumulocity/shell/shell_operation.robot
Trims `reason` field for sent "set operation to SUCCESSFUL" smartrest messages.
Additionally, `...<trimmed>` indicator is inserted at the end to let the user know that the output was trimmed.
- https://github.com/thin-edge/thin-edge.io/issues/3171
This PR solves the issue for operation success message for `c8y_Command`, but may still possibly fail for other types of messages.
For a follow-up we should do a clean up and use types to verify that message is smaller than max limit.
=> fix: Trim `reason` field in "succeed custom operation" smartrest message

crates/common/batcher/src/batchable.rs, crates/common/flockfile/src/unix.rs, crates/common/mqtt_channel/src/messages.rs, crates/common/tedge_utils/src/timestamp.rs, crates/common/upload/src/upload.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/operations.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge_actors/src/examples/mod.rs, crates/core/tedge_actors/src/servers/mod.rs, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/measurement/parser.rs, crates/core/tedge_write/src/api.rs, crates/extensions/c8y_mapper_ext/src/operations/handler.rs
Today, [Rust 1.82 was published](https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html), which means there are new clippy lints breaking our CI that we get to fix. Yay 🎉
I also fixed lints present on nightly (1.84), so we should be good for a while.
<br/>
=> chore: Fix Rust 1.82 clippy lints

tests/RobotFramework/tests/mqtt/offline_publishing.robot, tests/images/debian-systemd/debian-systemd.dockerfile
This PR adds a new test case to validate the behavior of ThinEdge.io when the tedge-mapper-c8y service is down, and events are published during the downtime. The test ensures that events sent via MQTT while the mapper is offline are published to Cumulocity when the service is restored.
Test Flow:
1.	Stop the tedge-mapper-c8y service.
2.	Publish an MQTT event with a random event type and a test message.
3.	Restart the tedge-mapper-c8y service.
4.	Assert that the event is correctly received and processed by Cumulocity, verifying both the event type and message content.
https://github.com/thin-edge/thin-edge.io/issues/3185
<br/>
=> test: check publishing of telemetry data whilst mapper is down

Cargo.lock, crates/common/download/src/download.rs, crates/common/download/src/lib.rs, crates/core/c8y_api/src/http_proxy.rs, crates/extensions/c8y_auth_proxy/src/actor.rs, crates/extensions/c8y_auth_proxy/src/server.rs, crates/extensions/c8y_auth_proxy/src/tokens.rs, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_firmware_manager/src/lib.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/src/worker.rs, crates/extensions/c8y_http_proxy/Cargo.toml, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/credentials.rs, crates/extensions/c8y_http_proxy/src/handle.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_http_proxy/src/messages.rs, crates/extensions/c8y_http_proxy/src/tests.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, crates/extensions/tedge_config_manager/src/tests.rs, crates/extensions/tedge_downloader_ext/src/actor.rs, crates/extensions/tedge_downloader_ext/src/tests.rs, crates/extensions/tedge_http_ext/src/messages.rs
Pure refactoring PR to make a progress of #3036 easier.
- Now `C8YJwtRetriever` returns `HeaderMap`, previously it was just JWT token (`String`).
- Deprecate `Auth` enum in downloader so that downloader can accept any headers easily
- Remove unused functions in 897c1022a28c8593578788055b422b6f048bd966
Why this refactoring is needed?
#3036 needs to introduce Basic authentication instead of JWT token authentication. However, the current implementation, especially HTTP APIs, are designed to use Authorization header together with JWT token. Since the JWT actor is actually a server trait, for basic authentication, we can just implement a server trait.
Question:
The JWT token inplementation in `c8y_remote_access_plugin` seems duplicated to `C8YJwtRetriever` implementation... 
- …
=> refactor: flexible Authorization header type of HTTP request

crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/smartrest/alarm.rs, crates/core/c8y_api/src/smartrest/csv.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/mod.rs, crates/core/c8y_api/src/smartrest/operations.rs, crates/core/c8y_api/src/smartrest/payload.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/c8y_mapper_ext/src/alarm_converter.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
NOTE: there are some `.expect("TODO: ...")` calls where it's unclear what should be done on certain corner cases, e.g. when operation name is so pathologically long that it increases the size of the payload over the limit. These TODOs will have to be resolved before merging. 
This PR introduces a `SmartrestPayload` type, meant to encode assumptions about payload of SmartREST messages, i.e. that:
- it is a "CSV-like" format
- it has a size limit
This type should be used in places where we previously just used a plain `String` or constructed smartrest messages directly with `format!`, to ensure that above invariants always hold, and as the diff shows, in some places these invariants were being ignored. Most of them are corner cases, i.e. where it is technically possible for a device id or …
=> Improve validation of SmartREST payloads

Cargo.lock, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/system_services/log_config.rs, crates/core/tedge_agent/src/lib.rs, crates/core/tedge_mapper/src/lib.rs, crates/core/tedge_watchdog/src/lib.rs, crates/extensions/c8y_mapper_ext/src/operations/handler.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, plugins/c8y_firmware_plugin/src/lib.rs
Flags should always take precedence over environment variables because are often used by users to override the environment which they usually have little control over.
To implement this change it was necessary to refactor the code a little bit as previously `set_log_level` function was not aware if desired log level was specifically requested by the user (`--debug` flag) or just the default (`INFO` level). As such, the new `log_init` function takes into account all sources that decide what log level we should select: CLI options, `RUST_LOG` env variable, and tedge configuration file.
<br/>
To be merged before #3205
=> Make `--debug` flag override `RUST_LOG`

crates/extensions/c8y_mapper_ext/src/converter.rs
Replaces `ERROR: Mapping error: EOF while parsing a value at line 1 column 0` error log with a more meaningful warning log when publishing an empty message to a command metadata topic.
There are some unresolved questions wrt. clearing command metadata (see discussion in #2739), so for now we just provide a helpful message to the user. This feature will be implemented after the questions are resolved.
#2739
This PR was created so that the relevant issue can be closed, because the error message itself is not really a problem or a bug, but there's a much bigger design question about how clearing command capabilities should work, primarily when it comes to clearing capabilities of builtin agent commands. As such this PR provides a more meaningful warning to any users, while we can discuss the …
=> Add a warning about clearing command metadata being unsupported

Cargo.lock, Cargo.toml, crates/common/axum_tls/src/config.rs, crates/core/tedge/src/cli/config/commands/list.rs
Separately group workspace crates and dependencies in top-level Cargo.toml so it's easier to see how many creates are ours and how many are external dependencies.
Also deduplicated two dependencies by aligning the versions we use with one used transitively by other dependencies.
<br/>
=> Group workspace crates first in top-level Cargo.toml and deduplicate yansi and toml dependencies

crates/core/tedge/src/bridge/c8y.rs
Subscribe to C8Y topics using QoS 1
- There is no point to use QoS 2 as the session is cleared on each reconnect
- The builtin bridge is already using QoS 1
<br/>
=> fix: Subscribe to C8Y topics using QoS 1

crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/error.rs
Improve error reporting in c8y mapper by printing the topic when there was an error converting a message on that topic.
Example: when publishing an invalid command metadata message: `$ tedge mqtt pub -r te/device/main///cmd/config_snapshot 'a'`
before:
`ERROR: Mapping error: expected value at line 1 column 1`
after:
`ERROR: Mapping error: Failed to convert a message on topic 'te/device/main///cmd/config_snapshot': expected value at line 1 column 1`
<br/>
=> Attach topic to c8y message conversion error

crates/core/tedge_agent/src/operation_workflows/actor.rs, tests/RobotFramework/tests/tedge_agent/workflows/dynamic_workflow_reloading.robot, tests/RobotFramework/tests/tedge_agent/workflows/sleep-command.toml
Reproduce https://github.com/thin-edge/thin-edge.io/issues/3149
=> fix: agent leaves interrupted operations in non-final state 

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/c8y_api/src/http_proxy.rs, tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot
Minor improvements to the Cumulocity Basic Authentication feature (introduced in https://github.com/thin-edge/thin-edge.io/pull/3196).
* Include path to the credentials file in the error message when it does not exist
* Rename `credentials` to `credentials.toml` (to make it more clear that a toml formated file is expected)
* Use `config-dir` aware default value for the `c8y.credentials_path` configuration value (to support custom install locations)
* https://github.com/thin-edge/thin-edge.io/issues/3036
=> feat: c8y basic auth improvements

crates/core/c8y_api/src/http_proxy.rs
When configured with hostnames without domains,
c8y_api::http_proxy::maybe_tenant_url wrongly assumes any hostname, given without a domain,
is related to the same tenant.
This was due to wrong defaults when parsing an url with no domain.
<br/>
=> fix: c8y http proxy wrongly assumes any hostname is from the same tenant

Cargo.lock, crates/common/download/Cargo.toml, crates/common/download/src/download.rs
Whereas previously we considered only some errors to be permanent and the rest to be retryable, that logic was inverted so we check if an error is one of a few that is transient, and the rest are considered permanent.
Biggest changes:
- connect errors are considered transient
- timeouts are considered transient
- #3212
=> Change which download errors are retryable

tests/RobotFramework/tests/tedge_agent/workflows/run_workflow_on_child_device.robot
Since there is no workflow test which is running on child device, this PR adds such a test.
The workflow definition file and the shellscript are reused from another test. Hence, this PR contains only a new robot file.
<br/>
=> test: add workflow test running on child device

crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/main.rs, plugins/c8y_remote_access_plugin/src/input.rs, plugins/c8y_remote_access_plugin/src/lib.rs
Adds `--log-level` flag to previously missed `tedge` and `c8y-remote-access-plugin` components.
Together with #3205, the flag is present in these top-level components:
- tedge
- tedge-mapper
- tedge-agent
- tedge-watchdog
- c8y-firmware-plugin
- c8y-remote-access-plugin
#2089
=> Add `--log-level` to `tedge` and `c8y-remote-access-plugin`

crates/core/tedge_agent/src/operation_workflows/persist.rs, crates/core/tedge_api/src/workflow/mod.rs, crates/core/tedge_api/src/workflow/supervisor.rs
Exclude builtin workflows from methods persisting workflow definitions that are in-use.
This was leading to confusing error messages as no files are related to builtin workflows.
```
ERROR tedge_agent::operation_workflows::persist: Fail to remove the workflow copy at /etc/tedge/.agent/workflows-in-use/software_list-builtin.toml: No such file or directory 
```
https://github.com/thin-edge/thin-edge.io/issues/3251
=> fix: builtin workflows don't have to be released

crates/core/c8y_api/src/smartrest/operations.rs, crates/extensions/c8y_mapper_ext/src/operations/convert.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
Now the workflow input of a custom operation can be built from several excerpts of the json payload sent by Cumulocity.
```toml
[exec.workflow]
operation = "command"
input.x = "${.payload.c8y_CombinedInput.inner.x}"
input.y = "${.payload.c8y_CombinedInput.inner.y}"
input.z = { foo = "bar" }
```
https://github.com/thin-edge/thin-edge.io/issues/3095
=> feat: Improve custom operation workflow input

crates/common/certificate/src/lib.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/renew.rs
Prepare the [integration with Cumulocity CA](https://github.com/thin-edge/thin-edge.io/issues/3248), by putting apart the code to create self-signed certificate, to create signing request and to renew a certificate.
These different tasks was implemented by a single structure using misc flags to drive checks and file generation.
Now each PEM operation is control by a specific flow.
https://github.com/thin-edge/thin-edge.io/issues/3248
=> refactor: Untangle certificate request, creation and renewal

crates/common/tedge_config/src/cli.rs, crates/common/tedge_config/src/lib.rs, crates/common/tedge_config/src/system_services/log_config.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/main.rs, crates/core/tedge_agent/src/lib.rs, crates/core/tedge_mapper/src/lib.rs, crates/core/tedge_watchdog/src/dummy_watchdog.rs, crates/core/tedge_watchdog/src/lib.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs, crates/core/tedge_write/src/bin.rs, plugins/c8y_firmware_plugin/src/lib.rs, plugins/c8y_remote_access_plugin/src/input.rs, plugins/c8y_remote_access_plugin/src/lib.rs, plugins/tedge_apt_plugin/src/lib.rs
As suggested in https://github.com/thin-edge/thin-edge.io/pull/3271#discussion_r1861554564, since we want both `log_args` and `config_dir` be used by all thin-edge components, and because `log_args` also needs the `config_dir` to use in `log_init()`, use a shared `CommonArgs` in all thin-edge components to parse these arguments.
<br/>
=> refactor(cli): use `CommonArgs` for common arguments

crates/core/c8y_api/src/smartrest/operations.rs, crates/extensions/c8y_mapper_ext/src/converter.rs
This PR introduces an `SupportedOperations` struct that is used by `CumulocityConverter` to load and save operations.
It achieves following things:
- **Extract all fs operations and path building from `CumulocityConverter` into new operations module**: The main `CumulocityConverter` doesn't create any files or symlinks, or doesn't need to create paths, the logic of mapping supported operations to the filesystem is contained in its own module
- **No main device/child device branching in `CumulocityConverter`**: instead of having separate `operations: Operations` and `children: HashMap<Child, Operations>`, `SupportedOperation` handles this distinction, the converter just passes an external id
- Use `BTreeMap` for to have only one operation under a given name and to ensure consistent …
=> refactor: Extract operation implementation details from `CumulocityConverter`

docs/src/references/agent/operation-workflow.md
Remove warning about some of the workflow features not being finalized.
In addition, some minor typos and consistencies were fixed (e.g. use "builtin" over "built-in" so the language reflects the workflow keyword `builtin`.
<br/>
=> docs: remove workflow warnings

crates/core/c8y_api/src/smartrest/alarm.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/message_ids.rs, crates/core/c8y_api/src/smartrest/mod.rs, crates/core/c8y_api/src/smartrest/payload.rs, crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs, crates/core/c8y_api/src/smartrest/smartrest_serializer.rs, crates/core/c8y_api/src/utils.rs, crates/core/tedge/src/cli/connect/c8y_direct_connection.rs, crates/core/tedge/src/cli/connect/command.rs, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/src/worker.rs, crates/extensions/c8y_mapper_ext/src/operations/convert.rs
Create a single module that contains ids for Smartrest messages and static templates.
- user code is easier to read
- can easily jump to definition
- easier to see the dependency and find usages by grepping for the usage of the module
The next steps would be for thin-edge not to use these ids directly, but to provide a higher-level layer of abstraction for interacting with Cumulocity, much like go-c8y-cli.
<br/>
=> refactor: Create a module with smartrest message id consts

crates/core/tedge_api/src/mqtt_topics.rs, crates/core/tedge_api/src/workflow/state.rs, crates/extensions/c8y_mapper_ext/src/operations/convert.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/custom_operation.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs, crates/extensions/c8y_mapper_ext/src/supported_operations/operation.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/c8y_RelayArray.template, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/operation_relay_array_workflow.robot, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/set_relay.sh, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/set_relay.toml, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/c8y_Command.template, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/operation_command_workflow.robot, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/shell_execute.sh, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/shell_execute.toml, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/custom_operation_workflow.robot, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/do_something.sh
This PR solves two issues.
1. The new custom operation handlers with workflow execution didn't send the third or more argument(s) of SmartREST `503`/`506` messages (successful operation status update). This issue disabled supports for `c8y_Command` and `c8y_RelayArray`.
2. `501`-`503` messages didn't use the Cumulocity's operation name for custom operations. Instead, the command name (`<cmd_name>`)  from the topic `te/.../cmd/<cmd_name>/tedge-mapper-1234` was used.
If user wants extra arguments for `503`/`506`, they have to provide `exec.workflow.output`.
```toml
[exec]
topic = "c8y/devicecontrol/notifications"
on_fragment = "c8y_Command"
[exec.workflow]
operation = "shell_execute"
input.command = "${.payload.c8y_Command.text}"
output = "${.payload.result}"
```
Once c8y-mapper receives a …
=> Custom operation handler should parse extra arguments for 503/506 messages

crates/extensions/c8y_mapper_ext/src/actor.rs, tests/RobotFramework/tests/cumulocity/registration/processes_many_devices.robot
Solve the deadlock that can arise when C8yMapperActor can't complete sending MqttMessage to some other actor because that other actor can't complete the send of a `PublishMessage` to C8yMapperActor by creating a fast path to drain PublishMessage buffer ASAP.
Previously when `PublishMessage`s were a part of the main message box we could not prioritize them because we had to process messages in order;
separating out the receiver for `PublishMessage`s makes it so no other messages can block `PublishMessage`s and allows us to use select! to concurrently process them when processing other events blocks
- #3279
About the test: added one in Robot Framework, but it has some problems: for some reasons it takes very long and it publishes a lot of messages to the cloud. Given that this test could be …
=> fix #3279: Create a fast path for sending `PublishMessage`s

docs/src/extend/firmware-management/building-image/yocto/tutorial.md
Update yocto instructions to direct users to the kas project files which are now stored in the [meta-tedge](https://github.com/thin-edge/meta-tedge) repository instead of the now deprecated [meta-tedge-project](https://github.com/thin-edge/meta-tedge-project).
Add some additional notes about requirements for a build machine.
* https://github.com/thin-edge/thin-edge.io/pull/2877
=> docs: update yocto instructions to use new kas project location

configuration/init/systemd/tedge-mapper-aws.service, configuration/init/systemd/tedge-mapper-aws.target, configuration/init/systemd/tedge-mapper-aws@.service, configuration/init/systemd/tedge-mapper-az.target, configuration/init/systemd/tedge-mapper-az@.service, configuration/init/systemd/tedge-mapper-c8y.target, configuration/init/systemd/tedge-mapper-c8y@.service, configuration/package_manifests/nfpm.tedge-mapper.yaml, configuration/package_scripts/_generated/c8y-firmware-plugin/apk/postinst, configuration/package_scripts/_generated/c8y-firmware-plugin/apk/postrm, configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postinst, configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postrm, configuration/package_scripts/_generated/tedge-agent/apk/postrm, configuration/package_scripts/_generated/tedge-mapper/apk/postinst, configuration/package_scripts/_generated/tedge-mapper/apk/postrm, configuration/package_scripts/_generated/tedge-mapper/deb/postinst, configuration/package_scripts/_generated/tedge-mapper/deb/postrm, configuration/package_scripts/_generated/tedge-mapper/deb/prerm, configuration/package_scripts/_generated/tedge-mapper/rpm/postinst, configuration/package_scripts/_generated/tedge-mapper/rpm/postrm, configuration/package_scripts/_generated/tedge-mapper/rpm/prerm, configuration/package_scripts/_generated/tedge-watchdog/apk/postinst, configuration/package_scripts/_generated/tedge-watchdog/apk/postrm, configuration/package_scripts/generate.py, configuration/package_scripts/packages.json, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation_multi_cloud.robot
Add [systemd target](https://www.freedesktop.org/software/systemd/man/latest/systemd.target.html) unit definitions to ensure that any configured cloud service is restarted after updating the `tedge-mapper` package (for packages which use systemd only, e.g. deb and rpm packages).
The goal of this PR is not to offer users a way to manage all of the `tedge-mapper-<cloud>` template services with one command, but more so that the package will restart the services after the tedge-mapper package has been upgraded. The usage of the `.target` unit definitions may be extended in the future, but for now a low-risk approach is taken to not affect users who don't plan on using the cloud profile feature.
Some important design notes:
* Only the cloud profile service instances (e.g. the service template …
=> feat(packaging): manage tedge-mapper cloud profile service instances in install/upgrade/uninstall

crates/core/c8y_api/src/smartrest/message.rs, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
c8y/devicecontrol/notifications topic, as many others, can contain in its smartrest payload multiple records. For now ensure that multiple records are parsed from this topic in particular, as C8y sends multiple operations in a single message if e.g. device is offline, multiple operations are started, and then the device connects, it then receives all those operations in a single MQTT message.
But a longer term solution would be to refactor the code to ensure that we're supporting collecting multiple smartrest messages from all the possible MQTT topics.
#3297
=> fix: Collect multiple smartrest messages from c8y devicecontrol topic

crates/core/c8y_api/src/smartrest/message.rs, crates/extensions/c8y_firmware_manager/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/tests.rs
#3301 was wrong: using a function meant for splitting Smartrest will mess up JSON over MQTT since that function will unescape \" sequences which we want to do in Smartrest but avoid in JSON over MQTT. This PR undoes this function's rename and uses regular line splitting for JSON over MQTT.
- #3297
=> fix: split c8y JSON over MQTT messages using newline delimiter

crates/common/tedge_config_macros/src/multi.rs, crates/core/tedge/src/cli/config/commands/list.rs, crates/core/tedge/src/cli/connect/command.rs, docs/src/operate/c8y/cloud-profiles.md
Adds documentation for using cloud profiles to connect to multiple Cumulocity instances. Hides the `c8y.device.id` and related configurations since those don't yet work due to external ID issues.
Hiding the device ID is done in a single separate commit so it should be easy to revert once the feature works properly.
There is also a small change to ensure profile names are always lowercased, in case someone accesses a key using e.g. `tedge config get c8y.profiles.EDGE.url`, where we weren't previously lowercasing the profile name.
<br/>
=> doc: cloud profiles in Cumulocity

crates/core/tedge_api/src/workflow/supervisor.rs, tests/RobotFramework/tests/cumulocity/self-update/apt_package_pinning, tests/RobotFramework/tests/cumulocity/self-update/software_update.toml, tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Fix handling of in-progress commands/workflows which originate from the tedge-agent prior to 1.4.0.
https://github.com/thin-edge/thin-edge.io/issues/3305
=> fix: process non-versioned in-progress commands on startup

crates/core/tedge_agent/src/operation_workflows/actor.rs, crates/core/tedge_agent/src/operation_workflows/persist.rs, crates/core/tedge_api/src/workflow/supervisor.rs
When the agent restarts and loads pending operations, these operations might not have been assign a workflow version. This is notably the case after a self update from a previous version of the agent that was oblivious of workflow versions.
In such a case, the agent assumes the current user-defined version of the workflow is the version to be used for the pending command. The workflow definition is persisted in `workflows-in-use` directory and assigned to the command.
https://github.com/thin-edge/thin-edge.io/issues/3305
=> fix: Persist workflow definition of pending commands on start

crates/core/tedge_agent/src/operation_workflows/actor.rs, crates/core/tedge_agent/src/operation_workflows/persist.rs, crates/core/tedge_api/src/mqtt_topics.rs, crates/core/tedge_api/src/workflow/mod.rs, crates/core/tedge_api/src/workflow/state.rs, crates/core/tedge_api/src/workflow/supervisor.rs
Address comments raised on https://github.com/thin-edge/thin-edge.io/pull/3307
https://github.com/thin-edge/thin-edge.io/pull/3307
=> refactor: Simplify command state update methods

tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Improve readability of tests using large json payloads by formatting them via pretty print (with 2 spaces) and disabling the robotidy auto formatter for such lines. Previously the payloads were pretty printed but the robotidy auto formatter would strip the leading whitespace.
<br/>
=> test: pretty print json payloads and disable robotidy to preserve leading whitespace

crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/c8y_api/src/smartrest/topic.rs, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/service_monitor.rs, crates/extensions/c8y_mapper_ext/src/tests.rs, crates/extensions/tedge_mqtt_ext/src/test_helpers.rs
While publishing to a nested child device, publish directly to the SmartREST topic
of that device (`c8y/s/us/<xid>`), without specifying all of all its ancestors.
<br/>
=> refactor: Simplify SmartREST publish topics

crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/main.rs, docs/src/references/cli/index.md, plugins/tedge_apt_plugin/src/lib.rs
Simplify the way `tedge-mapper`, `tedge-agent` and `tedge-write` are launched: it's no more mandatory to create symlinks to `tedge` with appropriate names.
The following are now equivalent (for the mapper, but also the agent and  all tedge services and plugins ):
- `tedge run tedge-mapper c8y`
- `tedge-mapper c8y` where `tedge-mapper` is a copy or a symlink of `tedge`
The former `tedge` cli can be invoked as before:
```
$ tedge help
tedge is the cli tool for thin-edge.io
Usage: tedge [OPTIONS] <COMMAND>
Commands:
init             Initialize Thin Edge
cert             Create and manage device certificate
...
run              Run thin-edge services and plugins
...
```
https://github.com/thin-edge/thin-edge.io/issues/2696
This PR supersedes https://github.com/thin-edge/thin-edge.io/pull/3311
=> feat: Trigger tedge multicall with symlinks as well as sub-commands

crates/common/tedge_config_macros/impl/src/input/validate.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/main.rs, crates/extensions/c8y_auth_proxy/src/server.rs, crates/extensions/tedge_mqtt_bridge/src/lib.rs
Fix the new clippy warning.
```
error: this `map_or` is redundant
--> crates/common/tedge_config_macros/impl/src/input/validate.rs:120:39
|
120 |                 Self::Field(field) => field.rename().map_or(false, |rename| *target == rename),
|                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use is_some_and instead: `field.rename().is_some_and(|rename| *target == rename)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
= note: `-D clippy::unnecessary-map-or` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_map_or)]`
error: could not compile `tedge_config_macros-impl` (lib) due to 1 previous error
warning: build failed, waiting …
```
=> refactor: clippy warning unnecessary_map_or

crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, plugins/c8y_firmware_plugin/Cargo.toml, plugins/c8y_remote_access_plugin/Cargo.toml
Description of these crates is shown by clap in CLI help, so the descriptions were updated to make them more consistent.
- a trailing dot `.` was removed (looking at most popular Rust crates at https://lib.rs/std, none of those that have only a single sentence have a trailing dot)
- the descriptions were uncapitalized (they consist of a single sentence anyway and sometimes start with `thin-edge`)
Here's how the help text looks now:
```
Run thin-edge services and plugins
Usage: tedge run [OPTIONS] <COMMAND>
Commands:
tedge-mapper              tedge-mapper translates thin-edge.io data model to c8y/az/aws data model
tedge-agent               tedge-agent interacts with a Cloud Mapper and one or more Software Plugins
c8y-firmware-plugin       thin-edge device firmware management for Cumulocity …
```
=> cli: Update component crates descriptions

crates/core/tedge/src/cli/certificate/cli.rs, tests/RobotFramework/tests/tedge/certificate_signing_request.robot
`tedge cert create-csr <cloud> --profile <profile>` should use the CN of the corresponding device certificate/private key if `--device-id` is not provided.
#3315
=> fix: tedge cert create-csr should use cloud profile's CN

Cargo.lock, Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/cli.rs, crates/common/tedge_config_macros/Cargo.toml, crates/common/tedge_config_macros/impl/src/input/validate.rs, crates/common/tedge_config_macros/impl/src/query.rs, crates/common/tedge_config_macros/tests/cli_completions.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/common.rs, crates/core/tedge/src/cli/completions.rs, crates/core/tedge/src/cli/config/cli.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/cli/mqtt/cli.rs, crates/core/tedge/src/main.rs, docs/src/install/index.md, docs/src/operate/troubleshooting/log-files.md
This adds shell completions (bash, zsh, fish) to the `tedge` CLI. It should be fairly self explanatory, and the documentation added in the PR should explain how you can enable the feature for testing locally.
- #3331
=> feat: support shell completions in `tedge` cli

crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/http_server/entity_store.rs, crates/core/tedge_api/src/entity_store.rs, crates/core/tedge_api/src/store/pending_entity_store.rs, crates/extensions/c8y_mapper_ext/src/actor.rs, crates/extensions/c8y_mapper_ext/src/converter.rs, crates/extensions/c8y_mapper_ext/src/entity_cache.rs
=> Refactoring: Simplify entity registration internal API

.github/workflows/build-workflow.yml, tests/RobotFramework/README.md, tests/RobotFramework/tasks.py
Change the default of `invoke build` to use the locally built packages as this is the option used the most by all developers.
Below shows how to migrate from the previous command defaults:
|Before|After|
|--|--|
|`invoke build --local` | `invoke build` |
|`invoke build` | `invoke build --no-local` |
Due to this change the build-workflow.yaml had to be updated so that it would place the packages under the `target/` directory. To facilitate migrating to the new workflow, a temporary commit had to be added to allow the PR checks to pass and the merge queue to pass (see commit 7cff046266c903c14b984a96e4d08542351f96e2). This commit can be removed after the PR is merged into main.
<br/>
=> tests: default to using locally build packages

tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt
Update the robotframework-devicelibrary where the underlying device_test_core libraries has been update to update paramiko (ssh library) and remove the dependency to fabric.
This should remove a deprecation warning which has been visible in the robotframework log output for a while now, for example:
```sh
/home/runner/work/thin-edge.io/thin-edge.io/tests/RobotFramework/.venv/lib/python3.9/site-packages/paramiko/transport.py:253: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
"class": algorithms.TripleDES,
```
<br/>
=> test: update robotframework-devicelibrary dependency

crates/core/tedge_agent/src/http_server/file_transfer.rs
Fixes some flaky tests and a bug in the file transfer service where files were not uploaded in their entirety.
We were previously calling `.write`, but ignoring the number of bytes written. Since we always want to write the entire chunk, I have replaced this with `.write_all`. In addition, I've added a `BufWriter` to improve the performance when writing files, and ensured this buffer is flushed before responding to the request.
I've seen multiple failures locally, all of them exhibit the same "empty file" behaviour, and cannot reproduce any tedge-agent failures after applying the fix:
- #3030 
- #2816
=> fix: ensure file transfer service always writes uploaded file

Cargo.lock, crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs, crates/common/tedge_config_macros/Cargo.toml, crates/common/tedge_config_macros/examples/macro.rs, crates/common/tedge_config_macros/examples/multi.rs, crates/common/tedge_config_macros/examples/reader_function.rs, crates/common/tedge_config_macros/impl/src/dto.rs, crates/common/tedge_config_macros/impl/src/input/parse.rs, crates/common/tedge_config_macros/impl/src/input/validate.rs, crates/common/tedge_config_macros/impl/src/query.rs, crates/common/tedge_config_macros/impl/src/reader.rs, crates/common/tedge_config_macros/src/define_tedge_config_docs.md, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/renew.rs, crates/core/tedge/src/cli/config/cli.rs, crates/core/tedge/src/cli/config/commands/list.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/upload/mod.rs, crates/core/tedge/tests/main.rs, docs/src/operate/c8y/smartrest-one.md, tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot, tests/RobotFramework/tests/tedge/tedge_cert_create.robot, tests/RobotFramework/tests/tedge_connect/tedge_connect_cn_validation.robot
This PR aims to open up `device.id` as read-write key. This is the last piece of supporting basic authentication, as it needs `device.id` but not need for device cert.
TODOs:
**tedge cert/connect part**
**tedge_config part** (originally started in the PR #3318 by @jarhodes314 )
**doc part**
#3242
=> feat: support read-write device.id in tedge cert/connect

crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/http_server/entity_store.rs, crates/core/tedge_api/src/entity.rs, crates/core/tedge_api/src/entity_store.rs, docs/src/operate/registration/register.md, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Basic entity store query REST API implementation: `GET /tedge/entity-store/v1/entities` to list all entities.
Additional filtering capabilities to be added in follow-up PRs.
https://github.com/thin-edge/thin-edge.io/issues/3339
=> feat: REST API for querying entity store

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge/src/bridge/aws.rs, crates/core/tedge/src/bridge/azure.rs, crates/core/tedge/src/bridge/c8y.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs
As per the request in #3153, add `<cloud>.bridge.keepalive_interval` to the tedge config settings. 
Example usage:
```
tedge config set c8y.bridge.keepalive_interval 60s
```
With mosquitto, the value will be shown explicitly in `c8y-bridge.conf` as :
```
....
keepalive_interval 60
```
Using `60s` as default as I found 60 seconds is the default for both [mosquitto](https://mosquitto.org/man/mosquitto-conf-5.html) and [rumqttc](https://docs.rs/rumqttc/latest/src/rumqttc/lib.rs.html#493-515). 
#3153
=> feat: add MQTT keepalive_interval config to allow custom value per bridge

crates/common/axum_tls/src/acceptor.rs
Remove the `#[ignore]` attribute on one of the client certificate tests. Due to a change in the underlying certificate verifier, the error  rustls produces is slightly different to what it was previously, and this was causing the test to fail. We aren't interested in the specifics of the error message produced, we simply care that the error arose from the client certificate verification and not some bug in the test code. Having updated the test to check for the updated error, I've verified that it still fails for otherwise failing connections (e.g. the client not trusting the server certificate). Therefore I think a simple update to the test to reflect the new behaviour is sufficient here.
- #3375
=> test: re-enable client certificate test

crates/common/tedge_config/src/tedge_config_cli/models/auth_method.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/log.rs
Adds "auth method" and "credentials path" to `tedge connect c8y` output, and hides "certificate file" when this isn't used.
- #3380
=> feat: log the auth method when running `tedge connect c8y`

crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/http_server/entity_store.rs, crates/core/tedge_api/src/entity.rs, crates/core/tedge_api/src/entity_store.rs, docs/src/operate/registration/register.md, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/tedge/tedge_http.robot, tests/RobotFramework/tests/tedge_agent/http_server/entity_query_rest_api.robot, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Decided not to add the `depth` parameter as agreed [here](https://github.com/thin-edge/thin-edge.io/pull/3383#issuecomment-2639211046).
Multiple values for the same parameter is also not supported.
#3339
=> feat: Query parameter support for entity store query API

docs/src/references/cli/tedge-http.md
Replace absolute paths (e.g. `/references/cumulocity-proxy/`) with relative ones (e.g. `(../../cumulocity-proxy/`)
- The absolute paths are version agnostic: i.e. jumping from the *new* release to the *official* one.
- The entity store documentation being tagged as draft in the *official* docs, this was causing broken links.
https://github.com/thin-edge/thin-edge.io/actions/runs/13291559191
=> fix: broken links in tedge http docs

crates/common/mqtt_channel/src/topics.rs, crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/entity_manager/tests.rs, crates/core/tedge_agent/src/http_server/entity_store.rs, crates/core/tedge_api/src/entity_store.rs, docs/src/operate/registration/register.md, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Fixes:
* https://github.com/thin-edge/thin-edge.io/issues/3385
* https://github.com/thin-edge/thin-edge.io/issues/3387
=> feat: Return entity metadata in delete REST API response

crates/core/c8y_api/src/json_c8y_deserializer.rs, crates/core/c8y_api/src/smartrest/inventory.rs, crates/core/tedge_api/src/commands.rs, crates/core/tedge_api/src/device_profile.rs, crates/extensions/c8y_mapper_ext/src/operations/convert.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs, crates/extensions/tedge_config_manager/src/tests.rs, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/sub_config_update.toml, tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
This PR adds operation fragments messages for `device profile` and switch the order of those messages for `firmware/software update` so that they are sent before the succesful state change.
Additionally, the structure of `device profile` command was changed as it was not deserializing properly. The `remote_url` field was changed to `String` from `Option<String>` as it is the mandatory field (this does not affect code as it was derived from mandatory value anyway).
* #3162
<br/>
=> fix: c8y operation fragments for firmware/software update and device profile

configuration/package_scripts/_generated/tedge/apk/postinst, configuration/package_scripts/_generated/tedge/apk/postrm, configuration/package_scripts/_generated/tedge/deb/postinst, configuration/package_scripts/_generated/tedge/deb/postrm, configuration/package_scripts/_generated/tedge/rpm/postinst, configuration/package_scripts/_generated/tedge/rpm/postrm, configuration/package_scripts/tedge/postinst, configuration/package_scripts/tedge/postrm, docs/src/install/index.md, tests/images/debian-systemd/debian-systemd.dockerfile
Install the shell completions during the `tedge` post installation phase if the detected shell scripts are found.
Adding the script as part of the installation allows for a more seamless completion experience as sometimes no setup needs to be done if the user has already enabled shell completion for their preferred shell.
The system test image now includes the shell completion out of the box to help developers during testing and demos.
Note: The shell completion script is added as part of the post installation and not a static file as the clap generated script will use the full path to the binary that called the `tedge completions` command which makes running at build time problematic as it would use the build time path of the `tedge` binary instead of the destinations path.
* …
=> feat: install tedge tab completions during installation

crates/common/certificate/Cargo.toml, crates/common/tedge_config_macros/impl/src/query.rs
Clippy has updated the `useless_conversion` rule so it now detects unnecessary `T::from` invocations. This PR ignores that lint for the `define_tedge_config` macro as it shouldn't apply here. In this case, we convert indiscriminately since we don't have the required type information to determine if the conversion is truly necessary.
<br/>
=> fix: clippy error from tedge_config_macros

tests/RobotFramework/tests/cumulocity/upload/tedge_c8y_upload.robot
Because the first test didn't set device context like the other ones, library defaulted to returning events for other devices, so if there are other devices that run this test that were not deleted, the test will fail.
The library will be updated to warn/err if device context is not set, because in tests 99% of the time we want to get events only for the device we are testing, but for now update the test to fix failing CI.
<br/>
=> test: fix `tedge_c8y_upload.robot` not setting device context

tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
Some tests checking that the mapper reports "CertificateRequired" errors have become flaky since the hyper 1.0 upgrade.
I've been unable to reproduce the alternative "channel closed" error from hyper-util locally. We still assert that "CertificateRequired" appears in the unit tests, so we are confirming that the rust code passes on the required information to the end user in this case. As I'm unable to reproduce, this PR softens the assertions on the failure reason to not check for "CertificateRequired" in the robot tests.
- #3401
=> test: soften failure reason assertions for certificate required errors

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
The location of `entity_store.jsonl` was moved from `/etc/tedge/.tedge-mapper-c8y` to `/etc/tedge/.agent` by #3230. However, since our system test `get_logs()` is still looking at the old location, the function always raises this error message in a system test log:
```
tedge-mapper-c8y message log: /etc/tedge/.tedge-mapper-c8y/entity_store.jsonl
cmd: ['/bin/sh', '-c', 'cat /etc/tedge/.tedge-mapper-c8y/entity_store.jsonl || true'], exit code: 0
stdout:
<<empty>>
stderr:
cat: /etc/tedge/.tedge-mapper-c8y/entity_store.jsonl: No such file or directory
```
This PR fixes the location and enables the `get_logs()` to retrive the contents of `entity_store.jsonl`.
<br/>
=> test: get_logs should look at the new location of entity_store.jsonl

tests/RobotFramework/tests/tedge_agent/workflows/restart-tedge-agent.toml
Even though the tedge-agent would complete a shutdown within a matter milliseconds in most cases, sometimes all actors may not shutdown immediately as seen in #3415 extending the time taken for the shutdown. The actor runtime will wait upto 60 seconds for all actors to gracefully shutdown. So, adjusting the test workflow also accordingly.
https://github.com/thin-edge/thin-edge.io/issues/3415
=> tests: Increase restart tedge-agent test timeout

crates/common/tedge_config_macros/impl/src/input/validate.rs, crates/common/tedge_config_macros/impl/src/query.rs, tests/RobotFramework/tests/tedge/tedge_completions.robot
Add some tests which verify `tedge` responds correctly to a shell completion request. These tests simulate the command that `fish` uses when requesting `tedge` completions and checks that the response is the expected list of values and accompanying values. `fish` output is used as it is very human-readable and includes help text. These tests don't verify that the completion script is installed.
- #3373
=> test: add robot tests for cli tab completions

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge/src/cli/certificate/cli.rs, tests/RobotFramework/tests/tedge/certificate_signing_request.robot
As mentioned in #3413 user could not specified `device.csr_path` per cloud profile. This PR appends multi profile config with `csr_path` and replaces old approach of accessing config value in `tedge cert create-csr`.
* #3413 
<br/>
=> fix: add device.csr_path to cloud profiles

crates/core/tedge/src/cli/http/cli.rs, crates/core/tedge/src/cli/http/command.rs, crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/entity_manager/tests.rs, crates/core/tedge_agent/src/http_server/entity_store.rs, crates/core/tedge_api/src/entity_store.rs, docs/src/operate/registration/register.md, docs/src/references/cli/tedge-http.md, tests/RobotFramework/tests/tedge/tedge_http.robot, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
REST API to update entity twin data
<br/>
=> feat: REST API to update entity twin data

crates/core/tedge/src/cli/mqtt/cli.rs, crates/core/tedge/src/cli/mqtt/mod.rs, crates/core/tedge/src/cli/mqtt/publish.rs, crates/core/tedge/src/cli/mqtt/subscribe.rs
The PR #3445 uses the MQTT keepalive mechanism to achieve a timeout. When an outgoing event `PINGREQ` occurs, the code checks the elapsed time, and if the elapsed time is larger than the specified duration, `tedge mqtt sub` exits.
MQTT keepalive must be at least 1s, that's why a panic occurred for the `100ms` input as the ticket #3447 describes.
After trying several approaches, I decided to take this approach https://github.com/thin-edge/thin-edge.io/pull/3448#discussion_r1984854857. It requires the least code changes compared to other approaches and `--duration` can even accept `100ms` input.
Also, this PR fixes regarding a `DISCONNECT` packet. Now it is sent before exiting the command when timeout occurred or message count limit is reached.
#3447
=> fix: don't panic when --duration has less than 1s value

crates/core/tedge/src/cli/log.rs
Hides loading spinners when `stdout` is not a terminal, since it is not useful to indicate progress in such environments. 
This will print a e.g. `Verifying device is connected to cloud... ✓` line once the action is complete. It won't print anything for the given action until this is complete. This could be changed, but this current solution is a completely trivial change.
- #3455
=> refactor: don't show loading spinner if stdout isn't a terminal

crates/common/mqtt_channel/src/connection.rs, tests/RobotFramework/tests/mqtt/session_persistence.robot
Resubscribe to MQTT topics on reconnection when the no session is present. No session is present when mosquitto persistence has not been configured, or inaccessible (e.g. corrupt or incorrect ownership/permissions).
Previously, the reconnection logic was assuming that the only time the client needs to resubscribe to the MQTT topics is when an anonymous session is used. However if the MQTT broker persistence layer is not working, then the client should be checking if a session is present or not, and then resubscribing to the topics if no session was restored.
The most notable symptom without this change was that the tedge-agent would stop reacting to operations sent via MQTT if it would be disconnected from the local MQTT broker and if the MQTT broker persistence layer was not working or …
=> fix: subscribe to topics on reconnection when session persistence is not enabled or broken

tests/RobotFramework/tests/tedge_agent/tedge_agent.robot, tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
Replace usage of mosquitto_sub with `tedge mqtt sub`  (where possible) in system tests.
<br/>
=> tests: replace mosquitto_sub with tedge mqtt sub

crates/core/tedge/src/cli/mqtt/cli.rs, crates/core/tedge/src/cli/mqtt/subscribe.rs, tests/RobotFramework/tests/tedge/tedge_mqtt.robot
Adding support for the `--retained-only` flag (same function as the mosquitto_sub flag of the same name), to allow users to only get the retained messages from the local MQTT broker.
Note: When subscribing to the retained messages, it will only return the messages with the retain flag set, and it will actively stop when receiving the first non-retained message, or if the user specifies a duration timeout.
Below shows the most common usage of the flag.
```sh
tedge mqtt sub '#' --retained-only --duration 1s
```
The change will also allow the remaining usage of `mosquitto_sub` in the system tests to be replaced with `tedge mqtt sub` and also providing a useful tool to users.
<br/>
=> feat: support retained-only flag in tedge mqtt sub

Cargo.lock, Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/certificate/src/parse_root_certificate/mod.rs, crates/common/tedge_config/Cargo.toml, crates/common/tedge_config/src/tedge_toml/models/cryptoki.rs, crates/common/tedge_config/src/tedge_toml/models/mod.rs, crates/common/tedge_config/src/tedge_toml/tedge_config.rs, crates/common/tedge_config/src/tedge_toml/tedge_config/append_remove.rs, crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs, crates/core/tedge/src/cli/connect/command.rs, crates/extensions/tedge-p11-server/Cargo.toml, crates/extensions/tedge-p11-server/README.md, crates/extensions/tedge-p11-server/src/client.rs, crates/extensions/tedge-p11-server/src/connection.rs, crates/extensions/tedge-p11-server/src/lib.rs, crates/extensions/tedge-p11-server/src/main.rs, crates/extensions/tedge-p11-server/src/pkcs11.rs, crates/extensions/tedge-p11-server/src/server.rs, crates/extensions/tedge-p11-server/src/service.rs, crates/extensions/tedge-p11-server/src/signer.rs, crates/extensions/tedge-p11-server/src/single_cert_and_key.rs
This PR adds the `tedge-p11-server` component, that unlike other services is built separately and runs directly on the host to allow other thin-edge services access to PKCS#11 cryptographic tokens. The server listens on a UNIX domain socket and exposes two kinds of procedures that is passes for execution to the PKCS#11 cryptographic token:
1. choosing the signature scheme from offered candidates
2. signing the message
The crate also exports a client that performs `rustls`' choosing scheme and signing operations by connecting via the UNIX socket and requesting them from the server, which interacts with the cryptoki device directly.
Replaced `device.cryptoki.enable` with `device.cryptoki.mode` which can be one of `off`/`module`/`socket`
- `off` - cryptoki is disabled and private key is read …
=> feat: cryptoki via UNIX socket

crates/core/tedge/src/cli/connect/command.rs
When a custom Cumulocity domain is used (aka the Cumulocity enterprise feature), the HTTP and MQTT endpoints will differ, however thin-edge.io was previously only checking the MQTT endpoint against URL derived from the Cumulocity JWT (which has the HTTP URL). The error only resulted in an invalid warning being shown to the user, however it just adds noise and confusion for the user.
Now, both the HTTP and MQTT endpoints are compared to ensure that at least one of them match.
https://github.com/thin-edge/thin-edge.io/issues/3501
=> fix: use both mqtt and http address when validating connecting c8y tenant url

Cargo.lock, crates/extensions/tedge-p11-server/Cargo.toml, crates/extensions/tedge-p11-server/src/main.rs, crates/extensions/tedge-p11-server/src/server.rs
If we bind the socket in tedge-p11-server (as opposed to receiving it from systemd), remove this socket after exiting.
Also improves error message when trying to bind at a path that already exists, as suggested in https://github.com/thin-edge/thin-edge.io/pull/3511#pullrequestreview-2724840631:
```
Error: Failed to bind to socket at '/run/tedge-p11-server/pkcs11.sock'
Caused by:
Address already in use (os error 98)
```
=> feat(tedge-p11-server): Remove owned socket file after exiting

crates/extensions/aws_mapper_ext/src/converter.rs, crates/extensions/az_mapper_ext/src/converter.rs
Currently, we skip the conversion message when it comes on the `aws` or `az` bridge status topics. However, this is not sufficient, as the mapper reacts to all bridge status topics. Moreover, it always fails if the payload cannot be parsed into the `Map<String, Value>` format.
This PR changes the logic: instead of checking the topic, we now attempt to parse the payload as a `u8` and check if value is 0 or 1. If so, we skip the conversion. For other payload formats, a more descriptive error message will be logged.
* #3488
<br/>
=> fix: skip bridge status messages in aws/az mappers

Cargo.lock, Cargo.toml, crates/common/certificate/src/lib.rs, crates/common/tedge_config/src/tedge_toml/tedge_config.rs, crates/common/tedge_config_macros/src/multi.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_api/src/json_c8y_deserializer.rs, crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/c8y/download.rs, crates/core/tedge/src/cli/certificate/c8y/mod.rs, crates/core/tedge/src/cli/certificate/c8y/renew.rs, crates/core/tedge/src/cli/certificate/c8y/upload.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/error.rs, crates/core/tedge/src/cli/certificate/mod.rs, crates/core/tedge/src/cli/certificate/renew.rs, crates/core/tedge/src/cli/certificate/show.rs, deny.toml, tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot, tests/RobotFramework/tests/tedge/tedge_upload_cert.robot, tests/RobotFramework/tests/tedge/tedge_upload_cert_custom_root_cert_path.robot
https://github.com/thin-edge/thin-edge.io/issues/3248
=> feat: Integration with Cumulocity CA

crates/core/tedge/src/cli/certificate/show.rs
Improve accessibility of tedge cert show: do not rely on color to distinguish a certificate which will expire soon from a certificate still valid for a safe period of time.
https://github.com/thin-edge/thin-edge.io/issues/3526
=> fix: improve accessibility of tedge cert show

crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge/src/cli/certificate/c8y/download.rs, crates/core/tedge/src/cli/certificate/c8y/renew.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/src/cli/certificate/create_csr.rs, crates/core/tedge/src/cli/certificate/error.rs, crates/core/tedge/src/cli/certificate/mod.rs, crates/core/tedge/src/cli/certificate/renew.rs
https://github.com/thin-edge/thin-edge.io/issues/3524
=> fix: tedge cert renew returning success exit code on error 

ci/build_scripts/package.sh, ci/package_list.sh, configuration/contrib/tedge-p11-server/tedge-p11-server.conf, configuration/init/systemd/75-tedge.preset, configuration/init/systemd/tedge-p11-server.service, configuration/init/systemd/tedge-p11-server.socket, configuration/package_manifests/nfpm.tedge-p11-server.yaml, configuration/package_scripts/_generated/tedge-p11-server/apk/postinst, configuration/package_scripts/_generated/tedge-p11-server/apk/postrm, configuration/package_scripts/_generated/tedge-p11-server/apk/preinst, configuration/package_scripts/_generated/tedge-p11-server/apk/prerm, configuration/package_scripts/_generated/tedge-p11-server/deb/postinst, configuration/package_scripts/_generated/tedge-p11-server/deb/postrm, configuration/package_scripts/_generated/tedge-p11-server/deb/preinst, configuration/package_scripts/_generated/tedge-p11-server/deb/prerm, configuration/package_scripts/_generated/tedge-p11-server/rpm/postinst, configuration/package_scripts/_generated/tedge-p11-server/rpm/postrm, configuration/package_scripts/_generated/tedge-p11-server/rpm/preinst, configuration/package_scripts/_generated/tedge-p11-server/rpm/prerm, configuration/package_scripts/packages.json, configuration/package_scripts/tedge-p11-server/preinst, crates/common/tedge_config/src/tedge_toml/tedge_config.rs, crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs, tests/RobotFramework/tests/pkcs11/data/init_softhsm.sh, tests/RobotFramework/tests/pkcs11/private_key_storage.robot, tests/images/debian-systemd/debian-systemd.dockerfile, tests/images/debian-systemd/files/bootstrap.sh
Package tedge-p11-server as linux packages and a tarball. The tedge-p11-server binary must not be compiled with the MUSL target as it relies on dynamically loading libraries (e.g. .so or .dylib files) which MUSL targets do not support, however the required build changes which ensures that the tedge-p11-server is compiled correctly was done in https://github.com/thin-edge/thin-edge.io/pull/3529.
A system test was added to test the tedge-p11-server interaction with thin-edge.io by using softhsm2 (which is a PKCS11 compliant HSM which allows testing of the PKCS11 interface without any additional hardware).
Minor changes:
* Changed the default socket path used by tedge and tedge-p11-server to match the systemd socket path
<br/>
=> feat: tedge-p11-server packaging

.github/workflows/build-workflow.yml, .github/workflows/pull-request-checks.yml
We have an issue that the merge queue failed due to flaky unit tests, however, the artifacts are published to cloudsmith. To prevent the issue, this PR proposes:
1. Move `cargo-test` job from the Pull Request Check workflow to the Build workflow so that publishing artifacts can be prevented if `cargo-test` job fails.
2. ~~Merge queue (event: `merge_group`) triggers **only** the build workflow.~~ Not able to do this, since GitHub required checks don't differentiate checks under PR and Merge Queue :/
3. Instead of 2), `Filter changes` is skipped when the event is `merge_group`, that allows to skip all the following jobs.
4. To do 3), I moved `Check whether Cargo.lock is up to date` after the filtering. Indeed, if the change is not related to Rust, this check should be skipped. 
<br/>
=> ci: move cargo-test job to build-workflow

crates/extensions/c8y_mapper_ext/src/config.rs, crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
This PR fixes the issue in https://github.com/thin-edge/thin-edge.io/issues/3545#issuecomment-2789804235.
`C8yMapperConfig` used the HTTP endpoint as its MQTT endpoint by mistake. This causes the issue highlighted by #3545. 
Unfortunately, the method `C8yMapperConfig::from_tedge_config()` cannot be tested by unit tests or integration tests. This is the reason of why this bug was not detected easily, although we have good unit/integration test coverage for that. The logic of replacing with proxy url that we have is correctly addressing the difference of these endpoints.
#3545
=> fix: c8y mapper config should use the value of c8y.mqtt as mqtt endpoint

tests/images/debian-systemd/files/mosquitto.conf
Increase the default mosquitto `max_inflight_messages` setting from 20 to 200 to avoid observed problems with the system test stability due to mosquitto 2.0.11 silently discarding some messages when the limit is exceeded.
The logs from the observed system test failures (currently they have only been visible on the CI workflow), show that some messages sent to the broker are not making it to the subscribed clients (e.g. niether the mqtt-logger nor the tedge-mapper) which makes the system tests fail.
Flaky system test issues:
* https://github.com/thin-edge/thin-edge.io/issues/3512
* https://github.com/thin-edge/thin-edge.io/issues/3489
=> tests: increase max inflight messages for mosquitto to avoid dropped messages

crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/entity_manager/tests.rs, crates/core/tedge_api/src/entity_store.rs, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Clear retained twin data messages on entity deregister.
https://github.com/thin-edge/thin-edge.io/issues/3492
=> fix: clear retained entity twin messages on deregister

crates/extensions/tedge-p11-server/Cargo.toml, crates/extensions/tedge-p11-server/src/main.rs
When tedge-p11-server is creating the socket itself (e.g. not using the systemd socket binding), then it should also create the required parent directories if they do not already exist.
Now the following `--socket-path` does not have to exist prior to starting the tedge-p11-server:
```
tedge-p11-server \
--pin 123456 \
--module-path /opt/homebrew/lib/libykcs11.dylib \
--socket-path /tmp/tedge-p11-server/example.sock
```
<br/>
=> fix: create tedge-p11-server socket parent directory if it does not exist

crates/common/tedge_config/src/tedge_toml/models/cryptoki.rs, crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs, crates/core/tedge/src/bridge/aws.rs, crates/core/tedge/src/bridge/azure.rs, crates/core/tedge/src/bridge/c8y.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/log.rs, crates/core/tedge_mapper/src/aws/mapper.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/extensions/tedge-p11-server/src/client.rs, tests/RobotFramework/requirements/requirements.txt, tests/RobotFramework/tests/pkcs11/private_key_storage_aws.robot
Add PKCS#11 support for AWS and Azure built-in bridges.
I have manually tested `tedge connect aws` and `tedge connect az` using a self-signed certificate created by `tedge cert create` which now creates a cert that uses the ECDSA P-256 with SHA256 sigscheme.
- #3543
=> feat: PKCS#11 support for aws and azure

Cargo.lock, configuration/contrib/tedge-p11-server/tedge-p11-server.conf, configuration/init/systemd/tedge-p11-server.service, crates/common/tedge_config/src/tedge_toml/tedge_config.rs, crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs, crates/extensions/tedge-p11-server/Cargo.toml, crates/extensions/tedge-p11-server/src/main.rs, crates/extensions/tedge-p11-server/src/pkcs11.rs, tests/RobotFramework/tests/pkcs11/private_key_storage.robot, tests/RobotFramework/tests/pkcs11/private_key_storage_aws.robot
Read tedge.toml in `tedge-p11-server` to avoid people having to supply the information via command-line arguments. This avoids using `tedge_config` to avoid unnecessary dependencies for `tedge-p11-server`.
During the refactoring the following additional changes were done (which are still configuration file related)
- #3539
=> feat: allow tedge p11 server to be configured through tedge.toml

crates/core/tedge/src/cli/http/command.rs, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Fix a bug where the `tedge http` command would not flush the stdout before exiting which would result empty stdout.
This behaviour caused some system tests to fail as a result, most notably https://github.com/thin-edge/thin-edge.io/issues/3559.
With this change linked flaky test ticket now passes 100% of the time (from a 100 run sample).
```
$ invoke flake-finder --test-name "Updating entities from a child device" --iterations 100 --clean
Overall: PASSED
Results: 100 iterations, 100 passed, 0 failed
Elapsed time: 0:16:13.157208
```
https://github.com/thin-edge/thin-edge.io/issues/3559
=> fix: flush stdout before exiting tedge http command

configuration/init/systemd/tedge-p11-server.service, crates/extensions/tedge-p11-server/src/main.rs, tests/RobotFramework/tests/pkcs11/private_key_storage.robot
tedge-p11-server proceeds on missing tedge config
https://github.com/thin-edge/thin-edge.io/issues/3579
=> fix: tedge-p11-server fails when configuration is missing

Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge/src/bridge/mod.rs, crates/core/tedge/src/cli/certificate/cli.rs, crates/core/tedge/src/cli/common.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/connect/mod.rs, crates/core/tedge/src/cli/refresh_bridges.rs, crates/core/tedge/src/lib.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/lib.rs
Use Cargo features to configure the supported cloud backends in the thin-edge mapper and the supported bridges.
An integrator who wants to use thin-edge in a product can use the features to explicitly disable supported cloud backends at compile time.
https://github.com/thin-edge/thin-edge.io/issues/3584
<br/>
=> Configure supported cloud backends at compile time

Cargo.lock, Cargo.toml, plugins/c8y_remote_access_plugin/Cargo.toml, plugins/c8y_remote_access_plugin/src/lib.rs, plugins/c8y_remote_access_plugin/src/proxy.rs, tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
Support the HTTP proxy configuration in the c8y remote access plugin. This was an accidental omission with the proxy feature.
- #3598
=> fix: support HTTP proxy in c8y remote access plugin

crates/extensions/tedge-p11-server/src/client.rs, crates/extensions/tedge-p11-server/src/pkcs11.rs, crates/extensions/tedge-p11-server/src/server.rs, crates/extensions/tedge-p11-server/src/service.rs, crates/extensions/tedge-p11-server/src/signer.rs
This PR has 2 parts:
1. Fix a bug where we didn't keep the handle to the key we found using the URI if it was declared, but used another search to find a new key capable of signing. Sometimes it worked, because the library could technically return the least recently used key as "first", which worked sometimes but not always. Now, within the session we keep track of the object handle in the key struct so the key is guaranteed to be correct.
2. Add a ready ready check when creating the `TedgeP11Client`. During a shared debugging session with @reubenmiller, we discovered that on certain setups loading the PKCS11 library can be unreasonably slow, so we decided to make a request that starts the server before the actual handshake to ensure the server is warm. More rationale in the method doc …
=> fix: pkcs11 signing with a wrong key and a ready check when `TedgeP11Client` is created

docs/src/references/hsm-support.md, docs/src/references/tedge-p11-server.md, docs/src/references/tedge-write.md
Fills in missing fallback text for `sh command="tedge ..."` blocks, which were generating fine locally, but were empty in the live docs because of missing thin-edge binaries.
https://github.com/thin-edge/tedge-docs/issues/110
=> docs: Fill in fallback values for sh command blocks

crates/extensions/tedge-p11-server/src/server.rs
A blocking sync operation that blocked the tokio executor was previously missed. All of the blocking operations were moved to spawn_blocking where they shouldn't block anymore.
* https://github.com/thin-edge/thin-edge.io/issues/3606
=> tests: Fix tedge-p11-server blocking test

crates/core/tedge/src/cli/certificate/cli.rs
Accept values provided to flags, which are related to passwords, to start with a hypen (to prevent cli parsing errors).
Only the password related flags were allowed for this, as other fields didn't make much sense starting with a hypen anyway.
The following commands should now work:
```sh
tedge cert download c8y --one-time-password "-example1234"
tedge cert upload c8y --password "-example1234"
```
* https://github.com/thin-edge/thin-edge.io/issues/3618
=> fix: accept values starting with hypen in flags related to passwords

tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot, tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/smartrest_template.robot, tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot
- Re-enable some maximum message count assertions that were skipped while #3402 was awaiting a fix
- Remove the maximum message count assertion in the custom smartrest operation test. In the case of custom smartrest operations, the mapper makes no attempt to de-duplicate incoming operations, so we can't guarantee that an operation won't be executed twice, particularly in the case of system tests which run just after tedge has started up.
<br/>
=> refactor: Update tests to check for maximum message counts only when appropriate

Cargo.lock, Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/mqtt_channel/src/config.rs
There's now been a rustls-pki-types release since https://github.com/rustls/pki-types/pull/71 was merged, so this adopts those changes meaning we can once again zeroize the private key.
- #3376
=> refactor: reinstate private key zeroisation

crates/common/certificate/src/parse_root_certificate/mod.rs, crates/common/download/src/download.rs, crates/common/tedge_config/src/system_toml/log_level.rs, crates/common/tedge_config/src/system_toml/mod.rs, crates/common/tedge_utils/src/file.rs, crates/common/tedge_utils/src/paths.rs, crates/common/upload/src/upload.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/tests/plugin.rs, crates/core/tedge/src/bridge/common_mosquitto_config.rs, crates/core/tedge/src/bridge/config.rs, crates/core/tedge/src/cli/certificate/create.rs, crates/core/tedge/tests/mqtt.rs, crates/core/tedge_agent/src/state_repository/state.rs, crates/extensions/tedge_log_manager/src/manager/log_utils.rs, crates/extensions/tedge_uploader_ext/src/tests.rs, crates/tests/tedge_test_utils/src/fs.rs, plugins/c8y_remote_access_plugin/src/lib.rs, plugins/c8y_remote_access_plugin/src/proxy.rs
Improve the file handling by:
- Making sure we flush any buffers once we have written to the file
- Making sure we use a `BufWriter` to improve file performance
- For cases where we write all the contents at once (often the case in tests, use `fs::write(...)` instead of manually opening a file
There are probably many cases here where it's not strictly necessary to do a flush (anywhere where we close a file before we rely on the data being persisted), but there are definitely quite a few cases where we this assumption doesn't hold for us.
<br/>
=> refactor: flush after calling write_all

crates/common/tedge_config/src/tedge_toml/tedge_config.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/log.rs, tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Change `cryptoki:` line in connection summary from simple `true/false` to display mode and key URI:
- If mode is off: `cryptoki: off`
- If mode is not off and `key_uri` is not set: `cryptoki: MODE`
- If mode is not off and `key_uri` is set: `cryptoki: MODE (key: KEY)`
<br/>
I'm not sure if this is the best way to format the information in the summary, I'm open to suggestions for changes.
An alternative would be to instead of separate `cryptoki:` line, to add a `private key:` line, and put there `key_uri` and `key_path` config settings, depending whether cryptoki is enabled or not.
=> feat: Connect summary cryptoki show mode and key URI

crates/core/tedge_agent/src/restart_manager/actor.rs
Cargo +nightly check is failing with error: future cannot be sent between threads safely because `args` of type `CommandArgs<'_>` is not `Send`
This is weird because `args` is not used by the future `command.status().await`. 
Fixed, by dropping `args` before the call to await.
<br/>
=> fix: broken 1.89.0-nightly build

configuration/contrib/operations/c8y_RemoteAccessConnect, configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
Fix an issue where the c8y-remote-access-plugin's maintainer scripts are not executed on Alpine Linux due to the apk package only containing a post-installation script (no actual files) which calls the `c8y-remote-access-plugin --init` which creates the required operation handler file. This resulted in the Remote Access not appearing in Cumulocity as the operation definition was missing.
To avoid this problem, the `c8y_RemoteAccessConnect` operation definition is being added to each of the linux packages (for consistency across deb, rpm and apk), to avoid this problem. The init command can still be run as it can correct any potential file ownership issues that may have changed over time on the user's device.
https://github.com/thin-edge/thin-edge.io/issues/3667
=> fix: missing operation file c8y-remote-access-plugin when installed on Alpine Linux

crates/core/tedge/src/system_services/managers/general_manager.rs
A wrong variant of ServiceCommand was used which caused an error message to wrongly report that `ServiceCommand::Enable` instead of `ServiceCommand::Start` failed when `start` command in `system.toml` did not contain a placeholder for an argument.
<br/>
Some of the service manager code could be further improved:
1. Many arguments are passed down unnecessarily just for sake of error reporting, we could instead not pass them down and instead attach the context up the call stack.
2. Could use docs comments describing why we use `system.toml` file and why handling it takes quite a bit of code
=> fix: wrong message being shown on `system.toml` parse error

crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/entity_manager/server.rs, crates/core/tedge_agent/src/entity_manager/tests.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
On entity deregistration, fetch all retained messages associated with that entity and its children and then clear them all.
<br/>
=> fix: clear all retained entity messages on entity deregistration

crates/core/tedge/src/cli/diag/collect.rs, tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
Only the tarball path prints out to `stdout` to make the following usecase work.
```sh
OUTPUT_PATH=$(tedge diag collect --name some_file_name)
tedge upload c8y --file "$OUTPUT_PATH"
tedge upload c8y --file "$(tedge diag collect)"
```
#3646
=> chore: tedge diag's tarball path prints out to stdout

crates/extensions/tedge-p11-server/src/pkcs11/mod.rs, crates/extensions/tedge-p11-server/src/pkcs11/uri.rs
Notable ECDSA signature formatting changes:
- replace an unwrap when serializing ASN.1 with a returned error
- add documentation
- add test checking if we're not misinterpreting `r` or `s` as negative values when MSB is set
<br/>
=> PKCS11 Extract uri module to another file and improve PKCS11 ECDSA signature formatting

crates/extensions/tedge_downloader_ext/src/tests.rs
This reverts commit dd5a8e0abc42c00ae69746154ad92b79d10d575d.
Re-enable the download tests following the merging of #3726.
<br/>
=> refactor: Revert "disable problematic tests to allow the CI changes to be merged"

crates/common/tedge_utils/src/atomic.rs, crates/common/tedge_utils/src/file.rs, crates/core/tedge_write/src/api.rs, crates/core/tedge_write/src/bin.rs, crates/core/tedge_write/src/lib.rs, crates/extensions/tedge_config_manager/src/actor.rs, crates/extensions/tedge_config_manager/src/config.rs, docs/src/operate/c8y/configuration-management.md, docs/src/references/agent/tedge-configuration-management.md, tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot, tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot, tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin.toml
Previously, the `config_update` operation would fail if any parent directories of the target file were missing.
This change ensures that missing parent directories are automatically created when the operation is executed.
The mode, user, and group of the immediate parent directory can be configured via `tedge-configuration-plugin.toml` using the following keys:
- `parent_mode`
- `parent_user`
- `parent_group`
If `parent_user` and `parent_group` are not explicitly specified, but the target file's ownership is provided, the parent directory will inherit the file's user and group.
#3693
=> feat: create parent directories if missing for config_update operation

crates/core/tedge/src/main.rs
Restore previous default log level for `tedge`, i.e. `WARN`. `tedge` uses that because `INFO` is too noisy for commands like `tedge mqtt pub/sub`
<br/>
=> fix: Restore `WARN` log level for tedge

tests/images/debian-systemd/files/gost-http-proxy.service
Modify the `gost-http-proxy` service definition to wait for gost to be running before executing the related tests.
This should fix a flaky test which appears to be caused when a test tries to connect to gost before the port is listening.
- #3729
=> refactor: ensure gost has started before running related tests

crates/extensions/c8y_mapper_ext/src/converter.rs
Ensure `tedge-mapper-c8y` doesn't handle incoming custom operations if received multiple times from Cumulocity.
The specific case this fixes is for custom operations from Cumulocity JSON fragements (e.g. on `c8y/devicecontrol/notifications`) where these execute using a `command` from the mapper. Since these don't use a workflow to execute, these operations didn't generate any `te/...` messages, so we didn't track them in `active_commands`. This PR changes this so that any operation with an ID is included in `active_commands`, and it will be removed after a 12 hour timeout elapses.
This won't fix any cases where we are using smartrest to receive the operation payload, since those messages do not have an ID included in the payload.
- #3399
=> fix: de-duplicate custom operations on c8y/devicecontrol/notifications

tests/RobotFramework/tests/cumulocity/inventory/inventory_update_bootstrap.robot
Fix a flaky test which was introduced in https://github.com/thin-edge/thin-edge.io/pull/3742.
The root case seems to be a race condition where if the mapper is restarted whilst the tedge-agent is still starting up, when results in inventory name/type values being non-deterministic. It is unclear whether there is something can be done in the mapper to make this more reliable, however the test needs to be patched so it does not block other PRs.
Below are multiple failures which occurred on the CI runner.
* https://github.com/thin-edge/thin-edge.io/actions/runs/16679498844
* https://github.com/thin-edge/thin-edge.io/actions/runs/16678104887
* https://github.com/thin-edge/thin-edge.io/actions/runs/16677349088
The failures can be easily re-produced by reducing the CPU quota for the system …
=> test: wait for agent to be ready before restarting mapper

docs/src/operate/c8y/custom-fragments.md
I've received feedback that it should be more obvious that Users need to Edit Widgets / Adapt the UI before seeing the custom fragments they created via thin-edge.io. 
For all other actions (create measurements, events, alarms, create child-devices/services, etc.) no changes are needed on cloud side, for custom fragments there is. This PR introduces a short note about it to the docs.
<br/>
=> docs: add info how to display custom fragments in Cumulocity Dev-Mgmt UI

crates/common/json_writer/src/lib.rs, crates/core/tedge_api/src/measurement/builder.rs, crates/core/tedge_api/src/measurement/group.rs, crates/core/tedge_api/src/measurement/mod.rs, crates/core/tedge_api/src/measurement/parser.rs, crates/core/tedge_api/src/measurement/serialize.rs, crates/extensions/c8y_mapper_ext/src/serializer.rs, docs/src/understand/thin-edge-json.md, tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Allow  meta properties to be published along tedge measurements, and forward these properties unchanged to Cumulocity.
```
tedge mqtt pub te/device/main///m/example '{
"time": "2020-10-15T05:30:47+00:00",
"temperature": 25,
"properties": {
"sensor": "DS18B20",
"has_alarm": false,
"samples": [ 25.1, 25.0, 24.9],
"range": {
"min": "-55°C",
"max": "+125°C"
}
}
}'
```
https://github.com/thin-edge/thin-edge.io/issues/3768
=> feat: publish properties along tedge measurements

configuration/init/systemd/tedge-cert-renewer-c8y.target, configuration/init/systemd/tedge-cert-renewer-c8y@.service, configuration/init/systemd/tedge-cert-renewer-c8y@.timer, configuration/init/systemd/tedge-mapper-c8y@.service, configuration/package_manifests/nfpm.tedge-mapper.yaml, docs/src/operate/c8y/cloud-profiles.md, tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
Add a new systemd service template to handle the certificate renewal when using a Cumulocity mapper with cloud profiles. The previous service `tedge-cert-renewer@.service` isn't able to support cloud profiles as the template variable (the part after the `@` sign) is used for the mapper type, and not the cloud profile name.
The new `tedge-cert-renewer-c8y@.timer` unit (not the `-c8y` before the `@` sign!) will be automatically activated when the `tedge-mapper-c8y@.service` is enabled/created. The timer then will trigger the corresponding `tedge-cert-renewer-c8y@.service` which then does the actual certificate renewal commands for the given cloud profile.
Note: You can manually enable and start the renewal process for a given Cumulocity cloud profile using the following commands:
```sh …
```
=> feat: enable cert renewal when using cloud profiles with Cumulocity

crates/core/tedge/src/cli/connect/c8y.rs, tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot
`tedge connect c8y --test` uses SmartREST `123` and expects to receive `124` when using basic auth.
#3791
=> fix: tedge connect c8y --test works with basic auth

crates/extensions/tedge-p11-server/src/pkcs11/mod.rs, crates/extensions/tedge-p11-server/src/pkcs11/uri.rs, tests/RobotFramework/tests/pkcs11/private_key_storage_runtime_changes.robot
When opening a session to a token as part of a request, all slots and tokens visible by the system will be printed.
We will also print URIs of all objects that we can see on the token.
NOTE: this PR also reverts "https://github.com/thin-edge/thin-edge.io/pull/3772", because this fix introduces TLS timeouts. For details see the commit message https://github.com/thin-edge/thin-edge.io/commit/7bcf8a91d7da11a4c5e7491063ff1ae48bda0190
<br/>
This is a follow-up to #3766 that we thought was solved but is not. The issue can't be reliably reproduced, so we need to improve diagnostics for when it eventually reappears.
=> improve: PKCS11 slots/tokens/objects logging

crates/common/tedge_config/src/lib.rs, crates/common/tedge_config/src/sudo.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/extensions/tedge_log_manager/src/plugin_manager.rs, tests/RobotFramework/requirements/requirements.adapter-docker.txt, tests/RobotFramework/requirements/requirements.adapter-local.txt, tests/RobotFramework/requirements/requirements.adapter-ssh.txt, tests/RobotFramework/tests/cumulocity/log/log_operation_plugins.robot
Improve error reporting when:
<br/>
=> refactor: Improve error reporting on sudo execution error
