thin-edge/thin-edge.io

docs/src/architecture/thin-edge-json.md, docs/src/tutorials/send-thin-edge-data.md
Replacing https://github.com/thin-edge/thin-edge.io/pull/135
=> [CIT-226] Document Thin Edge JSON format #135

docs/src/tutorials/connect-azure.md, tedge/src/cli/connect/az.rs
This PR fixes some typos related to azure connect source code and document
=> Fixed minor issues with azure

docs/src/howto-guides/002_installation.md, docs/src/howto-guides/003_registration.md, docs/src/references/README.md, docs/src/tutorials/connect-azure.md, docs/src/tutorials/connect-c8y.md, tedge/src/certificate.rs
This PR addresses fixing of tedge name typos and azure topic name
=> Fixed some typos with tedge name

BUILDING.md, CONTRIBUTING.md, README.md
=> [CIT-334] Add How to build doc

configuration/contrib/collectd/tedge-collectd.conf
A sample collectd config file that the users can use to enable some basic monitoring collecting the stats of cpu, memory and disk.
https://cumulocity.atlassian.net/browse/CIT-330
=> [CIT-330] Sample collectd configuration file

.github/workflows/hosted-post-merge_version_update.yml, release.toml
Add `--token` to cargo release to push back to gh.
=> Modify versioning script to use github token

Cargo.lock, mapper/thin_edge_json/Cargo.toml, mapper/thin_edge_json/examples/tej_example.rs, mapper/thin_edge_json/src/group.rs, mapper/thin_edge_json/src/lib.rs, mapper/thin_edge_json/src/measurement.rs, mapper/thin_edge_json/src/serialize.rs
Signed-off-by: Pradeep K J <Pradeep K J pradeekumar.kj@softwareag.com>
This PR captures the new feature that added to the thin_edge_json library to create a Thin Edge Json message and serialize the message from the raw data. This code changes use two traits to implement this new feature.
Also included an example to show how the feature works.
Todo
tests have to be added
documents have to be updated
- [X ] New feature (non-breaking change which adds functionality)
<br/>
- [x ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x ] I ran `cargo fmt` as mentioned in …
=> [CIT-309] thin edge json library for measurement

.github/workflows/commit-workflow.yml
Upload code coverage to codecov.io.
A status badge will be added one all tokens are generated and upload is working.
https://cumulocity.atlassian.net/browse/CIT-325
=> [CIT-325] Upload code coverage to codecov.io

README.md
Add codecov status badge to Readme.md
https://cumulocity.atlassian.net/browse/CIT-325
=> Add codecov status badge

get-thin-edge_io.sh
Check if terminal supports colours and use VERSION in the url.
=> [CIT-337] Add check if terminal supports colours and enable them if it does

tedge/src/cli/connect/cli.rs, tedge/src/cli/connect/command.rs, tedge/src/cli/connect/error.rs
Highlights:
- Add `--test` option to tedge connect az/c8y
- check_connection() returns Err if fails (previously Ok)
- `--test` returns exit code 1 if check_connection() fails
- Without `--test` returns exit code 0 if check_connection() fails (warning, no change)
Introduce `--test` option to `tedge connect az/c8y`.
Usage:
sudo tedge connect c8y --test
sudo tedge connect az --test
Returns
0 (successful)
1 (failed)
It doesn't diagnose why it failed. It could be several reasons, mosquitto is not running, bridge doesn't exists, configuration in bridge file is incorrect, the cloud server is down, the device has no connection to the internet...
Potential improvements are adding small diagnoses. For example, "mosquitto is not …
=> [CIT-300] Add --test option to tedge connect

.github/workflows/hosted-post-merge_version_update.yml
=> Add missing ':'

configuration/contrib/collectd/tedge-collectd.conf
These changes limit the collectd stats to:
```
collectd/alsu-VirtualBox/memory/percent-used 1620823056.140:21.629949542071
collectd/alsu-VirtualBox/memory/percent-buffered 1620823056.140:1.78092561188144
collectd/alsu-VirtualBox/memory/percent-cached 1620823056.140:60.3273147631985
collectd/alsu-VirtualBox/memory/percent-slab_unrecl 1620823056.140:1.6127107819838
collectd/alsu-VirtualBox/memory/percent-slab_recl 1620823056.140:2.44361380222239
collectd/alsu-VirtualBox/memory/percent-free 1620823056.140:12.2054854986429
collectd/alsu-VirtualBox/cpu/percent-active 1620823056.140:0.351053159478435
collectd/alsu-VirtualBox/df-root/percent_bytes-free 1620823056.140:71.1158752441406
collectd/alsu-VirtualBox/df-root/percent_bytes-reserved 1620823056.140:4.20682430267334 …
```
=> [CIT-366] Collectd config with minimal stats reported in percentage

common/mqtt_client/src/lib.rs
Add additional delay when mqtt_client gets connection refused.
=> [CIT-293] Add delay when mqtt_client connection error

docs/src/references/bridged-topics.md, tedge/src/cli/connect/bridge_config_c8y.rs
Remove extraneous topics from config.
=> [CIT-313] Remove 's/oc' and 's/os' topics from config

configuration/init/systemd/tedge-dm-agent.service
Add service file for tedge-dm-agent
=> [CIT-352] Add tedge-dm-agent service file

configuration/debian/tedge_dm_agent/postinst, mapper/dm_agent/Cargo.toml
Add cargo deb configuration to Cargo.toml for dm_agent.
Add postinst script for tedge-dm-agent.
=> [CIT-332] Add deb configuration for dm_agent

Cargo.lock, mapper/cumulocity/c8y_translator_lib/Cargo.toml, mapper/cumulocity/c8y_translator_lib/benches/thin_edge_json.rs
Add benchmark tests benchmark tests of the translation of thin-edge-json into c8y json
```
$ cargo bench
Translate reference measurement
time:   [2.2199 us 2.2320 us 2.2442 us]
change: [-2.5685% -1.0897% +0.2377%] (p = 0.14 > 0.05)
No change in performance detected.
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high mild
Translate 2 measurements
time:   [1.2666 us 1.2733 us 1.2812 us]
change: [-0.9141% -0.3642% +0.1641%] (p = 0.20 > 0.05)
No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
2 (2.00%) high mild
2 (2.00%) high severe
Translate 50 measurements
time:   [9.7494 us 9.8084 us 9.8721 us]
change: [-2.8495% -2.2200% -1.5213%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild …
```
=> [CIT-356] Add thin-edge-json benchmark tests

.github/pull_request_template.md
A new checkbox for "Improvement" PRs in the "Types of Changes" section.
<br/>
=> New Types of Changes entry for improvements

common/mqtt_client/tests/integration_test.rs
Fix compilation error in integration-test
<br/>
=> Fix compilation error in integration-test

BUILDING.md
=> Update MSRV in docs to 1.51

configuration/debian/tedge/postrm
Support purge option for tedge debian package removal
<br/>
=> [CIT-353] Support purge option for tedge debian package

.github/workflows/hosted-post-merge_version_update.yml
This is a very small change to stop running version update workflow in forked repositories every weekend.
<br/>
=> Stop version update workflow running in the forks

common/mqtt_client/examples/sawtooth_publisher.rs, common/mqtt_client/examples/simple_mapper.rs, common/mqtt_client/examples/temperature_publisher.rs, common/mqtt_client/src/lib.rs, mapper/dm_agent/src/collectd.rs, mapper/tedge_mapper/src/mapper.rs, tedge/src/cli/connect/command.rs, tedge/src/cli/mqtt/error.rs, tedge/src/cli/mqtt/subscribe.rs
This PR captures the code changes for the null-terminated payloads. The earlier fix was only taking care of the publishing side but the real issue was on the subscriber side. So, this will address the issue.
- Converted payload a private member of Message structure
- Added a function to trim the null character at the end of the payload
<br/>
If this is a relatively large or complex …
=> trim null terminated payload

common/mqtt_client/tests/integration_test.rs
This PR captures the code changes for fixing the broken mqtt integration test.
<br/>
=> Fix mqtt integration test

configuration/contrib/collectd/tedge-collectd.conf
Limit the monitoring stats published for memory and disk to just the "used" percent values and ignore other values like "free", "reserved" etc.
<br/>
=> [CIT-366] Minimal monitoring stats for memory and disk

Cargo.lock, common/certificate/Cargo.toml, common/certificate/src/lib.rs, common/mqtt_client/Cargo.toml, mapper/collectd_mapper/Cargo.toml, mapper/cumulocity/c8y_translator_lib/Cargo.toml, mapper/tedge_mapper/Cargo.toml, mapper/thin_edge_json/Cargo.toml, tedge/Cargo.toml
* tokio 1.1 -> 1.6
* proptest 0.10 -> 1.0
<br/>
=> Cargo outdated

Cargo.lock, common/certificate/Cargo.toml, common/clock/Cargo.toml, common/flockfile/Cargo.toml, common/mqtt_client/Cargo.toml, common/tedge_users/Cargo.toml, mapper/collectd_mapper/Cargo.toml, mapper/cumulocity/c8y_translator_lib/Cargo.toml, mapper/tedge_mapper/Cargo.toml, mapper/thin_edge_json/Cargo.toml, tedge/Cargo.toml, tedge_config/Cargo.toml
=> (cargo release) bump version 0.2.0

tests/PySys/call_tedge_-V/run.py
Fix a system test that checks the tedge version
<br/>
=> Adopt system test to new tedge version

common/mqtt_client/tests/integration_test.rs
This PR captures the code changes for fixing the broken mqtt client library integration test. 
The test was broken after I updated the library validation of mqtt payload for valid utf8.
- [ x] Bugfix (non-breaking change which fixes an issue)
<br/>
=> Fix broken integration test

docs/README.md, docs/gen-ref-docs.sh, docs/src/references/tedge-cert.md, docs/src/references/tedge-config.md, docs/src/references/tedge-connect.md, docs/src/references/tedge-disconnect.md, docs/src/references/tedge-mqtt.md, docs/src/references/tedge.md
* Add a script `docs/gen-ref-docs.sh` to generate the cli reference documentation
* Update the ref docs (after 0.2 release)
<br/>
=> [CIT-228] Generate the ref docs

common/mqtt_client/src/lib.rs
This introduces a small change to `mqtt_client` configuration as it seems the default limit of 10KB may be too small for some operations and therefore we need to make it configurable.
=> Add packet size config for mqtt client

Cargo.lock, mapper/tedge_mapper/Cargo.toml, mapper/tedge_mapper/src/az_mapper.rs, mapper/tedge_mapper/src/c8y_mapper.rs, mapper/tedge_mapper/src/component.rs, mapper/tedge_mapper/src/converter.rs, mapper/tedge_mapper/src/main.rs, mapper/tedge_mapper/src/mapper.rs
Introduce a TEdgeComponent trait that the az & c8y mappers implement. This interface could be used for future components running inside a single process - thus reducing memory footprint by running all the components in a single process rather than as separate processes.
https://cumulocity.atlassian.net/browse/CIT-380
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …
=> CIE-380: Migrate mappers to components

tedge/src/cli/connect/bridge_config_c8y.rs
* Forward to c8y the child-devices related topics.
#300 
=> [#300] Add the child device topics to c8y bridge

mapper/tedge_mapper/src/mapper.rs
Fix CIT-423 - where the mapper flock file was not working.
https://cumulocity.atlassian.net/browse/CIT-423
<br/>
=> CIT-423: Longer lifetime for flock handle

.github/workflows/hosted-post-merge_version_update.yml
Use GH Action to create pull request with bumped versions of crates.
=> [CIT-369] Create pull request from workflow

tests/PySys/tedge_mapper_az/tedge_mapper_az_with_timestamp/run.py, tests/PySys/tedge_mapper_az/tedge_mapper_az_without_timestamp/run.py
Fix system tests by removing trailing slashs from topics. Unclear if this worked before.
<br/>
=> Fix system test: remove trailing shashs from topics

common/mqtt_client/examples/publish_test.rs, common/mqtt_client/examples/sawtooth_publisher.rs, common/mqtt_client/examples/temperature_publisher.rs, common/mqtt_client/src/lib.rs, common/mqtt_client/tests/integration_test.rs, mapper/collectd_mapper/src/error.rs, mapper/tedge_mapper/src/error.rs, mapper/tedge_mapper/src/mapper.rs, mapper/thin_edge_json/src/serialize.rs, tedge/src/cli/connect/error.rs, tedge/src/cli/mqtt/error.rs, tedge/src/cli/mqtt/publish.rs, tedge/src/error.rs
Signed-off-by: Pradeep K J <Pradeep K J pradeekumar.kj@softwareag.com>
This PR captures the code changes to rename the mqtt_client::Error to mqtt_client::MQTTClientError.
- [x ] Improvement (general improvements like code refactorings that doesn't explicitly fix a bug or add any new functionality)
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> Rename mqtt_client::Error to mqtt_client::MQTTClientError

tests/PySys/call_tedge_-V/run.py, tests/requirements.txt
Read tedge version from tedge Cargo.toml
Will read the expected version automatically.
<br/>
=> Read tedge version from tedge Cargo.toml

Cargo.lock, common/mqtt_client/Cargo.toml, common/mqtt_client/examples/publish_test.rs, common/mqtt_client/src/lib.rs, mapper/collectd_mapper/src/batcher.rs, tedge/Cargo.toml, tedge/src/cli/mqtt/publish.rs
Related PR #299. This is an alternative approach that does not need any modifications of rumqttc. Completely untested.
=> WIP - Remove publish with ack

mapper/tedge_mapper/src/az_mapper.rs, tests/PySys/tedge_mapper_az/tedge_mapper_az_with_timestamp/run.py, tests/PySys/tedge_mapper_az/tedge_mapper_az_without_timestamp/run.py
Code changes include adding the trailing slash to the azure topic in azure mapper code as well as in system tests.
<br/>
=> [CIT-441] add trailing slash to azure topics

ci/ci_smoke_test.sh, ci/roundtrip_local_to_c8y.py, tests/PySys/environments/environment_roundtrip_c8y.py
Some improvements from the hackathon
- Improved output in case of missing messages (see pic)
- Avoid password on command line
<br/>
=> Improve c8y roundtrip test

Cargo.toml
This adds a couple of possible compilation profile options to minimise size of produced binaries.
Eg:
Current main with `cargo build --release` (in bytes):
```shell
7145128 ./target/release/collectd_mapper
9465112 ./target/release/tedge
7164464 ./target/release/tedge_mapper
```
With profile additions:
```shell
5699304 ./target/release/collectd_mapper
7508552 ./target/release/tedge
5756664 ./target/release/tedge_mapper
```
Short description of proposed changes:
[panic](https://doc.rust-lang.org/cargo/reference/profiles.html#panic) - abort should decrease size.
[codegen-units](https://doc.rust-lang.org/cargo/reference/profiles.html#codegen-units) - generally less should produce smaller and faster code.
[opt-level](https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level) - default …
=> Add release profile options to binaries

docs/src/SUMMARY.md, docs/src/references/README.md, docs/src/references/plugin-api.md
Approved specification for the Plugin API
<br/>
=> [CIT-412] Publish the Plugin API

common/mqtt_client/src/lib.rs
Fix QoS 0 counting PUBACKs and not removing them after pub (as server doesn't respond with PUBACK in QoS 0).
Fix a couple of spelling mistakes.
=> Change order of QoS statuses to correctly count publish in QoS 0

common/mqtt_client/src/lib.rs, tedge/src/cli/mqtt/publish.rs
This should get rid of any delays by using notifications.
=> Refactor inflight tracking and notify on completed instead of polling

.github/workflows/build-workflow.yml, .github/workflows/integration-test-workflow.yml
Remove remaining `collectd_mapper` from build workflow.
=> Remove collectd_mapper from workflow

.github/workflows/build-workflow.yml
=> Fix typo in build workflow

.github/workflows/build-workflow.yml, .github/workflows/integration-test-workflow.yml
Update artifacts names in workflows to adhere to new arm matrix builds.
=> Rename integration tests packages to use artificats from matrix

Cargo.lock, common/certificate/Cargo.toml, common/clock/Cargo.toml, common/flockfile/Cargo.toml, common/json_writer/Cargo.toml, common/mqtt_client/Cargo.toml, mapper/cumulocity/c8y_translator_lib/Cargo.toml, mapper/tedge_mapper/Cargo.toml, mapper/thin_edge_json/Cargo.toml, sm/plugins/tedge_apt_plugin/Cargo.toml, tedge/Cargo.toml, tedge_config/Cargo.toml
Update crates dependencies versions.
=> Update crates dependencies versions

Cargo.lock, docs/src/references/tedge-mqtt.md, tedge/src/cli/mqtt/cli.rs
Change the help message of tedge mqtt sub to show that the topic is for subscription, not for publication.
https://cumulocity.atlassian.net/browse/CIT-425
<br/>
=> CIT-425: Fix copy-paste error in mqtt sub help message

common/certificate/src/device_id.rs
Remove compiler warnings in device_id tests.
=> Fix warnings in tests

.gitignore, tests/PySys/mqtt_port/mqtt_port_change_connection_works/run.py
Update name of service in system tests.
=> Rename collectd_mapper service to tedge-mapper-collectd

mapper/thin_edge_json/src/parser.rs, mapper/thin_edge_json/tests/fixtures/invalid/reject_array_value.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_boolean_value.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_deep_hierarchy.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_empty_measurement.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_empty_record.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_huge_number.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_invalid_json.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_invalid_timestamp.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_just_time.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_measurement_named_type.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_number_for_time.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_partial_json.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_partial_timestamp.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_string_value.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_timestamp_missing_time_separator.expected_error, mapper/thin_edge_json/tests/fixtures/invalid/reject_toplevel_array.expected_error, mapper/thin_edge_json/tests/test_suite.rs
* My PR #336 broke the system tests.
* The error message was missing "Invalid JSON". Add it!
* Also add error fixtures for unit tests.
Found-by: makr11st
=> Fix system tests (broken due to PR #336)

Cargo.lock, Cargo.toml, common/batcher/Cargo.toml, common/batcher/src/batch.rs, common/batcher/src/batchable.rs, common/batcher/src/batcher.rs, common/batcher/src/config.rs, common/batcher/src/driver.rs, common/batcher/src/lib.rs
Implement the batching algorithm described here: https://github.com/albinsuresh/thin-edge.io-specs/blob/main/src/telemetry-data/message-batching/message-batching.md
https://cumulocity.atlassian.net/browse/CIT-459
<br/>
=> CIT-459: Deterministic batching algorithm

.github/workflows/integration-test-workflow.yml, docs/src/tutorials/device-monitoring.md
Collectd depends on the mosquito client library. When collectd-core is installed it does not install the mosquito client library. So, the collectd fails. 
This PR captures the document and workflow changes how to properly install the collectd-core and mosquito client library to start the collectd successfully.
<br/>
If this is a relatively large or complex change, kick off the …
=> [cit-421] collectd depends on mqtt client library

tests/PySys/apt_plugin/environment_apt_plugin.py
Make the variable a static member.
<br/>
=> [CIT-428] Fix system test by making the parameter accessible

sm/json_sm/src/lib.rs, sm/json_sm/src/messages.rs
* Methods to iterate over the module types and the updates of a software update request.
* Definition of the MQTT topic names for the misc requests and responses.
<br/>
=> [CIT-500] Add helper function to sm_json

Cargo.lock, common/tedge_utils/src/fs.rs, common/tedge_utils/src/lib.rs, tedge_config/Cargo.toml, tedge_config/src/tedge_config_repository.rs
Add async version of atomically write file and move it to tedge_utils
=> Add async version of atomically write file and move it to tedge_utils

.github/workflows/hosted-post-merge_version_update.yml
Since our version bump-up workflow was broken with the version 0.16.3 of cargo-release, install 0.16.2 explicitly
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did …
=> cargo-release version

sm/json_sm/src/lib.rs, sm/json_sm/src/messages.rs, sm/json_sm/src/software.rs
* Add an helper method to add updates to a request without grouping pre-requisite
* Make the type of a module optional
<br/>
=> [CIT-449] Improve `json_sm`

common/mqtt_client/src/lib.rs, common/mqtt_client/tests/mqtt_pub_sub_test.rs
An MQTT client can subscribe to several topics and receive all the messages on a single message stream
```
// Several topics and patterns can be added to a topic filter
let mut topic_filter = TopicFilter::new("/a/first/topic")?;
topic_filter.add("/a/second/topic")?;
topic_filter.add("/a/+/pattern")?; // one can use + pattern
topic_filter.add("/any/#")?; // one can use # pattern
// The messages for these topics will all be received on the same message stream
let mut messages = client.subscribe(topic_filter).await?;
```
<br/>
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! …
=> [CIT-468] subscribe to many topics

sm/tedge_agent/src/agent.rs
Use `tedge/res/software/update` topic for response when handling update request.
=> Use correct topic for sending executing status

common/tedge_utils/Cargo.toml
Add `io-util` and `macros` to tokio features set in `tedge_utils` crate.
=> Add missing tokio features to allow package only compilation

sm/plugin_sm/src/plugin.rs, sm/plugin_sm/src/plugin_manager.rs
Add errors only if errors list is empty from plugin.
Remove dbg statement.
=> Add errors only if non empty

sm/plugin_sm/Cargo.toml, sm/plugin_sm/src/plugin_manager.rs, sm/plugin_sm/tests/plugin_manager.rs, sm/plugins/tedge_dummy_plugin/src/main.rs
Check if plugin is executable and can perform list operation before adding it to the list of valid plugins.
=> [CIT-521] Add checks if plugins are executables

mapper/tedge_mapper/src/sm_c8y_mapper/smartrest_deserializer.rs, mapper/tedge_mapper/src/sm_c8y_mapper/smartrest_serializer.rs
Code changes handle the corner cases with package version names containing "::".
Updated tests as well.
<br/>
=> [CIT-520] version name corner cases

common/mqtt_client/tests/mqtt_pub_sub_test.rs, common/mqtt_client/tests/packet_size_tests.rs
Disabling unstable tests
<br/>
=> [CIT-515] Disabling unstable tests

mapper/tedge_mapper/src/sm_c8y_mapper/mapper.rs
Fixed the regression after #393. Now it failed to send software list when the software update response is failed. Integration test revealed it…
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why …
=> [CIT-528] Software update response failed case

sm/plugins/tedge_apt_plugin/Cargo.toml, sm/tedge_agent/Cargo.toml
tedge-agent requires apt plugin as dependency
<br/>
=> [CIT-542] tedge-agent requires apt plugin as dependency

tedge/src/cli/connect/command.rs
* Subscribe to `s/ds` topic only after device creation. Restart bridged mosquitto to force this resubscription.
* Start sm-agent and sm-c8y-mapper only after the device is created
<br/>
=> [CIT-532] Subscribe to cloud operations only after device creation

.github/workflows/commit-workflow.yml
[CIT-551] Make the job pass (temporarily) on job level as well
https://cumulocity.atlassian.net/browse/CIT-551
[CIT-551]: https://cumulocity.atlassian.net/browse/CIT-551
=> [CIT-551] Make the job pass (temporarily) on job level as well

.github/pull_request_template.md, Cargo.lock, common/batcher/Cargo.toml, common/certificate/Cargo.toml, common/clock/Cargo.toml, common/flockfile/Cargo.toml, common/json_writer/Cargo.toml, common/mqtt_client/Cargo.toml, common/tedge_users/Cargo.toml, common/tedge_utils/Cargo.toml, mapper/cumulocity/c8y_translator_lib/Cargo.toml, mapper/tedge_mapper/Cargo.toml, mapper/thin_edge_json/Cargo.toml, sm/json_sm/Cargo.toml, sm/plugin_sm/Cargo.toml, sm/plugins/tedge_apt_plugin/Cargo.toml, sm/plugins/tedge_dummy_plugin/Cargo.toml, sm/tedge_agent/Cargo.toml, tedge/Cargo.toml, tedge_config/Cargo.toml
Software Management feature added.
Release 0.3.0
=> Release 0.3.0

docs/src/howto-guides/009_touble_shooting_monitoring.md
Fix typos in the collectd document. Start proper service.
<br/>
=> [CIT-541] fix typos in collectd doc

tedge/src/cli/connect/command.rs
Resubscribe to Cumulocity cloud inbound topics only on new device creation
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
=> [CIT-532] Resubscribe to Cumulocity cloud inbound topics only on new device creation

get-thin-edge_io.sh
Add support for `aarch64` and `arm64` architectures in the install script.
Adding the download files to the release is required before merging.
=> [CIT-561] Add aarch64 and arm64 support to install script

tedge/src/cli/connect/bridge_config.rs, tedge/src/cli/connect/bridge_config_azure.rs, tedge/src/cli/connect/bridge_config_c8y.rs
The `clean_session` flag must be set to false for the bridges.
* Otherwise messages sent or received during a bridge disconnection are lost.
* See discussion https://github.com/thin-edge/thin-edge.io/pull/417/files#r703019009
<br/>
=> Fix the bridge configuration of the clean session flag

docs/src/howto-guides/002_installation.md
Update version in some docs to 0.3.0
=> Update version in some docs to 0.3.0

.github/workflows/system-test-workflow.yml
Set default Cumulocity URL for system tests
<br/>
=> Set default Cumulocity URL for system tests

Cargo.lock, common/flockfile/Cargo.toml, common/flockfile/src/unix.rs, common/mqtt_client/Cargo.toml, common/tedge_utils/Cargo.toml, common/tedge_utils/src/lib.rs, common/tedge_utils/src/logging.rs, mapper/tedge_mapper/Cargo.toml, mapper/tedge_mapper/src/az_mapper.rs, mapper/tedge_mapper/src/c8y_mapper.rs, mapper/tedge_mapper/src/collectd_mapper/mapper.rs, mapper/tedge_mapper/src/collectd_mapper/monitor.rs, mapper/tedge_mapper/src/main.rs, mapper/tedge_mapper/src/mapper.rs, mapper/tedge_mapper/src/sm_c8y_mapper/mapper.rs, sm/plugin_sm/Cargo.toml, sm/plugin_sm/src/plugin_manager.rs, sm/tedge_agent/Cargo.toml, sm/tedge_agent/src/agent.rs, sm/tedge_agent/src/main.rs
Simplification of logging
* The `mapper` and the `sm-agent` use the `tracing` crate for logging.
* The library crate can use the `log` crate: all the `error!`, `info!` emitted by such a library are catched up by `tracing_subscriber` of the `mapper` and the `sm-agent`.
* The `tedge` cli command directly writes to `stdout` and `stderr`.
* One doesn't use the `RUST_LOG` env variable to set the log level. Indeed, enabling the  `env-filter` feature of the tracing subscriber adds 600k on the stripped executable. It doesn't worth the value.
* Instead a `--debug` option has been added to the `mapper` and the `sm-agent`
* Running without any option, the mapper and the agent use the `WARN` log level.
* Running with `--debug`, the mapper and the agent use the `TRACE` log level.
* The spans of the …
=> Feature/cit 508/simplify logging

.github/workflows/commit-workflow.yml
Avoid rebuilding the thin-edge.io test code if its already built. This will quicken the process of code cov testing.
<br/>
=> [CIT-557] add skip-clean flag to fasten tarpaulin run

tests/PySys/monitoring/monitoring_smaller_interval/run.py, tests/PySys/monitoring/monitoring_with_simulated_messages/run.py
The monitoring tests were broken because using fake timestamps while the new algorithm reject any stale messages. 
* Inject the current timestamp in the test data.
<br/>
=> Update monitoring tests since the collectd timestamp are now used

tests/PySys/tedge_connect_test_positive/run.py
Fix failing tedge_connect_test_positive using wrongly using Cumulocity device id instead of device name in get_device_by_name REST call
<br/>
=> Fix failing tedge_connect_test_positive using wrong device name

tests/PySys/monitoring/monitoring_smaller_interval/run.py, tests/PySys/monitoring/monitoring_with_simulated_messages/run.py
Log the messages published by the collectd mapper in order to understand what is failing.
<br/>
=> Log the messages published by the collectd mapper

.github/workflows/system-test-workflow.yml, configuration/debian/tedge_agent/postinst, tests/PySys/tedge_agent_user_sudo_access/pysystest.xml, tests/PySys/tedge_agent_user_sudo_access/run.py
By this change, `tedge-agent` user can run `sudo /etc/tedge/sm-plugins/[plugin]`.
Restriction:
- Due to security issue, **we force a plugin name must start with [a-z].** If we use wildcard like `/etc/tedge/sm-plugins/*`, hacker can execute `/etc/tedge/sm-plugins/../../anything`.
- sudoers doesn't accept regrex. See man page: https://www.sudo.ws/man/sudoers.man.html#Wildcards
<br/>
If this is a relatively large or complex change, kick off …
=> [CIT-577] Update postinst script of tedge-agent

sm/json_sm/src/lib.rs, sm/json_sm/src/messages.rs, sm/plugin_sm/src/lib.rs, sm/plugin_sm/src/log_file.rs, sm/plugin_sm/src/logged_command.rs, sm/plugin_sm/src/plugin.rs, sm/plugin_sm/src/plugin_manager.rs, sm/plugin_sm/tests/plugin.rs, sm/tedge_agent/src/agent.rs, sm/tedge_agent/src/error.rs, sm/tedge_agent/src/main.rs, sm/tedge_agent/src/operation_logs.rs
* Every software operation is logged in a file that reports the status/stdout/stderr all the plugin actions triggered by the agent
* If one of this action fails the error is reported to the cloud admin user with a link to the file
* The files are stored into `/var/log/tedge/agent`
* Only the latest versions of these logs are kept (the 5 latest software updates, the latest software list) 
<br/>
If this is a relatively large or complex …
=> [CIT-564] Improve error reporting on software update

tests/PySys/apt_plugin/apt_sequence_install_with_version/run.py, tests/PySys/apt_plugin/apt_sequence_remove_with_version/run.py, tests/PySys/apt_plugin/apt_sequence_remove_with_version_fail/run.py
There are some apt plugin tests breaking under the current release (0.3.0). This PR fixes these minor errors. 
__Note__: only tests in the "apt_plugin" were checked and changed. 
=> fixing broken tests pre-testing feature [CIT-591]

common/tedge_utils/src/fs.rs
When removing files on failed write `atomically_write_file_async` was not calling `.await` which caused the files to not being removed.
=> [CIT-597] Add await on file remove in async_write_atomic

Cargo.lock, Cargo.toml, sm/download/Cargo.toml, sm/download/examples/simple_curl.rs, sm/download/src/download.rs, sm/download/src/error.rs, sm/download/src/lib.rs, sm/json_sm/src/lib.rs, sm/json_sm/src/messages.rs
Split from #444 
Add download crate serving solely purpose of downloading file from http.
Add structs `DownloadInfo` and `Auth` to support the information passing between mapper and agent.
=> [CIT-571] Add download crate and supporting struct in json_sm

sm/plugins/tedge_docker_plugin/tedge_docker_plugin.sh
=> [CIT-567] Docker plugin

Cargo.lock, sm/download/Cargo.toml
Fixes cross builds by using rustls.
=> [CIT-571] FIX - Change reqwest features to disable nativetls with openssl and use rustls

tedge/src/cli/config/config_key.rs, tedge/src/cli/connect/command.rs, tedge/src/cli/connect/common_mosquitto_config.rs, tedge_config/src/settings.rs, tedge_config/src/tedge_config.rs, tedge_config/src/tedge_config_defaults.rs, tedge_config/src/tedge_config_dto.rs, tedge_config/tests/test_tedge_config.rs
This change will allow users to choose whether they want to limit external connections to Mosquitto.
https://github.com/thin-edge/thin-edge.io/issues/449
<br/>
=> add option to allow connection from external clients

docs/src/references/plugin-api.md
- [] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
<br/>
If this is a relatively large or complex …
=> [CIT-598] Update Package Plugin API doc

.github/workflows/commit-workflow-all.yml, ci/ci_run_all_plugin_tests.sh, ci/ci_run_all_sm_tests.sh
Add worflow that runs smoke and system test as part of a commit (configureable as non-mandatory)
<br/>
=> EXPERIMENTAL DO NOT MERGE: Run all tests on commit

configuration/debian/tedge/postinst, configuration/debian/tedge_agent/postinst
Very short fix to make tedge-agent can add/remove log file from /var/log/tedge/agent directory.
<br/>
=> [CIT-607] Add log directory creation in tegde and tedge-agent postinst

tests/PySys/docker_plugin/docker_plugin_finalize/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_finalize/run.py, tests/PySys/docker_plugin/docker_plugin_install/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_install/run.py, tests/PySys/docker_plugin/docker_plugin_install_with_version/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_install_with_version/run.py, tests/PySys/docker_plugin/docker_plugin_remove/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_remove/run.py, tests/PySys/docker_plugin/docker_plugin_remove_with_version/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_remove_with_version/run.py, tests/PySys/docker_plugin/docker_plugin_update/pysystest.xml, tests/PySys/docker_plugin/docker_plugin_update/run.py, tests/PySys/docker_plugin/environment_docker_plugin.py, tests/PySys/pysysproject.xml
Pysys tests for docker plugin
<br/>
=> [CIT-567] Docker plugin tests

configuration/debian/tedge_agent/postinst
=> Update postinst of tedge-agent

.github/workflows/integration-test-workflow.yml
The purge step didn't work since we lack tedge-agent and the order wasn't correct in terms of dependencies.
<br/>
=> Fix purge step of integration test workflow

.github/workflows/integration-test-workflow.yml
Similar to #469, forgot to change one line, that is actually critical.
<br/>
=> Update integration test workflow

configuration/debian/tedge_agent/postrm
This should fix sudoer's issue.
<br/>
=> Correct sudoer file to remove

configuration/debian/tedge_agent/postrm
=> Update postrm of tedge-agent

sm/plugin_sm/src/plugin.rs, sm/plugin_sm/src/plugin_manager.rs, sm/plugin_sm/tests/plugin_manager.rs, sm/tedge_agent/src/agent.rs
Run `list` command with `sudo` while loading the plugin on tedge-agent startup.
<br/>
=> [CIT-616] Run plugin validation command with sudo

.github/workflows/integration-test-workflow.yml, configuration/debian/tedge/postrm
Actually, our system tests require the `mosquitto-clients` package, however, we didn't include this package in our installation step.
Also, `mosquitto-clients` has a dependency on `libmosquitto1`, so we should purge here, not in system test workflow.
<br/>
=> Fix system test workflow

mapper/cumulocity/c8y_smartrest/src/error.rs, mapper/cumulocity/c8y_smartrest/src/smartrest_deserializer.rs, mapper/tedge_mapper/src/sm_c8y_mapper/mapper.rs
=> [CIT-669] Publish operation failed only on valid operations

docs/src/howto-guides/004_connect.md
Update the Cumulocity document link in how to connect document.
- [ x] Bugfix (non-breaking change which fixes an issue)
<br/>
=> Fix the cumulocity link

configuration/debian/tedge_agent/prerm, configuration/debian/tedge_mapper/prerm
Add missing debhelper to prerm scripts.
=> [CIT-663] Add missing debhelper

docs/src/tutorials/connect-c8y.md
Update connect docs with current output of tedge connect.
Fixes #550 
=> [CIT-650] Update connect docs with current output of tedge connect

common/mqtt_client/tests/mqtt_pub_sub_test.rs
This is a temporary workaround. The proper fix is under way.
Signed-off-by: Wenzek <diw@softwareag.com>
Add arbitrary time wait after publish and subscribe steps to increase the chance to be ready for the next steps.
The current fix is under implementation: see #575.
<br/>
=> Wait for pub and sub ack before test resume

sm/tedge_agent/Cargo.toml
=> Add tedge_agent package description

crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml
Fix missed paths for cargo deb assets.
=> Fix paths for deb assets

tests/PySys/misc_features/mqtt_port_change_connection_works/pysystest.xml, tests/PySys/tedge/call_tedge_-V/run.py
update system test using path to tedge cargo to the new one.
=> Fix path for tedge cargo in system test

plugins/tedge_apama_plugin/Cargo.toml
Debian package for apama plugin
<br/>
=> [CIT-698] Debian package for apama plugin

.github/workflows/build-workflow.yml, .github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml, get-thin-edge_io.sh
Add Apama plugin protoype to build
https://cumulocity.atlassian.net/browse/CIT-690
https://github.com/thin-edge/thin-edge.io/issues/617
=> [CIT-617] Add Apama plugin protoype to build

Cargo.lock, crates/core/tedge/Cargo.toml, crates/core/tedge/src/cli/certificate/error.rs
Updated dependencies on `rustls` crates and fixed error handlers due to new errors structures in latest `hyper`.
Closes #624 
=> #624 Update dependencies and error handlers

configuration/debian/tedge_mapper/postinst, docs/src/tutorials/supported_operations.md
Update the supported operations docs to reflect correct permissions on operations.
Update `postinst` to use lower permissions than the parent directory.
=> #596 Update docs for supported operations with up to date permissions

crates/core/tedge/src/cli/connect/command.rs
Workaround to fix #680.
Start the mapper only after the connection has been checked
<br/>
=> [680] Start the mapper only after the connection has been checked

configuration/init/systemd/tedge-agent.service
Ensuring that on restart the mapper is available when `tedge_agent` starts. 
<br/>
=> restart tedge mapper before tedge agent (#683)

plugins/tedge_apama_plugin/src/main.rs
Wait for apama correlator to be ready before finishing project installation.
<br/>
=> Wait for apama correlator ready after project install

tests/PySys/plugin_apt/environment_apt_plugin.py, tests/PySys/plugin_docker/environment_docker_plugin.py, tests/PySys/software_management_end_to_end/dummy_plugin_configuration/Info.md, tests/PySys/software_management_end_to_end/sm_fake_install_remove/run.py, tests/PySys/software_management_end_to_end/sm_fake_install_remove_multiple/run.py, tests/PySys/software_management_end_to_end/sm_mixed_install_remove_multiple/run.py, tests/requirements.txt
A bunch of cherry-picks to fix various issues in the official CI chain.
- detection of rolldice debs
- Add junit report handlers to system-test python environment
Also pick un-merged docu and typo-fixes.
<br/>
=> Bug/various fixes for tests and CI

docs/src/tutorials/software-management.md
=> Fix the dead link in doc

tests/PySys/environments/environment_c8y.py, tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/pysystest.xml, tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/run.py
Pysys system test for alarms support
<br/>
=> Closes #667 Pysys system test for alarms support

Cargo.lock, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/c8y_converter.rs, crates/core/tedge_mapper/src/error.rs, crates/core/tedge_mapper/src/operations.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/error.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/tests.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/topic.rs, docs/src/tutorials/supported_operations.md
=> Operations execution from operations files.

ci/ci_smoke_test_c8y.sh
Wait for some time before tedge connect before the certificate appears on the cumulocity.
<br/>
=> wait for certificate to appear on c8y

.github/workflows/integration-test-workflow.yml
Forces cache update to rust 1.58 as per all other workflows.
=> Force cache in integration tests

configuration/debian/tedge_agent/postinst, configuration/debian/tedge_mapper/postinst, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/src/main.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs, tests/PySys/tedge_agent/agent_init_session/pysystest.xml, tests/PySys/tedge_agent/agent_init_session/run.py, tests/PySys/tedge_mapper_c8y/sm_tedge_mapper_init_session/pysystest.xml, tests/PySys/tedge_mapper_c8y/sm_tedge_mapper_init_session/run.py
Add `--init` feature to the tedge_agent and tedge_mapper sm-c8y
This feature will help to initialize the agent and the mapper to subscribe to their respective topics.
It will help to get the messages that are published on these topics when the mapper/agent starts.
This will help to start the agent and the mapper in any order during the tedge connect.
<br/>
If this is a relatively …
=> [699] init/clear agent and mapper sessions

.github/workflows/update-tedge-ref-docs.yml
To update `tedge cli` reference docs the [script](`https://github.com/thin-edge/thin-edge.io/tree/main/docs/gen-ref-docs.sh` ) has to be run manually and create the PR manually.
This PR automates this process by adding a GH action workflow to run this script on the `1st of every month`. 
Also, this workflow can be triggered manually. 
It creates the PR automatically and sends the PR review request.
- [ x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
<br/>
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> [800] CI workflow for updating tedge reference docs

Cargo.lock, crates/core/c8y_smartrest/Cargo.toml, crates/core/c8y_smartrest/src/event.rs, crates/core/c8y_smartrest/src/lib.rs, crates/core/tedge_mapper/src/c8y_converter.rs, crates/core/tedge_mapper/src/error.rs, crates/core/tedge_mapper/src/tests.rs, crates/core/thin_edge_json/src/event.rs, crates/core/thin_edge_json/src/lib.rs
Thin Edge JSON events support for Cumulocity mapper
<br/>
=> [#809] Thin Edge JSON events support for Cumulocity mapper

crates/core/agent_interface/src/lib.rs, crates/core/agent_interface/src/messages.rs, crates/core/c8y_smartrest/src/smartrest_deserializer.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/sm_c8y_mapper/mapper.rs
This is part of #825 - my patches to fix the clippy warnings in the `agent_interface` crate.
=> Clippy fixes for: agent_interface

crates/common/download/src/download.rs
This patch fixes an issue if compiled on 32 bit platforms, where usize is 4 bytes which would truncate the result from
`reqwest::Response::content_length()` and thus result in possibly weird errors.
The fix was to cast to u64 instead of usize.
Please merge this only after squash and rebase requirements have been removed (see [the discussion](https://github.com/thin-edge/thin-edge.io/discussions/795)).
=> Fix: Do not truncate integer type by casting

crates/common/mqtt_channel/src/topics.rs
This is part of #825 - my patches to fix the clippy warnings in the `mqtt_channel` crate.
=> Clippy fixes for: mqtt_channel

crates/tests/mqtt_tests/src/test_mqtt_client.rs
This is part of #825 - my patches to fix the clippy warnings in the `mqtt_tests` crate.
=> Clippy fixes for: mqtt_tests

plugins/tedge_apama_plugin/src/main.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_apama_plugin` crate.
=> Clippy fixes for: tedge_apama_plugin

crates/common/mqtt_channel/src/connection.rs, crates/common/mqtt_channel/src/tests.rs
The motivation is given by components as the [c8y_LogfileRequest operation](https://github.com/thin-edge/thin-edge.io/pull/844) that need to be sure that the messages published over MQTT have been actually published before the connection is dropped.
See [Add a close method to Mqtt_channel::Connection](https://github.com/thin-edge/thin-edge.io/issues/846)
If this is a relatively large or complex change, kick off the discussion by explaining …
=> Add a close method to Mqtt_channel::Connection

crates/core/thin_edge_json/src/alarm.rs, crates/core/thin_edge_json/src/builder.rs, crates/core/thin_edge_json/src/parser.rs, crates/core/thin_edge_json/tests/test_suite.rs
This is part of #825 - my patches to fix the clippy warnings in the `thin_edge_json` crate.
=> Clippy fixes for: thin_edge_json

crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/error.rs, crates/core/tedge_agent/src/operation_logs.rs, crates/core/tedge_agent/src/restart_operation_handler.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_agent` crate.
=> Clippy fixes for: tedge_agent

Cargo.lock, plugins/log_request_plugin/Cargo.toml, plugins/log_request_plugin/src/main.rs
=> Remove no longer used function from log plugin

crates/common/tedge_config/src/tedge_config.rs, crates/common/tedge_config/src/tedge_config_repository.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_config` crate.
=> Clippy fixes for: tedge_config

.github/workflows/update-tedge-ref-docs.yml
* Change the branch where the update-tedge-ref-doc workflow pushes
* Make it automatically run after hosted-post-merge_version_update workflow runs
<br/>
=> Update update-tedge-ref-doc workflow

Cargo.lock, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/logging.rs, crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/http_proxy.rs
Use latest `tracing_subscriber` which has moved to crate `time`.
=> Update tracing_subsciber to 0.3 which uses 'time' instead of 'chrono'

docs/src/SUMMARY.md, docs/src/tutorials/send-events.md
Document Thin Edge JSON events data model
<br/>
=> [#809] Document Thin Edge JSON events data model

crates/core/tedge_mapper/src/c8y/error.rs, crates/core/tedge_mapper/src/collectd/collectd.rs, crates/core/tedge_mapper/src/collectd/error.rs, crates/core/tedge_mapper/src/core/mapper.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge_mapper` crate.
=> Clippy fixes for: tedge_mapper

crates/core/tedge_mapper/src/c8y/tests.rs
This test constantly blocks CI because it fails unreproducably. This patch removes it, so we can get rid of these sporadic failures.
Closes #853 
IMHO we should remove all tests that access network.
=> Remove get_jwt_token_full_run() test

crates/common/mqtt_channel/src/config.rs
Implicitly clean the MQTT session on connect when no session name is provided
<br/>
=> Clean the session on connect when no session name is provided

configuration/debian/tedge_agent/postinst, configuration/init/systemd/tedge-agent.service, crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, plugins/log_request_plugin/src/main.rs
Closes #911 
Removing sm-c8y-mapper from init files.
#911 
=> #911 systemd init and connection reset fix 

crates/core/tedge/src/cli/connect/c8y_direct_connection.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge/src/cli/connect/common_mosquitto_config.rs, crates/core/tedge/src/error.rs, crates/core/tedge/src/system_services/managers/config.rs
This is part of #825 - my patches to fix the clippy warnings in the `tedge` crate.
=> Clippy fixes for: tedge

crates/common/tedge_config/src/tedge_config.rs, crates/common/tedge_config/src/tedge_config_location.rs, crates/common/tedge_utils/src/paths.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/main.rs, crates/core/tedge/tests/main.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/main.rs
=> #814 --config-dir option for tedge commands 

crates/core/tedge_mapper/src/c8y/tests.rs
This PR address the failing c8y_mapper_syncs_pending_alarms_on_startup test. The fix include
- Wait for a while to send all the messages properly before stopping the mapper
- Clean the session before restarting a new broker by keeping the keep-alive period shorter
- [ x] Bugfix (non-breaking change which fixes an issue)
<br/>
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> [870] fix tedge alarm test

crates/core/plugin_sm/src/plugin.rs, crates/core/plugin_sm/src/plugin_manager.rs
This is part of #825 - my patches to fix the clippy warnings in the `plugin_sm` crate.
=> Clippy fixes for: plugin_sm

docs/src/tutorials/raise-alarm.md
=> Fix an invalid command example in alarm tutorial

Cargo.lock, crates/common/certificate/Cargo.toml
`x509_parser 0.13` uses `time > 0.3`.
#625
=> Bump version of 'x509_parser' which uses 'time' instead of 'chrono'

Cargo.lock, plugins/tedge_apama_plugin/Cargo.toml
It looks like this would be the last in a series to finally close #625.
This disables unused use of `time 0.1` in `tedge_apama_plugin`.
#625 
=> Remove 'chrono' from 'zip' in apama plugin

crates/common/download/src/download.rs
This is part of #825 - my patches to fix the clippy warnings in the `download` crate.
=> Clippy fixes for: download

configuration/debian/tedge_mapper/postinst
c8y_LogfileRequest is now a plugin so this makes no sense here, and breaks tests due to an installation order issue. 
- Closes #931 
=> removed c8y_LogfileRequest from tedge-mapper (#931)

get-thin-edge_io.sh
* Closes #891 
* fixing `get-thin-edge.io.sh` script to install tedge agent before installing plugins. 
* fixes the issue that tedge agent was not installed for lower versions 
* Closes #891 
=> installing tedge first and then plugins

docs/src/SUMMARY.md, docs/src/howto-guides/README.md
Update the Summary and Readme with new how to docs links.
<br/>
=> update summary and README

crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs, docs/src/howto-guides/004_connect.md, docs/src/tutorials/connect-azure.md, docs/src/tutorials/connect-c8y.md
We changed the output of `tedge connect c8y` and `tedge connect az`, however, the sample output in our doc were still using the old output. This PR updates such docs.
Plus, to change all `c8y` or `az` output to `Cumulocity` or `Azure` by `tedge disconnect`. This keeps consistency with the output of `tedge connect`. 
Close #905.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> Update the output of tedge connect in tutorial and how-to guide

tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py, tests/PySys/software_management_end_to_end/sm_mapper_fail_and_reconnect/pysystest.xml, tests/PySys/software_management_end_to_end/sm_mapper_fail_and_reconnect/run.py, tests/PySys/tedge_mapper_c8y/sm_tedge_mapper_init_session/run.py
=> Remove remaining sm-mapper mentions

.github/workflows/integration-test-workflow.yml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_apt_plugin/tests/main.rs
Closes #912, #930  
- added new "requires-sudo" feature gate
#912 
=> #912 feature gate for apt install test

crates/core/tedge_agent/src/state.rs
Fix the tedge agent `agent_state_repository_exists_store` by removing the redundant file write.
<br/>
=> [869] remove redundant file write

crates/common/mqtt_channel/src/session.rs
Exit init and clear session when mosquito is not running.
<br/>
=> [974] fix init and clear session

crates/common/tedge_config/src/models/ipaddress.rs, crates/core/c8y_smartrest/src/operations.rs, crates/core/plugin_sm/tests/plugin.rs
Removes some warnings (in scope of #945 which I plan to update after this is merged).
=> (misc) Remove warnings

crates/common/flockfile/src/unix.rs, crates/common/tedge_config/src/models/file_path.rs, crates/common/tedge_config/src/settings.rs, crates/common/tedge_config/src/tedge_config.rs, crates/common/tedge_config/src/tedge_config_defaults.rs, crates/common/tedge_config/src/tedge_config_dto.rs, crates/common/tedge_config/tests/test_tedge_config.rs, crates/core/tedge/src/cli/config/config_key.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/restart_operation_handler.rs, crates/core/tedge_mapper/src/main.rs
* Closes #858
* logs.path implementation
* run.path implementation
The following are addressed in other PRs
* #858 
* linked: https://github.com/initard/thin-edge.io/pull/2
=> #858 configurable run/log path 

tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/pysystest.xml, tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/run.py
Clear all the raised alarms in the test cleanup
<br/>
=> Closes #966 Cleanup logic for tedge_mapper_c8y_alarms pysys test

crates/common/flockfile/src/unix.rs, crates/common/tedge_config/src/tedge_config.rs, crates/core/tedge_agent/src/restart_operation_handler.rs
- Closes #984
- fixed /run path bug introduced by #939
- updated /run default configuration to use /run
<br/>
=> #984 Error: Couldn't acquire file lock.

Cargo.lock, crates/common/download/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml
Upgrade dependencies to elimiate vulnerable regex crate v1.5.4
<br/>
=> Upgrade dependencies to elimiate vulnerable regex crate v1.5.4

crates/core/c8y_smartrest/src/error.rs, crates/core/c8y_smartrest/src/operations.rs, crates/core/plugin_sm/src/plugin_manager.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/state.rs
- Closes #882
Error handling for tedge agent and mapper, when there is no directory on startup (.agent, operations, sm-plugins)
#882
=> #882 agent start up failures

.github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml
`purge` step fails because of lacking `tedge_logfile_request_plugin`.
https://github.com/thin-edge/thin-edge.io/runs/5511562408?check_suite_focus=true
**Stop using `continue-on-error`, which took us so long time to find this issue, actually purging didn't happen!**
At least, `dpkg` returns `0` if there was no package. Also confirmed on Ubuntu 20.04 on amd64.
```
pi@raspberrypi:~ $ sudo dpkg -P tedge_agent tedge_logfile_request_plugin tedge_mapper tedge_apt_plugin tedge_apama_plugin tedge mosquitto libmosquitto1 collectd-core
dpkg: warning: ignoring request to remove tedge_agent which isn't installed
dpkg: warning: ignoring request to remove tedge_logfile_request_plugin which isn't installed
dpkg: warning: ignoring request to remove tedge_mapper which isn't installed
dpkg: warning: …
```
=> Add tedge_logfile_request_plugin to purge step

Cargo.lock, crates/common/batcher/Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/clock/Cargo.toml, crates/common/download/Cargo.toml, crates/common/flockfile/Cargo.toml, crates/common/json_writer/Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_users/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/agent_interface/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/c8y_smartrest/Cargo.toml, crates/core/c8y_translator/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/thin_edge_json/Cargo.toml, crates/tests/mqtt_tests/Cargo.toml, crates/tests/sawtooth_publisher/Cargo.toml, plugins/log_request_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
=> (cargo release) bump version 0.6

plugins/tedge_apama_plugin/src/main.rs
Apama plugin to return exit code 1 on update-list invocation instead of exit code 2.
<br/>
=> Fix apama plugin update-list command exit code

Cargo.lock, plugins/tedge_apama_plugin/Cargo.toml
Installation step of apama plugin fails due to the error **ERROR: unsupported Zip archive**.
This is caused by the commit https://github.com/thin-edge/thin-edge.io/commit/b21a5861c256bd5d2c858cbbcf2cbf32e3c56add.
We need to enable "deflate" feature, otherwise, the apama plugin cannot unzip.
The problem:
The commit https://github.com/thin-edge/thin-edge.io/commit/b21a5861c256bd5d2c858cbbcf2cbf32e3c56add is made to remove `chrono`'s dependency caused by the `time` crate. However, this PR will re-invoke this.
As I expected, `cargo audit` fails again...
<br/>
=> Enable "deflate" feature of zip crate

get-thin-edge_io.sh
Once the release note is ready, I will merge this PR.
<br/>
=> Update get-thin-edge_io.sh to 0.6.0

Cargo.lock, configuration/debian/tedge/postinst, configuration/debian/tedge_agent/postinst, configuration/debian/tedge_mapper/postinst, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/file.rs, crates/common/tedge_utils/src/lib.rs, crates/core/tedge/src/cli/mod.rs, crates/core/tedge/src/main.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/src/az/converter.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/core/tedge_mapper/src/collectd/monitor.rs, crates/core/tedge_mapper/src/core/component.rs, crates/core/tedge_mapper/src/main.rs
This PR introduces a feature (tedge/tedge-mapper/tedge-agent --init) to create all the directories and files that are required 
by these thin-edge components.
The creation of files moved from the installation script to the respective component.
<br/>
=> [#761] tedge init

crates/core/agent_interface/src/lib.rs, crates/core/agent_interface/src/messages.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/collectd/monitor.rs, crates/core/tedge_mapper/src/core/mapper.rs, docs/src/howto-guides/020_monitor_tedge_health
MQTT health endpoint for:
<br/>
=> Closes #769 MQTT health endpoint for c8y-mapper

crates/core/tedge_mapper/Cargo.toml
Closes #1032 
I just saw #1032 and thought I can fix this real quick. :laughing:
=> Fix missing features

Cargo.lock, crates/core/agent_interface/src/lib.rs, crates/core/agent_interface/src/messages.rs, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/collectd/monitor.rs, crates/core/tedge_mapper/src/core/mapper.rs, docs/src/howto-guides/020_monitor_tedge_health
* All tedge daemons to respond to health checks sent to common health check endpoint `tedge/health-check`
* Include process pid in health status response
<br/>
=> Common health check MQTT endpoint for tedge daemons

.github/workflows/integration-test-workflow.yml
- integration test workflow now requires amd64 to be installed first
- #1000
=> #1000 enabling integration tests for apt plugin

.github/workflows/integration-test-workflow.yml
Correct branch name for #1000 
#1000
=> Use main branch to download packages

ci/ci_run_all_plugin_tests.sh, ci/ci_smoke_test_c8y.sh, tests/PySys/tedge/call_tedge_-h_-V/run.py, tests/PySys/tedge_connect/tedge_connect_test_sm_services/run.py, tests/requirements.txt
Set of smaller fixes from Michaels CI branch.
- Enable Apama tests
- Switch to Pysys 2.1
- Test assertion fixes
<br/>
=> Test improvements for tedge 0.6 

plugins/tedge_apama_plugin/src/main.rs, plugins/tedge_apt_plugin/src/main.rs
Print an informative error message and the usage when command-line parsing fails for apt and apama plugins.
<br/>
=> Improve parse error reporting of apt and apama plugins

crates/core/tedge/src/cli/connect/bridge_config.rs, crates/core/tedge/src/cli/connect/bridge_config_azure.rs, crates/core/tedge/src/cli/connect/bridge_config_c8y.rs, docs/src/SUMMARY.md, docs/src/howto-guides/020_monitor_tedge_health.md, docs/src/howto-guides/README.md
Report mosquitto cloud bridge health status via MQTT. The reported status is just 0 or 1 and not any fancy JSON as reported by other tedge components as mosquitto doesn't allow customizations to that status message itself.
<br/>
=> Closes #862 Report mosquitto cloud bridge health status via MQTT

.github/workflows/system-test-offsite.yml
Repeat temporary workaround from #1035 on offsite workflow
#1035 
comment
=> Install individual packages on offsite workflow (#1035)

docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md
The document deployment fails due to broken link. See the error of https://github.com/thin-edge/thin-edge.io/runs/5871673988?check_suite_focus=true.
<br/>
=> Fix broken link in how-to-guide

Cargo.lock, Cargo.toml, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/smartrest.rs
The PR will merge the progress into **feature/1030/configuration-management** branch.
In the end, we will create a PR to merge the feature branch into main.
- This is the initial skeleton to implement the `c8y_configuration_plugin` daemon.  
- The skeleton reads the plugin config file, located `/etc/tedge/c8y/c8y_configuration_plugin.toml`, and reports the supported config types to c8y on the daemon start-up.
- Manual creation of relevant supported operation files is required.
- Issue tracked by #1030, Specs is by #1028
<br/>
=> Initial skeleton of c8y_configuration_plugin

crates/core/tedge/src/main.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/main.rs, crates/core/tedge_agent/src/state.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/collectd/mapper.rs, crates/core/tedge_mapper/src/core/component.rs, crates/core/tedge_mapper/src/main.rs
This PR captures the code changes to use the `config-dir` option for `init` to create all the required directories and files in `Path/to/base/dir`
`tedge --init --config-dir Path/to/base/dir`
`tedge-mapper --init --config-dir Path/to/base/dir` c8y/az/collectd 
`tedge-agent --init --config-dir Path/to/base/dir`
Also, when the `mappers and agent` are started `create/read/write` config files in/from `Path/to/base/dir`
`tedge-mapper  --config-dir Path/to/base/dir` c8y/az/collectd
`tedge-agent --config-dir Path/to/base/dir`
<br/>
=> Closes #1040 use config-dir feature for initalize and run

Cargo.lock, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_smartrest/src/smartrest_deserializer.rs, crates/core/c8y_smartrest/src/smartrest_serializer.rs, crates/core/tedge_mapper/src/c8y/tests.rs, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/smartrest.rs
Support c8y_UploadConfigFile operation
<br/>
=> Issue #1030 Support c8y_UploadConfigFile operation

crates/core/tedge_watchdog/Cargo.toml
Add tedge_watchdog.service file to the debian package. 
<br/>
=> Add watchdog systemd service file

.github/workflows/doc-check.yml
When a developer changes the documentation, sometimes "Build and Deploy GitHub pages" workflow fails due to a small failure (e.g. broken link) introduced by a commit. However, such commit should be prevented to get merged while PR is open.
This change adds a new workflow that will be **triggered only when there is a change in `/docs`**. `mdbook build` runs to check if it passes (no deployment to GitHub pages!).
<br/>
- [] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
=> Add mdbook build check workflow

Cargo.lock, plugins/log_request_plugin/src/smartrest.rs
_Previously it was sending any logs inside /var/log/tedge/agent._
This fix allows the log_request_plugin to filter for log type. 
For example for the payload:
```text
522,user,software,2022-04-20T22:21:47+0100,2022-04-21T22:21:47+0100,,1000
```
only logs of type "software" will be upload to the c8y.
This fix is needed for #1027 as it will enable the agent to filter log type. Example payloads coming from c8y could be:
522,user,**software**,2022-04-20T22:21:47+0100,2022-04-21T22:21:47+0100,,1000
522,user,**c8y_CustomOperation**,2022-04-20T22:21:47+0100,2022-04-21T22:21:47+0100,,1000
522,user,**c8y_AnotherCustomOperation**,2022-04-20T22:21:47+0100,2022-04-21T22:21:47+0100,,1000
No issue
Need to add test
=> added filtering for log type

crates/core/tedge/Cargo.toml
The `tedge` Debian package depends on `mosquitto`. Due to this when `mosquitto` is purged, the `tedge` was also getting uninstalled.
This `dependency` has been changed to `recommendation`, So that purging mosquito will not uninstall `tedge` as below.
[package.metadata.deb]
recommends = "mosquitto"
<br/>
=> Purging mosquitto removed tedge

docs/src/SUMMARY.md, docs/src/references/c8y-configuration-management.md
Specification of a thin-edge operation plugin for Device Configuration Management with Cumulocity.
* [Along the lines defined by Tobias Sommer @TyrManuZ](https://github.com/thin-edge/thin-edge.io/issues/866#issuecomment-1076533875)
Points that still needs to be clarified / defined:
* Issue: [configuration management](https://github.com/thin-edge/thin-edge.io/issues/866)
* Requirements: [New Feature: Configuration Management](https://github.com/thin-edge/thin-edge.io/discussions/1015)
=> Specify Device Configuration Management using Cumulocity

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml
By #1101, we add a new daemon `c8y_configuration_plugin`. We need to deliver it as a debian package.
* System tests have not yet created for c8y_configuration_plugin. However, installing & purging it is good.
* The plugin does not have any dependencies on other package level dependencies.
After #1101 gets merged, this PR needs to be merged.
<br/>
=> Add c8y_configuration_plugin to workflows

.github/workflows/ci_pipeline.yml
Fix the failure of https://github.com/thin-edge/thin-edge.io/actions/runs/2232350704.
<br/>
=> Fix the wrong package type for rpi runners

.github/workflows/integration-test-workflow.yml, tests/PySys/plugin_apama/environment_apama_plugin.py, tests/PySys/smoketests/smoketest_smartrest_400_samples_1Xms/run.py, tests/PySys/smoketests/smoketest_smartrest_400_samples_20ms/run.py, tests/PySys/software_management_end_to_end/environment_sm_management.py, tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py, tests/PySys/tedge_mapper_c8y/mapper_awaits_before_reconnect/run.py
Set of smaller changes from Michaels CI branch
- Fix Apama installation issues
- Fix SmartREST Smoketest on hosted Pis
- Raise exception when the software list is emtpy
=> Fix multiple small test issues

configuration/contrib/tedge_upgrade/upgrade_tedge_0.6.sh
update tedge update script with missing lockfile and directory owner and group.
The following were missed to update 
- sudo chown tedge:tedge /etc/tedge/operations/az
- sudo chown tedge:tedge /run/lock/tedge-mapper-az.lock
- sudo chown tedge:tedge /run/lock/tedge-mapper-collectd.lock
<br/>
=> update tedge update script

crates/core/c8y_translator/fuzz/Cargo.lock, crates/core/tedge_mapper/src/c8y/tests.rs
=> fix broken big measurement tests

configuration/debian/tedge/preinst
=> Update from 0.5.1 to 0.6.2 failed

crates/common/tedge_config/src/models/templates_set.rs, crates/common/tedge_config/src/tedge_config.rs, crates/common/tedge_config/src/tedge_config_defaults.rs, crates/common/tedge_config/tests/test_tedge_config.rs
=> [1051] Add defaults to TemplatesSet

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml, configuration/contrib/operations/c8y/c8y_LogfileRequest, get-thin-edge_io.sh
renaming tedge_logfile_request_plugin to c8y_log_plugin
<br/>
=> update rename of c8y_log_plugin #1077

docs/src/SUMMARY.md, docs/src/howto-guides/024_smartrest_templates.md, docs/src/howto-guides/README.md
Documentation for Custom Smartrest templates configuration.
=> [1051] Add documentation for configuration of smartrest templates

.github/workflows/ci_pipeline.yml, .github/workflows/commit-workflow-optional.yml, .github/workflows/commit-workflow.yml
- Run commit workflows on PRs from all branches
- Run ci pipeline auch für release branches
<br/>
=> Prepare repo for release branch

.github/workflows/ci_pipeline.yml, .github/workflows/commit-workflow-optional.yml, .github/workflows/commit-workflow.yml
- Run commit workflows on PRs from all branches
- Run ci pipeline auch für release branches
Identical to [#1157](https://github.com/thin-edge/thin-edge.io/pull/1157) but cherry-picked onto the release branch.
<br/>
=> Prepare repo for release branch - onto release branch

Cargo.lock, configuration/debian/c8y_log_plugin/postinst, configuration/init/systemd/c8y-log-plugin.service, docs/src/howto-guides/023_c8y_log_plugin.md, plugins/c8y_log_plugin/Cargo.toml, plugins/c8y_log_plugin/src/logfile_request.rs
- added logic to sort files by file metadata
- added tests for c8y log plugin
- updated documentaion
- updated service file to enable service if connect to c8y
<br/>
=> log plugin bugfix, tests, doc and service update

Cargo.lock, configuration/debian/c8y_log_plugin/postinst, configuration/init/systemd/c8y-log-plugin.service, docs/src/howto-guides/023_c8y_log_plugin.md, plugins/c8y_log_plugin/Cargo.toml, plugins/c8y_log_plugin/src/error.rs, plugins/c8y_log_plugin/src/logfile_request.rs, plugins/c8y_log_plugin/src/main.rs
Picking commits from release branch that should go to main branch
=> Porting c8y log plugin hotfixes to main

docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md
From `tedge_watchdog.service` to `tedge-watchdog.service`.
<br/>
=> Correct the service file name

.github/workflows/ci_pipeline.yml
Add `tedge_watchdog` build and installation steps on `ci-pipeline` workflow. Later, this change should be ported to the `main` branch.
<br/>
=> Add tedge_watchdog to ci_pipeline workflow

Cargo.lock, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/collectd/monitor.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/core/tedge_watchdog/Cargo.toml, crates/core/tedge_watchdog/src/systemd_watchdog.rs, docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md
Avoid any timing misalignment between `tedge-watchdog` and any service that it monitors, by increasing the health-check frequency.
<br/>
=> Fix tedge watchdog timeout misalignment with monitored services

Cargo.lock, crates/core/c8y_smartrest/Cargo.toml, crates/core/c8y_smartrest/src/operations.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/dynamic_discovery.rs, crates/core/tedge_mapper/src/c8y/error.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/c8y/mod.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/tedge_mapper/src/core/converter.rs, crates/core/tedge_mapper/src/core/mapper.rs, docs/src/tutorials/supported_operations.md
This new feature provides an option to discover operations dynamically.
1. When the `operation file` is copied into the `config-dir/operations/c8y` the operation will be added to the supported operation list. And the newer list will be sent to the c8y cloud.
2. When the `operation file` is removed from the  `config-dir/operations/c8y` the operation will be removed from the supported operation list and the newer list will be sent to the c8y cloud.
Todo
Add the documentation.
Note: As of now the operation trigger is manual. One has to add and remove the operation file manually.
<br/>
- [] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
=> Dynamic discovery of new operations

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/integration-test-workflow.yml, .github/workflows/system-test-offsite.yml
Building/installing/purging `tedge_watchdog` was forgotten since we released `tedge_watchdog`. This PR adds `tedge_watchdog` building, installing, purging steps to our workflows.
<br/>
=> Port adding tedge_watchdog pipeline to main branch

docs/src/references/c8y-log-management.md
Specification for the `c8y_log_plugin` to support log file management from Cumulocity.
<br/>
=> Issue #1077: Specification for log file management from Cumulocity

configuration/init/systemd/tedge-watchdog.service, crates/core/tedge_watchdog/src/error.rs, crates/core/tedge_watchdog/src/systemd_watchdog.rs
Enable systemd watchdog monitoring for tedge-watchdog daemon.
- Read the `watchdogsec` from service file, if its present then enable the `watchdog`, and send the `health notification` to the `systemd` on regular intervals.
<br/>
=> Enable systemd watchdog monitoring for tedge-watchdog daemon

crates/common/flockfile/src/unix.rs, crates/common/mqtt_channel/src/session.rs, crates/common/tedge_config/src/models/file_path.rs, crates/common/tedge_users/src/unix.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_smartrest/src/error.rs, crates/core/c8y_smartrest/src/operations.rs, crates/core/c8y_smartrest/src/smartrest_serializer.rs, crates/core/tedge/src/main.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/restart_operation_handler.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/dynamic_discovery.rs, crates/core/tedge_mapper/src/c8y/error.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/core/tedge_mapper/src/main.rs, crates/tests/tedge_test_utils/src/fs.rs, plugins/c8y_log_plugin/src/config.rs, plugins/c8y_log_plugin/src/logfile_request.rs, plugins/c8y_log_plugin/src/main.rs
Fixing clippy warnings throughout the project.
<br/>
=> #825 fixing clippy warnings

.github/workflows/pull-request-checks.yml
As it's proposed at [here](https://github.com/thin-edge/thin-edge.io/discussions/1200#discussioncomment-2985918) and discussed at #945, merges will be blocked by warnings.
<br/>
=> Deny warnings by cargo

docs/src/SUMMARY.md, docs/src/references/thin-edge-config-files.md
Add `references/thin-edge-config-files.md` to `SUMMARY.md`
<br/>
=> Add ref doc link into summary.md

README.md
Since we deprecated "commit-workflow", "integration-test-workflow" and "system-test-workflow" and replaced them by "ci-pipeline", the budges on README.md need to be updated.
<br/>
=> Update workflow status budges on README.md

plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
Quick fix error handling for log and configuration plugins. If the wrong payload is specified, the plugins will now display an `error!` message with the (malformed) payload in question. And most importantly, this will no longer cause the programs to exit. 
To reproduce: 
start c8y_log_plugin or c8y_configuration_plugin: 
```
sudo ./target/debug/c8y_log_plugin 
```
send the following with mosquitto_pub
```
mosquitto_pub -t 'c8y/s/ds' -m '522,'
```
c8y_log_plugin should no longer exit and should display: 
```
ERROR c8y_log_plugin: Incorrect payload: 522,  
```
- Closes #1220
=> Fixing plugins panic if incorrect payload

crates/common/tedge_utils/src/file.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
`tedge/tedge_mapper/tedge_agent/c8y_config_plugin/c8y_log_plugin --init` must create the config files only if the config files does not exists.
Changed the signature of the `create_file_with_user_group` function to take `default_content` and write it to the file.
https://github.com/thin-edge/thin-edge.io/issues/1189
=> c8y_configuration_plugin --init and c8y_log_plugin --init are overwriting exiting files

.github/workflows/pull-request-checks.yml, Cargo.lock, crates/common/tedge_utils/Cargo.toml, crates/common/tedge_utils/src/fs_notify.rs, crates/common/tedge_utils/src/lib.rs, crates/tests/tedge_test_utils/src/fs.rs
Inotify API implementation only. This change was required because our use of the [inotify](https://docs.rs/inotify/latest/inotify/) crate duplicated throughout our code base.
1. in the cumulocity log plugin 
2. in the cumulocity configuation plugin
3. in the cumulocity mapper (updating operations) 
In these three cases: 1. and 2. required a file watch while 3. required a directory watch. The goal of this PR is to propose a new inotify API that is caters for both needs (file or directory watch). 
It also tries to be flexible to allow multiple combinations of files and directories to be watched (and hopefully the logic there is bug-free). 
After this PR, 3 more PRs will show the implementation of this API for the three cases above. Any changes requested here will spill to those PRs.
Below …
=> fs_notify an inotify implementation (only)

.github/workflows/pull-request-checks.yml
It is inconvenient if someone wants to change the workflow files, but the jobs are skipped in the pull requests. For example, https://github.com/thin-edge/thin-edge.io/pull/1263 should run all pull request checks workflow inside the PR. 
#1233
=> Run all pull request checks on the changes of workflow files

.github/workflows/pull-request-checks.yml
The PR #1244 added a feature flag 'fs-notify' to amd64 test, however, not added to armv7 test. The armv7 test also needs the flag.
<br/>
#1173
=> Add feature flag fs-notify to armv7 test

crates/common/tedge_utils/src/fs_notify.rs
fixing clippy warning for fs_notify
To test this fix works run: 
cargo clippy --all-features
=> fix cargo clippy --all-features for fs_notify

.github/workflows/pull-request-checks.yml
cargo clippy should run on features flags too. 
No issue
=> run clippy with --all-features

Cargo.lock, crates/common/certificate/Cargo.toml, crates/common/certificate/src/lib.rs
Closes #1280 
Supersedes #1280 
This PR includes the patches from dependabot from #1280 and a fix for a changed interface in the x509-parser crate.
=> Update x509 parser

Cargo.lock, crates/common/mqtt_channel/Cargo.toml, crates/core/c8y_smartrest/src/operations.rs, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_mapper/src/c8y/dynamic_discovery.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/core/mapper.rs
Implementing fs_notify crate for c8y configuration plugin.
This commit contains the changes of #1244 applied on top of it. When reviewing please review only the last commit: d737517d97837d3fffd64ba6d5b900297e4748e0
- #1246
=> tedge mapper dynamic discovery of operations

docs/src/references/c8y-configuration-management.md, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_configuration_plugin/src/main.rs
Implementing `fs_notify` crate for c8y configuration plugin. 
This commit contains the changes of #1244 applied on top of it. When reviewing please review only the last commit: 8e5f1f84f440e1f589cad6117b02be34540918e3
- #1248
=> c8y configuration plugin implementation

Cargo.lock, plugins/c8y_log_plugin/Cargo.toml, plugins/c8y_log_plugin/src/main.rs
Implementation of the new fs_notify crate for Cumulocity log plugin. The review of the crate is here: #1244. Please discuss crate-specific topics there. 
When reviewing please review only the last commit: a7203cffb23637f7bfc0b743e14f2fbfa4b7fca3
- #1244 
- #1247
=> fs_notify crate for c8y log plugin

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/doc_improvement.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/refactoring_request.md
Issues and labels must be connected. Therefore, modified the existing issue templates to distinguish what the reporter wants with labels.
- Based on the type of issue, add a corresponding label automatically
- Add a template for refactoring
<br/>
=> Improve GitHub issue template

docs/src/howto-guides/002_installation.md
As per request of #1232, 
- Add information how to upgrade thin-edge.io
- Change the structure of doc
#1232
=> Improve installation guide of thin-edge

.github/workflows/pull-request-checks.yml
All jobs that require the filtering result must run after the filtering
job finishes. Refer to https://github.com/dorny/paths-filter#examples.
#1312
=> Add "needs" on the Udeps job to run after Rust code changes

docs/src/howto-guides/020_monitor_tedge_health.md
Update the `health-check` endpoints for `c8y-log-plugin` and `c8y-configuration-plugin`.
<br/>
=> update health check doc

crates/common/tedge_utils/src/file.rs, crates/core/tedge/src/main.rs, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_mapper/src/az/mapper.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
Hi!
While browsing the code of the `tedge_util`I found some things that can be improved style-wise.
Please find my patches, where I expressed what I did in great detail in the commit messages, so that others can understand why a specific change was done.
=> tedge_util style fixes

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/thin_edge_json/src/alarm.rs
- Extend the alarms feature to child/external devices.
- Create the child device, if it does not exists, and then forward the `alarm` message.
- Added tests to check the basic feature as well as to test the `reconciliation` of alarm messages.
https://github.com/thin-edge/thin-edge.io/issues/1204
=> Extend alarms API to support child devices

tests/RobotFramework/MQTT_health_check/MQTT_health_endpoints.robot
Testing MQTT Health endpoints, both testcases added in one robot file
- MQTT_health_endpoints.robot
#1172
=> Add RF test case for MQTT health check c8y

docs/src/howto-guides/002_installation.md
This PR captures the documentation updates to describe how to use the `uninstall-thin-edge.io` script.
<br/>
=> Update the document to show how to uninstall thin-edge.io

crates/core/c8y_translator/src/serializer.rs, crates/core/tedge/src/cli/connect/command.rs, crates/core/tedge_mapper/src/c8y/tests.rs, plugins/c8y_configuration_plugin/src/main.rs
Removes some unnecessary `let _ =`s in the codebase.
=> Remove let nothing equals

crates/core/tedge/Cargo.toml, crates/core/tedge_mapper/Cargo.toml
Add fields `package.homepage` and `package.repository` to manifests of crates `tedge` and `tedge_mapper`.
This change is necessary to generate bitbake recipes from tedge and tedge_mapper crates as part of #1329. Currently, we're trying to set up a minimal working example, and as such only these crates required this change.
=> Yocto: Add homepage and repository fields to manifests of tedge and tedge_mapper crates

docs/src/tutorials/send-events.md
Document events API for child devices
<br/>
=> Issue #1197 Document events API for child devices

docs/src/howto-guides/002_installation.md, uninstall-thin-edge_io.sh
Update the `uninstall script` and document to use the correct command line options.
<br/>
=> fix the typos in the uninstall script and doc

docs/src/tutorials/raise-alarm.md
Document alarms API for child devices
<br/>
=> Issue #1204 Document alarms API for child devices

.github/workflows/pull-request-checks.yml
The filter expression is written to the best of my knowledge, but I
don't know whether this actually catches all Cargo.toml files or whether
it misses the topmost one.
Closes #1322
=> Add check whether lockfile is up to date

crates/common/download/src/download.rs, crates/common/flockfile/src/unix.rs, crates/common/logged_command/src/logged_command.rs, crates/core/agent_interface/src/error.rs, crates/core/agent_interface/src/messages.rs, crates/core/agent_interface/src/software.rs, crates/core/agent_interface/src/topic.rs, crates/core/c8y_api/src/json_c8y.rs, crates/core/c8y_smartrest/src/operations.rs, crates/core/c8y_smartrest/src/smartrest_deserializer.rs, crates/core/c8y_smartrest/src/smartrest_serializer.rs, crates/core/c8y_smartrest/src/topic.rs, crates/core/c8y_translator/src/serializer.rs, crates/core/tedge/src/cli/connect/bridge_config.rs, crates/core/tedge/src/cli/connect/bridge_config_azure.rs, crates/core/tedge/src/cli/connect/bridge_config_c8y.rs, crates/core/tedge/src/cli/connect/cli.rs, crates/core/tedge/src/cli/connect/common_mosquitto_config.rs, crates/core/tedge/src/system_services/managers/config.rs, crates/core/tedge_agent/src/state.rs, crates/core/tedge_mapper/src/c8y/topic.rs, crates/core/thin_edge_json/src/alarm.rs, crates/core/thin_edge_json/src/event.rs, crates/tests/sawtooth_publisher/src/main.rs, plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/tedge_apt_plugin/src/main.rs
Here go more clippy fixes.
Probably relevant for #1297
=> Clippy fixes

plugins/tedge_apt_plugin/src/error.rs, plugins/tedge_apt_plugin/src/main.rs, plugins/tedge_apt_plugin/src/module_check.rs
Enhance the `Package` validation error messages to be more verbose.
Print the `Expected` value and `Provided` value.
For example for the version mismatch case
When the below command is sent to the `apt` plugin.
`sudo apt install tedge_mapper  --file ./target/debian/tedge_mapper_0.7.3_amd64.deb --module-version 1.0`
The error message should be as below.
`ERROR: Validation of ./target/debian/tedge_mapper_0.7.3_amd64.deb metadata failed, expected value for the Version is  0.7.3, but provided  1.0`
https://github.com/thin-edge/thin-edge.io/issues/1183
=> Enhance the tedge_apt_plugin error message to be more verbose

.github/workflows/pull-request-checks.yml, ci/build_scripts/build_for_amd64.sh, ci/build_scripts/build_for_arm.sh, ci/ci_smoke_test_az.sh, ci/ci_smoke_test_c8y.sh, ci/configure_bridge.sh, ci/installation_scripts/clean_up_rpi.sh, ci/installation_scripts/install_for_amd64.sh, ci/installation_scripts/install_for_arm.sh, ci/package_list.sh, ci/report/build.sh, ci/report/build_local.sh, docs/gen-ref-docs.sh, get-thin-edge_io.sh, plugins/tedge_docker_plugin/tedge_docker_plugin.sh, tests/PySys/misc_features/custom_init_system/dummy_init/dummy_init.sh, uninstall-thin-edge_io.sh
This PR adds a `shellcheck` job. Shellcheck is reasonably fast that this does not impact our CI time _at all_.
This PR also fixes _most_ issues shellcheck reports. The ones I did not fix here are issues where I don't know how to go forward and might need some investigation from someone who knows better.
=> Add shellcheck action, fix issues

configuration/debian/tedge/preinst, configuration/debian/tedge_agent/postinst, configuration/debian/tedge_mapper/postinst
Signed-off-by: Krzysztof Piotrowski <krzysztof.piotrowski@inetum.com>
Replace `addgroup`, `adduser` and `runuser` for cross-Unix system compatibility.
#1329 
This changes are necessary to run scripts on yocto embedded system as was mentioned in #1329.
=> Replace scripts commands for the cross-Unix system compatibility

crates/core/tedge_agent/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
We have added all the remaining plugins to our meta-tedge Yocto layer, so `homepage` and `manifest` fields were added for the rest of the necessary crates so that cargo-bitbake utility can generate recipe files for them.
=> Add manifest fields to all crates

crates/common/flockfile/src/unix.rs
Some small (misc) refactorings in the `flockfile` crate.
Only readability things, nothing too important.
=> Flockfile misc refactorings

ci/configure_bridge.sh
Rename the environment variable `C8YPASSWORD` to `C8YPASS` to be inline with other places.
<br/>
=> Rename C8YPASSWORD to C8YPASS

GOVERNANCE.md
Signed-off-by: Marcel Müller <m.mueller@ifm.com>
A proposal for thin-edge open-source project governance.
The central idea of this proposal is to align the project structure with the decision drivers.
* Decisions impacting all the contributors should be concentrate on a core as small as possible.
* Contributors should be able to add their own extensions to this core with great decision-making autonomy.
* Users should be able to build their applications using their own criteria to select and combine extensions.
The project architect is organized along the same lines:
* A small core set of APIs, runtime and tools.
* An open set of extensions - north-bound or south-bound connectors, telemetry data sources and processors, device management …
=> Agreement on a governance model for thin-edge

vision.md
@AndrejS321 as the vision.md file was PRd from a branch from within this repository instead of your fork, I have to open this PR against the branch in this repo instead of your fork.
---
The following patchset includes formatting fixes for the whole document (f881900..87a7496) and updates from our side (written and reviewed by Matthias Betz, @TheNeikos and me as noted by the commit trailers).
Our changes are in the range [87a7496..8332af8](https://github.com/matthiasbeyer/thin-edge.io/compare/87a74961144a0dc5739ac7a69c649f81ef60fb9e..8332af871c157f3b96cc259f675f815756a65f5c).
---
Please include these patches into PR #1226 (by merging them) and lets discuss the changes there, so we do not split discussion into (two or more) seperate PRs!
=> Patches for Vision

crates/core/tedge_agent/src/agent.rs
fixed a bug where the tedge agent logs directory was duplicated on --init call
I introduced this bug with this PR: https://github.com/thin-edge/thin-edge.io/pull/1338
Running sudo tedge_agent --init would duplicate /"logs_path"/tedge/agent part of the logs path to /"logs_path"/tedge/agent/tedge/agent where "logs_path" is `sudo tedge config get logs.path` 
#1387
Fixes #1070
=> fixed tedge agent --init duplicating sub folders

CONTRIBUTING.md
This is the second part of #1379 and
Closes #1378
=> Cleanup contributing

GOVERNANCE.md
=> Rewrite sections about maintainers and teams

crates/common/mqtt_channel/src/connection.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
This PR fixes the issue related to the MQTT library.
When the `MQTT` connection is lost may be because of `MQTT broker` goes down the existing MQTT client connections will be lost. When the `MQTT Broker` comes back again the existing `MQTT` clients will reconnect to the broker. During that the MQTT clients must also re-subscribe to the topics if there is no `session-name` present.
https://github.com/thin-edge/thin-edge.io/issues/1286
https://github.com/thin-edge/thin-edge.io/issues/1332
=> Re-subscribe to the mqtt topics once the connection comes back

configuration/init/systemd/tedge-watchdog.service, docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md
The `tedge-watchdog` works only if any of the `thin-edge` services is enabled with the `watchdog` feature, else the service will fail to start. Since `restart=always` is set in the systemd file, it was keep getting restarted and the state was moved to `activating`.
So in this PR the `tedge-watchdog` systemd service file is updated to `Restart=on-failure` . Now if the tedge-watchdog is started, it will move to an inactive (Exited successfully) state if the WatchdogSec is not enabled for any of the `thin-edge` services.
https://github.com/thin-edge/thin-edge.io/issues/1372
=> tedge-watchdog.service stays in status activating

.github/workflows/pull-request-checks.yml
Updated CI task to use 1.63.0 to be in line with the other ones.
=> Update cargo.lock check to 1.63.0

README.md
removed unmaintained roadmap project link, to be replaced by aligned roadmap md file
<br/>
=> Update README.md - removal of unmaintained roadmap project

crates/core/c8y_smartrest/src/operations.rs, crates/core/tedge_mapper/src/c8y/converter.rs
Extract all the `valid smart rest template IDs` and use them for invoking the corresponding operations.
- [] New feature (non-breaking change which adds functionality)
https://github.com/thin-edge/thin-edge.io/issues/1356
=> Custom operations do not accept arbitrary topics

Cargo.lock, configuration/debian/tedge_agent/postinst, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_agent/src/agent.rs, crates/core/tedge_agent/src/error.rs, crates/core/tedge_agent/src/http_rest.rs, crates/core/tedge_agent/src/main.rs
Exposing REST endpoints to exchange binary files between a thin-edge connected device and child devices. 
- #1335
=> #1335 file transfer http api

configuration/init/systemd/tedge-agent.service
Change tedge agent service file to run as root
=> Change tedge agent service file to run as root

crates/core/tedge_mapper/src/c8y/converter.rs
Signed-off-by: alexandru solomes <solo@softwareag.com>
Fixed the typo that was seen in the files changed tab of PRs:
<br/>
=> Fix spell check GitHub Actions warning

Cargo.lock, crates/common/download/src/download.rs, crates/core/c8y_api/src/http_proxy.rs, crates/core/tedge_mapper/src/c8y/tests.rs, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_configuration_plugin/src/child_device.rs, plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/error.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/topic.rs, plugins/c8y_configuration_plugin/src/upload.rs, plugins/c8y_log_plugin/src/logfile_request.rs
Extend c8y-config-plugin to support `c8y_UploadConfigFile` and `c8y_DownloadConfigFile` operations on child devices
<br/>
=> Issue #1337 Child device support for c8y-config-plugin

docs/src/references/tedge-binary-repository
A reference guide for the Thin Edge binary repository and its APIs.
<br/>
=> Thin Edge File Transfer Repository reference guide

crates/core/c8y_smartrest/src/error.rs, crates/core/c8y_smartrest/src/operations.rs, crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/core/converter.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/core/mapper.rs
This PR adds the code changes to publish the supported operations for the child devices to the c8y cloud.
**Features supported**
As of now it only publishes the `supported operations` for the `existing child` devices
It `dynamically discovers` the operations for the existing child devices and sends them to the c8y cloud
**Todo**
It can not dynamically discover the ` new child devices`, if a new child device has to be recognized then the `mapper` has to be restarted.
https://github.com/thin-edge/thin-edge.io/issues/1448
=> Update the c8y mapper to declare child supported operations

crates/core/tedge_mapper/src/c8y/converter.rs, crates/core/tedge_mapper/src/c8y/tests.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
**c8y_configuration_plugin**, **c8y_log_plugin**, and **tedge_mapper c8y** does not expect multiple-line SmartREST messages like
```
c8y/s/ds 526,10000000b1bc91d3,t3k_PlcList
526,10000000b1bc91d3,c8y-configuration-plugin
```
However, it can happen when
* Multiple operations were created when the process is down. When the process is up again, the process calls `500` SmartREST message. Then, all operations will be sent with multiple-line as above.
The current implementation picks up only the first line. This PR fixes to pick up all lines and address them.
#1359
=> Handle multiple-line SmartREST operations

crates/core/tedge_mapper/src/c8y/tests.rs
Added tests to verify the thin-edge `device fragments` feature.
1. tedge-mapper sending default fragments
2. tedge-mapper sending fragments that are defined in `inventory.json`
3. Addressed child ops tests readability improvments
<br/>
=> Add test for device inventory fragments

docs/src/SUMMARY.md, docs/src/tutorials/yocto-linux.md
As outlined in #1329 as part of Yocto Linux support, this PR adds a tutorial for building Thin Edge for Yocto. It'd be nice if somebody from the team went through the steps in the tutorial and confirmed that everything is working and all is clear.
<br/>
#1329
=> Yocto: Add Yocto Linux documentation tutorial page

crates/common/tedge_utils/Cargo.toml
dca5a93 introduced tracing inside tedge_utils, however, it required to update Cargo.toml of the crate.
With this fix, finally this works.
```
cargo build --release -p tedge
```
<br/>
=> Fix compilation error in tedge_utils regarding tracing

configuration/debian/c8y_configuration_plugin/postinst, configuration/debian/c8y_configuration_plugin/prerm, configuration/debian/c8y_log_plugin/postinst, configuration/debian/c8y_log_plugin/prerm, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml
To enable the self-update via OTA, update the debian maintainer scripts for `c8y_configuration_plugin` and `c8y_log_plugin`. 
Prepared two packages from this fix, named `0.100.0` and `0.100.1`.
1. The device has already installed the released version `0.7.5`.
2. Upgrade from `0.7.5` to `0.100.0`.
3. Upgrade from `0.100.0` to `0.100.1`.
4. Purge `0.100.1`.
5. Install `0.100.0`.
6. Remove `0.100.0`. (systemd unit files will be masked)
7. Install `0.100.0` again.
1. The device has already installed the released version `0.7.5`.
2. Upgrade from `0.7.5` to `0.100.0`.
3. Upgrade from `0.100.0` to `0.100.1`.
4. Remove `0.100.1`.
5. Install `0.100.0`.
#1466 
- [] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
The …
=> [Self-Update] Update Debian maintainers scripts of c8y-*-plugin

crates/tests/mqtt_tests/src/test_mqtt_server.rs
Increased the number of characters displayed by the mqtt test broker from 60 characters to 110.
<br/>
=> Increase mqtt test server debug message

configuration/debian/tedge_mapper/postinst, configuration/debian/tedge_mapper/prerm, configuration/debian/tedge_watchdog/postinst, configuration/debian/tedge_watchdog/prerm, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml
To enable the self-update via OTA, update the debian maintainer scripts for `tedge_mapper` and `tedge_watchdog`. 
---
This is the test what I've done before creating this PR.
Prepared two packages from this fix, named `0.100.0` and `0.100.1`.
**Note: Upgrade from the released version to the new version always fails. It works only from the new version to new version.**
1. The device has already installed the released version `0.100.0`.
2. Upgrade from `0.100.0` to `0.100.1`.
3. Purge `0.100.1`.
4. Install `0.100.0`.
5. Remove `0.100.0`. (systemd unit files will be masked)
6. Install `0.100.0` again.
**Note: You should not remove tedge_mapper as it's a part of Software Management feature**
1. The device has already installed the released version `0.100.0`.
2. Upgrade from `0.100.0` to …
=> [Self-Update] Update Debian maintainer scripts of tedge_watchdog tedge_mapper

.gitignore
Hi, I have a small request. Can we ignore this .vimspector.json file? I use it for setting up a debugger. It would help me to not accidentally commit it. (The breaking change tick is a joke)
<br/>
=> Ignore .vimspector.json a debug configuration file

tests/RobotFramework/tasks/build_install_rpi.robot
Signed-off-by: Gligor <gligorisaev@gmail.com>
Add step in which tedge will disconnect from c8y before start of the purge uninstall
<br/>
=> Add step to disconnect from c8y before uninstalling tedge

configuration/debian/tedge_agent/postinst, configuration/debian/tedge_agent/postrm, configuration/debian/tedge_agent/prerm, crates/core/tedge_agent/Cargo.toml
To enable self-update, when systemd is available on the device, on upgrading, maintainer script doesn't stop tedge_agent service. To complete upgrading, user need to restart a device.
There is a workaround regarding #DEPHELPER#
- postinst and postrm should not use #DEPHELPER#, however, cargo-deb returns an error if #DEPHELPER# doesn't exist. To prevent this, stop adding automatically the #DEPHELPER# code, and add them to maintainer script directly.
This is the error.
```
$ cargo deb -p tedge_agent --no-strip --no-build --target=armv7-unknown-linux-gnueabihf
cargo-deb: unable to replace #DEBHELPER# token in maintainer script '/home/rina/thinedge/thin-edge-fork/crates/core/tedge_agent/../../../configuration/debian/tedge_agent/postinst'
```
I couldn't find a good solution for #DEPHELPER# …
=> [Self-Update] Update Debian maintainer scripts of tedge_agent

plugins/tedge_apt_plugin/src/main.rs
`tedge_apt_plugin` returns an error when you try downgrading package. It is not intended.
```
stderr <<EOF
E: Packages were downgraded and -y was used without --allow-downgrades.
EOF
```
See https://github.com/thin-edge/thin-edge.io/issues/1466#issuecomment-1286558932.
#1466
=> Allow tedge_apt_plugin to downgrade packages

plugins/c8y_configuration_plugin/src/child_device.rs, plugins/c8y_configuration_plugin/src/config.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/error.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/operation.rs, plugins/c8y_configuration_plugin/src/upload.rs
The c8y-config-plugin to fail cloud operation when the execution of that operation on the child device fails, for cases like:
- If the plugin fails to download the config file for a child device, on a c8y_DownloadConfigFile request, fail that operation, before even passing that request to the child device
- On receipt of a c8y_UploadConfigFile request, if the child device sends successful status without uploading the file, the plugin should fail that operation ignoring the successful status from the child.
<br/>
=> Issue #1480: c8y-config-plugin to fail cloud operation on execution failure

plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_configuration_plugin/src/upload.rs
Fix path to `c8y-configuration-plugin.toml` read by `c8y-configuration-plugin` during operation request handling.
<br/>
=> Fix path to c8y-configuration-plugin.toml

Cargo.lock, crates/common/batcher/Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/clock/Cargo.toml, crates/common/download/Cargo.toml, crates/common/flockfile/Cargo.toml, crates/common/json_writer/Cargo.toml, crates/common/logged_command/Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/agent_interface/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, crates/core/thin_edge_json/Cargo.toml, crates/tests/mqtt_tests/Cargo.toml, crates/tests/sawtooth_publisher/Cargo.toml, crates/tests/tedge_test_utils/Cargo.toml, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
Bump up to 0.8.0. After this commit, I will branch out.
<br/>
=> (cargo release) bump version 0.8.0

Cargo.lock, crates/common/batcher/Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/clock/Cargo.toml, crates/common/download/Cargo.toml, crates/common/flockfile/Cargo.toml, crates/common/json_writer/Cargo.toml, crates/common/logged_command/Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/agent_interface/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, crates/core/thin_edge_json/Cargo.toml, crates/tests/mqtt_tests/Cargo.toml, crates/tests/sawtooth_publisher/Cargo.toml, crates/tests/tedge_test_utils/Cargo.toml, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
Have `0.8.0-rc.1` on release-0.8.0 branch.
<br/>
=> (cargo release) bump version 0.8.0-rc.1

plugins/c8y_log_plugin/src/config.rs, plugins/c8y_log_plugin/src/error.rs, plugins/c8y_log_plugin/src/main.rs
The log plugin didn't load the .toml file at the startup. This PR fixes it.
#1532
=> Log plugin does not load config file at startup

plugins/c8y_log_plugin/src/config.rs, plugins/c8y_log_plugin/src/error.rs, plugins/c8y_log_plugin/src/main.rs
The same fix as #1533 porting to the main branch.
#1532
=> Fix log plugin does not load .toml configuration file at startup

Cargo.lock, crates/common/batcher/Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/clock/Cargo.toml, crates/common/download/Cargo.toml, crates/common/flockfile/Cargo.toml, crates/common/json_writer/Cargo.toml, crates/common/logged_command/Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/agent_interface/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, crates/core/thin_edge_json/Cargo.toml, crates/tests/mqtt_tests/Cargo.toml, crates/tests/sawtooth_publisher/Cargo.toml, crates/tests/tedge_test_utils/Cargo.toml, plugins/c8y_configuration_plugin/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apama_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml, plugins/tedge_dummy_plugin/Cargo.toml
rc version up due to the fix of #1532 (PR is #1533)
<br/>
=> (cargo release) bump version 0.8.0-rc.2

crates/common/tedge_utils/src/notify.rs, crates/core/tedge_mapper/src/c8y/dynamic_discovery.rs, crates/core/tedge_mapper/src/core/error.rs, crates/core/tedge_mapper/src/core/mapper.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
While trying to fix the tedge mapper to send child device created events, I thought it would be simpler to do this if `notify` was extended to allow directories to be separated from files. This PR proposes an extension of the `notify` crate to allow for DirectoryCreated, DirectoryDeleted, FileCreated, FileDeleted events, while using this to send 101 events for child device creation. 
#1520
=> `notify` event extension - fix tedge mapper child device create events

docs/src/SUMMARY.md, docs/src/howto-guides/child_device_config_management_agent.md, docs/src/howto-guides/howto-guides.md
Document how to write child device config management agent
<br/>
=> Issue #1513 Document how to write child device config management agent

docs/src/howto-guides/004_connect.md
Fix https://github.com/thin-edge/thin-edge.io/issues/1541.
I confirmed that only this doc has minus instead of hyphen. All other docs are file.
#1541
=> Replace minus by hyphen in doc

docs/src/tutorials/supported_operations.md
Update the `thin-edge.io` supported operations docs to reflect the `thin-edge.io child device` supported operations.
<br/>
=> Update supported ops doc for child devices

docs/src/howto-guides/002_installation.md
Port the doc update to the release-0.8.0 branch. The first PR was #1548 (merged to main)
=> Port update installation guide to release 0.8.0 branch

.github/workflows/pull-request-checks.yml
To unblock the typo job failure found in https://github.com/thin-edge/thin-edge.io/actions/runs/3393851504/jobs/5642134876.
#1558
=> Update pull-request-checks.yml to fix typos job

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/hosted-post-merge_version_update.yml, .github/workflows/pull-request-checks.yml, .github/workflows/update-tedge-ref-docs.yml
The current workflows get many warnings regarding 
- Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Swatinem/rust-cache, Swatinem/rust-cache
- The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See [this](https://github.com/thin-edge/thin-edge.io/actions/runs/3384648327) for example.
These warnings can be resolved by updating the version of `Swatinem/rust-cache` from `v1` to `v2`.
Note: There seem more actions are …
=> Update workflows to remove deprecated warning messages

crates/core/tedge_mapper/src/c8y/tests.rs
Fix the thin-edge device operation name typo in test.
<br/>
=> Fix the operation name typo

.typos.toml
Fix spell check false warning.
<br/>
=> Add "OT" in spell-check dictionnary

crates/core/tedge_mapper/src/c8y/tests.rs
Create the operations only once.
<br/>
=> Fix redundant ops create

crates/core/tedge_mapper/src/c8y/mapper.rs, crates/core/tedge_mapper/src/c8y/tests.rs, crates/core/thin_edge_json/src/parser.rs, crates/core/thin_edge_json/src/utils.rs
Supersedes [Simplify the implementation of `thin_edge_json::utils::excerpt`](https://github.com/thin-edge/thin-edge.io/pull/857)
<br/>
=> Simplify implementation of thin_edge_json::utils::excerpt

crates/common/tedge_utils/src/lib.rs, crates/common/tedge_utils/src/timers.rs, plugins/c8y_configuration_plugin/src/config_manager.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/upload.rs
* Allow child devices to reset device config operation timers with "executing" status messages
* Make "executing" status message optional
<br/>
=> Issue #1544 Enable config operation timer reset with executing status

ci/build_scripts/build.sh
When building the project, only install `gcc` dependencies if directed by the user. The `--install-gcc` flag has been added as a supported argument to the build script.
This is also an attempt to fix the unexpected glibc dependencies which were added by automatically installing the latest gcc packages in the refactored `build.sh` script (introduced in https://github.com/thin-edge/thin-edge.io/pull/1587)
=> Only install gcc on when requested

ci/installation_scripts/clean_up_rpi.sh
Fix debian broken packages during the CI cleanup task.
The situation arose where a previous installation of tedge caused "broken packages" due to a missing libc dependency. This blocks the removal of other packages, as apt does not allowing installing or removing of packages when in a broken state.
<br/>
=> fix broken debian packages in cleanup

ci/installation_scripts/clean_up_rpi.sh
Use assume yes when fixing debian broken packages (`apt-get install -f -y`).  The build was previously prompting for confirmation which resulted in the CI workflow which prevented the action from executing successfully.
<br/>
I tested the command command locally on the device to confirm the functionality.
=> use force when fixing broken deb packages

docs/src/tutorials/software-management.md, plugins/tedge_apt_plugin/src/main.rs
Users can set the version of an apt package equal to "latest" as a substitute for the default of blank space.
#1594
- [] I have added tests that prove my fix is effective or that my feature works
=> Add support for `latest` version keyword

crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs, crates/core/tedge/src/cli/config/config_key.rs
Adding http port to `tedge config list` command
<br/>
=> http port bug fix

crates/common/tedge_config/src/system_services/managers/config.rs
Making the system.toml "[system]" key optional (defaulting to ["init", "6"]
N/a
=> Add default value for reboot command in system.toml

tests/RobotFramework/config_management/child_conf_mgmt_plugin.robot
Signed-off-by: Gligor Isaev <glgorisaev@gmail.com>
Created test for the child device configuration management
<br/>
=> Adding test for child device conf mgmt

docs/src/howto-guides/017_apama_software_management_plugin.md
Leaving the version before the :: blank works and gets the latest available, which is what we want
=> Don't specify version

.github/workflows/pull-request-checks.yml
=> Enable toolchain via github action for cargo fmt

.github/workflows/gh-pages.yml, .github/workflows/pull-request-checks.yml
Removing an unused dependency on `mdbook-toc`.
This [mdbook-toc issue](https://github.com/badboy/mdbook-toc/issues/30) is blocking the PR check workflow due to a dependency issue. Upon investigation it was found that the page "toc" functionality is not currently used. Once the issue is fixed the mdbook toc may be added in and the feature activated.
<br/>
An example of the error can be viewed [here](https://github.com/thin-edge/thin-edge.io/actions/runs/3704877256/jobs/6278656511)
=> remove mdbook-toc dependency

crates/core/tedge_api/src/alarm.rs, crates/core/tedge_api/src/event.rs, crates/core/tedge_mapper/src/c8y/alarm_converter.rs, crates/core/tedge_mapper/src/c8y/converter.rs
Make `Alarm` and `Event` message conversion error log messages more verbose by adding payload, topic and error string to the error log message.
For example the `alarm` conversion error message looks as below
```
2022-12-08T05:36:45.031302856Z ERROR tedge-mapper-c8y:messages{ops_dir=Some("/etc/tedge/operations/c8y")}: tedge_mapper::core::converter: Mapping error: Deserialing of alarm message: {
"message": "Temperature is very high",
", received on topic: tedge/alarms/critical/temperature_high, failed due to error: trailing characters at line 4 column 2
```
<br/>
=> Enhance the alarm and event message conversion error logs

.github/workflows/build-workflow.yml, .gitignore, ci/build_scripts/build.sh, ci/build_scripts/publish_debian.sh
Publish the built Debian packages to an private Debian repository (controlled via GitHub secrets). This makes it easier to install a specific non-official release for development and testing purposes.
It also gain experience with the Debian repository to prepare for having a public repository. The documentation on how to use the repository is not included in this PR due to the url being private.
The packages are published in the `build-workflow`, and on any changes to `main` or `release-*` branches
<br/>
=> publish debian packages to jfrog for development purposes

tests/RobotFramework/README.md
Made the list in the section 5 of RobotFramework tests README file render correctly and fixed some inconsistencies.
<br/>
=> Improve formatting in RobotFramework README

.github/workflows/pull-request-checks.yml, crates/common/batcher/Cargo.toml, crates/common/certificate/Cargo.toml, crates/common/logged_command/Cargo.toml, crates/common/mqtt_channel/Cargo.toml, crates/common/tedge_config/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_api/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, crates/core/tedge_watchdog/Cargo.toml, crates/tests/mqtt_tests/Cargo.toml, crates/tests/sawtooth_publisher/Cargo.toml, crates/tests/tedge_test_utils/Cargo.toml, plugins/c8y_log_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml
Signed-off-by: alexandru solomes <solo@softwareag.com>
Ran `cargo sort -w .` to sort all files in directory
<br/>
=> Sort dependencies

.typos.toml
Ignore files with extension `*min.js`
<br/>
=> Ignore spurious typo warning in *min.js files

.github/workflows/pull-request-checks.yml
Remove cargo-sort check as a required dependency to run build & test.
All build & test tasks are skipped because cargo sort is failing.
```
error: failed to compile `cargo-sort v1.0.9`, intermediate artifacts can be found at `/tmp/cargo-installuKSg6O`   
Caused by:  
package `clap v4.1.1` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0
```
This PR doesn't fix cargo-sort but let the main checks run even if the dependencies are not properly sorted.
<br/>
=> Remove cargo-sort check as a required dependency to run build & test

crates/core/tedge_agent/src/main.rs, crates/core/tedge_mapper/src/main.rs, crates/core/tedge_watchdog/src/main.rs, docs/src/howto-guides/014_thin_edge_logs.md, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
Update the `thin-edge` services names to use `-` instead of `_`
<br/>
=> update the tedge services names according to the convention

docs/src/tutorials/getting-started.md
Fix typo in the "getting started" doc
<br/>
=> fix tedge connect typo in getting started docs

get-thin-edge_io.sh
Fix logic which was setting the default version after the version comparison which decides what package naming convention to use (e.g. underscores or dashes).
<br/>
=> Fix default version logic in thin-edge install script

docs/src/references/c8y-configuration-management.md
The [how-to-guide](https://thin-edge.github.io/thin-edge.io/html/howto-guides/child_device_config_management_agent.html#declare-supported-configuration-list-to-thin-edge) says
> The child device agent needs to upload this file to thin-edge with an HTTP PUT request to the URL: `http://{tedge-ip}:8000/tedge/file-transfer/{child-id}/c8y-configuration-plugin`
whilst the [specs](https://thin-edge.github.io/thin-edge.io/html/references/c8y-configuration-management.html#the-child-device-uploads-its-configuration-file-list-on-start-and-on-change) was written as
> Uploads this file to `http://$TEDGE_HTTP/tedge/file-transfer/$CHILD_DEVICE_ID/config_snapshot/c8y-configuration-plugin` with a `PUT` call.
It seems `$TEDGE_HTTP/tedge/file-transfer/{child-id}/c8y-configuration-plugin` is correct (without …
=> Doc fix misalignment and typos in c8y-configuration-plugin specs

Cargo.lock, get-thin-edge_io.sh
The `c8y-remote-access-plugin` was added to the `get-thin-edge_io.sh` script (in #1694) even though it has not been officially released. This was causing the installation script to then fail due to 404 errors when trying to download a non-existent binary from the releases page.
It can be added back in once the next release is ready and the artifacts have been uploaded to the releases page.
<br/>
=> Fix remove remote access install

docs/src/howto-guides/020_monitor_tedge_health.md
Update the `tedge daemon health status` document to be inline with the code changes.
<br/>
=> Update the health status document

docs/src/tutorials/supported_operations.md
Now there is no need to send the operation status update message to c8y from the command that is executed by the tedge-mapper.
<br/>
=> Doc: Update the supported operation file example

Cargo.lock, crates/common/download/examples/simple_download.rs, crates/common/download/src/download.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs, crates/common/tedge_utils/src/file.rs, crates/core/c8y_api/Cargo.toml, crates/core/c8y_api/src/http_proxy.rs, crates/core/c8y_api/src/smartrest/error.rs, crates/core/plugin_sm/src/plugin.rs, crates/core/tedge_mapper/src/c8y/tests.rs, plugins/c8y_configuration_plugin/src/child_device.rs, plugins/c8y_configuration_plugin/src/download.rs, plugins/c8y_configuration_plugin/src/error.rs, plugins/c8y_configuration_plugin/src/tests.rs
Before having a new firmware plugin, moving some codes from `c8y-configuration-plugin` to the `common` crate.
This will make the firmware plugin implementation easier.
<br/>
=> Refactor the download implementation of c8y-configuration-plugin

docs/src/howto-guides/002_installation.md, uninstall-thin-edge_io.sh
Refactor the `uninstall-thin-edge_io.sh` script to use `#!/bin/sh` (a posix compatible script), to make it more portable in different shells (not just bash). This is applicable for other linux distributions such as Alpine Linux.
It also provides a more consistent user experience as the `get-thin-edge_io.sh` already uses the `#!/bin/sh` shebang, so the uninstall can be run the same way the install script is run.
Included an example on how to run the uninstall as a one-liner as well.
<br/>
For references, the main changes when switching from bash to a posix shell format:
* Remove usage of bash arrays (as this is not posix, so not supported in `/bin/sh`)
=> Support posix shells in uninstall script

docs/src/references/plugin-api.md, docs/src/tutorials/write-my-software-management-plugin.md
Improving some of the documentation about the software management plugin:
* Fixed some inconsistencies in the command line arguments names
* Fixed some minor grammar things
* Removed TODOs
<br/>
=> Software management plugin docs: fix grammer and api mistakes

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add some additional dev utilities to the devcontainers:
* cargo components like clippy, rustfmt etc
* gh utility
* vim
<br/>
=> Additional dev tools in devcontainer

crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_actors/src/tasks.rs
A first step toward simplify the Task/Actors traits: only one should be required.
* Remove various ways to spawn a task or an actor, to keep a single one.
* Make the public methods of RuntimeHandle match RuntimeAction entries.
[<br/>](https://github.com/thin-edge/thin-edge.io/issues/1724)
=> Simplify actor spawn logic

crates/core/tedge_mapper/src/c8y/tests.rs
Disabled the flaky alarm tests.
<br/>
=> disable unstable alarm tests

tests/RobotFramework/README.md, tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tasks.py
Small improvements to making it easier to run the tests (and preparation steps). The following changes are included
* Add new test related tasks (in `invoke`)
* Build image using locally built debian packages (choosing the host target)`invoke build --local`
* Clean task `invoke clean` to remove existing. This is automatically run when using `invoke build --local`
* Extend `invoke test` task to include more options to filter tests by name, suite, tags (include/exclude)
* Improved task output by using colours (e.g. ERRORs are in red)
* Support for running tests using podman (and instructions)
<br/>
=> Test tasks improvements

.github/workflows/pull-request-checks.yml
Switched to stable clippy on CI. Rationale for the change in this comment:
https://github.com/thin-edge/thin-edge.io/pull/1761#issuecomment-1446642236
<br/>
=> Switched to stable clippy

crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/tedge_http_ext/src/lib.rs, crates/extensions/tedge_http_ext/src/tests.rs
Deprecate : 
- `C8YConnectionBuilder` : replaced by `ServiceProvider<C8YRestRequest, C8YRestResult, NoConfig>`
- `HttpConnectionBuilder`  : replaced by `ServiceProvider<HttpRequest, HttpResult, NoConfig>`
- `HttpHandle` : replaced by  `ClientMessageBox<HttpRequest, HttpResult>`
=> Deprecate useless specialization: C8YConnectionBuilder

docs/src/tutorials/child-device-config-management.md
Use a relative path to the image on the configuration management design diagram to prevent the [CORB error](https://chromestatus.com/feature/5629709824032768).
<br/>
#1779
=> use relative svg link to prevent CORB error

tests/RobotFramework/tasks.py
Fix a problem when running the integration tests (docker adapter) where a duplicate docker network causes all of the tests to fail. Duplicate networks are caused by a potential race condition in the docker engine.
The changes at least are able to cleanup duplicate network always leaving the first network untouched (if it exists). This should at least not prevent subsequent runs on the same runner instance from failing.
See the following for references about the network race condition:
* https://github.com/moby/moby/issues/20648
* https://github.com/moby/moby/issues/33561
<br/>
=> remove duplicate container networks before tests

crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/examples/mod.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/test_helpers.rs
Documentation improvements [WIP]:
<br/>
=> Document tedge_actors crate

plugins/c8y_firmware_plugin/Cargo.toml, tests/RobotFramework/tasks.py, tests/RobotFramework/tests/installation/install_apt.robot, tests/images/debian-systemd/files/bootstrap.sh
Fix the issue reported in #1793. 
Note: there are still suspicious dependency management regarding all plugins' `--init` directory creation.
#1793
=> Fix the dependency of c8y-firmware-plugin and add test

docs/src/tutorials/yocto-linux.md
Update of Yocto documentation after 0.9.0 release where some things have changed, e.g. new dependency and name of the image.
<br/>
=> update yocto documentation

.github/workflows/gh-pages.yml, .github/workflows/pull-request-checks.yml
Fix $PATH so that mdbook-cmdrun can run tedge
<br/>
=> Fix $PATH so that mdbook-cmdrun can run tedge

docs/src/tutorials/connect-aws.md
=> Document improvement Connect AWS

crates/extensions/tedge_mqtt_ext/src/lib.rs
The MqttMessage were wrapped with two envelopes adding RuntimeMessage twice.
* Deprecate `MqttRuntimeMessage` as the messages are already wrapped with a `RuntimeMessage` by the `CombinedReceiver`.
<br/>
=> Remove one useless level of message envelope

.github/workflows/ci_pipeline.yml
#1813 accidentally broke the ci_pipeline workflow as the expected location of the target location was changed to always store them under an explicit `target/<triple>/debian` instead of `target/debian` (for more consistent behaviour).
<br/>
=> fix amd64 target path used in workflow

tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Fix a small issue with a child device serial number used within a the health check integration tests. A fixed child device id was used which resulted in the first run passing, however subsequent runs would fail as the device would already exist (if it was not cleaned up properly).
Solution is just to prefix the child serial number with the parent's id to ensure uniqueness.
<br/>
=> fix duplicate child device serial number bug in test

crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/tedge_file_system_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs
=> Message box logging

ci/build_scripts/build.sh
Minor improvements to the build.sh script so that it works on older ba
* Allow user to control which bash is used (via `PATH` env variable instead of `/bin/bash`)
* Support running on bash version 3 (default version on MacOS) by removing undeclared variable checks due to handling of empty bash arrays across bash v 3, 4, 5
<br/>
References:
* https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u
=> improve build script bash compatibility

crates/core/tedge/src/cli/connect/bridge_config_azure.rs, crates/core/tedge_mapper/src/az/converter.rs, plugins/c8y_firmware_plugin/Cargo.toml, tests/RobotFramework/tasks.py, tests/RobotFramework/tests/installation/install_apt.robot, tests/images/debian-systemd/files/bootstrap.sh
Add child device support for azure. This PR considers only measurements.
#1799
=> Add child device support for azure (measurements)

crates/core/tedge_actors/src/test_helpers.rs
Add two test helpers:
* `tedge_actors::test_helpers::assert_received` checks that a message box receives a list of messages, in the given order and without other messages.
*  `tedge_actors::test_helpers::assert_received_all_expected` checks that all the given messages have been received, possibly in a different order or interleaved with other messages.
<br/>
- [x I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
=> Add test helpers to expect a sub-set of messages

crates/extensions/c8y_http_proxy/src/credentials.rs
Fix C8YJwtRetriever actor by making it subscribe to `c8y/s/dat`
<br/>
=> Fix C8YJwtRetriever actor MQTT subscription

tests/RobotFramework/tests/tedge/tedge_config_get.robot
Add tests to cover setting configuration settings via environment variables (see linked issues sections for the exact tickets)
<br/>
#1783 
#1835
=> test: control config via env variables

tests/images/debian-systemd/files/bootstrap.sh
Fix small typo in the banner displayed in the test's bootstrap.sh script.
<br/>
=> fix(test): correct typo in bootstrap banner

plugins/c8y_firmware_plugin/src/firmware_manager.rs, plugins/c8y_firmware_plugin/src/tests.rs
Previously, the plugin ignores the new operation from c8y that has completely the same contents as the already addressed request.
This fix stops ignoring, instead, to resend a new firmware update request with incremented "attempt" value.
#1843
=> Change the behaviour when c8y-firmware-plugin receives the same c8y op

get-thin-edge_io.sh, uninstall-thin-edge_io.sh
Add following new plugins (in preparation for the 0.10.0 release) to the install and uninstall scripts:
* c8y-firmware-plugin
* c8y-remote-access-plugin
<br/>
=> feat: add new plugins to install/remove script

crates/core/tedge/Cargo.toml, get-thin-edge_io.sh
Auto detect the "latest" thin-edge.io version in the get-thin-edge_io.sh script via github api rather hardcoding the current latest version. The latest version is only fetched if the user does not specify a version.
This change simplifies the release process as there is now no need to update the script. As soon as a new release is done on GitHub (and it is marked as the "latest" release), the script will automatically select it when user's try to install thin-edge.io.
The approach does have one downside, technically this does make the install script dependent on the GitHub API endpoint (which it previously was not), so if the GitHub API service is down it would interrupt downloads. However it is only really a problem if only the …
=> Feat: Detect latest thin-edge.io version via github api in install script

crates/bin/c8y-device-management/src/main.rs, crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/examples/mod.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_actors/src/tasks.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/core/tedge_actors/src/tests.rs, crates/extensions/c8y_config_manager/src/actor.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_http_proxy/src/tests.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/tedge_file_system_ext/src/lib.rs, crates/extensions/tedge_health_ext/src/actor.rs, crates/extensions/tedge_health_ext/src/lib.rs, crates/extensions/tedge_health_ext/src/tests.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/tests.rs, crates/extensions/tedge_signal_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/actor.rs, crates/extensions/tedge_timer_ext/src/builder.rs, crates/extensions/tedge_timer_ext/src/tests.rs, plugins/c8y_log_plugin/src/main.rs
=> Remove message box trait

crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs
This commit removes unnecessary serde alias for `aws` field in `TEdgeConfigDto` struct. The alias was introduced when merging initial AWS support for version 0.9.0, so the comment was wrong at the time, and the alias was never used, but I missed that during review.
<br/>
=> Remove unnecessary AWS config field alias

uninstall-thin-edge_io.sh
Fixes the assumption that a package must be in the "installed" state before it can be purged. For instance, if the user removes the packages first, then calls again with purge, it previously did not purge the packages. Now it does.
Background:
A package exists in different states (not just installed), e.g.
* installed
* installed (but with config errors)
* removed (but config files exist)
The uninstall script just checks if the package is in any state of the above states, and will run remove or purge based on the user's preference.
<br/>
=> fix: always remove/purge if package exists

crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/converter.rs, crates/core/tedge_actors/src/examples/calculator.rs, crates/core/tedge_actors/src/examples/mod.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/message_boxes.rs, crates/core/tedge_actors/src/runtime.rs, crates/core/tedge_actors/src/test_helpers.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_http_proxy/src/actor.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/tedge_health_ext/src/actor.rs, crates/extensions/tedge_health_ext/src/tests.rs, crates/extensions/tedge_http_ext/src/test_helpers.rs, crates/extensions/tedge_signal_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/actor.rs, crates/extensions/tedge_timer_ext/src/tests.rs
Impl `Sender` trait for for `TimedMessageBox` test helper
<br/>
=> Impl Sender for TimedMessageBox test helper

Cargo.lock, plugins/c8y_remote_access_plugin/Cargo.toml, plugins/c8y_remote_access_plugin/src/main.rs, tests/RobotFramework/tests/installation/install_tedge.robot, tests/images/debian-systemd/files/bootstrap.sh
Fixes #1869 by ignoring cleanup errors.
#1869
=> Ignore errors when cleaning up remote access plugin

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/hosted-post-merge_version_update.yml, .github/workflows/integration-tests.yml, .github/workflows/pull-request-checks.yml, .github/workflows/update-tedge-ref-docs.yml
This adds support for the GitHub actions to pick up the Rust version dynamically. I've created this PR as my other PR (#1877) is currently failing the integration tests because I cannot update the Rust version used.
For security, the integration tests run the workflow file from main rather than the branch that is being merged, so they need to detect the MSRV from Cargo.toml in order to run in a PR which bumps this.
Adding these changes to the other workflows should make it simpler to bump the MSRV in future, and also allows me to sanity check the changes to integration test workflows (which won't be tested here for the limitation mentioned above).
<br/>
=> Install rust version from Cargo.toml in CI checks

configuration/debian/c8y-configuration-plugin/postinst, configuration/debian/c8y-firmware-plugin/postinst, configuration/debian/c8y-log-plugin/postinst, configuration/debian/tedge-agent/postinst, configuration/debian/tedge-mapper/postinst, configuration/debian/tedge-watchdog/postinst, tests/images/debian-systemd/debian-systemd.dockerfile
The following changes are covered by this PR:
* Remove conditional logic in postinst commands (where possible), as the `#DEBHELPER#` was already starting and enabling the service, so the additional call to start and enable the service was unnecessary in all services except (`tedge-mapper` and `tedge-agent`)
* Avoid using `systemctl` directly and use the systemd debian helpers, `deb-systemd-invoke` and `deb-systemd-helper`. The helper commands respect the [policy-rc.d](https://manpages.ubuntu.com/manpages/focal/en/man8/policy-rc.d-declarative.8.html) which gives the user more control over the services, for example the user can decide if they should be installed or not.
**Advantages**
* Installing the debian packages does not fail due to a call to `systemctl start <service>` because systemd …
=> Improve debian systemd service enable/start logic in post installation scripts

Cargo.lock, crates/extensions/tedge_downloader_ext/Cargo.toml, crates/extensions/tedge_downloader_ext/src/actor.rs, crates/extensions/tedge_downloader_ext/src/lib.rs, crates/extensions/tedge_downloader_ext/src/tests.rs
tedge-downloader-actor receives DownloadRequest, then try to download. After a try finish, tedge-downloader-actor responses DownloadResponse, which is the result of download attempt.
This actor will be used by c8y-firmware-manager.
#1806
=> Add tedge-downloader-actor

Cargo.lock, crates/common/download/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/tedge/Cargo.toml, crates/core/tedge_mapper/Cargo.toml, plugins/c8y_firmware_plugin/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml
Use operating system (OS) Certificate Authority (CA) store by default for all http requests (done by the `reqwest` crate).
Since thin-edge.io is not operating in isolation, using the OS CA store is to provide more consistent and expected behaviour for users. For instance users can debug certificate issues using `curl` which defaults to using the OS CA store. More details are discussed in #1678. 
<br/>
#1678
=> feat: use native (OS) certs by default for reqwest

docs/src/BUILDING.md, docs/src/architecture/mapper.md, docs/src/howto-guides/002_installation.md, docs/src/howto-guides/003_registration.md, docs/src/howto-guides/004_connect.md, docs/src/howto-guides/008_config_local_mqtt_bind_address_and_port.md, docs/src/howto-guides/010_add_self_signed_trusted.md, docs/src/howto-guides/012_install_and_enable_software_management.md, docs/src/howto-guides/013_connect_external_device.md, docs/src/howto-guides/014_thin_edge_logs.md, docs/src/howto-guides/015_installation_without_deb_support.md, docs/src/howto-guides/020_monitor_tedge_health.md, docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md, docs/src/howto-guides/024_smartrest_templates.md, docs/src/howto-guides/025_config_management_plugin.md, docs/src/howto-guides/026_how_to_install_thin_edge_manually.md, docs/src/howto-guides/028_c8y_service_monitoring.md, docs/src/tutorials/connect-c8y.md, docs/src/tutorials/raise-alarm.md, docs/src/tutorials/send-events.md, docs/src/tutorials/send-thin-edge-data.md, docs/src/tutorials/software-management.md, docs/src/tutorials/supported_operations.md, docs/src/tutorials/write-my-software-management-plugin.md, docs/src/tutorials/yocto-linux.md
* Replace UTF-8 NBSP by regular spaces
* Use admonish for all notes, warnings and examples
<br/>
=> Cosmetic documentation improvements

docs/src/developer/DEBIAN_PACKAGE_HOSTING.md
Add the thin-edge.io debian packages that were missing from the public debian repository usage instructions.
<br/>
=> docs: add missing debian packages to instructions

crates/common/flockfile/src/unix.rs
Implement `get_pid` api and re-use it.
<br/>
=> get pid api

CONTRIBUTOR-LICENSE-AGREEMENT.md, GOVERNANCE.md, docs/src/howto-guides/child_device_config_management_agent.md, docs/src/tutorials/child-device-config-management.md
Replace open/close double quotes (`“` / `”`) with plain double quotes (`"`).
<br/>
=> docs: use double quotes instead of open/close

GOVERNANCE.md, docs/src/SUMMARY.md, docs/src/architecture/domain-model.md, docs/src/architecture/faq.md, docs/src/howto-guides/004_connect.md, docs/src/howto-guides/026_how_to_install_thin_edge_manually.md, docs/src/howto-guides/howto-guides.md, docs/src/references/bridged-topics.md, docs/src/references/c8y-configuration-management.md, docs/src/tutorials/getting-started.md
Various spelling mistake fixes
<br/>
=> doc: fix spelling mistakes

crates/extensions/c8y_config_manager/src/upload.rs
Replaced hard-coded `/var/tedge/file-transfer` path with the configured transfer_dir setting.
<br/>
=> fix: use transfer dir setting instead of hard-coded path

crates/bin/c8y-device-management/src/main.rs, crates/common/batcher/src/lib.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/converter.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_mapper/src/core/mapper.rs, crates/extensions/c8y_config_manager/src/lib.rs, crates/extensions/c8y_config_manager/src/tests.rs, crates/extensions/c8y_firmware_manager/src/lib.rs, crates/extensions/c8y_firmware_manager/src/tests.rs, crates/extensions/c8y_http_proxy/src/lib.rs, crates/extensions/c8y_log_manager/src/actor.rs, crates/extensions/c8y_log_manager/src/lib.rs, crates/extensions/collectd_ext/src/actor.rs, crates/extensions/tedge_health_ext/src/lib.rs, crates/extensions/tedge_health_ext/src/tests.rs, crates/extensions/tedge_mqtt_ext/src/lib.rs, crates/extensions/tedge_mqtt_ext/src/tests.rs, crates/extensions/tedge_signal_ext/src/lib.rs, crates/extensions/tedge_timer_ext/src/builder.rs, plugins/c8y_configuration_plugin/src/main.rs, plugins/c8y_firmware_plugin/src/main.rs, plugins/c8y_log_plugin/src/main.rs
- Add a connect_consumer method to the ServiceProvider trait
- Simplify ConfigManagerBuilder::new()
- Simplify LogManagerBuilder::new()
- Simplify FirmwareManagerBuilder::new()
- Simplify LogManagerBuilder::new()
- Simplify SignalActor::builder()
- Simplify use of HealthMonitorBuilder::new()
<br/>
=> Improve actor builders

crates/common/mqtt_channel/src/config.rs, crates/extensions/c8y_http_proxy/src/credentials.rs
The MQTT connection created by the C8Y JWT retriever must nor clash with one of the tedge daemons.
Use an anonymous session with the clear flag set.
<br/>
=> Fix MQTT session of c8y_http_proxy

tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
This test case checks.
1. Is collect running
2. Is collectd publishing MQTT messages
3. Starting tedge-mapper-collectd
4. Check collected and translated metrics
5. Check if c8y messeges are generated
<br/>
=> Create collectd test case

tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot
Reduce the scope of the `c8y-firmware-plugin` restart integration test due to accidental rebase/squash error which is causing the CI workflow to fail.
The error was accidentally introduced in https://github.com/thin-edge/thin-edge.io/pull/1934.
<br/>
=> fix(test): reduce test scope for firmware restart

tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py, tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
Fix MQTT message assertions to avoid using a list and only assert the first message.
This fix is necessary as it is causing sporadic failures when running the integration tests.
Changes
* Avoid using `Should Contain` with a list as it fails when the list length is greater than 1. Use the first message instead.
* Add documentation and explicit arguments for MQTT message filtering based on payload in the  `Should Have MQTT Messages` keyword
<br/>
=> fix: improve collectd integration test to avoid sporadic failures

.github/workflows/build-workflow.yml, ci/build_scripts/build.sh
Add a OS agnostic artifact (tarball aka `tar.gz`) which just includes the thin-edge.io binaries. This allows the user to install it on their own systems or in a container very easily without building it themselves.
Changes
* Add a step to package the binaries as a tarball (`tar.gz`) using `just release`
* Archive the artifact in the build-workflow (so it can be used for GitHub releases)
Below is an example of the name of the archive:
```sh
tedge_{version}_{target}.tar.gz
tedge_0.9.0-575-g48f43b5c_aarch64-unknown-linux-musl.tar.gz
```
Where an underscore (`_`) is used as the delimiter to enable easier parsing of the version from the file name.
<br/>
=> feat: package all binaries in single tarball

configuration/init/systemd/c8y-log-plugin.service
Avoid explicit service dependencies with other tedge components. This also aligns the systemd `Unit.After` setting with the value used by other thin-edge.io components (e.g. `c8y-configuration-plugin`, `c8y-firmware-plugin` etc.)
<br/>
=> fix: remove service dependency on tedge-mapper-c8y

justfile
Small improvements to the just recipes related to the integration tests. The following changes were made:
* Simplify the `integration-test` recipe by composing recipes
* Add `setup-integration-test` recipe to install all test dependencies (called manually though)
<br/>
=> dev: refactor/extend just integration test recipes

crates/core/tedge_actors/Cargo.toml, crates/core/tedge_actors/src/actors.rs, crates/core/tedge_actors/src/builders.rs, crates/core/tedge_actors/src/converter.rs, crates/core/tedge_actors/src/examples/calculator_server.rs, crates/core/tedge_actors/src/lib.rs, crates/core/tedge_actors/src/servers/mod.rs, crates/extensions/c8y_config_manager/Cargo.toml, crates/extensions/c8y_firmware_manager/Cargo.toml, crates/extensions/c8y_mapper_ext/Cargo.toml, crates/extensions/tedge_file_system_ext/Cargo.toml, crates/extensions/tedge_mqtt_ext/Cargo.toml, crates/extensions/tedge_mqtt_ext/src/lib.rs
Hide `tedge_mqtt_ext/test_helpers` module behind a feature flag.
<br/>
=> Feature flag guard for test-helpers

crates/core/tedge/src/cli/connect/jwt_token.rs
A clean session avoids the problem of receiving older jwt tokens via the local broker from a different c8y.url then the currently configured url.
This bug would be most noteable when switching the c8y.url that thin-edge.io connects to.
Switching c8y.urls would result in the following warning message when calling `tedge connect c8y`:
```sh
Warning: Connecting to thin-edge-io.eu-latest.cumulocity.com, but the configured URL is test-ci-runner01.latest.stage.c8y.io.
The device certificate has to be removed from the former tenant.
```
<br/>
=> fix(cli): use clean session when validating url connectivity during tedge connect

crates/core/tedge_actors/src/servers/actors.rs
The fix for https://github.com/thin-edge/thin-edge.io/issues/1972 re-introduce the issue https://github.com/thin-edge/thin-edge.io/issues/1962. The active loop that was preventing the mapper to shutdown, have been move from on actor to another. 
Let shutdown on ^C all the actors implemented using the `Server` trait.
- https://github.com/thin-edge/thin-edge.io/issues/1972
- https://github.com/thin-edge/thin-edge.io/issues/1962
The correct behavior on shutdown might be specific to each actor implementation. This will be addressed after the 0.11 release.
=> Shutdown a server actor on ^C

crates/extensions/tedge_mqtt_ext/src/lib.rs
Both `tedge-agent` and `tedge-mapper` fail to gracefully shutdown when mosquitto is down.
To reproduce the issue:
1. Stop the mosquitto broker
2. Stop the tedge-agent service
3. Start tedge-agent on the console
4. Stop the service (using ctrl-c)
5. ....then tedge-agent takes 1 minute to shutdown
We expect tedge-agent to shutdown immediately on such a case.
This issue also affects tedge-mapper and all the c8y plugins.
The MQTT actor needs to be ready to shutdown even before the connection is established.
<br/>
=> Fix agent and mapper failing to gracefully shutdown when mosquitto is down

tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Added steps to cover:
1. aws.url
2. aws.root.sert.path
3. aws.mapper.timestamp
4. http.port
5. firmware.child.update.timeout
6. c8y.url
7. az.url
8. mqtt.external.port
9. mqtt.external.bind_address
10. mqtt.external.bind_interface
11. mqtt.external.capath
12. mqtt.external.certfile
13. mqtt.external.keyfile
14. software.plugin.default
<br/>
=> Added 14 steps to cover the whole config list

docs/src/SUMMARY.md, docs/src/howto-guides/howto-guides.md
The documentation page for server/client authentication for the local MQTT broker was not being rendered by mdbook because it was not linked.
The page was added to `howto-guides.md` and `SUMMARY.md` and now appears correctly in html output.
<br/>
=> Fix server/client auth docs page not appearing

.github/workflows/pull-request-checks.yml, crates/core/plugin_sm/tests/plugin.rs, crates/core/plugin_sm/tests/plugin_manager.rs
This PR includes various improvements to the "PR checks" CI pipeline:
- Add code coverage measurement on codecov.io
> NOTE: to finish setting up coverage, a secret token for `thin-edge/thin-edge.io` repository may have to be generated on codecov.io and added to the repository secrets in settings. But it might also start working immediately, as we have used codecov previously and the token might already be there.
- Add `cargo doc` check, which checks if API documentation for the workspace can be generated
- Expand testing to include all targets, e.g. examples and doc tests
- Sped up PR checks a bit by adding cache to jobs, fixing it where it wasnt taking effect, or reducing amount we build unnecessarily, and starting more jobs in parallel
<br/>
=> CI improvements

.github/codecov.yml, .github/workflows/gh-pages.yml, .github/workflows/hosted-post-merge_version_update.yml, .github/workflows/pull-request-checks.yml, Cargo.lock, crates/common/download/Cargo.toml, crates/common/logged_command/Cargo.toml, crates/common/tedge_utils/Cargo.toml, crates/core/c8y_api/Cargo.toml, crates/core/plugin_sm/Cargo.toml, crates/core/tedge_agent/Cargo.toml, crates/core/tedge_api/Cargo.toml, crates/extensions/c8y_log_manager/Cargo.toml, plugins/tedge_apt_plugin/Cargo.toml
- Replace actions-rs with toolchain install
- remove unused dependencies
- add cache to cargo-udeps check
<br/>
=> Replace actions-rs with toolchain install

.github/workflows/build-workflow.yml, .github/workflows/ci_pipeline.yml, .github/workflows/pull-request-checks.yml
Use `ubuntu-20.04` over `Ubuntu-20.04` even though both work, the latter is not part of the official names: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
Previosly the yaml validation in some IDE's (e.g. VSCode) was complaining about `Ubuntu-20.04` as it was not officially part of the list. The changes removes these warnings.
<br/>
=> fix(ci): use official github hosted runner names

.github/workflows/gh-pages.yml
Fix the yaml syntax in the `gh-pages` workflow which was introduced in https://github.com/thin-edge/thin-edge.io/pull/2011.
<br/>
=> fix(ci): remove erroneous prefix before run commands

Cargo.lock, crates/extensions/tedge_script_ext/Cargo.toml, crates/extensions/tedge_script_ext/src/lib.rs
Adding missing `pub` so this extension can be used ;-)
<br/>
=> Add missing pub constructor

crates/core/c8y_api/src/smartrest/message.rs, tests/PySys/plugin_apt/apt_list_format/run.py
Fix two spell check failures.
<br/>
=> Fix spell check failures

configuration/debian/tedge-apt-plugin/postinst, configuration/debian/tedge-apt-plugin/postrm, plugins/tedge_apt_plugin/Cargo.toml
Problem:
With the existing way of installing `tege-apt-plugin` the binary will be installed into `/etc/tedge/sm-plugins/`  unlike the other 
`thin-edge` binaries which are installed into `/usr/bin`. Also, the `tedge-apt-plugin` binary is renamed as `apt`. 
Proposed solution:
To make it consistent with other components, this PR makes the required changes to install the `tedge-apt-plugin` into `/usr/bin` and also, adds the `postinst` scripts that creates the `symlink` to `/etc/tedge/sm-plugins/apt`.
This also adds a `postrm` script to remove the `apt` plugin from `/etc/tedge/sm-plugins` directory.
<br/>
=> Add a sym link to tedge-apt-plugin in /etc/tedge/sm-plugins

tests/RobotFramework/tests/customizing/tedge_init.robot
Added test:
/tests/RobotFramework/tests/customizing/tedge_init.robot
<br/>
=> Add test fot tedge init

docs/src/tutorials/supported_operations.md
Update the `supported operations doc` to reflect the custom operation timeout feature.
<br/>
=> update doc to reflect the custom ops timeout

Cargo.lock, crates/common/mqtt_channel/src/config.rs, crates/common/tedge_config/src/tedge_config_cli/new.rs, crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs
Compiling in nightly was failing because a feature name got changed and proc-macro2@1.0.59 was referring to the previous name that no longer existed. Issue was fixed in 1.0.60+, we have updated to 1.0.63, which is the most recent version.
https://github.com/rust-lang/rust/issues/113152
Also fixed a warning when compiling on nightly.
<br/>
=> Fix compilation error on nightly

docs/src/operate/c8y/apama_software_management_plugin.md, docs/src/operate/c8y/c8y_fragments.md, docs/src/operate/c8y/remote_access_with_cumulocity.md, docs/src/operate/configuration/config_local_mqtt_bind_address_and_port.md, docs/src/operate/connection/connect.md, docs/src/operate/installation/how_to_install_thin_edge_manually.md, docs/src/operate/installation/install_and_enable_software_management.md, docs/src/operate/operations/restart_device_operation.md, docs/src/references/c8y-log-management.md, docs/src/references/cli/index.md, docs/src/start/getting-started.md, docs/src/start/index.md, docs/src/start/software-management.md
Minor docs layout improvements:
* Use `<img />` for specific images to reduce the default size
* Use docusaurus note blocks
* Remove unnecessary punctuation and empty lines
<br/>
=> docs: minor formatting improvements

.github/workflows/gh-pages.yml
Publish new docusaurus documentation to github pages.
It will use the [tedge-docs](https://github.com/thin-edge/tedge-docs) repository to build and publish the docs to the gh pages of the thin-edge.io repository. This is replacing the previous static website generator framework, mdbook.
<br/>
=> feat: publish docusaurus docs to github pages

docs/src/operate/installation/install_and_enable_software_management.md
Fix management typo in title.
<br/>
=> docs: fix management typo in title

docs/src/start/getting-started.md
Fix indentation level of the sub-step headers so they appear in the page toc at the correct level.
<br/>
=> docs: fix getting started step indentation
