- docs/src/SUMMARY.md
- docs/src/install/index.md
- docs/src/operate/connection/connect.md
- docs/src/operate/index.md
- docs/src/operate/installation/install_and_enable_software_management.md
- docs/src/operate/installation/installation_without_deb_support.md
- docs/src/overview.md
- docs/src/start/connect-aws.md
- docs/src/start/connect-azure.md
- docs/src/start/connect-c8y.md
- docs/src/start/index.md
- Make the "Install" section the first one.
- For now, keep some installation details and alternatives under operate/installation. However, we need to fix these pages.
<br/>
> Move out Install section

- docs/src/contribute/writing-documentation/index.md
- docs/src/contribute/writing-documentation/markdown-components.md
- docs/src/contribute/writing-documentation/markdown-guidelines.md
General improvements to the "Writing documentation" section:
* Group markdown guide under common writing-documentation section
* Add a new page detailing the custom markdown components available for usage
<br/>
> docs: refactor markdown guidelines to show components

- docs/src/contribute/index.md
- docs/src/contribute/writing-documentation/index.md
- docs/src/extend/index.md
- docs/src/operate/c8y/index.md
- docs/src/operate/configuration/index.md
- docs/src/operate/connection/index.md
- docs/src/operate/index.md
- docs/src/operate/installation/index.md
- docs/src/operate/monitoring/index.md
- docs/src/operate/operations/index.md
- docs/src/operate/security/index.md
- docs/src/operate/telemetry/index.md
- docs/src/operate/troubleshooting/index.md
- docs/src/references/index.md
Add DocCardList to all index pages
- with few exceptions as for intall where its better to directly dive into
<br/>
> Add DocCardList to all index pages

- .gitignore
Ignoring the `docs/src/src` symlink which is created when building the docs under the [tedge-docs](https://github.com/thin-edge/tedge-docs) repo. This is to prevent accidentally commiting the symlink to the repo.
<br/>
> dev(docs): ignore symlink created when building the docs

- docs/src/start/getting-started.md
Fix broken links for the steps of the main tutorial
<br/>
> Fix broken anchor links

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Enable additional tools in dev-containers:
1. bash-completion
2. ping
3. mosquitto-clients
4. just
5. yarn (nodejs package manager used for the tedge docs which use docusaurus)
**Note**
Additional rust specific tooling can be installed manually by the user by running the `install-tools` task. It is not run automatically in the post dev container create lifecycle hook because users who just want to run the integration tests, don't need to have cargo-sort installed. This decreases the devcontainer setup time significantly.
```sh
just install-tools
```
<br/>
> Extra tools in dev-containers

- docs/src/references/data-model.md
- docs/src/understand/thin-edge-json.md
Fix minor json syntax errors in some examples in the documentation.
<br/>
> docs(fix): add missing commas to json examples

- crates/tests/mqtt_tests/src/test_mqtt_server.rs
This removes hard-coded port for the test MQTT broker, allowing the tests to be run concurrently and removes some flakiness. The difference can be observed by running `cargo nextest run -p mqtt_channel` - without the changes some or most tests failed, with the changes, all test finish successfully (at least on my machine).
Unfortunately neither the older `rumqttd` version we use, nor the latest version (that additionally drops QoS 2 support) provides a way to query the broker port after it started, so the workaround with binding a TCP listener just to drop it, has to be used for now.
<br/>
> Remove hardcoded port in test_mqtt_server.rs

- crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
A change in the c8y platform caused subscriptions to the s/dat/# and s/uat/# topics to break the jwt request/response mechanism.
Changing the bridge topics to `s/dat` and `s/uat` fixes it. It is possible that the c8y platform behaviour will be fixed, however it is safer to use the offical topics rather than a wildcard as there were no subtopics being used anyway.
<br/>
@jarhodes314 found this issue during work being done with Cumulocity ThickEdge.
> fix(c8y-bridge): don't use mqtt wildcard due to breaking change in cumulocity

- docs/src/operate/monitoring/connect_external_device.md
Remove duplicate row in the connecting an external device instructions.
<br/>
> docs: remove duplicate row in the external broker instructions

- tests/RobotFramework/tests/customizing/tedge_init.robot
Removing an accidental Resource import in a Robot Framework integration test.
<br/>
> fix(test): remove erroneous robot framework resource import

- docs/src/references/mqtt-api.md
Minor fix to an example in the mqtt api spec which uses invalid json (missing a comman and has a trailing comma). Invalid json affects the te2mqtt directive which relies on parsing the payload to pretty print it.
<br/>
> docs(mqtt): fix invalid json in an example

- docs/src/references/mappers/c8y-mapper.md
- docs/src/references/mappers/index.md
Mark the mqtt v1 mapper docs as draft to prevent from appearing in the online docs. The draft flag will be removed once a new release is made.
Since the docs were not previously marked as draft, it was causing a build error as the page was linking to a draft page which resulted in a "broken link" (as draft packages are excluded from the production build).
The following failed PR run demonstrating the error can be found here:
* https://github.com/thin-edge/thin-edge.io/actions/runs/5613061942
<br/>
> docs: mark mqtt v1 mapper docs as draft

- crates/common/tedge_config/src/tedge_config_cli/new.rs
- crates/core/tedge/src/cli/certificate/upload.rs
- crates/core/tedge/src/cli/config/commands/set.rs
- crates/core/tedge/src/cli/config/commands/unset.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/cli/connect/jwt_token.rs
- crates/core/tedge/src/cli/mqtt/cli.rs
- crates/core/tedge/src/cli/mqtt/publish.rs
- crates/core/tedge/src/cli/mqtt/subscribe.rs
- crates/core/tedge/src/error.rs
`tedge` must use the new tedge config APIs to parse the configurations. 
https://github.com/thin-edge/thin-edge.io/issues/2019
> Refactor tedge to use new config

- .devcontainer/devcontainer.json
The plugin with the old name `matklad.rust-analyzer` does not exist anymore and got renamed to `rust-lang.rust-analyzer`.
<br/>
> Switch to latest rust-analyzer vscode plugin

- docs/src/references/mqtt-api.md
Minor improvements to the mqtt api spec
* Remove incomplete sentence
* Add additional context to service registration
* Add more details about health LWT message
<br/>
> docs(mqtt-spec): minor corrections and additional context

- tests/RobotFramework/tasks.py
Usuability improvements to the integration test `flake-finder` task to find flakey integration tests.
* Add the `--clean` option to the integration test `flake-finder` task to make it easier to remove existing output folders.
* Improve console messages indicating if the output folder already exists and --clean is not used
Note: The `--clean` option is not set to True by default to avoid accidentally deleting the output folder from a previously flake finder run. This is useful because finding flake tests often requires running all the tests 100 times (which takes hours to run). Preserving the output folder data by default prevents accidental flake finder report loss.
**Example**
Providing `--clean` will delete the output folder if it already exists.
```sh
invoke flake-finder --suite "Lock …
```
> test(tasks): add clean option to flake finder task

- Cargo.lock
- crates/common/tedge_config_macros/Cargo.toml
- crates/common/tedge_config_macros/macro/Cargo.toml
The PR #2099 discovered that there's inconsistency definition in Cargo.toml file in `tedge_config_macros` crate.
This PR fixes it.
<br/>
> Update Cargo.toml of tedge_config_macros crate

- README.md
- get-thin-edge_io.sh
Fix various links to documentation.
<br/>
> docs: fix broken links in readme and install script

- README.md
- docs/README.md
- docs/src/operate/c8y/apama_software_management_plugin.md
- docs/src/operate/configuration/child-device-config-management.md
- docs/src/start/getting-started.md
Fix broken documentation links. The broken links were not detected as they were using an external link which is not validated automaticallly by docusaurus during build time.
* Switch to using internal links between any docs hosted on the same page (this also works better for versioned docs)
* Remove the `/html/` suffix from the doc website links in READMEs as this is from mdbooks
<br/>
> docs: fix broken doc references

- docs/src/contribute/writing-documentation/markdown-components.md
Extending the markdown examples with the following examples:
* ProposalBanner - to show when a page is a proposal only (no implementation)
* More examples for new te2mqtt options (e.g. formats, grouping etc.)
<br/>
> docs: add more markdown examples for te2mqtt and the proposal banner

- docs/src/start/getting-started.md
Update doc urls to use `/index.md` instead of referring to a folder as it causes unnecessary redirects.
This also puts unnecessary workload on the search scraper as it needs to navigate both links.
<br/>
> docs: use links to files instead of folders to avoid unnecessary redirects

- tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot
Move child alarm tests into telemetry directory
<br/>
> Move all telemetry test to same directory

- crates/common/tedge_config_macros/src/option.rs
Fixed error message shown on the console when a required configuration setting is missing. The format string used erroneously `\n` in a raw Rust string, which resulted in the literal `\n` being displayed.
Below shows the improvement.
**Before**
```text
A value for 'c8y.url' is missing. \n\
A value can be set with `tedge config set c8y.url <value>`
```
**After**
```text
A value for 'c8y.url' is missing.
A value can be set with `tedge config set c8y.url <value>`
```
<br/>
> fix(config): removing escaped newline char shown in console message

- configuration/debian/tedge-apt-plugin/postrm
Simplify the post remove maintainer script for `tedge-apt-plugin` to always remove the symlink.
Use `rm -f` which does not fail if the file does not exist (as this also avoid race conditions between the test and action).
The previous logic also was erroneous (as indicated by shellcheck rule [SC2107](https://www.shellcheck.net/wiki/SC2107)).
<br/>
[#2113](https://github.com/thin-edge/thin-edge.io/issues/2113)
> fix(tedge-apt-plugin): remove symlink using rm -f instead of using conditional logic

- plugins/c8y_remote_access_plugin/build.rs
Use the same auto versioning logic used by other thin-edge.io components for the `c8y-remote-access-plugin`. Previously this component was just getting the version set via the Cargo.toml instead of the semver value set via git.
For example, the auto versioning uses git describe to generate a semver compatible version without having to bump the Cargo.toml version each time a PR is merged into main. The Cargo.toml only needs to be bumped for official releases.
**Before**
```
$ c8y-remote-access-plugin --version
c8y-remote-access-plugin 0.12.0
```
**After**
```
$ c8y-remote-access-plugin --version
c8y-remote-access-plugin 0.12.1-2-gabcdefab
```
<br/>
> fix(c8y-remote-access-plugin): use auto versioning to align with other components

- configuration/debian/tedge-agent/postrm
- configuration/debian/tedge-mapper/postinst
- configuration/debian/tedge-mapper/postrm
- configuration/debian/tedge/postinst
- configuration/debian/tedge/postrm
- configuration/debian/tedge/preinst
Various improvements and fixes to the debian maintainer scripts including. Some of the changes are in preparation for support other linux package formats, so they are intended to be more generic and remove debian specific assumptions.
* remove reliance on sudo (as maintainer scripts run as root anyway)
* avoid using recurse option when deleting files e.g. `rm -r` (as this can have unintended consequences if the path is a folder and not a file)
* don't delete operations folder when the mapper is removed (as the mapper is not the owner of the folder contents, and tedge will delete /etc/tedge on purge anyway)
* only add sudoer config if sudoers config folder exists
* fallback to systemctl commands if deb helper is not installed
* support user and group management using adduser or useradd for …
> fix(install): improve maintainer script compatibility in preparation for future package support

- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/prerm
- configuration/package_scripts/_generated/c8y-log-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-log-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-log-plugin/deb/prerm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/prerm
- configuration/package_scripts/_generated/tedge-agent/deb/postinst
- configuration/package_scripts/_generated/tedge-agent/deb/postrm
- configuration/package_scripts/_generated/tedge-agent/deb/prerm
- configuration/package_scripts/_generated/tedge-apt-plugin/deb/postinst
- configuration/package_scripts/_generated/tedge-apt-plugin/deb/postrm
- configuration/package_scripts/_generated/tedge-mapper/deb/postinst
- configuration/package_scripts/_generated/tedge-mapper/deb/postrm
- configuration/package_scripts/_generated/tedge-mapper/deb/prerm
- configuration/package_scripts/_generated/tedge-watchdog/deb/postinst
- configuration/package_scripts/_generated/tedge-watchdog/deb/postrm
- configuration/package_scripts/_generated/tedge-watchdog/deb/prerm
- configuration/package_scripts/_generated/tedge/deb/postinst
- configuration/package_scripts/_generated/tedge/deb/postrm
- configuration/package_scripts/_generated/tedge/deb/preinst
The maintainer scripts will be added to assist with comparison with the upcoming refactoring to the linux packaging.
This basis for a comparison was taken from the current debian packages produced by cargo-deb using the following snippet:
```sh
mkdir -p configuration/package_scripts/_generated
cd configuration/package_scripts/_generated
dpkg-deb --control c8y-firmware-plugin_0.12.0-47-gab4e0787_arm64.deb c8y-firmware-plugin/deb/
dpkg-deb --control c8y-log-plugin_0.12.0-47-gab4e0787_arm64.deb c8y-log-plugin/deb/
dpkg-deb --control c8y-remote-access-plugin_0.12.0-47-gab4e0787_arm64.deb c8y-remote-access-plugin/deb/
dpkg-deb --control tedge-agent_0.12.0-47-gab4e0787_arm64.deb tedge-agent/deb/
dpkg-deb --control tedge-apt-plugin_0.12.0-47-gab4e0787_arm64.deb tedge-apt-plugin/deb/
dpkg-deb …
```
> chore: add maintainer scripts from existing debian packages for later comparison

- configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-configuration-plugin/deb/prerm
Followup PR to https://github.com/thin-edge/thin-edge.io/pull/2133 where the c8y-configuration-plugin package maintainer scripts were missed.
<br/>
> chore: add c8y-configuration-plugin maintainer scripts in preparation for new packaging

- crates/core/tedge_agent/src/agent.rs
- crates/core/tedge_agent/src/tedge_to_te_converter/converter.rs
- crates/core/tedge_agent/src/tedge_to_te_converter/tests.rs
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
This PR fixes two issues
1. The misplaced `child-id` in the `alarm` and `event` topics. This has to be as per [this link ](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/#telemetry-child-device)
2. Output message pattern matching in robot tests. Especially for the `alarm` tests.
Since the  `te converter` adds the `severity` into the payload, the order in which it adds will become very random. So, better to check if the output message contains the `severity` fragment or not, instead of the whole payload.
<br/>
> fix the order of child id in the tedge topics

- install.sh
Fix some spelling mistakes in the new install script (introduced in https://github.com/thin-edge/thin-edge.io/pull/2138)
<br/>
> chore: fix typos in comments

- crates/core/tedge/src/cli/init.rs
- tests/RobotFramework/tests/customizing/tedge_init.robot
Use tedge as the user and group owner of all folders created by `tedge init`. This removed the dependency on the mosquitto user when initializing the file system, as the initialization could be done on a device which does not have mosquitto installed and is using an external mqtt broker hosted on a different device.
<br/>
> feat(cli): use tedge instead of mosquitto as owner of mosquitto files/folders

- crates/core/tedge_api/src/entity.rs
- crates/core/tedge_api/src/entity_store.rs
- crates/core/tedge_api/src/lib.rs
- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
Add `entity` and `entity_store` modules that represent entities and allow keeping track of registered entities, respectively.
https://github.com/thin-edge/thin-edge.io/issues/2081
> Digital twin

- .github/workflows/pull-request-checks.yml
- crates/common/tedge_config_macros/Cargo.toml
Fixes cargo doc tedge_config_macros error by just putting tracing into `tedge_config_macros` dependencies. Needed to fix it because `cargo doc --workspace --exclude tedge_config_macros` stopped working on my machine for some reason.
Because `tedge_config_macros` is included in `tedge_config`, and we depend on `tedge_config` in almost every our crate, this probably puts `tracing` inside most of our crates, which might be undesirable.
Also removed unnecessary duplicate `cargo-udeps` check in PR checks.
- #1993
> Fix cargo doc tedge_config_macros error

- ci/build_scripts/build.sh
With the release of [cargo-zigbuild 0.17.1](https://github.com/rust-cross/cargo-zigbuild/releases/tag/v0.17.1), it now supports the latest ziglang version, 0.11.0.
The previous constraint of limiting to ziglang 0.10.1 version has been removed as previous issue with building the musl variants on ziglang 0.11.0 has been resolved.
The display of the ziglang version has also be adapter to also check the python ziglang module if the zig command is not found (purely for debugging purposes).
<br/>
> build: update cargo-zigbuild to support ziglang 0.11.0

- ci/ci_smoke_test_az.sh
- ci/ci_smoke_test_c8y.sh
- crates/extensions/c8y_mapper_ext/src/tests.rs
The tests were failing on systems where they do not have bash installed at /usr/bin/bash (e.g. on Debian). Using `#!/usr/bin/env bash` is more compatible with different operating systems ([reference](https://linuxize.com/post/bash-shebang/#using-shebang-in-bash-scripts).
The problem was discovered when building inside a docker conatiner (`debian:11-slim`).
<br/>
> fix(tests): use more portable bash shebang to prevent units test from failing

- crates/extensions/c8y_mapper_ext/src/actor.rs
Remove `unwrap()`s in the c8y mapper actor that would crash the actor if updating the store failed.
<br/>
> Write error log if updating entity store fails

- crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
- docs/src/references/mqtt-topics.md
Remove the subcription to s/dcr and forwarding for s/ucr as these serve no useful purpose in the context of thin-edge.
https://github.com/thin-edge/thin-edge.io/issues/2168
> Avoid subscribing to s/dcr and forwarding s/ucr

- crates/common/download/src/download.rs
- crates/common/logged_command/src/logged_command.rs
- crates/common/mqtt_channel/src/connection.rs
- crates/core/plugin_sm/src/operation_logs.rs
Fix clippy lints for rust 1.73.
<br/>
> Fix clippy lints for rust 1.73

- crates/common/tedge_config_macros/src/all_or_nothing.rs
- crates/core/c8y_api/src/smartrest/message.rs
- crates/core/tedge_api/src/parser.rs
The rust clippy tool got updated to 1.72. So, there are a few warnings. This PR addresses these warnings.
<br/>
> Address clippy warnings with 1.72 cargo clippy

- ci/build_scripts/build.sh
Fix ci build bug where the current project's MSRV was causing the installation of cargo-zigbuild to fail as the later requires at least rust 1.70 to compile.
<br/>
> build: install cargo-zigbuild using latest stable version

- justfile
Fix/refactor `integration-test` justfile task to activate the python virtual environment before calling the `invoke test` task, as the previous method of calling the python binary under the virtual environment path did not expose all of the other binaries included in the virtual environment in the PATH variable (e.g. `robot` binary would not be found.
The integration-test task will also run the setup if the virtual environment does not exist. However if the python virtual environment already exists and some python packages still need to be updated, then the user will still manually need to run `just setup-integration-test` before running `just integration-test` (this was chosen to reduce the time it takes for the setup)
#2187
> dev: activate python venv before calling integration tests

- tests/RobotFramework/requirements/requirements.adapter-docker.txt
- tests/RobotFramework/requirements/requirements.adapter-local.txt
- tests/RobotFramework/requirements/requirements.adapter-ssh.txt
- tests/RobotFramework/tasks.py
- tests/RobotFramework/tests/installation/install_tedge.robot
- tests/images/debian-systemd/debian-systemd.dockerfile
- tests/images/debian-systemd/files/tedge.toml
Integration test improvements: 
* Update test libraries which includes an improvement to handle time drift between the host and device under test better by using the device time where possible
* Skip on demand tests by default (as this is the default for the CI workflow). Background is that the on demand tests (e.g. linux install tests) currently require more memory allocated to the containers however the testing framework does not support this.
* Use apt name filter setting by default in container image to reduce the noise introduced by having large number of apt packages
<br/>
> test: integration test improvements by updating libraries and reducing apt packages

- crates/core/plugin_sm/src/plugin.rs
- crates/core/plugin_sm/src/plugin_manager.rs
- tests/RobotFramework/tests/cumulocity/software_management/dummy-plugin.sh
- tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
Adding test case that validates the max packages of sw plugin
* Resolves max packages problem. #2200
* Resolves unstable sorting of sm-plugin modules. #2199 
#1926
#2199
#2200
> Add test for sm plugin max packages (and fixes)

- Cargo.lock
- Cargo.toml
- crates/common/tedge_config/Cargo.toml
- crates/core/c8y_api/src/smartrest/error.rs
- crates/core/c8y_api/src/smartrest/operations.rs
- crates/core/tedge/Cargo.toml
- crates/core/tedge/src/cli/mqtt/cli.rs
- crates/core/tedge/tests/main.rs
- crates/core/tedge_agent/src/state_repository/error.rs
- crates/core/tedge_agent/src/state_repository/state.rs
- crates/extensions/c8y_config_manager/Cargo.toml
- crates/extensions/c8y_mapper_ext/src/tests.rs
- crates/tests/tedge_test_utils/src/fs.rs
- plugins/tedge_apt_plugin/Cargo.toml
- plugins/tedge_apt_plugin/src/main.rs
Inherit the `clap` and `toml` from workspace Cargo.toml.
#2181
> inherit clap and toml crates from workspace

- Cargo.lock
- Cargo.toml
- crates/common/download/src/download.rs
- crates/core/tedge/src/cli/certificate/upload.rs
- crates/extensions/tedge_downloader_ext/src/tests.rs
- crates/extensions/tedge_http_ext/Cargo.toml
This PR fixes `download` crate unit tests which didn't terminate when lack of disk space caused a failure.
The tests did not terminate because previously used version of mockito (0.31) had an issue where a destructor for objects created in spawned task would sometimes hang. It caused the tests to hang as well because when returning `Result` from a function (instead of `panic!`ing) the runtime would wait for all tasks to finish.
The issue was solved by upgrading to the latest version of mockito and rewriting tests to use panics. This version was already used in another crate, so this change also removes a duplicate version so that we use only 1 version of mockito.
After the upgrade to the latest mockito version, a test that checked `Content-Length` header stopped working because after …
> Fix `download` crate unit tests not terminating

- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/json.rs
- crates/extensions/c8y_mapper_ext/src/serializer.rs
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Converter must parse the `measurement type` from topic if its present and use it in the converted `c8y` payload.
The priority is as below
Use `measurement type` from `payload` if it is present
Otherwise, use the `measurement type` that is mentioned in the topic.
If both are not present then use the default to `ThinEdgeMeasurement`.
https://github.com/thin-edge/thin-edge.io/issues/2215
> Forward measurement type to c8y

- docs/src/operate/troubleshooting/monitor_tedge_health.md
Fix header level for mosquitto health topics section. Level 1 anchors (e.g. `#`) do not support anchors as they are reserved for page titles. This helps directing people to exact sections to answer any of their questions.
For example, level 2 headers, `## header` produce a link that references that exact section:
Where as a level 1 header, `# header`, does not.
<br/>
> docs(health): fix header level to produce an anchor which can be referenced

- docs/src/start/device-monitoring.md
- docs/src/start/getting-started.md
Update collect installation instructions to be consistent between the getting-started and the device-monitoring pages. Also avoid installing recommended packages when installing the required dependencies via apt.
By avoiding installing the recommended packages it ensures that thin-edge.io stays "thin".
<br/>
> docs(collectd): align installation instructions and avoid installing unnecessary packages

- tests/requirements.txt
Bump python requests package due to security notification:
* https://github.com/thin-edge/thin-edge.io/security/dependabot/9
This will have zero effect but it will eliminate noise in the security notifications to prevent alarm fatigue which might overshadow more important notifications.
The python requirements.txt file is limited to the older PySys tests however there is already ongoing work to remove all PySys tests, but this is out of the scope of this PR.
<br/>
> chore(tests): bump python requests lib due to security notification

- Cargo.lock
- Cargo.toml
- crates/core/tedge/Cargo.toml
- crates/core/tedge/src/cli/config/commands/list.rs
Updates to some libraries which are now possible due to bump in the MSRV 1.70
* Remove atty usage as Rust 1.70 includes native support for terminal/tty detection (resolves very minor/not applicable security notice which wasn't very applicable to our project however it reduces the "noise" in the security warnings in GitHub. https://github.com/thin-edge/thin-edge.io/security/dependabot/10)
* Update clap dependency requirement to use newest version as MSRV is not 1.70 (MSRV was previously 1.6x which was blocking updating to clap >= 4.3)
<br/>
> chore(deps): update dependencies which required Rust 1.70

- ci/build_scripts/build.sh
The new cargo-zigbuild version (0.17.2) fails to build on aarch64. Fixing the version to 0.17.1 until the bug is solved (https://github.com/rust-cross/cargo-zigbuild/issues/179)
<br/>
> build: limit cargo-zigbuild version due to bug in newly released version

- tests/images/debian-systemd/debian-systemd.dockerfile
Add netcat, netstat, and ping to test image.
<br/>
> Add netcat, netstat, and ping to test image

- crates/core/tedge_agent/src/tedge_operation_converter/actor.rs
This PR fix unexpected termination of mqtt actor when wrong payload was parsed. More in #2225.
* #2225
<br/>
> Fix tedge agent's mqtt actor termination when wrong payload was parsed

- ci/build_scripts/build.sh
Update cargo-zigbuild version to latest version after a fix was released.
* https://github.com/rust-cross/cargo-zigbuild/releases/tag/v0.17.3
<br/>
> chore(build): update cargo-zigbuild version

- .github/workflows/build-workflow.yml
Cloudsmith cli 1.1.0 removed support for python 3.8 (see cli's [CHANGELOG](https://github.com/cloudsmith-io/cloudsmith-cli/blob/master/CHANGELOG.md)) which is used by default in the GitHub runner. Bumping python version used for publishing packages to cloudsmith
Example of the failing jobs:
* https://github.com/thin-edge/thin-edge.io/actions/runs/6123795770/job/16623037691
<br/>
> fix(build): update python version used to publish linux packages

- ci/package_list.sh
Remove `c8y-log-plugin` as the ci_pipeline uses the list to install all the packages.
Having both the tedge-log-plugin and the c8y-log-plugin causes a conflict during installation.
<br/>
> fix(build): remove c8y-log-plugin as the ci_pipeline uses the list to install all the packages

- crates/extensions/c8y_firmware_manager/src/actor.rs
- crates/extensions/tedge_log_manager/src/actor.rs
Remove trailing full stop in log entries as it is unnecessary. Also when a full stop is after a value in the log entry, it makes it hard to copy from as the shell highlighting will include the full stop as well.
The only downside to not having the full stop is that if the value has a whitespace after the last visible character, then it will not be obvious in the log entry, however improving the copy/paste of the value trumps the less common trailing whitespace scenario.
**Before**
```
INFO tedge_log_manager::actor: Log request processed for log type: example.
```
**After**
```
INFO tedge_log_manager::actor: Log request processed for log type: example
```
And example showing that it is annoying to copy just the value by double-clicking in the shell to select the value shown in the log …
> remove trailing full stop in log entries as it is unnecessary

- crates/core/tedge_agent/src/agent.rs
- tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
Do not start `TedgeToTeConverter` and file transfer actors if running on a child device. We check whether or not we're running on a child device by seeing if our `mqtt_device_topic_id` is different than `MqttSchema::default_main_device()` (i.e. `device/main//`). This will have to be changed once we start properly supporting custom device schemas.
https://github.com/thin-edge/thin-edge.io/issues/2018#issuecomment-1705325553
> tedge-agent: disable converter and file transfer if running as child device

- configuration/contrib/collectd/collectd.conf
- docs/src/operate/troubleshooting/trouble_shooting_monitoring.md
- docs/src/start/device-monitoring.md
- tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
Increase the default collectd intervals as the current defaults were "too aggressive" and resulted in higher than expected network traffic and load on the IoT platforms.
For demo purposes high frequency data is nice, but it often generates unnecessary load in more productive environments.
Ultimately, if users want a higher frequency interval, then they can modify the values via the configuration update functionality offered by thin-edge.io.
In addition, the following minor improvements to the collectd configuration were made:
* Reduce configuration "noise" by removing collectd configuration which is not suited to IoT solutions as it makes it easier to see which settings are configured and the common use-cases
* Included monitoring of processes including a grouped process group for all of …
> chore(collectd): increase the default intervals to avoid spamming iot platforms

- Cargo.lock
- crates/extensions/c8y_firmware_manager/src/actor.rs
- crates/extensions/tedge_downloader_ext/Cargo.toml
- crates/extensions/tedge_downloader_ext/src/actor.rs
- crates/extensions/tedge_downloader_ext/src/tests.rs
New feature of downloader actor that allows to create download request with `permission` field that will be applied to target file. This change is needed inside `tedge-configuration-plugin` to pass proper permission to downloaded config update.
<br/>
> Add support for permission in download request

- Cargo.lock
- Cargo.toml
- crates/common/tedge_utils/Cargo.toml
- crates/common/tedge_utils/src/file.rs
Resolve security warning by switching from the unmaintained users crate to a fork ([uzers-rs](https://github.com/rustadopt/uzers-rs)):
* https://github.com/thin-edge/thin-edge.io/security/dependabot/13
<br/>
> chore(build): switch from unmaintained users crate to fork to fix security warning

- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
System test improvements regarding the supported operation
* Add supported operations check
* Use auto registration mechanism over manually registration via file creation
* Add protection against an empty supported operations
<br/>
> test: check registration of log file request capability

- Cargo.lock
- Cargo.toml
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/c8y_api/src/http_proxy.rs
- crates/core/tedge_mapper/Cargo.toml
- crates/core/tedge_mapper/src/c8y/mapper.rs
- crates/extensions/c8y_auth_proxy/Cargo.toml
- crates/extensions/c8y_auth_proxy/src/actor.rs
- crates/extensions/c8y_auth_proxy/src/body.rs
- crates/extensions/c8y_auth_proxy/src/lib.rs
- crates/extensions/c8y_auth_proxy/src/server.rs
- crates/extensions/c8y_auth_proxy/src/tokens.rs
- crates/extensions/c8y_auth_proxy/src/url.rs
- crates/extensions/c8y_firmware_manager/src/actor.rs
- crates/extensions/c8y_firmware_manager/src/config.rs
- crates/extensions/c8y_http_proxy/src/actor.rs
- crates/extensions/c8y_http_proxy/src/lib.rs
- crates/extensions/c8y_mapper_ext/Cargo.toml
- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- plugins/c8y_remote_access_plugin/src/main.rs
- tests/RobotFramework/tests/cumulocity/software_management/dummy-plugin-2.sh
- tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
This adds a proxy server for Cumulocity to the mapper which automatically authenticates requests using a JWT, intended to address the issues we've observed with 401s from JWT caching.
#2174
> Add c8y auth proxy

- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/c8y_api/src/json_c8y.rs
- crates/core/c8y_api/src/smartrest/alarm.rs
- crates/core/c8y_api/src/smartrest/topic.rs
- crates/core/tedge_api/src/alarm.rs
- crates/extensions/c8y_mapper_ext/src/alarm_converter.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/error.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/raise_alarms.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Implement #2243.
Behaviour changes:
- Defined the default values for mandatory fields for Cumulocity if it's missing or wrongly given.
a. type: `ThinEdgeAlarm`
b. text: The alarm type (the same as previous behaviour)
c. severity: `minor`
- The definition of uniqueness of alarm. Now it's per alarm type, although it was the combination of alarm type and severity previously. So, alarm A `"type": "foo", "severity": "major"` and alarm B `"type": "foo", "severity": "critical"` are no longer considered as different alarms.
#2243
> c8y-mapper consume the "te" new alarm mqtt scheme

- crates/core/tedge/src/cli/connect/bridge_config.rs
- crates/core/tedge/src/cli/connect/bridge_config_azure.rs
General improvements/fixes to the Azure IoT Hub bridge connection:
* Fix Azure bridge topic mapping direction so that thin-edge.io automatically subscribes to device bound messages
* Use wildcards when subscribing to digital twin topics so that any request id (`$rid`) value can be used
* Allow publishing to the `$iothub/PATCH/#` topic
* Add support for receiving and responding to [direct methods](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#handle-a-direct-method-on-a-device) (aka commands)
**Example publishing to digital twin PATCH topic:**
```sh
tedge mqtt pub 'az/twin/PATCH/properties/reported/?$rid=patch_temp' '{"hello":"world"}'
```
Should receive a response on a topic following the pattern of:
```
[az/twin/res/204/?$rid=patch_temp&$version=4]
``` …
> feat(az): extend supported topics on Azure IoT Hub bridge

- crates/core/tedge_agent/src/file_transfer_server/http_rest.rs
Disables flaky file transfer server test in tedge-agent which sometimes returns 404 when it's supposed to return 200.
<br/>
> Ignore flaky test_file_transfer_http_methods test

- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/extensions/aws_mapper_ext/src/converter.rs
- tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Aws mapper uses the `te` topics for measurements, events, and alarms.
Todo:
Health check messages
https://github.com/thin-edge/thin-edge.io/issues/2244
> Aws mapper using te topic for measurements

- tests/RobotFramework/tests/aws/aws_telemetry.robot
- tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot
Move aws mapper integration tests into a separate directory
<br/>
> move aws mapper tests into separate directory

- Cargo.lock
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/extensions/az_mapper_ext/Cargo.toml
- crates/extensions/az_mapper_ext/src/converter.rs
- crates/extensions/az_mapper_ext/src/error.rs
- tests/RobotFramework/tests/azure/azure_telemetry.robot
- tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-az.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
The Azure mapper is updated to support `te` topics for telemetry and publish them onto the `az/messages/events` topic.
**Todo in a follow-up task**
The `device-id, telemetry kind (measurement/event/alarm), and telemetry type`  that are part of the `te` topic have to be used to create `telemetry/child/parent` specific Azure topics and then push the messages on to those specific topics.
> Azure mapper using te topics for telemetry

- plugins/tedge_configuration_plugin/build.rs
- plugins/tedge_log_plugin/build.rs
Adding missing `build.rs` files which set the version based on the git semver version rather than the version included in the Cargo.toml file. This aligns the two newer/generic tedge-log-plugin and tedge-configuration-plugin with the existing components.
<br/>
> fix: add missing build.rs script to use the auto generated git based versioning

- crates/extensions/tedge_downloader_ext/src/tests.rs
In https://github.com/thin-edge/thin-edge.io/actions/runs/6482674100/job/17602646359, these tests failed, but the only information that we got back is that `response.is_ok()` is `false`. Removing this assertion means the test instead fails when we unwrap `response`, which means the test will fail with the underlying error object.
On a related note, I've removed the `Result` return type from the tests, as it wasn't being widely used and again hinders diagnosing failing tests (if you unwrap an error, you get the line number for the unwrap that caused the error, but if you return an error you don't)
<br/>
> Simplify tedge downloader tests to improve the debugging experience

- crates/core/tedge/src/cli/connect/command.rs
- tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Set `c8y-bridge.conf` file permissions to `644` to allow non-root users to read the contents of the file.
Task list:
https://github.com/thin-edge/thin-edge.io/issues/2154
> feat: allow non-root users to read c8y-bridge configuration file

- Cargo.lock
- crates/common/download/src/download.rs
- crates/common/tedge_utils/Cargo.toml
- crates/common/tedge_utils/src/file.rs
- crates/extensions/tedge_downloader_ext/Cargo.toml
- crates/extensions/tedge_downloader_ext/src/tests.rs
- crates/extensions/tedge_mqtt_ext/Cargo.toml
- crates/extensions/tedge_mqtt_ext/src/tests.rs
- crates/tests/mqtt_tests/src/test_mqtt_server.rs
- justfile
This makes a few test improvements. One of them concerns running the tests under `cargo-nextest`, which fails on some MQTT tests which spin up a server on a random port due to a conflict. The other two are changes to fix the tests on my machine, as they assume I have a group with the same name as my username, and assume a specific error messages for DNS errors (they expect `dns error: Failed to lookup address information`, but my machine gives the error `dns error: Device or resource busy`).
For simplicity, I've assumed there is always a group called `root`, but I think this a more reliable assumption than a group sharing a name with the current username.
<br/>
> Test improvements

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
* Set the python exec path for Robot framework language server
* Install nfpm packager
<br/>
> Updates to devcontainer definition

- crates/core/c8y_api/src/utils.rs
- crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
- crates/core/tedge_agent/src/agent.rs
- crates/core/tedge_api/src/health.rs
- crates/core/tedge_watchdog/src/error.rs
- crates/core/tedge_watchdog/src/systemd_watchdog.rs
- crates/extensions/c8y_log_manager/src/actor.rs
- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/tests/cumulocity/jwt/jwt_request.robot
This PR removes all remaining references to old `tedge/health` topic in C8y.
The old topics were updated to new ones but a default `te` topic root is used. Properly handling this will require more refactoring of the bridge code, so I decided to defer that for later.
Azure and AWS mappers are also outside of the scope of this PR, being a target of #2351.
Health checks will also be done in another PR, affecting #2308.
Closes #2349.
- #2349
> Remove old health topics from c8y mapper

- ci/build_scripts/version.sh
Improve SCM version detection when git describe does not return the last known tag and git distance. This situation happens when checking out PRs locally. Previously this resulted in using a version (e.g. `aee467a.aee467a.1~aee467a+aee467a`) that was incompatible with the linux packaging (namely with Debian).
The difference in behaviour is highlighted in the following `just info` commands:
**Before**
```
$ just info
OS:             macos
OS_FAMILY:      unix
HOST_ARCH:      aarch64
VERSION:        aee467a.aee467a.1~aee467a+aee467a
DEFAULT_TARGET: aarch64-unknown-linux-musl
```
**After**
```
$ just info
OS:             macos
OS_FAMILY:      unix
HOST_ARCH:      aarch64
VERSION:        0.12.1~445+g4757231
DEFAULT_TARGET: aarch64-unknown-linux-musl
```
<br/>
> build: use fallback version when git describe only returns a hash

- configuration/package_manifests/nfpm.tedge-agent.yaml
- configuration/package_scripts/_generated/tedge-agent/apk/postinst
- configuration/package_scripts/_generated/tedge-agent/deb/postinst
- configuration/package_scripts/_generated/tedge-agent/rpm/postinst
- configuration/package_scripts/tedge-agent/postinst
- tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Fix an issue discovered during development where updating the tedge-agent using the software management feature would cause the operation to be stuck in executing.
The root cause was the fact that when upgrading from version <=0.8.1, the prerm maintainer script would be executed unexpectidly due to the tedge_agent being listed as a conflict/breaks in the package definition. The prerm script would stop the tedge-agent service thus interrupting the apt package installation during an over the air update.
The only downside to removing the conflict/break fields from the tedge-agent package definition is that the `tedge_agent` deprecated package is that `tedge_agent` will still appear in the software install list as it is technically not replaced. The user can simply remove `tedge_agent` …
> fix: prevent tedge-agent service stoppage when upgrading from tedge_agent

- crates/core/tedge_watchdog/src/systemd_watchdog.rs
- crates/extensions/tedge_health_ext/Cargo.toml
- crates/extensions/tedge_health_ext/src/lib.rs
- crates/extensions/tedge_health_ext/src/tests.rs
- tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-aws.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
tedge-watchdog and other thin-edge services were updated to use new `te/.../cmd/health/check` topic for health check commands. All the mappers, including Azure and AWS, respond to new health checks on new health status topics, because they use `HealthMonitorActor`s, but these status messages are not sent to the cloud due to mappers themselves not yet being updated. Tests checking that health messages are converted should be added when working on #2351.
Test cases were added to ensure that changes to the watchdog, c8y mapper, and other services, did not impact AWS and Azure mappers negatively,
- #2308
> Health check on `te/.../cmd/health/check`

- crates/common/upload/src/error.rs
- crates/extensions/tedge_config_manager/src/actor.rs
- crates/extensions/tedge_config_manager/src/tests.rs
This PR fix ambiguous failure reason in `uploader` that directly affects `tedge-configuration-plugin` and `tedge-log-plugin`. Now example mentioned in #2366 will look like this:
```
Handling of operation failed with: Can't open a file "/etc/config1.json" No such file or directory (os error 2)    
```
#2366 
<br/>
> Fix ambiguous failure reason in uploader

- docs/src/references/mappers/c8y-mapper.md
- docs/src/references/mqtt-api.md
Fix the registration examples in the API docs to reflect the current implementation.
<br/>
> docs: fix registration examples

- docs/src/operate/c8y/config_management_plugin.md
- docs/src/operate/configuration/update_config_paths.md
- docs/src/operate/troubleshooting/monitor_tedge_health.md
- docs/src/operate/troubleshooting/thin_edge_logs.md
- docs/src/references/agent/restart-operation.md
- docs/src/references/agent/tedge-configuration-management.md
- docs/src/references/agent/tedge-log-management.md
- docs/src/references/domain-model.md
- docs/src/start/getting-started.md
- docs/src/understand/tedge-agent.md
- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Update documentation to address the following:
* Fix broken links (introduced in https://github.com/thin-edge/thin-edge.io/pull/2380 and https://github.com/thin-edge/thin-edge.io/pull/2235)
* Replace references to the deprecated c8y-configuration-plugin (as the tedge-configuration-plugin was mentioned in some of the broken links)
<br/>
> docs: fix broken links and references to tedge-configuration-plugin

- docs/src/contribute/design/mqtt-topic-design.md
- docs/src/references/mappers/c8y-mapper.md
- docs/src/references/mqtt-api.md
Remove the propsoal banners in the documentation in preparation to the 0.13.0 release. The proposals have now been implemented.
<br/>
> docs: remove the proposal banners

- docs/src/operate/troubleshooting/monitor_tedge_health.md
- docs/src/references/mappers/c8y-mapper.md
- docs/src/references/mqtt-api.md
Some mistakes slipped through the previous docs PR.
- #2348
> docs: fix some docs mistakes introduced by #2375

- docs/src/references/agent/tedge-configuration-management.md
> docs: fix typo in tedge-configuration-management

- crates/common/tedge_config/src/tedge_config_cli/models/auto.rs
- crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/tedge/src/cli/connect/bridge_config.rs
- crates/core/tedge/src/cli/connect/bridge_config_aws.rs
- crates/core/tedge/src/cli/connect/bridge_config_azure.rs
- crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
- crates/core/tedge/src/cli/connect/command.rs
- tests/RobotFramework/tests/cumulocity/bridge_config/local_cleansession.robot
Add a new `tedge config` setting .
`c8y.include.local_cleansession` can be set either to `true`,  `false` or `auto`:
https://github.com/thin-edge/thin-edge.io/issues/2184
> Add a BridgeConfig field to include or not local_cleansession

- .github/workflows/integration-tests.yml
- tests/RobotFramework/tasks.py
- tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
Skip the benchmarking system tests by default due to the unpredictable performance of the CI runner resulting in sporadic test failures.
The benchmarking should be performed on a device with dedicated resources to ensure predictable results.
Note: The robot framework keywords had to be changed from `Test Tags` to `Force Tags` in order to correctly add the given tags to each test in the suite, though there is an open PR to change this in the future of robot framework https://github.com/robotframework/robotframework/issues/4365
<br/>
> tests: skip benchmarking tests by default

- ci/build_scripts/version.sh
Fix a build issue where the version generation when on a tag.
**Before**
```
0.13.1~0.13.0+0.13.0
```
**After**
```
0.13.0
```
<br/>
> build: fix generated version on a tag

- crates/core/c8y_api/src/http_proxy.rs
- crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/cli/connect/jwt_token.rs
Use qos 0 (Atmostonce) while requesting the jwt token from Cumulocity over MQTT.
* https://github.com/thin-edge/thin-edge.io/issues/2417
* https://github.com/thin-edge/thin-edge.io/issues/2412
> use qos 0 when publishing to c8y/s/uat to request a Cumulocity IoT token

- docs/src/contribute/design/mqtt-topic-design.md
Fix small documentation typo where a "pub" command is used instead of "sub"
<br/>
> docs: fix incorrect mqtt sub command

- crates/core/tedge_agent/src/restart_manager/actor.rs
Use proper error messages when the tedge-agent fails to access the state file.
https://github.com/thin-edge/thin-edge.io/issues/2413
> misleading log entry when state file does not exist in tedge-agent

- crates/extensions/tedge_log_manager/src/actor.rs
tedge-log-manager previously marked `log_upload` operation as successful without waiting for the actual HTTP file upload operation to finish successfully. This lead to race conditions where after marking the operation as successful the actual logfile may not yet be available, or to bugs where the operation is marked as successful but the upload could not be completed.
Now tedge-log-manager actor waits for the upload to be successful to mark the operation as successful.
#2414
I thought about adding a test, but I don't quite know how to go about it. The scope seems very limited and I don't know if it's even possible to write that test in such a way that it's not flaky. Suggestions welcome.
> tedge-log-manager: wait for upload before marking operation successful

- crates/core/c8y_api/src/smartrest/operations.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- docs/src/operate/c8y/supported_operations.md
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/c8y_RelayArray
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/operation_relay_array.robot
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/set_relay.sh
Support custom operation option to set the expected formatting of the results returned by the custom operation so that the result can be handled correctly when building the SmartRest message output send via the Cumuocity IoT [503](https://cumulocity.com/guides/reference/smartrest-two/#set-operation-to-successful-503) message.
Available options are:
```toml
result_format = "text"
result_format = "csv"
```
**Example: c8y_RelayArray operation**
```to l
[exec]
topic = "c8y/s/ds"
on_message = "519"
result_format = "csv"
command = "/etc/tedge/operations/set_relay.sh"
timeout = 10
```
Tasks
https://github.com/thin-edge/thin-edge.io/issues/2438
> custom operation option to disable quoting of results to enable c8y_RelayArray compatibility

- Cargo.lock
- crates/core/tedge_agent/src/restart_manager/actor.rs
- crates/core/tedge_agent/src/state_repository/error.rs
- crates/core/tedge_agent/src/state_repository/state.rs
- crates/extensions/c8y_http_proxy/Cargo.toml
- crates/extensions/c8y_http_proxy/src/actor.rs
- crates/extensions/c8y_http_proxy/src/messages.rs
While working on #2391, I found details in some of the error messages lacking, so I changed them and included in a separate PR.
<br/>
> Improve error messages for c8y-http-proxy and tedge-agent

- crates/extensions/tedge_script_ext/src/lib.rs
As no stdin content is provided to the scripts, their stdin has to be closed.
<br/>
> Close stdin of child processes

- .github/workflows/pull-request-checks.yml
- .taplo.toml
- Cargo.toml
- crates/common/download/Cargo.toml
- crates/common/tedge_config_macros/Cargo.toml
- crates/common/tedge_config_macros/macro/Cargo.toml
- crates/core/c8y_api/Cargo.toml
- crates/core/tedge/Cargo.toml
- crates/core/tedge_actors/Cargo.toml
- crates/extensions/aws_mapper_ext/Cargo.toml
- crates/extensions/az_mapper_ext/Cargo.toml
- crates/extensions/c8y_auth_proxy/Cargo.toml
- crates/extensions/c8y_http_proxy/Cargo.toml
- crates/extensions/c8y_mapper_ext/Cargo.toml
- crates/extensions/collectd_ext/Cargo.toml
- justfile
- plugins/tedge_apt_plugin/Cargo.toml
cargo-sort was replaced by [taplo](https://taplo.tamasfe.dev/), which besides sorting dependencies, can also perform TOML reformatting.
New rules for formatting Cargo.toml files are:
- indent 4 spaces
- only split into multiple lines if content doesn't fit in a single line
- reorder only dependencies
<br/>
> fix: use taplo for formatting Cargo.toml

- crates/core/tedge/src/cli/certificate/cli.rs
- crates/core/tedge/src/cli/certificate/create.rs
- crates/core/tedge/src/cli/certificate/error.rs
- crates/core/tedge/src/cli/certificate/mod.rs
- crates/core/tedge/src/cli/certificate/remove.rs
- crates/core/tedge/src/cli/certificate/renew.rs
- tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
- tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
`tedge` command to `renew` the certificate.
```
sudo tedge cert renew
```
https://github.com/thin-edge/thin-edge.io/issues/2489
> New tedge cli command to renew current self-signed certificate

- Cargo.lock
- crates/core/tedge_write/Cargo.toml
- crates/core/tedge_write/src/api.rs
- crates/core/tedge_write/tests/main.rs
`sudo` should only be used in tedge-write if it's both installed and enabled via `enable.sudo`
- #2523
> tedge-write: use sudo only if installed

- crates/core/tedge_api/src/messages.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/inventory.rs
- crates/extensions/c8y_mapper_ext/src/operations/firmware_update.rs
This PR replaces current mechanism that send firmware info with the device twin feature. On succesful firmware update, the firmware info is send to `te/<identifier>/twin/firmware` that is later on converted into `c8y/inventory/managedObjects/update/<external-id>` on mapper output. Current mechanism around `FirmwareMetadata` is removed. More specs in #2497.
* #2497 
<br/>
> Send firmware info with device twin message

- .github/workflows/ci_pipeline.yml
Fix #2534 
Ensured that yml has no longer error by https://github.com/rina23q/thin-edge.io/actions/runs/7273907768
<br/>
> Fix wrong layer of fail-fast

- docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
- docs/src/extend/firmware-management/building-image/yocto/tutorial.md
- docs/src/overview.md
Fix broken links in the documentation
[<br/>](https://github.com/thin-edge/thin-edge.io/actions/runs/7278306476/job/19832194014)
> Fix broken links

- Cargo.lock
- Cargo.toml
Preparing for the 1.0.0 Release Candidate, `1.0.0-rc.1`
The release was prepared by running:
```
cargo release 1.0.0-rc.1 --no-publish --no-push --no-tag -vv --no-confirm --execute
```
<br/>
> (cargo release) bump version

- ci/build_scripts/version.sh
- configuration/package_manifests/virtual/nfpm.tedge-full.yaml
- configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
- justfile
Fix a bug with package dependencies when referencing other packages in the virtual package definition do not match the debian version syntax.
The problem is caused when tags are formatted as `1.0.0-rc.1`.
<br/>
> fix: linux package release candidate compatibility

- ci/installation_scripts/install_for_amd64.sh
- ci/installation_scripts/install_for_arm.sh
- tests/RobotFramework/tasks/build_install_rpi.robot
- tests/RobotFramework/tests/installation/install_tedge.robot
- tests/RobotFramework/tests/plugin_apt/filter_packages_list_output.robot
- tests/RobotFramework/tests/tedge/call_tedge.robot
Fix errors building main from the tests attempting to install 1.x
<br/>
> Remove reference to version in installation scripts

- docs/src/contribute/DEBIAN_PACKAGE_HOSTING.md
- docs/src/operate/c8y/config_management_plugin.md
- docs/src/operate/c8y/tedge_log_management.md
- docs/src/operate/configuration/update_config_paths.md
- docs/src/references/domain-model.md
- docs/src/start/getting-started.md
- docs/src/understand/tedge-agent.md
Remove references to the deprecated tedge-log-plugin and tedge-configuration-plugins. The functionality is now provided by the `tedge-agent`.
* https://github.com/thin-edge/thin-edge.io/issues/2551
* https://github.com/thin-edge/thin-edge.io/issues/2503
> docs: remove tedge-log-plugin and tedge-configuration-plugin references

- docs/src/operate/c8y/smartrest_templates.md
Add instructions to reconnect to c8y after changing Cumulocity IoT SmartREST settings so that thin-edge.io will make use of the new changes to the custom templates.
<br/>
> docs: add instructions to reconnect with c8y after changing settings

- docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
Update MacOS troubleshooting instructions when building rugpi images.
<br/>
> docs: update MacOS instructions for building rugpi images

- .github/CODEOWNERS
Add GitHub CODEOWNERS definition to formally communicate responsibilities when changing different files/folders in the repository.
See the [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more information about the syntax.
https://github.com/thin-edge/thin-edge.io/issues/1391
> dev: add CODEOWNERS definition

- .github/workflows/integration-tests.yml
- .github/workflows/pull-request-checks.yml
- tests/RobotFramework/devdata/env.template
- tests/RobotFramework/resources/common.resource
Enable Github merge queue for merging PRs into main.
References to the `C8Y_TENANT` environment variable was also removed as it was unused (and would have required adding it to the new "Test Auto" workflow environment).
https://github.com/thin-edge/thin-edge.io/issues/2569
> ci: enable merge queue

- .github/workflows/pull-request-checks.yml
PR check workflow improvements to be compatible when running in the merge queue.
Some checks don't make sense under the merge queue, and other items can't run due to some issues, [failed run example](https://github.com/thin-edge/thin-edge.io/actions/runs/7459996940).
https://github.com/thin-edge/thin-edge.io/issues/2569
> ci: fix incompatible PR checks from merge queue trigger

- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs
- crates/core/tedge_agent/src/agent.rs
- crates/core/tedge_write/src/lib.rs
- plugins/tedge_configuration_plugin/src/lib.rs
This PR renames configuration `enable.sudo` to `sudo.enable` to be consistent with other configurations that uses `enable`.
* #2566
> Rename configuration `enable.sudo` to `sudo.enable`

- tests/RobotFramework/README.md
- tests/RobotFramework/requirements/requirements.adapter-docker.txt
- tests/RobotFramework/requirements/requirements.adapter-local.txt
- tests/RobotFramework/requirements/requirements.adapter-ssh.txt
- tests/RobotFramework/requirements/requirements.txt
Update system test dependencies:
* Use latest official robotframework version (version 7 is already in the release candidate phase).
* Update other dependencies (no major updates)
* Bump is minimum required python version to 3.8 as robotframework v7 will required 3.8 (so this is preemptive)
<br/>
> chore: update system test dependencies

- Cargo.lock
- Cargo.toml
Upgrade tempfile dependency to update the underlying rustix version to resolve https://github.com/thin-edge/thin-edge.io/security/dependabot/15
https://github.com/thin-edge/thin-edge.io/security/dependabot/15
> chore: upgrade tempfile to resolve dependentabot alert about rustix

- tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
Fix flaky system test as the collectd mapper batches the collectd messages based on time windows, which results in the previous assertion failing sporadically as more than 1 measurement would be found.
Adding filtering on the `Should Have MQTT Messages` avoids this problem.
Problem was discovered during this CI run:
* https://github.com/thin-edge/thin-edge.io/actions/runs/7474067067/job/20339748558
> test: filter MQTT message to avoid false negatives when thin-edge.io splits measurements

- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
Add examples to:
* `mqtt.topic_root`
* `mqtt.device_topic_id`
https://github.com/thin-edge/thin-edge.io/issues/2462
> Add examples to `tedge config list --doc`

- docs/src/operate/telemetry/data-model.md
- docs/src/references/agent/index.md
- docs/src/references/init-system-config.md
- docs/src/references/mappers/index.md
- docs/src/references/mappers/mqtt-topics.md
- docs/src/references/mqtt-api.md
- docs/src/references/supported-platforms.md
- docs/src/references/thin-edge-config-files.md
- docs/src/start/connect-aws.md
- docs/src/start/connect-azure.md
- docs/src/start/connect-c8y.md
- docs/src/start/device-monitoring.md
- docs/src/understand/tedge-mapper.md
- Move under reference/mappers the page MQTT-topics (as only related to the mappers)
- Re-order the reference sub-sections.
<br/>
> Improve doc TOC

- Cargo.toml
Configuration to strip symbols in debug build was committed erroneously. This PR re-enables default configuration for debug profile.
<br/>
> reenable default settings for dbg profile

- .github/workflows/pull-request-checks.yml
- docs/src/contribute/INSTALLING_DOCKER.md
- docs/src/references/agent/device-management-api.md
- docs/src/references/agent/running-tedge-agent.md
- docs/src/references/agent/software-management.md
- docs/src/references/mappers/mqtt-topics.md
- docs/src/references/tedge-file-transfer-service.md
- docs/src/start/connect-aws.md
- docs/src/start/connect-azure.md
* Prepare markdown docs to be compatible with MDX v3 to enable an upgrade of the doc engine (docusaurus, from v2 to v3).
* Include PR check task to validate the docs to avoid publishing invalid markdown docs which will prevent the docs from being published
* Fix broken anchors (as docusaurus v3 can validate broken anchors in addition to broken links)
**Notes**
The docusaurus website has details about [differences and how to upgrade](https://docusaurus.io/docs/migration/v3)
<br/>
> docs: make markdown compatible with mdx v3

- Cargo.lock
Fix vulnerability notification https://github.com/thin-edge/thin-edge.io/security/dependabot/16
* https://github.com/thin-edge/thin-edge.io/security/dependabot/16
* https://github.com/thin-edge/thin-edge.io/issues/2601
> fix: update h2 dependency

- tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
Fixing a bug in the test which resulted in the wrong operation being used when simulating the operation updates coming from a child device.
Root cause was the fact that the wrong mqtt message was sometimes being matched when using a relative time interval in the second operation, which sometimes returns results from the first firmware operation sent.
Fix was to be more specific about the timespan to look for the MQTT messages.
System test failure was observed in the following CI test run:
* https://github.com/thin-edge/thin-edge.io/actions/runs/7654472811
> test: fix flaky firmware update test on child devices

- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tasks.py
Minor improvements to reduce some noise within the system test logs (whilst running the logs and the report output).
* update robotframework-c8y lib to latest version which removes some unnecessary warning log entries
* silency docker network creation
* Update pabot dependency which fixes the following deprecation notices:
```
/Users/reubenmiller/dev/projects/tedge/tmp/thin-edge.io/tests/RobotFramework/.venv/lib/python3.11/site-packages/robot/utils/argumentparser.py:80: UserWarning: ArgumentParser option 'auto_pythonpath' is deprecated since Robot Framework 5.0.
warnings.warn("ArgumentParser option 'auto_pythonpath' is deprecated "
/Users/reubenmiller/dev/projects/tedge/tmp/thin-edge.io/tests/RobotFramework/.venv/lib/python3.11/site-packages/robot/running/builder/builders.py:112: …
```
> test: minor improvements to reduce log noise in system tests

- docs/src/start/getting-started.md
> Fixed typo in getting-started.md

- docs/src/contribute/DEBIAN_PACKAGE_HOSTING.md
- docs/src/operate/monitoring/enable_tedge_watchdog_using_systemd.md
- docs/src/operate/troubleshooting/thin_edge_logs.md
Unlisting the tedge-watchdog docs so they will not be listed/index in the productions docs (though the link will still be accessible)
Decision was made due to problems highlight in the following issue:
* https://github.com/thin-edge/thin-edge.io/issues/2354
In short, the instructions and develoment which lead to the settings being lost on thin-edge.io updates which leads to the watchdog no longer being active. However since tedge-watchdog is not widely used (as these problems have been around for a while), it will be better to not encourage people to use it for now.
<br/>
> docs: unlist tedge-watchdog documentation

- tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
Collect logs from both the parent and child when running the child log file operation system test. Having both logs helps debug any errors that may occur.
<br/>
> test: collect both parent and child logs on test teardown for child log file operation

- .github/workflows/cloudsmith-cleanup.yml
- ci/admin/cloudsmith_admin.sh
Cloudsmith tedge-main* repo cleanup workflow to remove older non-official packages older than 60 days.
The cleanup will avoid exceeding the cloudsmith limits and remove older packages which were build from the main branch (so are superseded by the next merge into main, but still allowing some "lookback"). More advanced strategies of "keep last N versions" could be assessed in the future.
<br/>
> ci: add cloudsmith cleanup job to remove old packages

- tests/RobotFramework/bin/setup.sh
Fix minor mistake with the output redirection in the system test setup script. It has no impact on the running of the script however it was errenously printing out unexpected messages to the user.
<br/>
> test: fix redirection syntax error in setup

- ci/admin/cloudsmith_admin.sh
Fix annoyance with a Github typo false positive.
<br/>
> dev: avoid github typo false positive by using another version example

- README.md
Fix integration-test badge shown in the README.md to show the status from the merge queue event, otherwise it was showing incorrectly as failed.
For example, the current status shows as failed eventhough the merge queue passed.
After the change the badge should be green:
[![integration-tests](https://github.com/thin-edge/thin-edge.io/actions/workflows/integration-tests.yml/badge.svg?event=merge_group)](https://github.com/thin-edge/thin-edge.io/actions/workflows/integration-tests.yml)
<br/>
> docs: fix integration-tests badge by linking to merge queue event

- README.md
Replace twitter with linkedin links as the twitter handle is no longer used.
<br/>
> docs: replace twitter with linkedin

- docs/src/start/getting-started.md
Fix a formatting issue on step 6 of the getting started section.
**Before**
**After**
<br/>
> docs: fix step6 list rendering error due to erroneous formatting

- docs/src/operate/troubleshooting/testing-cloud-connection.md
Add details about how the aws MQTT connection is tested, so the instructions are consistent with the other supported cloud connections.
https://github.com/thin-edge/thin-edge.io/issues/2641
> docs(aws): add aws connection test details

- tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
Fix device_registration test teardown to include the log collection at the end of the test
<br/>
> Fix device_registration test teardown

- docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
Fixing some minor typos and grammar on the rugpi image build instructions.
<br/>
> docs: fix typos and grammar on rugpi image build instructions

- ci/build_scripts/build.sh
- ci/build_scripts/package.sh
Preparation for future work to make it easier to reuse the same build scripts to build the linux packages from binaries produced by other tools (such as clang instead of cargo-zigbuild). The changes should not have any effect on the current build process.
The following improvements were made:
* don't install zigbuild when using the --skip-build option (previously zigbuild was installed even when not building the Rust binaries)
* option to skip building the test packages
* option to skip building deprecated packages
<br/>
> build: support build/packaging using other tooling

- .github/workflows/build-workflow.yml
* Avoid building twice by removing the main branch trigger. The merge queue already builds, tests and publishes the packages.
* Don't publish build artifacts to cloudsmith when triggered from by a PR event (e.g. only publish on merge_queue and tagging)
Related to work done in https://github.com/thin-edge/thin-edge.io/pull/2699
> ci: don't build on main as merge_group already builds/publishes

- README.md
Removing the integration-tests workflow badge from the README as the workflow has been merged into the build-workflow (see https://github.com/thin-edge/thin-edge.io/pull/2699)
> docs: remove integration test badge

- .github/workflows/build-workflow.yml
Fix incorrect workflow event_name filter, where `pull_request` was used instead of `pull_request_target`.
This is the reason why the RobotFramework report is not being published to PRs.
<br/>
> ci: correct pull request event name

- .github/workflows/build-workflow.yml
Fix ci checkout action when triggered from a PR. Previously the build was being trigger from the merge destination instead of the source (due to the usage of the pull_request_target).
A conditional checkout ref has been added to the jobs which run under under the PR.
<br/>
> ci: fix checkout reference when on a PR

- .github/workflows/build-workflow.yml
- ci/admin/cloudsmith_admin.sh
- ci/build_scripts/build.sh
- ci/build_scripts/version.sh
Add step to promote the cloudsmith artifacts from the `tedge-main*` repo to the `tedge-release*` repo.
To enable this the following changes were required:
* Support setting the `git describe` input version via a flag (this enable users to check what the equivalent package versions are for a given "tag" or intermediate git describe value).
> ci: promote cloudsmith artifacts on tags

- crates/core/c8y_api/src/utils.rs
- crates/core/tedge_mapper/src/c8y/mapper.rs
- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
- tests/RobotFramework/tasks/debug.robot
- tests/RobotFramework/tests/cumulocity/bootstrap.robot
- tests/images/debian-systemd/files/bootstrap.sh
The bug was caused by sending messages to `c8y/s/us` topic before the c8y-bridge connection is even established, resulting in those messages getting lost. With this fix we make sure that the mapper does not start mapping or even send any init messages to the cloud until the bridge connection is established.
https://github.com/thin-edge/thin-edge.io/issues/2689
> Fix missing supported operations #2689

- .github/workflows/release.yml
Rename the workflow used to bump the Rust version to "release" as this is the start of the release process.
For context, the release process follows:
1. Manually trigger release.yml (which creates a PR)
2. Approve/merge PR, this will merge into the main branch
3. autotag.yml will check if a tag exists for the Cargo.toml version, and create the tag
4. buildworkflow.yaml will trigger on tagging and create a Github Release
> ci: rename version bump workflow to release

- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
The memory allocation logging was introduced in https://github.com/thin-edge/thin-edge.io/pull/2693, however it was overlooked that the logging was enabled by default.
To avoid spamming the logs on devices, the interval was changed to 0 which disables the logging. Users can activate the logging via the tedge configuration, though it is more meant for troubleshooting deep dives rather than the causual user.
<br/>
> fix: disable memory logging by default to avoid log spamming

- .github/workflows/build-workflow.yml
- .github/workflows/gh-pages.yml
Avoid deprecation warnings about nodejs due to the `extractions/setup-just@v1` action.
Instead, use the `taiki-e/install-action@just` action which is also referenced from [just README](https://github.com/casey/just?tab=readme-ov-file#github-actions). `taiki-e/install-action` seems to be more actively maintained anyway and it can be used to also install other common Rust tooling.
[Example](https://github.com/thin-edge/thin-edge.io/actions/runs/7901731131) deprecation warning from a workflow
**note**
* Using `sudo snap install --edge --classic just` in the workflow was not an option as the [version in the snapstore](https://snapcraft.io/just) is very old, from 2022.
Example run showing the nodejs 16.x deprecation warning:
* https://github.com/thin-edge/thin-edge.io/actions/runs/7901731131
> ci: switch gha to install just to avoid nodejs 16 deprecation warnings

- Cargo.lock
- Cargo.toml
> patch version bump

- .github/workflows/autotag.yml
- .github/workflows/build-workflow.yml
Fixing a few minor problems with the release process.
* Fix typo in the autotag workflow which caused the tag detection to fail
* Ensure publish workflow is run even when testing is skipped
<br/>
> ci: release process fixes after first run

- .github/workflows/autotag.yml
Fix small shell mistake which prevented the autotag from detecting if a tag already exists or not.
The error was spotted by running shellcheck on it and it raised the problem about the missing quotes, https://www.shellcheck.net/wiki/SC2046
<br/>
> ci: add missing quotes which prevented git tag detection

- .github/workflows/autotag.yml
Set git username and email before creating the tag.
<br/>
> ci: add git user name and email before creating tag

- .github/workflows/autotag.yml
Avoid permission denied error by using a PAT in checkout and followup git actions (a test run found that a `You're not authorized to create a tag` errors occurs when using the default token).
Note: the if statement was moved to the job level to avoid useless checkouts (and accessing the ACTIONS_PATH secret that probably won't exist on forks).
<br/>
> ci: use PAT when creating tag

- .github/workflows/build-workflow.yml
Correct the conditional publish job to use `always()` to avoid being skipped if its predecessor is skipped.
<br/>
> ci: correct conditional publishing logic which resulted in job being skipped

- .github/workflows/build-workflow.yml
Continuing address release workflow problems due to conditional jobs.
<br/>
> ci: fix job conditionals on publish and publish-containers

- .github/workflows/build-workflow.yml
Ensure release job is run on tagging by using `always()` (this should be the last conditional job-run problem)
**Note** The whole reason for requiring `always()` on jobs which are downstream from a skipped job is tracked by an open issue on github, https://github.com/actions/runner/issues/2205
<br/>
> ci: correct release conditional problem due to upstream skipping

- ci/admin/cloudsmith_admin.sh
An oversight (and inconsistency on the cloudsmith-api) where `--yes` is not supported on all commands. The release task was failing to promote cloudsmith packages to the `tedge-release*` repositories due to usage of an unsupported flag, `--yes`, on the `cloudsmith copy` command.
An additional fix/improvement was made to speed up the promotion by not waiting for the sync to complete before promoting the next package to limit the period of time where a package is "half promoted" (as cloudsmith does not have a bulk copy api)
<br/>
> ci: remove unsupported cloudsmith flag on promotion task

- crates/core/plugin_sm/src/plugin_manager.rs
- crates/core/tedge_agent/src/software_manager/actor.rs
- crates/core/tedge_agent/src/software_manager/tests.rs
- crates/core/tedge_agent/src/tedge_operation_converter/actor.rs
- crates/core/tedge_agent/src/tedge_operation_converter/tests.rs
- crates/core/tedge_api/src/messages.rs
- crates/core/tedge_api/src/workflow/mod.rs
- crates/core/tedge_api/src/workflow/supervisor.rs
- tests/RobotFramework/tests/cumulocity/software_management/software-update-child.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
Currently, `tedge-agent` ignores to include its supported software types in `software_list` and `software_update` capabilities messages, although it's clearly documented [here](https://thin-edge.github.io/thin-edge.io/references/agent/software-management/#operation-registration).
This PR changes to include `types` in these operation registration messages as below.
```
[te/device/main///cmd/software_list] {"types":["apt","dummy"]}
[te/device/main///cmd/software_update] {"types":["apt","dummy"]}
```
It is the first step to support advanced software management in c8y as the feature requires supported software types declaration.
#2654
> tedge-agent publishes "types" for software_list and software_update

- crates/common/mqtt_channel/src/tests.rs
Simply add the test proposed by https://github.com/thin-edge/thin-edge.io/issues/824
With the previous versions of rumqttd it was not feasible for a test to check that a retained message is properly cleared. This has been fixed.
https://github.com/thin-edge/thin-edge.io/issues/824
> Test clearing retained messages

- docs/src/understand/tedge-mapper.md
Removing a section in the mapper concept page about the "tedge-mapper" specific topics which was an incomplete list of topics, and generally does not provide much value to the user.
The MQTT topics for each mapper are already covered in the following reference guide:
* https://thin-edge.github.io/thin-edge.io/references/mappers/mqtt-topics/
https://github.com/thin-edge/thin-edge.io/issues/1749
> docs(mapper): remove out of date and unused section

- crates/core/tedge/src/cli/init.rs
The [chown](https://linux.die.net/man/1/chown) `--no-dereference` option is a GNU specific option name for the more common shorthand `-h` option.
Switching to using the `-h` (which is functionaly the same) improves compatibility to other environments such as busybox and bsd.
References
* [freebsd chown](https://man.freebsd.org/cgi/man.cgi?chown(8))
<br/>
> feat(cli): use chown -h option for improved compatibility in busybox/bsd environments

- crates/common/tedge_utils/src/file.rs
Use [std::os::unix::fs::MetadataExt](https://doc.rust-lang.org/std/os/unix/fs/trait.MetadataExt.html) over `std::os::linux::fs::MetadataExt` to improve compatibility for unix targets.
<br/>
> refactor: use unix::fs::MetadataExt over linux variant to improve unix compatibility

- crates/common/download/src/download.rs
The `as_raw_fd` method is only used when building for a linux target_os, therefore the corresponding import should only be used in the same context:
```rust
// Reserve diskspace
#[cfg(target_os = "linux")]
let _ = fallocate(
file.as_raw_fd(),
FallocateFlags::empty(),
0,
file_len.try_into().expect("file too large to fit in i64"),
);
```
<br/>
> fix(build): only import `AsRawFd` trait when used under linux target

- crates/core/tedge_agent/src/file_transfer_server/http_rest.rs
Improve cross platform support by improving the "is a directory" check as the current implementation only supported linux targets.
<br/>
> feat(fts): improve is a directory error detection to support other OS targets

- crates/core/tedge/src/cli/init.rs
- tests/RobotFramework/tests/customizing/tedge_init.robot
Set folder ownership to the given user/group rather than using the fixed `root` ownership. This improves compatibility with other unix systems which may not have a `root` group (e.g. MacOS). It also allows users to install thin-edge.io as a non-root user (if they specify the --config-dir to use a folder owned by them).
<br/>
> feat(cli): set directory ownership using given user/group instead of root

- crates/extensions/c8y_mapper_ext/src/tests.rs
Use posix shell, `sh`, in tests which slighlty improves the cross platform compatibility (e.g. between Linux and MacOS).
One of the common problems that can occur is if the locale is not correctly configured in bash (which is unfornately the default MacOS settings), then a warning is printed on stderr when the script is launched. This affects the script output assertion causing it to fail. Using posix shell does not have the same problem.
Notes on bash to posix shell conversion:
* Use `seq N M` over `{N..M}` as the later is bash specific syntax
* Use short form of signal names, e.g. `TERM` instead of `SIGTERM` as the later is not supported by posix shell (though it has the same function)
<br/>
> tests: use posix shell over bash for improved cross platform compatibility

- docs/src/extend/firmware-management/building-image/yocto/tutorial.md
Add missing build dependency for Yocto as it was discovered that a ubuntu minimal image does not have the `file` package installed.
<br/>
> docs(yocto): add missing build dependency `file`

- ci/build_scripts/build.sh
- ci/build_scripts/package.sh
- ci/build_scripts/publish_packages.sh
- crates/common/logged_command/src/logged_command.rs
- crates/common/tedge_utils/src/file.rs
- crates/common/tedge_utils/src/notify.rs
- crates/extensions/tedge_file_system_ext/src/lib.rs
- plugins/tedge_apt_plugin/src/lib.rs
Support developing thin-edge.io on MacOS to ease development. It does not yet included any CI workflow to build and run the tests, this will be done in a follow up PR due it requiring larger changes in the workflow setup.
It is not expected to be able to run a full thin-edge.io instance, however it is possible to run the tests and locally debug the process natively on MacOS.
Most of the changes are related to differences in the OS in the Rust tests, the most notable differences are:
* notify events are different between Linux and MacOS (e.g. Linux will published a `EventKind::Modify` event on new file creation, where as MacOS will use `EventKind::Create`). As a result some tests have been marked as skipped for now.
* MacOS does not have a group called `root`, but instead `staff` can be …
> feat: compile on macos

- docs/src/operate/registration/deregister.md
- docs/src/operate/registration/index.md
Document commands to de-register entities.
https://github.com/thin-edge/thin-edge.io/issues/2700
> docs: Document commands to de-register entities #2700

- ci/build_scripts/package.sh
Due to a build bug instruced by [#2741](https://github.com/thin-edge/thin-edge.io/pull/2741), no virtual packages were being built or published to cloudsmith. This resulted in the install script failing as there was a mismatch in between the last published virtual package and the newer published tedge packages (non-virtual packages).
The following improvements were made:
* Add missing target case `all` which is used when building the virtual packages (this is the part was the root cause)
* Fail the build (e.g. non zero exit code) if no virtual packages are created - this should at least avoid future silent errors when no virtual packages are produced.
* https://github.com/thin-edge/thin-edge.io/pull/2741
* https://github.com/thin-edge/thin-edge.io/issues/2776
> build: fix building of virtual packages

- .gitignore
- kubernetes/README.md
- kubernetes/tedge/.helmignore
- kubernetes/tedge/Chart.yaml
- kubernetes/tedge/templates/_helpers.tpl
- kubernetes/tedge/templates/mosquitto-config.yaml
- kubernetes/tedge/templates/mosquitto.yaml
- kubernetes/tedge/templates/tedge-agent.yaml
- kubernetes/tedge/templates/tedge-pv.yaml
- kubernetes/tedge/templates/tests/test-connection.yaml
- kubernetes/tedge/values.yaml
A draft helm chart for deploying thin-edge.io in kubernetes.
This PR is not a full polished feature however it is a great step forward to supporting an official helm chart in the future. Hopefully this will also encourage people to contribute to make future improvements on the helm chart.
<br/>
> feat(containers): Draft Kubernetes deployment of tedge

- crates/core/tedge/src/cli/connect/command.rs
Remove a debug print statement introduced by https://github.com/thin-edge/thin-edge.io/pull/2716.
The unexpected debug print statements were noticed when running `tedge connect|reconnect c8y`:
```sh
$ sudo tedge reconnect c8y
Restarting mosquitto service.
[crates/core/tedge/src/cli/connect/command.rs:546] path.as_ref() = "/etc/tedge/device-certs/tedge-certificate.pem"
[crates/core/tedge/src/cli/connect/command.rs:546] path.as_ref() = "/etc/tedge/device-certs/tedge-private-key.pem"
Awaiting mosquitto to start. This may take up to 5 seconds.
```
<br/>
> fix: remove debug print statement

- crates/extensions/tedge_mqtt_bridge/src/lib.rs
Fix a typo in the Rust doc
<br/>
> style: fix Rust doc typo

- tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
Covers:
https://github.com/thin-edge/thin-edge.io/pull/2755
https://github.com/thin-edge/thin-edge.io/pull/2768
> Add deregister test steps to register testcase

- crates/core/tedge_actors/src/servers/mod.rs
Fix unused imports that has been unnoticed because the CI run `cargo clippy --all-features`.
<br/>
> refactor: fix unused imports (was used only by test-helpers)

- tests/RobotFramework/tasks.py
Fix subtle bug in the script used to build the test container, where the incorrect target would be selected if the user has previously built gnu and musl variants on their machine.
The change forces the "detect_target" to explicitly use the musl variants to prevent pulling in unexpected build artifacts. User's can still set an explicit target if they want to build gnu targets.
<br/>
> tests: explicitly select musl builds when building test container

- docs/src/references/mqtt-api.md
Update examples showing how to request a health check from services to avoid using retained messages (as per our own [guidelines](https://github.com/reubenmiller/thin-edge.io/blob/926169fcf908a2574825bfa5541a6931545ccfcf/docs/src/references/agent/device-management-api.md#L225)).
> Health checks is a notable exception to the rule "command status are published as retained messages". A health check is sent to the channel cmd/health/check of a service (or a device) as a non-retained request {}, triggering a health message response published on the status/health channel of the same service (or respectively the channels of all the service running on that device).
<br/>
> docs: remove retain from cmd/health/check examples

- tests/RobotFramework/requirements/requirements.dev.txt
Resolved security alert about a test-only dependency. https://github.com/thin-edge/thin-edge.io/security/dependabot/18. This has no effect on thin-edge.io itself, as black is only used by devs to format the test code which is written in python.
https://github.com/thin-edge/thin-edge.io/security/dependabot/18
> test(dev): update black version CVE-2024-21503

- .github/workflows/build-workflow.yml
Temporary workaround due to an invalid InRelease file published to the microsoft debian repository used by ubuntu 22.04 (see https://github.com/microsoft/linux-package-repositories/issues/130). This error stops the build job from running successfully as the `apt-get update` returns an error.
The temporary workaround is detailed [here](https://github.com/microsoft/linux-package-repositories/issues/130#issuecomment-2074645171)
The workaround can be removed once the linked ticket has been resolved.
<br/>
> ci: remove microsoft debian repo due to invalid repo

- crates/core/tedge_watchdog/src/systemd_watchdog.rs
Cap tedge-watchdog interval in which we expect to receive health check response to a minimum of 1s.
I also had questions of "why is the interval one-fourth of what we read from `WatchdogSec`?", so decided to make it a constant and document it a little more clearly. Found that this ratio was changed [here](https://github.com/thin-edge/thin-edge.io/pull/1060) and [here](https://github.com/thin-edge/thin-edge.io/pull/1170), but the PRs don't mention why these specific values were chosen (and links to issues are missing).
- #2355
> fix(#2355): cap tedge-watchdog interval to 1s minimum

- .github/workflows/build-workflow.yml
Reverting the ci workaround regarding the microsoft repo which has now been resolved.
* https://github.com/thin-edge/thin-edge.io/pull/2840
* https://github.com/microsoft/linux-package-repositories/issues/130
> ci: remove workaround since the upstream microsoft repo has been resolved

- tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
- tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
- tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
- tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
- tests/RobotFramework/tests/installation/install_apt.robot
- tests/RobotFramework/tests/plugin_apt/improve_tedge_apt_plugin_error_messages.robot
Perform an explicit ```apt-get update``` to ensure the apt cache is up to date, as on dev machines the apt-get cache can get out of date if the docker layers are reused and apt-get update has not been executed recently, resulting in ```apt-get install``` failures
<br/>
> Add apt-get update befor executing apt-get install

- crates/common/tedge_config_macros/impl/src/dto.rs
- crates/common/tedge_config_macros/impl/src/reader.rs
- crates/common/tedge_utils/src/notify.rs
- crates/core/c8y_api/src/smartrest/operations.rs
- crates/core/plugin_sm/src/plugin_manager.rs
- crates/core/tedge_api/src/commands.rs
- crates/core/tedge_api/src/entity_store.rs
- crates/core/tedge_api/src/workflow/mod.rs
- crates/core/tedge_api/src/workflow/script.rs
- crates/core/tedge_mapper/src/core/component.rs
- crates/extensions/c8y_http_proxy/src/credentials.rs
This fixes a new clippy warning triggered by the output of `define_tedge_config!`, which was generating some empty doc comments. Since the error message was unscoped, i.e. it merely pointed to the invocation of `define_tedge_config!`, and not the field that was causing the error, I have also added span information to tie the relevant generated code to the field in question.
<br/>
> Fix new clippy warning and add more span information to aid future debbuging of `define_tedge_config!`

- docs/src/operate/troubleshooting/monitoring-service-health.md
Coincidentally, I found the doc was not updated when we switched from RFC3339 to Unix time in the service status payload.
https://github.com/thin-edge/thin-edge.io/issues/2337
> Update doc: Troubleshooting > Monitoring Service Health

- crates/common/logged_command/src/logged_command.rs
- crates/core/tedge_agent/src/tedge_operation_converter/actor.rs
- crates/core/tedge_api/src/workflow/state.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Improve workflow layout and styling to make it easier and quicker for humans to follow complex workflows. The following changes were implemented:
* Display nested workflow states visually
* Display state contents in input/output format
* Add log header section to display workflow trigger info
* Remove duplicated information from each state
* Include user friendly hints for exit code and empty stdout/stderr
<br/>
> feat(workflow): improve workflow log readability for humans

- crates/core/tedge/src/cli/connect/cli.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/cli/reconnect/command.rs
- docs/src/references/cli/tedge-connect.md
- docs/src/start/connect-aws.md
- docs/src/start/connect-azure.md
- docs/src/start/connect-c8y.md
- tests/RobotFramework/tests/tedge_connect/tedge_connect_offline.robot
This PR adds a `--offline` flag to `tedge connect c8y` that skips connection checks and device registration, which allows the creation of bridge configuration and enables all services while offline.
TODO:
* #2831 
<br/>
> feat: create bridge configuration in offline mode

- tests/RobotFramework/requirements/requirements.adapter-docker.txt
- tests/RobotFramework/requirements/requirements.adapter-local.txt
- tests/RobotFramework/requirements/requirements.adapter-ssh.txt
- tests/RobotFramework/requirements/requirements.dev.txt
- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
- tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
- tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
- tests/RobotFramework/tests/cumulocity/telemetry/raise_alarms.robot
- tests/RobotFramework/tests/customizing/data_path_config.robot
- tests/RobotFramework/tests/mqtt/basic_pub_sub.robot
- tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- tests/RobotFramework/tests/tedge/http_file_transfer_api.robot
- tests/RobotFramework/tests/tedge/tedge_config_get.robot
- tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
- tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Update system tests to use Robotframework 7.0 (upgrading from 6.0).
<br/>
> test: update to robotframework 7.0

- configuration/package_manifests/nfpm.tedge.yaml
Removing the adduser dependency improves compatibility with custom linux distributions like Yocto where the `adduser` is provided via busy-box and not via debian package.
https://github.com/thin-edge/thin-edge.io/issues/2882
> feat(packaging): remove adduser debian dependency declaration

- plugins/c8y_remote_access_plugin/src/lib.rs
Launch the c8y-remote-access-plugin child process using the executable path of the running process. Also propogate the same `--config-dir` value used by the existing process.
**Note**
Below is the original PR which was created to address the "hard coded c8y-remote-access-plugin" executable path, however it seems the implementation was somewhat misguided.
* https://github.com/thin-edge/thin-edge.io/issues/2132
* https://github.com/thin-edge/thin-edge.io/issues/2887
> fix(remote-access): spawn process using current process path and config dir

- crates/extensions/c8y_mapper_ext/src/converter.rs
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
Finish auto-registration even on bad input.
#2737
> fix(#2737): Finish auto-registration even on bad input

- Cargo.lock
- Cargo.toml
> minor version bump

- crates/core/tedge_api/src/health.rs
- crates/core/tedge_api/src/mqtt_topics.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/service_monitor.rs
- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
https://github.com/thin-edge/thin-edge.io/issues/2902
> fix(mqtt): Map mosquitto bridge service health status updates

- .github/workflows/build-workflow.yml
Note: still needs to be tested by running through the merge queue
Prevent progression of the workflow if a build job is cancelled or skipped.
Without a direct link to the publish and build jobs, the publish was previously triggered if the test job was marked as skipped (due to its upstream job being not marked as "success").
https://github.com/thin-edge/thin-edge.io/issues/2908
> ci: add explicit dependency on build job

- .github/workflows/build-workflow.yml
Add ci checks to validate if *any* of the build matrix jobs was marked as failed, cancelled, or skipped.
It has been observed that if a Github Runner fails on one of the build matrix jobs, it can lead to the job being skipped, which in turns is treated by the workflow as a "don't care". This leads to the publishing jobs only partially publishing all of the expected packages (from those build jobs which passed), see [an example](https://github.com/thin-edge/thin-edge.io/actions/runs/9300637045) .
References:
* https://github.com/orgs/community/discussions/26822
https://github.com/thin-edge/thin-edge.io/issues/2908
> ci: validate build jobs

- crates/core/c8y_api/src/smartrest/inventory.rs
- crates/extensions/c8y_mapper_ext/src/service_monitor.rs
- docs/src/operate/c8y/health-monitoring.md
I found 104 message is unused by us. Fix the doc and remove the unused code.
<br/>
> Cleanup unused code and fix doc related to SmartREST 104

- .github/CODEOWNERS
Add @gligorisaev **explicitly** to CODEOWNERS of ~~.robot and .md files~~ `/tests/` and `/docs/`.
<br/>
> Add gligorisaev to CODEOWNERS of /tests/ and /docs/

- Cargo.lock
- Cargo.toml
- crates/common/tedge_config/Cargo.toml
- crates/common/tedge_config/src/tedge_config_cli/models/seconds.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/common/tedge_config_macros/impl/src/input/parse.rs
- crates/common/tedge_config_macros/impl/src/lib.rs
- crates/common/tedge_config_macros/impl/src/query.rs
- crates/common/tedge_config_macros/impl/src/reader.rs
- crates/core/tedge/src/cli/config/commands/list.rs
- crates/extensions/tedge_mqtt_bridge/Cargo.toml
- crates/extensions/tedge_mqtt_bridge/src/backoff.rs
- crates/extensions/tedge_mqtt_bridge/src/lib.rs
- crates/extensions/tedge_mqtt_bridge/src/topics.rs
- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
This adds some backoff logic to the MQTT bridge reconnection based on the [backoff crate](https://docs.rs/backoff).  It also fixes a minor issue with the tedge_config macro I encountered in the process of making the changes.
Still TODO before merging:
- #2899
> feat: Add reconnection backoff to built-in bridge

- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Resolve python warning about invalid escape characters being used in a doc string, e.g. changing `\s` to `\\s`.
This error would manifest when running the system tests:
```sh
/Users/peter/dev/projects/tedge/tmp/thin-edge.io/tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py:626: SyntaxWarning: invalid escape sequence '\s'
```
<br/>
> test(system): fix regex escaping in doc string

- docs/internal/RELEASE.md
Update the internal release process description and include more helpful instructions which provide links to the appropriate workflows, pull requests etc.
The manual step of updating the search index (related to the search function provide by Algolia) was also removed and added as a note to the tedge-docs step.
Note: the accuracy of these instructions won't be able to be verified in this PR, however it will be used in the next release to verify that it describes the process enough for any team member to publish a new release.
<br/>
> docs: update internal release process

- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
Append `@id` if not given in entity registration messages.
Remark:
I haven't decided how to support the main device **before** any metadata messages for the main device are sent. Should mapper publish as part of init messages?
=> I gave it up. Read my comment. https://github.com/thin-edge/thin-edge.io/pull/2925#issuecomment-2155552747
#2923
> refactor: c8y mapper republishes metadata message with `@id`

- crates/core/tedge/tests/mqtt.rs
- crates/core/tedge_actors/src/test_helpers.rs
- crates/core/tedge_agent/src/operation_workflows/tests.rs
- crates/core/tedge_agent/src/restart_manager/tests.rs
- crates/core/tedge_agent/src/software_manager/tests.rs
- crates/extensions/c8y_firmware_manager/src/tests.rs
- crates/extensions/c8y_mapper_ext/src/operations/config_snapshot.rs
- crates/extensions/c8y_mapper_ext/src/operations/config_update.rs
- crates/extensions/c8y_mapper_ext/src/operations/firmware_update.rs
- crates/extensions/c8y_mapper_ext/src/operations/log_upload.rs
- crates/extensions/c8y_mapper_ext/src/operations/mod.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- crates/extensions/tedge_config_manager/src/tests.rs
- crates/extensions/tedge_log_manager/src/tests.rs
- crates/extensions/tedge_mqtt_ext/src/test_helpers.rs
> chore: Fix long running unit tests

- crates/extensions/c8y_auth_proxy/src/server.rs
~This should fix a customer issue we have observed seemingly due to duplicate host headers from the c8y-auth-proxy. Currently it just removes the headers, although I am currently trying to reproduce the issue and write a test to verify it is now actually fixed.~
This fixes a bug in `c8y_auth_proxy` where the original headers were sent unmodified, meaning the Host header that was sent with the request originated from the request to the proxy, not the request the proxy makes to Cumulocity. This meant the request had a host of `127.0.0.1:8001` rather than the host that we were proxying to (e.g. `xyz.cumulocity.com`).
<br/>
> fix: Remove unwanted host header before forwarding request to Cumulocity

- docs/src/operate/c8y/configuration-management.md
Update the example in the configuration management section to use a default permisions (`0o644`) which is less likely going to cause issues for users (e.g. can read the file, but not write to it).
<br/>
> docs: change config management permissions in the example

- CODING_GUIDELINES.md
- CONTRIBUTING.md
- docs/internal/RELEASE.md
- docs/src/extend/software-management.md
- docs/src/operate/c8y/apama.md
- docs/src/start/device-monitoring.md
- tests/RobotFramework/README.md
Fix broken links in our markdown files.
I used [this GitHub action](https://github.com/gaurav-nelson/github-action-markdown-link-check) to find broken links. However, I wound not add this to our PR check as I found many false-positives. You can check the [result](https://github.com/rina23q/thin-edge.io/actions/runs/9663794079/job/26656865897) that I ran it on my fork against the current main branch contents. 
<br/>
> docs: fix broken links in markdown files

- .github/workflows/pull-request-checks.yml
- Cargo.lock
- Cargo.toml
- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
- crates/tests/mqtt_tests/src/test_mqtt_server.rs
This PR updates nightly toolchain for cargo udeps to latest one. Newer toolchain is required to bump MSRV to 1.78.
<br/>
> chore: update nightly toolchain for udeps in workflow

- docs/src/start/connect-c8y.md
Add instructions for Cumulocity IoT users which are using the [custom domain feature](https://cumulocity.com/docs/enterprise-tenant/customization/#domain-name).
Add both instructions to a dedicated section (which is easier to link to), and add the error message in the "common errors" section.
<br/>
> docs: add instructions for Cumulocity IoT custom domains

- Cargo.lock
- Cargo.toml
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs
- crates/common/tedge_config_macros/examples/macro.rs
- crates/common/tedge_config_macros/examples/renaming_keys.rs
- crates/common/tedge_config_macros/impl/Cargo.toml
- crates/common/tedge_config_macros/impl/src/query.rs
- crates/common/tedge_config_macros/src/all_or_nothing.rs
- crates/common/tedge_config_macros/src/define_tedge_config_docs.md
- crates/common/tedge_config_macros/src/example.rs
- crates/common/tedge_config_macros/tests/aliases.rs
- crates/common/tedge_config_macros/tests/arc.rs
- crates/common/tedge_config_macros/tests/defaults.rs
- crates/common/tedge_config_macros/tests/examples.rs
- crates/common/tedge_config_macros/tests/optional.rs
- crates/core/tedge/src/cli/config/cli.rs
- crates/core/tedge/src/cli/config/commands/add.rs
- crates/core/tedge/src/cli/config/commands/mod.rs
- crates/core/tedge/src/cli/config/commands/remove.rs
- crates/core/tedge/src/cli/config/commands/unset.rs
- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
- docs/src/operate/c8y/smartrest-templates.md
- docs/src/references/cli/tedge-config.md
- tests/RobotFramework/tests/tedge/tedge_config_add_remove.robot
This PR introduces two new tedge config commands: `add` and `remove`. User can append array type tedge config using the `tedge config add <key> <value>`. If this command is used on non array type config, it will work just like `tedge config set` and replace the value. The `tedge config remove <key> <value>` will remove one or more elements from the array type if they match the <value>. If it is used on non array type config, it will unset the config, provided `<value>` match it.
* #2864
<br/>
> feat(config): add new subcommand for appending/removing values in an array-type tedge configs

- Cargo.lock
- crates/common/mqtt_channel/src/messages.rs
- crates/common/mqtt_channel/src/topics.rs
- crates/core/tedge_actors/src/message_boxes.rs
- crates/extensions/tedge_mqtt_ext/Cargo.toml
- crates/extensions/tedge_mqtt_ext/src/lib.rs
One of the cause of [too many software list requests](https://github.com/thin-edge/thin-edge.io/issues/2954), is that NanoMQ has not the same behavior as Mosquitto when a connection has overlapping subscriptions. See https://github.com/thin-edge/thin-edge.io/issues/2954#issuecomment-2188244048
https://github.com/thin-edge/thin-edge.io/issues/2954
> fix: too many software list requests

- tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot
Adding test:
tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot
https://github.com/thin-edge/thin-edge.io/issues/2922
> test: ensure the MQTT connection is properly closed

- tests/images/debian-systemd/debian-systemd.dockerfile
Fix an issue where system tests were failing due to missing the `/run/lock` folder. The change no longer deletes the `systemd-tmpfiles-setup.service` which is the mechanism systemd uses to create temporary files such as `/run/lock`. Using `systemd-tmpfiles-setup.service` is preferable over using the docker tmpfs mechansim as the former behaves more true to a device installation (rather than a docker container).
In addition, mosquitto is now installed from the debian "bookworm-backports" rather than "sid", as it seems the "sid" channel is installing a much newer version of systemd (v256 vs v253) and there might be some unexpected changes in the new version (which are still to be investigated in a follow up PR).
Note: It is still unclear when the exact change was introduced, possibly due to …
> tests: don't remove systemd-tmpfiles-setup service which is responsible for creating tmp folders

- tests/RobotFramework/tests/customizing/tedge_init.robot
Small refactoring of a system tests to use the `Path Should Have Permissions` Keyword over calling `ls` manually, as the former does a check via `stat` which is less problematic to localization errors and it also standardizes the check across system tests (though this PR does not look to update other tests if it is not already using this keyword).
<br/>
> tests: use library keyword to check folder ownership

- docs/src/operate/security/cloud-authentication.md
Document a common errors with the `update-ca-certificates` when the device has an older version of `openssl` which does not support the `rehash` command resulting in mosquitto being not able to connect to the cloud due to ssl verify errors.
The documentation also includes a work around to manually generate the ca-certificate hashes/symlinks.
This problem was first observed on Opto22 devices.
<br/>
> docs: add common errors section for update-ca-certificates when rehashing fails

- crates/core/tedge/src/cli/config/commands/get.rs
- crates/core/tedge/tests/main.rs
- tests/RobotFramework/tests/tedge/tedge_config_get.robot
Return `1` if `tedge config get` is called for unset key.
#2990
> fix(tedge): `tedge config get` returns 1 when a key is not set

- docs/src/start/connect-aws.md
Use a static link to the example aws policy as the relative link resulted in a 404 request, for example:
<br/>
> docs: fix link to the example aws policy

- docs/internal/RELEASE.md
Update internal release instructions to include not about the removal of older doc versions (snapshots), since a the snapshot process was updated to automatically remove older versions, see https://github.com/thin-edge/tedge-docs/pull/84.
https://github.com/thin-edge/tedge-docs/pull/84
> docs: update notes on doc version management

- crates/common/axum_tls/src/lib.rs
- crates/common/tedge_config/src/tedge_config_cli/models/seconds.rs
- crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
- crates/core/tedge/src/cli/certificate/upload.rs
- crates/core/tedge/src/cli/init.rs
- crates/extensions/c8y_firmware_manager/src/actor.rs
- crates/tests/mqtt_tests/src/test_mqtt_client.rs
Fix some clippy errors which have appeared from the latest nightly version:
* Fix doc string indentation
* Remove dead code found by the nightly version of clippy.
```
error: struct `InvalidSecondsNumber` is never constructed
--> crates/common/tedge_config/src/tedge_config_cli/models/seconds.rs:15:12
|
15 | pub struct InvalidSecondsNumber {
|            ^^^^^^^^^^^^^^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
```
Note: Some additional clippy fixes were also detected when running locally which did not turn up on the CI runner.
Found from the following ci runs:
* https://github.com/thin-edge/thin-edge.io/actions/runs/10099617229/job/27929147661?pr=3015
> chore: fix clippy errors

- configuration/init/systemd/75-tedge.preset
- configuration/init/systemd/c8y-remote-access-plugin.socket
- configuration/init/systemd/c8y-remote-access-plugin@.service
- configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
- configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postinst
- configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postrm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/prerm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/prerm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/rpm/postinst
- configuration/package_scripts/_generated/c8y-remote-access-plugin/rpm/postrm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/rpm/prerm
- configuration/package_scripts/c8y-remote-access-plugin/postinst
- configuration/package_scripts/c8y-remote-access-plugin/prerm
- configuration/package_scripts/generate.py
- configuration/package_scripts/packages.json
- plugins/c8y_remote_access_plugin/src/input.rs
- plugins/c8y_remote_access_plugin/src/lib.rs
- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/remote-access/restart-service.sh
- tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
Use systemd socket activated service to spawn the c8y-remote-access-plugin connection so that it is independent from the tedge-mapper-c8y process which allows the tedge-mapper-c8y service to be restarted without interrupting the connection (or performing actions like `tedge reconnect c8y`).
The c8y_RemoteAccessConnect operation will launch the connection using the socket only if is available, so it should make it flexible for OS's with and without systemd.
* PR is current rebase upon https://github.com/thin-edge/thin-edge.io/pull/3006
* https://github.com/thin-edge/thin-edge.io/issues/2859
> feat: socket activated c8y-remote-access-plugin service

- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
- crates/tests/mqtt_tests/src/test_mqtt_server.rs
Bind the MQTT broker used in unit tests to `127.0.0.1` instead of `0.0.0.0` to avoid additional permissions which are generally required when binding to all network interfaces (e.g. on MacOS, the firewall warnings pops up each time when binding to 0.0.0.0).
Also the tests do not require binding to `0.0.0.0`, so it is best to avoid it.
<br/>
> test: bind to localhost instead of all interfaces

- crates/core/tedge_agent/src/agent.rs
- tests/RobotFramework/tests/tedge_agent/tedge_agent_as_child.robot
Note: This PR is based on a very similar PR https://github.com/thin-edge/thin-edge.io/pull/3033, so it should be merged afterwards.
Skip the subscription to legacy tedge topics when **tedge-agent** is run as a child device.
The TedgetoTeConverter actor is only started when **tedge-agent** is run on the main device however it would incorrectly subscribe to the legacy topics regardless.
* https://github.com/thin-edge/thin-edge.io/issues/3034
> fix: tedge-agent skip legacy topic subscription when running as a child device

- .github/codecov.yml
In 80..100 the 100 is when the coverage should be marked as green. Because we want to have nice things and would rather prefer codecov not to complain in PR comments about files where coverage is already pretty high, we'll be decreasing this threshold.
Also changing precision to 2 because it's the default and why not.
Also change comment layout to the "most up to date one" according to codecov.
<br/>
> ci: update codecov range

- crates/core/c8y_api/src/json_c8y_deserializer.rs
- crates/core/plugin_sm/src/plugin_manager.rs
- crates/core/tedge_agent/src/operation_workflows/tests.rs
- crates/core/tedge_agent/src/software_manager/tests.rs
- crates/core/tedge_api/src/commands.rs
- crates/core/tedge_api/src/error.rs
- crates/core/tedge_api/src/software.rs
- crates/core/tedge_api/src/workflow/log/command_log.rs
Don't discard the error messages from unknown software types, and specify the error message in the failure reason when only one error has occurred. This is in response to a misdiagnosed customer issue, where thin-edge gave no indication that the customer needed to create a plugin for a software type as no error message appeared anywhere in the logs.
- #3057
> fix: display error information for failed software update due to unrecognised type

- crates/core/tedge_agent/src/operation_workflows/actor.rs
- crates/core/tedge_api/src/workflow/error.rs
- crates/core/tedge_api/src/workflow/mod.rs
- crates/core/tedge_api/src/workflow/script.rs
- crates/core/tedge_api/src/workflow/state.rs
- crates/core/tedge_api/src/workflow/toml_config.rs
Inject workflow default values while parsing the workflow definition and not during execution. 
When a workflow is used to execute an operation, all the transitions must have been resolved.
<br/>
> refactor: improve handling of workflow default values

- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
Retry the connection to the MQTT broker in the bridge integration tests since the broker may not have started at the time the proxy starts.
- #3071
> test: retry connecting to broker in bridge test proxy

- crates/core/tedge_agent/src/operation_workflows/mod.rs
- crates/core/tedge_api/src/workflow/error.rs
- crates/core/tedge_api/src/workflow/mod.rs
- crates/core/tedge_api/src/workflow/state.rs
- crates/core/tedge_api/src/workflow/toml_config.rs
- tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
- tests/RobotFramework/tests/tedge_agent/workflows/issue-3079.toml
Replace any ill-defined workflow by a placeholder that fails all the commands for that operation and reports the workflow definition errors.
The aim is to fix the current situation where workflow definition errors are not reported to the clients, the corresponding operations being ignored and not reported to Cumulocity where they stay in the pending state for ever with no clue for the end-user. See https://github.com/thin-edge/thin-edge.io/issues/3074
- https://github.com/thin-edge/thin-edge.io/issues/3074
> feat: report to the cloud workflow definition errors

- Cargo.lock
- Cargo.toml
- crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs
- crates/common/tedge_utils/src/fs.rs
- no longer fail when `.tmp` file already exists, new tempfile are created with 6 random bytes and names are regenerated if such name already exists
- ensure async tempfile is cleaned up by wrapping it in a `tempfile::NamedTempFile` that provides a drop implementation
`tempfile` was also bumped because `tempfile::Builder::permissions` was not available on the current version.
Running `configuration_operation.robot` suite, it was flaking for me, and I have found the following error that caused `tedge-agent` to never start:
```
ERROR sm-agent: tedge_actors::runtime: Aborted due to Writing the
content to the file "/etc/tedge/.agent/software-current-operation"
failed: "could not create the temporary file \"/etc/tedge/.agent/software-current-operation.tmp\"".
source=Os { code: 17, kind: …
```
> fix issues in atomically_write_file_* functions

- .github/workflows/pull-request-checks.yml
Don't fail `cargo test` on warnings. We already have a separate `cargo clippy` check that fails on warnings.
https://github.com/thin-edge/thin-edge.io/pull/3069#issuecomment-2311800027
<br/>
> ci: don't fail cargo test on warnings

- Cargo.lock
- crates/core/c8y_api/src/json_c8y_deserializer.rs
- crates/core/tedge_api/src/commands.rs
- crates/core/tedge_api/src/device_profile.rs
- crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
- tests/RobotFramework/tests/tedge_agent/device_profile/firmware_update.toml
The firmware URL in the C8y operation request was wrongly getting mapped to a `url` field, whereas it should have been mapped to a `remoteUrl` field to be consistent with `firmware_update` operation mapping.
<br/>
> Fix firmware url mapping in device profile

- .github/workflows/pull-request-checks.yml
Add codecov token to `cargo test` check because coverage was failing when running on the merge queue (example [1]). Token is as of v4 required to upload from the context of a repository. From codecov-action's [README.md](https://github.com/codecov/codecov-action/blob/dad251dcaf4fdaa10dfaa1c32aab58f9cb23a448/README.md):
> Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token). For details, see our docs
[1]: https://github.com/thin-edge/thin-edge.io/actions/runs/10581903169/job/29320341526#step:13:36
<br/>
> ci(coverage): add codecov token

- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
- tests/RobotFramework/tests/installation/install_tedge.robot
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
- tests/images/debian-systemd/files/tedge.toml
Refactor the Cumulocity IoT device profile system tests to use keywords provided in the newer version of [robotframework-c8y](https://github.com/reubenmiller/robotframework-c8y).
Note: The creation of the device profile and applying it to a device has been separated into two keywords to enable improved control, and the cleanup of the device profile (e.g. deletion from the repository) happens automatically in the `Create Device Profile` keyword.
<br/>
> test: Refactor Cumulocity IoT device profile system tests

- crates/extensions/tedge_config_manager/Cargo.toml
- crates/extensions/tedge_config_manager/src/actor.rs
- crates/extensions/tedge_config_manager/src/lib.rs
- crates/extensions/tedge_config_manager/src/tests.rs
As in #2904, control flow was simplified by replacing fragmented control flow and hashmaps with tokio tasks and regular async/await.
A test was added to confirm that requests are still processed concurrently.
<br/>
Commits are kept small for ease of reviewing, once reviewed I'll merge them and add a description, unless it's not desired.
Fragmented uploads and downloads are only left in `FileCacheActor` and `LogManagerActor`, I will do them in next PRs.
> refactor: Simplify config manager control flow

- Cargo.lock
- crates/common/tedge_utils/src/atomic.rs
- crates/common/tedge_utils/src/lib.rs
- crates/core/tedge_write/Cargo.toml
- crates/core/tedge_write/src/bin.rs
- crates/extensions/tedge_config_manager/src/actor.rs
Make tedge-write and config-manager use the same atomic write function
<br/>
> Extract atomic write function into a module

- docs/src/references/agent/device-profile.md
Fix the documentation title for the agent device profile page (due to a copy/paste error).
<br/>
> doc: fix device profile page title

- tests/RobotFramework/tests/tedge_write.robot
- add tests checking that sudo elevates permissions for tedge and does not for normal users when using tedge-write
- simplified ownership/mode tests by extracting checks into keywords
<br/>
> test: improve tedge-write RobotFramework suite

- docs/src/operate/security/mqtt-tls-configuration.md
- Remove deprecated config settings
<br/>
> doc: fix deprecated mTLS setting in user docs

- docs/src/references/agent/device-profiles.md
Fix minor typo in the device profile examples where the json payload of the MQTT message was missing a closing double quote.
<br/>
> docs: fix invalid json in the example json payload

- Cargo.toml
- crates/extensions/tedge_mqtt_bridge/Cargo.toml
Fix deprecated `default_features` cargo warning.
<br/>
> chore: Fix cargo deprecated default_features warning

- crates/core/tedge_agent/src/resources/device_profile.toml
- crates/core/tedge_api/src/mqtt_topics.rs
- crates/core/tedge_api/src/workflow/state.rs
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Device profile twin update as part of the workflow execution.
<br/>
> Device profile twin update before operation completion

- plugins/c8y_remote_access_plugin/src/input.rs
Fix `c8y-remote-access-plugin --help` that was referencing the wrong executable
<br/>
> fix: c8y-remote-access-plugin help

- containers/tedge/Dockerfile
Initialize the c8y-remote-access-plugin within the docker container so that it is enabled by default.
<br/>
> feat: initialize the remote access plugin in the container image

- crates/core/tedge_write/src/bin.rs
- crates/core/tedge_write/src/lib.rs
- docs/src/references/agent/tedge-configuration-management.md
- docs/src/references/tedge-write.md
Adds a documentation page for `tedge-write` component, which should contain information about the component relevant to users and references relevant tedge-write information in `config_update` operation reference. 
- #3073
> docs: Add tedge-write documentation page

- docs/src/references/mappers/c8y-mapper.md
Fix documentation where the service status was still publishing as a string instead of a json number.
<br/>
> docs: publish pid as number instead of string

- Cargo.toml
- crates/core/tedge/Cargo.toml
- crates/core/tedge_api/src/health.rs
- crates/core/tedge_watchdog/src/systemd_watchdog.rs
- crates/extensions/c8y_mapper_ext/src/service_monitor.rs
- plugins/tedge_apt_plugin/Cargo.toml
tedge-mapper will now not only try to parse `status` field and will ignore other extra fields.
- #3128
> fix: Ignore extra HealthStatus fields in service monitor

- tests/RobotFramework/requirements/requirements.adapter-docker.txt
- tests/RobotFramework/requirements/requirements.adapter-local.txt
- tests/RobotFramework/requirements/requirements.adapter-ssh.txt
- tests/RobotFramework/requirements/requirements.txt
Update the location of the testing libraries after they were transfered to the `thin-edge` Github organization.
<br/>
> test: update source to testing libraries

- crates/common/mqtt_channel/src/config.rs
- crates/common/mqtt_channel/src/connection.rs
- crates/common/mqtt_channel/src/tests.rs
- crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/tedge/src/cli/mqtt/mod.rs
- crates/core/tedge_agent/src/agent.rs
- crates/core/tedge_mapper/src/aws/mapper.rs
- crates/core/tedge_mapper/src/az/mapper.rs
- crates/extensions/aws_mapper_ext/src/converter.rs
- crates/extensions/az_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
* Increase default MQTT payload size to 256 MiB
* Make MQTT cloud payload size configurable
https://github.com/thin-edge/thin-edge.io/issues/3124
> Increase default MQTT payload size to 256 MiB

- crates/core/tedge_api/src/workflow/mod.rs
- docs/src/references/agent/device-profiles.md
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Support skipping operations in device profile
<br/>
> fix: Support skipping operations in device profile

- configuration/package_manifests/nfpm.tedge-agent.yaml
Add the `tedge-apt-plugin` package as recommended dependency of `tedge-agent` package (for debian only).
This makes for a more seamless installation for users who want to manage a debian based child device using `tedge-agent`. Useres can still opt out of it using `apt-get install tedge-agent --no-install-recommends`.
<br/>
> feat: add tedge-apt-plugin as recommended dependency of tedge-agent

- configuration/package_manifests/nfpm.tedge.yaml
- configuration/package_manifests/virtual/nfpm.tedge-full.yaml
- configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
Fix the tedge's linux package dependency to mosquitto by making it a weak dependency so that mosquitto is not installed by default when installing `tedge` directly (and not via the `tedge-full` or `tedge-minimal` virtual linux packages).
This will allow users to install tedge and any other package which depends on tedge (like tedge-agent) to be installed without mosquitto. The virtual packages will have a hard dependency to mosquitto as this is a "typical" setup and mosquitti is required on the main device.
The official `thin-edge.io/install.sh` script uses the virtual packages, so this does not break and existing behaviour.
FYI: Debian has [good documentation](https://www.debian.org/doc/debian-policy/ch-relationships.html) which go into details about the package dependency types.
<br/>
> fix: add mosquitto as a weak dependency to tedge

- crates/core/c8y_api/src/smartrest/operations.rs
- crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/error.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_1
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_2
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/command_handler.sh
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
The extension of custom operation handler makes it easy to use c8y custom operations in thin-edge. Users no longer have to create custom SmartREST templates.
Changes:
- custom operation handler can accept JSON over MQTT topic
- command field accepts arguments from JSON payload, same format as operation workflow
- supporting `504`-`506` messages to update operation status
- added `skip_status_update = true` option
Todo:
Will be done in follow-up:
---
**Example usage:**
Install [`c8y-command-plugin`](https://github.com/thin-edge/c8y-command-plugin) and modify `/etc/tedge/operations/c8y/c8y_Command` as below.
```toml
[exec]
topic = "c8y/devicecontrol/notifications"
on_fragment = "c8y_Command"
command = "/usr/bin/c8y-command ${.payload.c8y_Command.text}"
skip_status_update = true
```
Then, …
> feat: allow operation handlers to match on json payloads

- docs/src/references/agent/operation-workflow.md
Add missing variable to the workflow documentation:
* `${.topic.root_prefix}`
<br/>
> docs: add missing variable available in workflow states

- crates/core/c8y_api/src/smartrest/operations.rs
Reorder structs and functions suggested in https://github.com/thin-edge/thin-edge.io/pull/3144#discussion_r1785941656. No contents change.
#3144
> refactor: reorder crates/core/c8y_api/src/smartrest/operation.rs

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- ci/build_scripts/build.sh
Update packages and add additional tools in the dev container image:
* Update nodejs to v20
* Install wget
* Install json tools (jq and jo)
* Install mosquitto from bookworm-backports instead of sid
* Install utilities like ssh, sudo, gnupg2, net-tools, netcat
* Remove systemd policies (aligning to the system test image)
<br/>
> dev: update packages in dev container image

- ci/build_scripts/build.sh
Adjust the build.sh script to accept targets with the gnu libc version as a suffix. 
This is a feature of cargo-zigbuild (see https://github.com/rust-cross/cargo-zigbuild?tab=readme-ov-file#specify-glibc-version). It is only intended for testing and experiments. It does not change the way the official binaries are built!
**Examples**
```sh
just release aarch64-unknown-linux-gnu.2.17
just release aarch64-unknown-linux-gnu.2.27
just release aarch64-unknown-linux-gnu.2.30
```
<br/>
> build: add support for building against specific gnu libc versions

- .github/workflows/pull-request-checks.yml
Run `just format-check` in the Pull Request workflow which will check the formatting of both Rust and RobotFramework tests.
<br/>
> ci: run format checks on entire code base including Robotframework tests

- docs/src/extend/firmware-management/device-onboarding.md
Add a note about the on-boarding instructions under the firmware section for tips on using the `c8y-tedge` go-c8y-cli extension.
Also update the `c8y tedge scan` command output example to reflect the current state of the `c8y-tedge` output (where the mdns suffix was added to each of the detected devices)
<br/>
> docs: add notes to firmware on-boarding instructions

- .github/workflows/build-workflow.yml
- ci/build_scripts/build.sh
- ci/build_scripts/detect_target.sh
- ci/build_scripts/package.sh
- ci/build_scripts/publish_packages.sh
- containers/tedge/Dockerfile
Switch the armv6 package from using `arm-unknown-linux-musleabihf` to `arm-unknown-linux-musleabi` due to an issue being discovered with the format.
When using tedge compiled with the target `arm-unknown-linux-musleabihf`, an "illegal instruction" error whilst running `tedge connect c8y`.
https://github.com/thin-edge/thin-edge.io/issues/3183
> fix: target incompatibility with armv6 package for raspberry pi

- CONTRIBUTING.md
- CONTRIBUTOR-LICENSE-AGREEMENT.md
- GOVERNANCE.md
- docs/src/operate/security/device-certificate.md
- docs/src/start/getting-started.md
Replace company references to Cumulocity GmbH.
There are still a few links referencing the previous company name, but these will have to be changed once the appropriate services are made available:
* Reference in Apama docs, `/opt/softwareag/Apama/bin/apama_env`
* Reference to `https://tech.forums.softwareag.com`
<br/>
> chore: replace company references to Cumulocity GmbH

- crates/core/tedge_mapper/src/c8y/mapper.rs
Removing a duplicate topic subscription when using the built-in bridge with Cumulocity.
The duplicate would cause some MQTT brokers (like nanomq) to deliver two messages (one per topic) which would ultimately result in duplicate telemetry data being created in Cumulocity.
The MQTT wildcard, `c8y/s/us/#`, will also receive messages from `c8y/s/us`.
<br/>
> fix: remove duplicate subscription in c8y built-in bridge

- docs/src/references/supported-platforms.md
- docs/src/start/getting-started.md
Add information about which ports are required by thin-edge.io to communicate to each cloud.
This work was spawned from a debug session which a customer which was using thin-edge.io behind a strictly controlled network and firewall rules needed to be created before thin-edge.io could connect to the appropriate cloud.
An additional "Debug section" could also be added, however it was decided it would be a better UX to create built-in command to do the connectivity checks like "can I reach the network" to give clear guidance on how to check these scenearios.
<br/>
> docs: add required ports information for cloud connections

- design/decisions/0005-tedge-watchdog.md
Add a new decision page after a decision about the future of the **tedge-watchdog** component and rationale on why shifting focus to independent solutions such as `monit` would lead to a more reliable/holistic approach to moniting components and performing corrective actions to bring a system back to a healthy state.
<br/>
> docs: add tedge-watchdog decision page

- crates/core/tedge/src/bridge/c8y.rs
This PR replace one hardcoded topic prefix in bridge config with the one from tedge config.
<br/>
> fix: replace hardcoded topic prefix for smartrest templates when creating bridge config

- crates/core/tedge_api/src/commands.rs
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
https://github.com/thin-edge/thin-edge.io/issues/3136
> fix: agent stops processing ill-formed software_update command payloads

- crates/common/mqtt_channel/src/topics.rs
- crates/core/c8y_api/src/smartrest/error.rs
- crates/core/c8y_api/src/smartrest/operations.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/inventory.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_4
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
- tests/RobotFramework/tests/cumulocity/shell/c8y_Command
This PR adds support for user topics when handling custom operation. Custom topic can be provided in custom operation in following way (templates supported):
```
[exec]
topic = "${.bridge.topic_prefix}/custom/topic/one"
on_fragment = "com_cumulocity_model_WebCamDevice"
command = "/usr/bin/do_something.sh ${.payload.com_cumulocity_model_WebCamDevice.parameters.duration}"
```
Mapper replace template with mapper prefix (if needed) and subscribe to the topic. If template is different than `${.bridge.topic_prefix}` then this topic will be skipped. 
TODO:
* #3095
<br/>
> feat: support user topics when handling custom operation

- Cargo.lock
- crates/common/download/src/download.rs
- crates/common/upload/src/upload.rs
- crates/extensions/c8y_auth_proxy/src/server.rs
- crates/extensions/c8y_http_proxy/src/tests.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- crates/extensions/tedge_downloader_ext/src/tests.rs
- crates/extensions/tedge_http_ext/src/tests.rs
- crates/extensions/tedge_uploader_ext/src/tests.rs
> refactor: update crate dependencies

- crates/core/tedge/src/cli/connect/error.rs
Fix error text which directed to an incorrect tedge statement, `tedge config --set` instead of `tedge config set`.
<br/>
> fix: config set instructions in certificate error message

- crates/common/certificate/src/lib.rs
- crates/common/certificate/src/parse_root_certificate.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/tedge/src/cli/certificate/create.rs
- crates/core/tedge/src/cli/certificate/show.rs
Add path to io errors reading certificates
https://github.com/thin-edge/thin-edge.io/issues/3159
> fix: tedge-agent error does not show which file does not exist

- crates/core/tedge_api/src/entity_store.rs
Implementation of a de-registration method from the entity store. 
https://github.com/thin-edge/thin-edge.io/issues/3227
> feat: Deregister entity tree

- docs/src/references/mappers/c8y-mapper.md
A section which detailed the propsoal to publish units with measurements made its way into the production documentation even though it is not implemented! This gave the user the impression that it could be used, when in fact it thin-edge.io would just ignore the `/meta` topic.
https://github.com/thin-edge/thin-edge.io/issues/3243
> docs: remove docs for measurements with units

- .github/workflows/build-workflow.yml
Removing the explicit test exclusion options from the workflow allows the code from the PR to control which tests are run or not (without having to change the workflow).
<br/>
> ci: remove test exclusion options from workflow

- tests/RobotFramework/tasks.py
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
- tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access_custom_root_cert_path.robot
Skips the remote access tests by default since they are currently flaky due to factors outside our control.
<br/>
> test: skip remote access tests that are failing to Cumulocity core issue

- crates/core/c8y_api/src/smartrest/operations.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
This PR fixes issue introduced with #3198. Previously we always matched operation that had no topic provided in the operation file as we assumed the default one is device control topic. Now operation can be run with any topic that user provides in the operation file so this rule no longer applies. Operation without provided topic is added to operation handlers no matter which topic delivered the message, wheras it should be added to handlers only if the message was delivered by device control topic.
<br/>
> fix: match operation without topic only when it was delivered by device control topic

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- .github/workflows/devcontainer.yml
- justfile
Publish the dev container to Github container registry to reduce the time it takes to install all of the dependencies to start developing. In addition it makes the dev environment more reliable as apt-get install performance can be unreliable at times as the automatic mirror selection does not always choose a close-by debian mirror.
A workflow has been added to also periodically publish the devcontainer image (or on demand).
<br/>
> dev: publish devcontainer image

- justfile
Follow PR to fix a publishing error in the development container (recently published in https://github.com/thin-edge/thin-edge.io/pull/3265).
Removing `linux/arm/v7` as it is not supported in the Rust base container image.
<br/>
> dev: don't publish image for linux armv7 as it is not supported by the Rust image

- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
Currently we publish message to `te/errors` when `/etc/tedge/operations/c8y` directory was modified but no operation update is required. This might be misleading to users that there is something wrong with operations so this PR removes that message. Not other logging was introduced as this information should just be skipped. 
* #3252
<br/>
> fix: skip publishing error message if operation update is not required

- crates/common/tedge_utils/src/file.rs
- crates/core/c8y_api/src/smartrest/operations.rs
- crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
- crates/core/tedge_api/src/workflow/state.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/operations/convert.rs
- crates/extensions/c8y_mapper_ext/src/operations/handlers/custom_operation.rs
- crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- tests/RobotFramework/requirements/requirements.adapter-docker.txt
- tests/RobotFramework/requirements/requirements.adapter-local.txt
- tests/RobotFramework/requirements/requirements.adapter-ssh.txt
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/c8y_OpenDoor.template
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/c8y_TakePicture.template
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/custom_operation_workflow.robot
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/do_something.sh
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/open_door.toml
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/take_picture.sh
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/take_picture.toml
> feat: add workflow support for custom operation (drop 2)

- crates/core/tedge/src/cli/log.rs
- crates/extensions/c8y_auth_proxy/src/server.rs
- crates/extensions/tedge_health_ext/src/tests.rs
> chore: fix rust 1.83 clippy lints

- Cargo.lock
- crates/core/tedge/src/cli/log.rs
- crates/core/tedge_write/Cargo.toml
- crates/core/tedge_write/src/bin.rs
- crates/extensions/c8y_auth_proxy/src/server.rs
- crates/extensions/tedge_health_ext/src/tests.rs
- plugins/tedge_apt_plugin/Cargo.toml
- plugins/tedge_apt_plugin/src/lib.rs
Add `--log-level` flag to `tedge-write` and `tedge-apt-plugin`.
- #2089
> Add `--log-level` to `tedge-write` and `tedge-apt-plugin`

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- justfile
Add rust `nightly` toolchain to the required project build tools.
<br/>
> dev: Update rust dev tools

- crates/core/tedge/src/cli/config/cli.rs
- crates/core/tedge/src/cli/config/commands/list.rs
This adds an optional argument to `tedge config list` and `tedge config list --doc` which filters the list of configuration keys shown, since the complete list is now very large.
For example:
```bash
$ ./tedge config list --doc agent
agent.state.path  The directory where the tedge-agent persists its state across restarts. 
Note: If the given directory doesn't exists, `/etc/tedge/.agent` is used as a fallback irrespective of the current setting.
Example: /data/tedge/agent
agent.enable.config_update  Determines if tedge-agent should enable config_update operation. 
Example: true
agent.enable.config_snapshot  Determines if tedge-agent should enable config_snapshot operation. 
Example: true
agent.enable.log_upload  Determines if tedge-agent should enable log_upload operation. 
Example: true …
```
> feat: add filtering to `tedge config list`

- .github/workflows/devcontainer.yml
Only build/publish the dev container on the main branch. Previously the merge queue event was triggering the devcontainer workflow
<br/>
> dev: only build devcontainer on main branch

- tests/RobotFramework/requirements/requirements.txt
Update the robotframework-c8y library to fix an issue where the Cumulocity bulk device registration api would fail due to the randomly generated password not meeting the Cumulocity password policy.
The bug was discoverred from a failed workflow run (in the merge queue)
* https://github.com/thin-edge/thin-edge.io/actions/runs/12115548790/job/33774366914
<br/>
> test: update robotframework-c8y library

- .github/CODEOWNERS
> dev: update code owners

- crates/core/tedge/src/bridge/c8y.rs
- crates/core/tedge_mapper/src/c8y/mapper.rs
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
Add Cumulocity bulk telemetry creattion topics to the bridge (both mosquitto bridge and built-in bridge):
This enables users to publish bulk measurements using the following topics:
* c8y/event/events/createBulk
* c8y/alarm/alarms/createBulk
* c8y/measurement/measurements/createBulk
See [Cumulocity documentation](https://cumulocity.com/docs/smartrest/json-via-mqtt/#supported-endpoint) for details.
https://github.com/thin-edge/thin-edge.io/issues/3203
> feat: add c8y createBulk topics to bridge

- docs/src/operate/c8y/supported-operations.md
This PR creates documentation for custom operation workflow handler.
* #3095
<br/>
- [] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
> Add documentation for custom operation workflow handler

- crates/core/tedge_actors/src/servers/message_boxes.rs
This fixes an issue that was causing `tedge-mapper` to fail to shutdown properly in certain cases, namely when the HTTP actor was busy when the shutdown request was received.
The root cause is in these lines of code
https://github.com/thin-edge/thin-edge.io/blob/82cde4094fbfdb073fa26b353393f9f59e3cbef4/crates/core/tedge_actors/src/servers/message_boxes.rs#L51-L65
When we receive a `RuntimeRequest::Shutdown`, `self.requests.recv()` returns `None`. Since this doesn't match `Some(request)`, this branch then becomes inactive and we wait for `self.running_requests_handlers.next()`. If any request handlers are running, when this returns, the code will loop, running `self.requests.recv()` again, meaning we've completely ignored the shutdown request and will never receive another one.
A similar …
> fix: ensure concurrent server always responds to shutdown signal

- crates/common/tedge_config_macros/impl/src/query.rs
- crates/common/tedge_config_macros/src/multi.rs
Clean up empty profiles when calling `tedge config unset`, e.g. running
```
tedge config set c8y.url example.com --profile test
tedge config unset c8y.url --profile test
tedge config list test # <- should return nothing
```
<br/>
> fix: cleanup empty profiles

- crates/core/tedge/src/cli/connect/jwt_token.rs
- tests/RobotFramework/devdata/env.template
The pull request check "Spell Check with Typos" started failing now. [example run](https://github.com/thin-edge/thin-edge.io/actions/runs/12579988654/job/35061132478?pr=3292)
I cherry-picked the commit a23796eebc9aa6857311cbd303a6086f6794e04b from the PR #3311.
Since these typos are unrelated to all opened PRs, I think it would be more helpful to merge the fixing typo part only now.
<br/>
> fix: Fix typos

- docs/src/operate/registration/deregister.md
add missing argument in docs: https://github.com/thin-edge/thin-edge.io/issues/3319
https://github.com/thin-edge/thin-edge.io/issues/3319
> doc: Add documentation exemple missing arg

- crates/common/tedge_utils/src/fs.rs
Support resolving symlink targets files when calling `atomically_write_file_sync` and `atomically_write_file_async`.
Note: A symlinks target file will only be resolved if the target file exists, otherwise the path will be the symlink itself.
https://github.com/thin-edge/thin-edge.io/issues/3323
> fix: support symlinks in atomic file write methods

- docs/src/operate/c8y/apama.md
- docs/src/references/mappers/mqtt-topics.md
Update company references.
Apama installation path was taken from the [Cumulocity Apama docs](https://cumulocity.com/apama/docs/latest/deploying-and-managing-apama-applications/overview-of-deploying-apama-applications/).
<br/>
> docs: update company references

- docs/src/operate/c8y/smartrest-templates.md
- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi.json
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi.sh
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/smartrest_template.robot
This PR adds missing test for custom operation execution using smartrest templates. Additionally, it fixes the script content in documentation that currently is not printing any information. 
<br/>
> test: missing test for custom operation execution using smartrest templates

- docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
- docs/src/extend/firmware-management/building-image/yocto/tutorial.md
- docs/src/legacy/child-device-firmware-management.md
- docs/src/operate/c8y/configuration-management.md
- docs/src/operate/c8y/connect.md
- docs/src/operate/c8y/custom-fragments.md
- docs/src/operate/c8y/remote-access.md
- docs/src/operate/c8y/smartrest-templates.md
- docs/src/operate/c8y/supported-operations.md
- docs/src/operate/security/device-certificate.md
- docs/src/operate/troubleshooting/testing-cloud-connection.md
- docs/src/overview.md
- docs/src/references/mappers/c8y-mapper.md
- docs/src/start/connect-c8y.md
- docs/src/start/getting-started.md
- docs/src/start/raise-alarm.md
- docs/src/start/send-events.md
- docs/src/start/software-management.md
- docs/src/understand/tedge-mapper.md
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
Update all references to Cumulocity's update documentation under https://cumulocity.com/docs/
<br/>
> docs: update links to Cumulocity documentation pages

- tests/RobotFramework/tasks.py
Auto detect the usage of docker buildx when building the test image (via `docker build`). If buildx is detected, then the `--load` argument is automatically added so that the built image can be used by docker.
If this isn't done, then the image is not accessible as indicated by the warning printed by docker buildx:
```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```
<br/>
> tests: load image into docker when using buildx

- .github/workflows/build-workflow.yml
- tests/RobotFramework/tasks.py
Revert workflow migration commit 7cff046266c903c14b984a96e4d08542351f96e2 as it is no longer needed due to PR https://github.com/thin-edge/thin-edge.io/pull/3348 being merged into main.
<br/>
> test: remove workflow transition logic/commit

- crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
- crates/common/tedge_config/src/tedge_config_cli/models/topic_prefix.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config/append_remove.rs
- crates/common/tedge_config/src/tedge_config_cli/tedge_config/version.rs
Extract versioning/migration and `TopicPrefix` into suitable submodules from `tedge_config.rs`.
`tedge_config.rs` file is often modified when adding/removing configuration options, so other stuff in the file unrelated to that and unlikely to change can be extracted to other files.
<br/>
> refactor: extract versioning/migration and `TopicPrefix` from tedge config into submodules

- tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Ignore the test "Check absence of OpenSSL Error messages".
This test has been introduced by https://github.com/thin-edge/thin-edge.io/issues/3024 but is flaky because a similar OpenSSL error occurs but for an unrelated reason.
It the original ticket, the issue was clients failing to disconnect properly after a successful session. In the flaky case, the client is not even able to establish an MQTT connection:
```
Jan 27 13:06:41 0578accd2d08 mosquitto[787]: 1737983201: New connection from 127.0.0.1:35138 on port 8883.
Jan 27 13:06:41 0578accd2d08 mosquitto[787]: 1737983201: OpenSSL Error[0]: error:0A000126:SSL routines::unexpected eof while reading
Jan 27 13:06:41 0578accd2d08 mosquitto[787]: 1737983201: Client <unknown> disconnected: Protocol error.
```
To be compared to a client that …
> test: Ignore flaky test failing on spurious OpenSSL errors

- docs/src/start/connect-c8y.md
- docs/src/start/getting-started.md
Add note to the "Getting Started" docs which tells the user that they need the "Tenant Manager" role assigned before they can upload a certificate and add a link to instructions on how to do this in c8y.
https://github.com/thin-edge/thin-edge.io/issues/3353
> docs: add c8y tenant manager note to getting started guide

- docs/src/operate/c8y/cloud-profiles.md
Add a missing positional argument to the `tedge connect` command which shows users how to use the cloud profiles feature with Cumulocity.
https://github.com/thin-edge/thin-edge.io/issues/3378
> docs: add missing c8y argument to cloud connect command

- docs/src/operate/c8y/smartrest-one.md
Fix an invalid tedge config key in the example, and improve the UX of the examples by adding a title and avoid using confusion by using shell redirection characters when showing customizing the credentials file path.
https://github.com/thin-edge/thin-edge.io/issues/3240
> docs: fix Cumulocity username/password instructions

- tests/RobotFramework/tests/customizing/tedge_init.robot
Fix flaky system tests (after discovering failed test run https://github.com/thin-edge/thin-edge.io/actions/runs/13239647793), where the already running tedge services would affect the output as the services also call `tedge init` when starting up.
* Failed test run: https://github.com/thin-edge/thin-edge.io/actions/runs/13239647793
> test: stop services during setup to prevent tedge init race condition

- crates/core/tedge/src/cli/mqtt/cli.rs
- crates/core/tedge/src/cli/mqtt/publish.rs
- crates/core/tedge/src/cli/mqtt/subscribe.rs
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
https://github.com/thin-edge/thin-edge.io/issues/3395
> fix: tegde mqtt panics on invalid MQTT topics

- crates/core/tedge_agent/src/agent.rs
- crates/core/tedge_agent/src/entity_manager/tests.rs
- crates/core/tedge_api/src/entity_store.rs
- tests/RobotFramework/tests/tedge_agent/http_server/entity_query_rest_api.robot
- tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
The entity store need not add a default service type to the entity if the service type is not provided in the registration message. The service type is mandatory only for the Cumulocity mapper and not for any other tedge components.
<br/>
> refactor: No default service type in entity store

- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-firmware-plugin/deb/prerm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postinst
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postrm
- configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/prerm
- configuration/package_scripts/_generated/tedge-agent/deb/postinst
- configuration/package_scripts/_generated/tedge-agent/deb/postrm
- configuration/package_scripts/_generated/tedge-agent/deb/prerm
- configuration/package_scripts/_generated/tedge-mapper/deb/postinst
- configuration/package_scripts/_generated/tedge-mapper/deb/postrm
- configuration/package_scripts/_generated/tedge-mapper/deb/prerm
- configuration/package_scripts/_generated/tedge-watchdog/deb/postinst
- configuration/package_scripts/_generated/tedge-watchdog/deb/postrm
- configuration/package_scripts/_generated/tedge-watchdog/deb/prerm
- configuration/package_scripts/templates/deb/postinst-systemd-dont-enable
- configuration/package_scripts/templates/deb/postinst-systemd-enable
- configuration/package_scripts/templates/deb/postinst-systemd-restart
- configuration/package_scripts/templates/deb/postinst-systemd-restartnostart
- configuration/package_scripts/templates/deb/postinst-systemd-start
- configuration/package_scripts/templates/deb/postrm-systemd
- configuration/package_scripts/templates/deb/prerm-systemd
- configuration/package_scripts/templates/deb/prerm-systemd-restart
Add additional checks to the `*.deb` (Debian) packages' maintainer scripts to check if the helpers (e.g. `deb-systemd-helper` and `deb-systemd-invoke`) are available before using them. If they are not available, then fallback to `systemctl` commands. Beaware that the debian helper scripts do more than what systemctl does, so there is not always a systemctl equivalent command, but this is ok.
The main motivation for this PR is to be more compatible with a Yocto based distribution where it can include the APT package manager but the debian helper scripts are not installed. This allows the debian packages to be installed on these Yocto images without printing warnings and failing to do the systemd service management actions (e.g. enable, start, restart etc.).
Writing a system test to check …
> fix: fallback to systemctl command when debian helpers are not available

- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_timeout/custom_operation.robot
Remove the (now) unnecessary restarting of the tedge-mapper during the test as the mapper should be able to detect such changes dynamically.
A fixed sleep is used instead to give the mapper a grace period to detect the change (e.g. via hanlding of the the inotify event).
The change was motivated by observing a local test failure during a flake finder run, where it seemed that restarting the mapper would negatively affect the test by introducing unnecessary noise (though exact reason does not matter too much as the restart is now unnecessary).
<br/>
> test: avoid restarting the tedge-mapper during the test

- .devcontainer/Dockerfile
Building the dev container is very slow (over 1 hour) and it has been failing for the last few weeks. It seems that this in part due to building some of the Rust tools from source (and this is really slow when compiling under CPU emulation which is used by docker when building multi-arch images).
Instead, use `cargo-bininstall` to install these additional tools to speed up the process.
You can see the recent slow builds here:
* https://github.com/thin-edge/thin-edge.io/actions/workflows/devcontainer.yml
<br/>
> dev: use cargo-bininstall to install additional rust tooling

- configuration/package_scripts/_generated/tedge/apk/postinst
- configuration/package_scripts/_generated/tedge/deb/postinst
- configuration/package_scripts/_generated/tedge/rpm/postinst
- configuration/package_scripts/tedge/postinst
Since postinst failures can cause issues with packages manager (e.g. apt broken packages) which can make it harder to fix. The package status isn't dependent on the recreation of the bridge, so it shouldn't influence the install status.
The [referenced ticket](https://github.com/thin-edge/thin-edge.io/issues/3408) suggests a broader scope to improve the robustness to handle upgrade/configuration scenarios more securely, however these larger changes are not part of the scope of this PR. This PR just focuses on reducing immediate problems.
https://github.com/thin-edge/thin-edge.io/issues/3408
> fix: only warn if refresh-bridges fails during installation

- Cargo.lock
- crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
- crates/core/tedge_actors/src/runtime.rs
- crates/extensions/tedge_mqtt_bridge/Cargo.toml
- crates/extensions/tedge_mqtt_bridge/src/backoff.rs
- crates/extensions/tedge_mqtt_bridge/src/health.rs
- crates/extensions/tedge_mqtt_bridge/src/lib.rs
- crates/extensions/tedge_mqtt_bridge/src/test_helpers.rs
- crates/extensions/tedge_mqtt_bridge/src/topics.rs
- crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
This is an attempt at testing the built-in bridge without relying on a real MQTT broker and client. This has a few advantages:
- It's faster than spinning up an MQTT broker
- It's not performance sensitive. I don't know fully how rumqttc tries to deal with excessive load, but I believe our existing tests sometimes put it under more pressure than its happy with, and this causes the connections to fail.
- It's deterministic - if we need to reproduce errors, we can do this directly, we don't have to merely hope that we reproduce the edge case we are attempting to test
Some of the logic we want to test concerns connecting to the broker, this is not something we can cover here. However, this approach should allow us to perform simpler integration tests that are much less likely to suffer from …
> test: add deterministic tests for the built-in bridge

- crates/core/tedge_agent/src/entity_manager/server.rs
- crates/core/tedge_agent/src/entity_manager/tests.rs
- crates/core/tedge_agent/src/http_server/entity_store.rs
- crates/core/tedge_api/src/entity.rs
- crates/core/tedge_api/src/entity_store.rs
- crates/core/tedge_api/src/mqtt_topics.rs
- crates/extensions/c8y_mapper_ext/src/availability/actor.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/entity_cache.rs
- crates/extensions/c8y_mapper_ext/src/inventory.rs
- crates/extensions/c8y_mapper_ext/src/service_monitor.rs
- crates/extensions/tedge_health_ext/src/lib.rs
- tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
- tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
> feat: Initial twin data from entity registration message

- tests/RobotFramework/tests/cumulocity/software_management/software.robot
Soften the test assertion when checking for the Cumulocity SmartREST message related to advanced software management list.
Since the tedge-mapper-c8y is restarted it is hard to check if any existing operations created by the mapper itself are still in progress or not at the time that the service is restarted.
https://github.com/thin-edge/thin-edge.io/issues/3426
> test: remove maximum mqtt message count assertion

- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/bridge_config/builtin_bridge.robot
Update the robotframework-c8y library to 0.40.x which includes a fix to fail if Measurement/Event/Alarm count assertions are missing the Cumulocity source value (set explicityly by the user, or via the current c8y context).
This should avoid assertions passing if Measurement/Events/Alarms are detected for other devices (due to the missing device source query parameter used in the Cumulocity REST API call).
With the change, another test was detected which didn't set the c8y device context before running an assertion. The fix for this test is included in this PR.
Example of a PR which fixed an issue where the device context was not called prior to the assertion:
* https://github.com/thin-edge/thin-edge.io/pull/3422
> tests: update robotframework-c8y library to detect missing source in c8y api

- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Improve a flaky system test by ensuring the `tedge-mapper-c8y` service is running.
Whilst it might include some duplicate in the `tedge-mapper-c8y` test case, where the tedge-mapper-c8y service is started twice, this does not cause any problems as the second service start will be a no-operation as systemd does not restart an already started service.
**Flakey System Test Root cause**
The Robotframework test cases are not isolated so they are run in the same container. When the **tedge-mapper-c8y** test case ends, it will stop the service which can cause some of the following services to fail if the services (which are started by default in the `Test Setup`) were published to Cumulocity before the `tedge-mapper-c8y` service was stopped.
https://github.com/thin-edge/thin-edge.io/issues/2427
> tests: ensure tedge-mapper-c8y is running before running assertions

- tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
Refactor the inventory update test case to address a flaky test issue.
**Root Cause**
* Some inventory fragment values were being checked without checking if the value exists. The test was making an assumption that if fragment1 exists then fragment2 should also exist (which is wrong as the updates are sent as individual messages and processed indpendently by the server).
https://github.com/thin-edge/thin-edge.io/issues/3434
> tests: check if all fragments exist first before checking the value

- .github/workflows/build-workflow.yml
- .github/workflows/pull-request-checks.yml
- .github/workflows/release.yml
Github Runner [ubuntu-20.04 is deprecated](https://github.com/actions/runner-images/issues/11101) so upgrading to `ubuntu-22.04`
> ci: upgrade to ubuntu-22.04

- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
Remove the maximum MQTT message count assertion due to sporadic failures on the CI runner. The failures occur because sometimes the mapper recieves duplicated operations from the cloud and this will result in the operation being processed twice (despite having the same operation id).
The test failures are tracked here:
* https://github.com/thin-edge/thin-edge.io/issues/3399
A [ticket has been created](https://github.com/thin-edge/thin-edge.io/issues/3403) to address the duplicate operations from the cloud, so once that it implemented then the assertion can be reinstated.
https://github.com/thin-edge/thin-edge.io/issues/3399
> tests: ignore maximum message count assertion due to sporadic test failures

- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/availability/builder.rs
- crates/extensions/c8y_mapper_ext/src/availability/tests.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
Remove from C8yMapperActor the publish_messages receiver
The motivation, for this receiver of wrapped MqttMessages, was that: "other actors may want to send MqttMessages but we want to ensure that the entity referred to in the message topic exists; that's why we route them to the mapper rather than to MqttActor directly."
However, the C8yMapperActor was sending these messages unchanged. And futhermore, this was requiring a specific mechanism to avoid deadlocks. Better to remove all that, and let the other actors (actually only the AvailabilityActor) send their messages directly over MQTT.
https://github.com/thin-edge/thin-edge.io/issues/3368
> refactor: Remove from C8yMapperActor the publish_messages receiver

- crates/core/c8y_api/src/json_c8y_deserializer.rs
- crates/core/tedge_api/src/device_profile.rs
- crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
- docs/src/references/agent/device-profiles.md
This PR fixes an issue where the `skip` field in the device profile was treated as mandatory by serde. Now, if the field is omitted, it defaults to `false`. Additionally, the field has been renamed to `@skip` so that it is properly recognized by the workflow and aligns with our documentation. Finally, this PR addresses a problem where the mapper did not verify whether an operation fragment sent to the cloud was marked as skipped.
<br/>
> fix: make device profile `skip` field optional and skip operation fragment when it is set to `true` 

- docs/src/operate/c8y/smartrest-templates.md
Change the SmartREST 2.0 guide to refer to the external id of a template to avoid confusion for users using custom templates.
This PR was promopted by direct customer feedback where a custom template was being created where the name of the template differed from the external id, so when configuring thin-edge.io, the template's name was incorrectly refererned instead of the templates's external id.
<br/>
> docs: use SmartREST 2.0 external id terminology instead of name

- crates/core/tedge/src/cli/mqtt/cli.rs
- crates/core/tedge/src/cli/mqtt/subscribe.rs
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
- tests/RobotFramework/tests/tedge/tedge_mqtt.robot
This PR introduces two new options to `tedge mqtt sub` to give a break to the command.
```shell
-W, --duration <DURATION>
Set a timeout duration (e.g., 60s, 1h)
-C, --count <COUNT>
Set the number of packets before stopping
```
* `--duration`: `tedge mqtt sub` breaks after given time. e.g.,
```
tedge mqtt sub "#" --duration 10s
```
* `--count`: `tedge mqtt sub` breaks after the given number of packets received. e.g.,
```
$ tedge mqtt sub "#" --count 3
INFO: Connected
[te/device/main/service/c8y-firmware-plugin] {"@parent":"device/main//","@type":"service","type":"service"}
[te/device/main/service/c8y-firmware-plugin/status/health] {"pid":1400,"status":"down"}
[te/device/main/service/mosquitto-c8y-bridge] {"@id":"rina0010:device:main:service:mosquitto-c8y-bridge","@parent":"device/main//","@ …
```
> feat: add optional break conditions to `tedge mqtt sub`

- Cargo.lock
Bump ring dependency due to a new security alert for ring 0.17.7 (https://rustsec.org/advisories/RUSTSEC-2025-0009).
Looking at the notice, it doesn't seem that thin-edge.io would be affected by this, however bumping the version is still the safer approach.
https://rustsec.org/advisories/RUSTSEC-2025-0009
> chore: update ring prompted by RUSTSEC-2025-0009

- .github/pull_request_template.md
- CONTRIBUTING.md
- ci/dev/add-git-hook-prepare-commit.sh
- justfile
Since our contributing guide requests that all commits be signed off, this add a task to make it easier for users to fullfil such a requirement by adding a git pre-commit hook (as finding the right docs about this is more complicated than it needs to be).
Now users can simply run the following task once:
```sh
just prepare-dev
```
<br/>
> dev: add task to add a git commit hook for adding the signoff option

- .github/pull_request_template.md
- CODING_GUIDELINES.md
- justfile
The contributing guide was no longer aligned with common project tasks (e.g. using `cargo fmt` instead of `just format`), to ensure any changes run both Rust and system tests requirements (and can cater for any future extension of these tasks).
Note: The build guide will be updated in a separate PR as it has also become stale.
<br/>
> dev: update commands in contributing guide

- justfile
- tests/RobotFramework/tasks.py
- tests/RobotFramework/tests/tedge/device_id/device_id_derivation.robot
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Some Robotframework linting violations were found in the tests due to the CI job only running the format check but not the lint checking. To avoid this in the future, the format and lint checks have been combined into one (python) task, and they are executed both when running `just check` (not run during CI) and `just format-check` (run during CI).
The linting violations have also been resolved in this PR.
<br/>
> test: fix robotframework tests lint/format checks and ci checks

- .github/workflows/build-workflow.yml
Fix a minor typo found in a comment in the GitHub build-workflow.yaml
<br/>
> chore: fix typo in gh workflow

- .github/workflows/pull-request-checks.yml
- justfile
Failing on unmaintained crates is introducing too much churn into the project. Whilst it is generally beneficial to be aware of crates which are "no longer maintained", it rarely requires immediate action. And switching from a crate to fork, or a similar crate just introduces unwanted risk into the project.
The PR therefore disables the "unmaintained" errors, and instead manual periodic assessments on the state of the dependencies can be evaluated by a human to check whether switching to a different crate makes sense or not.
<br/>
> ci: ignore unmaintained crate errors due to unnecessary project churn

- ci/admin/cloudsmith_admin.sh
- ci/build_scripts/publish_packages.sh
Try to improve reliability of installing cloudsmith-cli via pip by ignore any pre-existing cache (based on [this post](https://stackoverflow.com/questions/16025788/why-does-pip-fail-with-bad-md5-hash-for-package)).
Below shows the pip error which sometimes occurs (seen in the build workflow publishing step):
```
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
unknown package:
Expected sha256 c7362add18b416b69d58c910caa217f980c5ef39b23a38a0880dfd87bdf8cd23
Got        baed275f67435c0067eaba69efb88808069091d6e0eb3ea6c228c0c21f978855
```
Failures have been …
> ci: ignore pip cache when installing cloudsmith-cli

- crates/common/tedge_config_macros/src/multi.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/cli/connect/jwt_token.rs
- crates/core/tedge_agent/src/operation_workflows/persist.rs
- crates/core/tedge_api/src/workflow/state.rs
- plugins/c8y_remote_access_plugin/src/input.rs
> refactor: Fix clippy warnings

- .devcontainer/Dockerfile
- justfile
Installing of the `rls` component via `rustup component add` fails as the deprecated `rls` component has been removed from Rust nightly.
* Failed build due to the removal of `rls` in the nightly branch. https://github.com/thin-edge/thin-edge.io/actions/runs/13860070512/job/38786081374?pr=3472
> dev: replace deprecated rust language server (rls) with rust-analyzer

- plugins/c8y_remote_access_plugin/src/proxy.rs
- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/tasks.py
Fix c8y-remote-access-plugin functionality by adding missing header. Previous versions of the websocket crate were not particular about the missing header, however now it closes the connection if it is not present.
The system tests have also been enabled again.
* https://github.com/thin-edge/thin-edge.io/issues/3475
> fix: c8y-remote-access-plugin websocket connection

- docs/src/start/connect-c8y.md
Move common errors section to its own subheader as these are common errors that could occur during any of the stages (e.g. uploading the certificate or when connecting to c8y). Previously the common errors section was only under the "Making the device trusted by Cumulocity section".
Also add a user tip to at the top of the page to direct them to look at the common errors section if they run into any unexpected errors.
<br/>
> docs: move common errors section to its own subheader

- crates/common/tedge_config/src/tedge_toml/models/auth_method.rs
- crates/core/tedge/src/bridge/aws.rs
- crates/core/tedge/src/bridge/azure.rs
- crates/core/tedge/src/bridge/c8y.rs
- crates/core/tedge/src/bridge/config.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/cli/log.rs
Skip changing ownership for device certificate as it is not needed when connecting via Basic Auth credentials.
#3476
<br/>
> fix: skip chown for cert and key when using Basic Auth

- ci/build_scripts/package.sh
- mk/cargo.sh
- mk/install-build-tools.sh
**Note:** This does not mean that thin-edge.io will/can support android, it is just removing explicit limitations when building thin-edge.io for android targets if someone wants to explore this topic further. This topic arose after hearing a discussion about "does thin-edge.io support Android", so some time was invested into trying to get thin-edge.io to compile (not work, just compile).
Changes:
* Update Android SDK version
* Use Android Platform API 24 (minimum version which will compile due to the usage of user/group API calls to`getgrnam_r`, see [reference](https://android.googlesource.com/platform/bionic/+/HEAD/docs/status.md))
* Add additional Android targets to build script
Since the changes aren't adding the new targets into the build job, an example showing that the binaries can …
> ci: remove blockers to build for android targets

- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Add for the Robotframework robocop linter for the large JSON payloads which are formatted for readability rather than following the linting rules.
An exception was already added for the robotidy (auto formatter), but not for robocop (linter).
<br/>
> test: add robocop lint exception for the large JSON payloads

- crates/common/tedge_config/src/tedge_toml/figment.rs
Allow a configuration to be reset to the default by passing an environment variable value of `''` (an empty string). Previously, to "undo" the effects of setting a `TEDGE_` variable for configuration (so you can use the default value), you would need to unset the value
- #3414
> feat: allow environment variables to be reset by setting them to the empty string

- crates/common/tedge_config_macros/impl/src/input/parse.rs
- crates/common/tedge_config_macros/impl/src/input/validate.rs
- crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
- crates/core/plugin_sm/src/plugin_manager.rs
- crates/core/tedge_actors/src/runtime.rs
- crates/core/tedge_api/src/workflow/log/logged_command.rs
- crates/extensions/tedge_script_ext/src/lib.rs
- plugins/c8y_remote_access_plugin/src/lib.rs
Adds a missing `format!` in one command error to print the command line and resolve trivial clippy 1.78 lints.
The suggested fixes use version 1.74, our MSRV is 1.78 so it should be okay.
There are two categories of lints left to address:
- ~~`large_enum_variant`: this is in `tedge_config_macros`, and probably only has very very small impact on macro compilation speed, so we can most likely ignore it and apply `#[allow]`, but defering to @jarhodes314 as the author.~~
Added `#[allow]` because it's low impact macro code, see https://github.com/thin-edge/thin-edge.io/pull/3500#issuecomment-2751082148
- `result_large_err`: there's loads and loads of instances of this lint being triggered by the amount of big error enums that we have (by both byte-size and number of variants). Lower level …
> chore: Add missing `format!` and resolve trivial clippy 1.87 lints

- ci/build_scripts/publish_packages.sh
Support for filtering which packages are published to Cloudsmith via a flag. By default, the `*` character is used (as this is the current behaviour prior to this PR).
This change was motivated by the upcoming tedge-p11-server support which requires publishing a subset of packages.
<br/>
> ci: support filtering the list of packages to publish

- .github/workflows/build-workflow.yml
Improve the build-workflow to allow the target cloudsmith repository to be changed by simply changing the `PUBLISH_REPO` secret project's settings. This makes it easier to check the publishing of packages to forks, as the target repo can be redirected to a the project's test repo (`tedge-dev`).
The change was motivated by the ongoing work to package the new tedge-p11-server package which requires significant changes to the packaging and publishing logic.
<br/>
> ci: allow projects to control where the packages are published to using secrets

- ci/build_scripts/publish_packages.sh
- mk/cargo.sh
- mk/install-build-tools.sh
Fix minor inconsistencies where not all supported targets were handled correctly, or some were just missing. Though none of the changes should impact the current set of targets that thin-edge.io builds for.
<br/>
> ci: build script fixes for various targets

- ci/build_scripts/package.sh
Fix inconsistency in the building of the tarball which assumes that `tedge` is the only binary that should be pacakged. In addition the existing code was very misleading as a list of packages were passed to it, but these were being ignored by the function.
Instead, just specify which binary should be included as part of the tarball (though it is still limited to 1 binary)
<br/>
> ci: parameterize the tarball contents

- docs/src/references/agent/index.md
Minor fix with a mermaidjs diagram used to display how the agent function as the previously used arrow direction (right-to-left) no longer renders correctly (it throws an exception), and rearranging the block sequence results in the entire diagram layout changing.
Long term it might be worth evaluating a different mermaid diagram type where the layout can be controlled more easily, but the newer types are not yet readily available.
**Before**
**After**
Link to the broken documentation rendering of the tedge agent diagram:
* https://thin-edge.github.io/thin-edge.io/next/references/agent/
> docs: use bi-directional arrow as right-to-left arrows cause a rendering issue in mermaid js

- crates/extensions/tedge_config_manager/src/lib.rs
- crates/extensions/tedge_log_manager/src/lib.rs
Fixes flaky `tedge_log_manager tests::default_plugin_config` and `tedge_config_manager tests::default_plugin_config` tests. [Here](https://github.com/thin-edge/thin-edge.io/actions/runs/14167661263/job/39684266274?pr=3519#step:11:2383) is the failed run for one of them, but the second one was reproduced locally to also fail for the same reason.
The tests themselves were not edited, but config creation code was modified to use `atomically_write_file_sync` function for the following reasons:
- The tests failed because the files were created, but haven't yet been written to. In the context of creating a config file atomicity isn't AFAIK crucial, but since the functions were available it was easy to use them and it fixed the issue.
- We were using async API to write a very small config file. …
> tests: fix flaky default_plugin_config tests

- .github/workflows/build-workflow.yml
- ci/build_scripts/build.sh
- ci/package_list.sh
- mk/install-build-tools.sh
Motivation: Building for the new tedge-p11-server component adds some additional build challenges due having to build this component with gnu libc (not musl!).
Normalize the building of thin-edge.io so that both local developers and the build workflow use the same entrypoint to build via `just release`, though each environment can still control which tooling is used to actually build the required binaries (e.g. clang (current default for the workflow), and cargo-zigbuild (previous default when running locally).
There are provisions in the build.sh script which:
* Select gnu vs musl based on binary target (tedge will use the given target, where as tedge-p11-server will be forced to use the musl equivalent)
* Use cargo-zigbuild to control which gnu libc version is used when building for gnu …
> ci: refactor build script and workflow

- crates/extensions/tedge-p11-server/src/pkcs11.rs
Use a custom debug impl to shorten cryptoki pin placeholder.
Previous:
```
INFO tedge_p11_server: crates/extensions/tedge-p11-server/src/main.rs:77: Using cryptoki configuration cryptoki_config=CryptokiConfigDirect { module_path: "/usr/lib/aarch64-linux-gnu/pkcs11/libtpm2_pkcs11.so", pin: Secret([REDACTED alloc::string::String]), serial: None }
```
Now:
```
INFO tedge_p11_server: crates/extensions/tedge-p11-server/src/main.rs:77: Using cryptoki configuration cryptoki_config=CryptokiConfigDirect { module_path: "/usr/lib/aarch64-linux-gnu/pkcs11/libtpm2_pkcs11.so", pin: "[REDACTED]", serial: None }
```
#3506
> feat: shorten cryptoki pin debug display placeholder

- crates/extensions/tedge-p11-server/build.rs
Align the version generation used for the tedge-p11-server with other tedge components, by deriving the version from the GIT distance instead of the static Cargo.toml version. This enables the component to uniquely versioned when being merged into the main branch.
**Before**
```sh
$ target/aarch64-apple-darwin/release/tedge-p11-server --version
tedge-p11-server 1.4.2
```
**After**
```sh
$ target/aarch64-apple-darwin/release/tedge-p11-server --version
tedge-p11-server 1.4.3~428+g42bf3a1
```
<br/>
> fix: use git semver generated version for tedge-p11-server

- crates/core/tedge/src/cli/certificate/c8y/mod.rs
Improve the compatibility of the tedge with other tooling which can be used for creating Certificate Signing Requests (CSRs). For example, the gnutls certtool (which supports creating CSRs from private keys stored in HSMs via PKCS11)
processes CSR files which use an older BEGIN/END blocks, and can also contain additional details about the CSR in plain text (so it is readable for humans).
https://github.com/thin-edge/thin-edge.io/issues/3546
> feat: support CSR file formats from gnutls certtool

- crates/common/tedge_config/src/tedge_toml/tedge_config.rs
- crates/core/c8y_api/src/smartrest/inventory.rs
- crates/extensions/c8y_mapper_ext/src/config.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/tests.rs
- docs/src/references/mappers/c8y-mapper.md
The static SmartREST template 101 is extended to accept boolean if a newly created child device should hold the `c8y_IsDevice` fragment.
This change adds a new tedge configuration to control it.
todos:
#3487
> feat: append the option whether to add c8y_IsDevice to child devices

- Cargo.lock
- crates/extensions/tedge-p11-server/Cargo.toml
- crates/extensions/tedge-p11-server/src/lib.rs
- crates/extensions/tedge-p11-server/src/main.rs
- crates/extensions/tedge-p11-server/src/server.rs
- crates/extensions/tedge-p11-server/src/service.rs
#3421 introduced a new component, `tedge-p11-server`, which wasn't accompanied by tests due to time pressures and packaging changes. This PR aims to improve testing of tedge-p11-server with 2 kinds of tests:
- Rust tests: testing things that don't require interaction with environment/hardware, i.e. communication between client and server, framing, serialization
- ~~Robot Framework tests: we'll probably need to use Robot Framework environment to setup a SoftHSM device to mock the real HSM device.~~ Because of the need to include tedge-p11-server in the test image and to build using a GNU libc, Robot Framework test is included as part of #3514.
<br/>
> tests: tedge-p11-server testing

- crates/core/tedge/src/cli/certificate/c8y/mod.rs
- crates/core/tedge/src/cli/certificate/cli.rs
Update the references to the now removed `--self-signed` flag (replaced by `--ca self-signed`).
One reference was just in a comment, and the other reference was in an error message where the message has been change to not explicitly mention the exact flag name.
<br/>
> fix: change references to the removed --self-update flag

- configuration/init/systemd/tedge-cert-renewer.target
- configuration/init/systemd/tedge-cert-renewer@.service
- configuration/init/systemd/tedge-cert-renewer@.timer
- configuration/init/systemd/tedge-mapper-c8y.service
- configuration/init/systemd/tedge-mapper-c8y@.service
- configuration/package_manifests/nfpm.tedge-mapper.yaml
- tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
Add certificate renewal service which is a dependency of the tedge-mapper-c8y service (and its systemd template variant).
The renewal is called by the systemd components (timer and script), however a script has been created to reliably renew the certificate and verify it and roll back to the previous certificate if necessary.
Note: The certificate renewer service will be installed and enabled by default when using the tedge-mapper-c8y service. However the renewal will fail if the user has not activated the new Cumulocity certificate-authority feature.
<br/>
> feat: add certificate renewal service

- crates/core/tedge_agent/src/entity_manager/server.rs
- tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
The test flakiness where the `twin/name` fragment was becoming `null` after the same was updated with a new value because of a faulty logic in how twin updates are handled. When a given twin fragment is updated with a new value, instead of overwriting the existing value with the new one, the current code was trying to clear the old value with a null message first, followed by publishing the updated value. This is the cause of the race, as sometimes, the `twin` query in the test was happening immediately after the `null` value is processed which results in empty response.
When existing twin data like {"a": 1, "b": 2, "c": 3} is updated with {"b": 2, "c": 4, "d": 5}, the update is handled as follows:
1. The removed key: "a" is cleared
2. The unchanged key: "b" is not republished
3. The …
> fix: Avoid clearing updated keys on twin update

- Cargo.lock
- Cargo.toml
- configuration/init/systemd/tedge-p11-server.service
- crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
- crates/extensions/tedge-p11-server/Cargo.toml
- crates/extensions/tedge-p11-server/src/lib.rs
- crates/extensions/tedge-p11-server/src/main.rs
- crates/extensions/tedge-p11-server/src/pkcs11.rs
- crates/extensions/tedge-p11-server/src/service.rs
- crates/extensions/tedge-p11-server/src/signer.rs
- tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Allows the user to denote private key that will be used by `tedge-p11-server` for signing by a new optional `--uri` parameter.
The PKCS #&NoBreak;11 URI is explained in [RFC 7512](https://www.rfc-editor.org/rfc/rfc7512.html). It can be used to identify any cryptoki resource by its properties. In our case it's used to select a key, but the URI given by the user doesn't have to identify a key, but can identify e.g a token which we can select and ~~find its first~~ if the token contains only one private key, use that key.
- #3538
> feat: Key selection using PKCS #11 URI

- crates/core/tedge_api/src/mqtt_topics.rs
The default string deserializer bypasses the `FromStr` implementation, which is responsible for normalizing the topic ID (e.g., ensuring it has the correct number of segments by appending slashes). As a result, invalid or malformed IDs could be silently accepted.
This commit adds a custom deserializer that properly delegates to EntityTopicId's `FromStr` implementation, enforcing consistent parsing and validation during deserialization.
Found in #3537
> fix: ensure EntityTopicId deserialization uses FromStr logic

- crates/core/c8y_api/src/http_proxy.rs
- crates/core/tedge_agent/src/entity_manager/server.rs
- crates/core/tedge_agent/src/entity_manager/tests.rs
- crates/core/tedge_agent/src/http_server/entity_store.rs
- crates/core/tedge_api/src/entity.rs
- crates/core/tedge_api/src/entity_store.rs
- crates/core/tedge_api/src/mqtt_topics.rs
- crates/extensions/c8y_http_proxy/src/actor.rs
- crates/extensions/c8y_http_proxy/src/handle.rs
- crates/extensions/c8y_mapper_ext/src/actor.rs
- crates/extensions/c8y_mapper_ext/src/availability/actor.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
- crates/extensions/c8y_mapper_ext/src/entity_cache.rs
- crates/extensions/c8y_mapper_ext/src/json.rs
- crates/extensions/c8y_mapper_ext/src/serializer.rs
- crates/extensions/c8y_mapper_ext/src/service_monitor.rs
- crates/extensions/tedge_health_ext/src/lib.rs
- crates/extensions/tedge_http_ext/src/messages.rs
- tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
- tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
https://github.com/thin-edge/thin-edge.io/issues/3342
> feat: Entity PATCH API to update parent of an entity

- crates/core/tedge_api/src/workflow/handlers.rs
- crates/core/tedge_api/src/workflow/state.rs
- crates/core/tedge_api/src/workflow/toml_config.rs
- Preserve workflow failure reasons if set by a state
https://github.com/thin-edge/thin-edge.io/issues/3582
> fix: Overwritten workflow failure reason

- docs/src/install/index.md
- docs/src/operate/registration/register.md
> doc: Entity PATCH API to update entity definition

- crates/core/tedge_agent/src/entity_manager/server.rs
- crates/core/tedge_agent/src/http_server/entity_store.rs
- crates/core/tedge_api/src/entity_store.rs
- crates/extensions/c8y_mapper_ext/src/availability/builder.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
Parse entity registration message using serde for better error messages.
<br/>
> refactor: parse entity registration message using serde

- crates/extensions/tedge-p11-server/src/pkcs11.rs
- tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Correctly sign the message when an RSA instead of ECDSA key is used.
#3573
> feat: tedge-p11-server support RSA keys

- crates/extensions/tedge_health_ext/src/lib.rs
- crates/extensions/tedge_health_ext/src/tests.rs
Include `name` in tedge service registration message, along with `type` that already existed. This prevents the any auto-registration messages generated for the same service, with the `name` fragment, from conflicting with their initial explicit registration message.
https://github.com/thin-edge/thin-edge.io/issues/3591
> fix: Include name in tedge service registration message

- Cargo.lock
- Cargo.toml
> release: minor version bump

- docs/src/install/index.md
- docs/src/start/getting-started.md
- tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
Add instructions and system tests for installing thin-edge.io on a device which is in a network behind a HTTP proxy
Note: Requires the following PR to be merged before the system tests will work:
* https://github.com/thin-edge/thin-edge.io-website/pull/75
<br/>
> docs: add instructions and tests on how to install thin-edge.io behind a proxy

- tests/RobotFramework/requirements/requirements.txt
- tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
- tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
- tests/RobotFramework/tests/customizing/config_dir.robot
- tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Use the new robotframework-c8y `Get Domain` keyword to normalize the usage in the tests (as there was also a previous bug in the `sed` usage).
Corresponding change in the RF library: https://github.com/thin-edge/robotframework-c8y/pull/31
<br/>
> test: use new library keyword to get c8y domain

- crates/common/mqtt_channel/src/connection.rs
Ensure that all outstanding publishes are sent when running `tedge mqtt pub -q 2 ...`.
The root cause was the queue in rumqttc's event loop. When we attempt to publish a message, this is sent to the event loop via a channel. In the case of this bug, the event loop didn't receive this publish notification before we detected the sender loop had shut down, and thus we started the disconnection process before publishing the message. The publish would still be processed before the disconnect request, but the disconnection caused us not to respond to the broker's PubRec acknowledgement, thus the QoS 2 message wasn't fully processed.
- #3512
> fix: ensure that `tedge mqtt pub` fully publishes messages sent with QoS 2

- crates/common/tedge_config/src/tedge_toml/tedge_config.rs
- docs/src/references/hsm-support.md
- docs/src/references/tedge-p11-server.md
Update main HSM documentation page to remove outdated information and use `tedge-p11-server` and add a reference page about `tedge-p11-server` itself.
#3594
> docs: Add `tedge-p11-server` reference and update `hsm-support.md`

- docs/src/references/certificate-management.md
Fix a broken document link picked up by the Github workflow which builds the production documentation.
* https://github.com/thin-edge/thin-edge.io/actions/runs/14995316317/job/42128024687
<br/>
> docs: fix broken document link

- tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
Enable the Cumulocity certificate-authorith system tests now that the Cumulocity tenant used for the tests has the feature enabled now.
<br/>
> tests: enable Cumulocity certificate-authority system tests

- crates/core/tedge_actors/src/actors.rs
- crates/core/tedge_actors/src/converter.rs
- crates/core/tedge_actors/src/messages.rs
- crates/core/tedge_actors/src/servers/mod.rs
- crates/core/tedge_actors/src/test_helpers.rs
- crates/extensions/tedge_timer_ext/src/builder.rs
- crates/extensions/tedge_timer_ext/src/tests.rs
Remove the useless `Sync` trait constraint on `Actor`
<br/>
> refactor: Remove useless Sync constraint on actors

- crates/core/plugin_sm/src/plugin.rs
- crates/core/plugin_sm/src/plugin_manager.rs
- crates/core/plugin_sm/tests/plugin.rs
- crates/core/tedge_api/src/workflow/log/command_log.rs
- crates/core/tedge_api/src/workflow/log/logged_command.rs
- crates/extensions/c8y_mapper_ext/src/converter.rs
Standardize the use of configurable temporary directories across `LoggedCommand` and related areas. This removes hardcoded `/tmp` paths and enables consistent directory management by using `tmp.path` from tedge config.
This PR removes 3 todos related to the hardcoded `/tmp` directory path.
```rust
command
// TODO: should use tmp from config
.current_dir("/tmp")
.stdin(Stdio::piped())
.stdout(Stdio::piped())
.stderr(Stdio::piped());
```
<br/>
> refactor: remove hardcoded temporary directory handling in LoggedCommand

- tests/RobotFramework/pyproject.toml
- tests/RobotFramework/requirements/requirements.dev.txt
- tests/RobotFramework/resources/common.resource
- tests/RobotFramework/tasks.py
- tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
robotidy has been [deprecated][dep] and it's functionality has been moved to robocop. This commit upgrades robocop to use the new formatting functionality and removes robotidy.
Apart from the deprecation, the change was made because robotidy formatted code in a [manner inconsistent with robocop][issue]. After the upgrade, robocop applies correct formatting.
[dep]: https://github.com/MarketSquare/robotframework-tidy/blob/a4940bd/README.md#deprecation-notice
[issue]: https://github.com/MarketSquare/robotframework-tidy/issues/744
<br/>
The above mentioned issue with incorrect `robotidy` formatting caused format check failures in #3631, so this PR will have to be merged first to fix the format check.
https://github.com/thin-edge/thin-edge.io/actions/runs/15142269251/job/42569282617?pr=3631
> style: upgrade robocop to 6.1.1 and remove robotidy

- docs/src/references/hsm-support.md
- docs/src/references/tedge-p11-server.md
Fix some broken anchors in the tedge-p11-server reference guide which linked back to the HSM doc page.
Note: Using explicit anchor tags for section which are referenced on another page is preferred otherwise if the title is changed, then the reference also breaks.
In addition, some trailing whitespace was also removed from the HSM page, and a reference to `thin-edge` was replaced with the `%%te%%` variable.
The broken anchors were detected when building the tedge-docs locally:
```sh
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /thin-edge.io/next/references/tedge-p11-server/:
-> linking to /thin-edge.io/next/references/hsm-support/#part-2-thin-edge-setup
- Broken anchor on source page path = /thin-edge.io/references/tedge-p11-server/:
-> linking to …
```
> docs: fix broken anchors in HSM / tedge-p11-server docs

- crates/extensions/tedge-p11-server/src/pkcs11.rs
This is a small refactor extracted from #3631 and made into a separate PR to get a cleaner diff and for easier comparison of code required to support EC keys to code required to support RSA keys, once RSA PR is made.
The main improvements of this refactor are:
- Remove separate structs for EC keys and RSA keys, use a single struct that contains a sigscheme to be used
- create a struct for sigschemes we support, so it's easier to see at a glance what's supported and extraneous unwraps/checks can be removed because we rely on the type system more
- remove duplicate attribute query when signing, use a sigscheme we saved when creating the signing key struct
<br/>
Previously the behaviour was a little bit wrong because if we got an EC key we put 3 different signature schemes as "supported" for …
> refactor: Use one SigningKey struct

- crates/extensions/tedge-p11-server/src/pkcs11.rs
- tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Currently we support only EC keys using curve SECP256R1, as during initial development we confirmed that C8y, Azure and AWS all offered `ecdsa_secp256r1_sha256` sigscheme. However, if that ever changes, or if a user simply wishes to use a bigger key, it is impossible to connect. Therefore we should support the other sizes of EC keys. 
<br/>
> feat: PKCS11 support EC SECP384R1 and SECP521R1 keys

- docs/src/understand/faq.md
Fix minor markdown typo on the FAQ page.
<br/>
> docs: fix markdown typo in link

- clippy.toml
Remove rules from clippy.toml for types and methods that were unreachable and were being marked as warnings by clippy from nightly-2025-05-25.
On April 1, a PR was merged into clippy to check if paths in `disallowed_*` configurations are actually reachable. In our case, some rules relating to hyper and reqwest::blocking were outdated probably due to upgrades of versions of these crates.
This commit removes the outdated rules, but alternatively we could set `allow-invalid` field to silence the warnings but keep the rules, e.g. if we expect to add `reqwest::blocking` back in the future.
<br/>
> tools: Remove obsolete clippy disallowed rules

- crates/core/tedge/src/cli/diag/cli.rs
- tests/RobotFramework/tests/tedge/diag/tedge_diac_collect.robot
Rename an option of diagnostic CLI from `--tarball-name` to `--name` as suggested by @albinsuresh.
Bullet point 5. of https://github.com/thin-edge/thin-edge.io/issues/3646#issuecomment-2930392519
> refactor: rename option for output tarball name

- crates/core/tedge/src/cli/certificate/show.rs
Improve the certificate validity duration by only using years, days, hours, minutes and seconds (avoiding months), to align to user expectations and avoid the "days in a month" rounding errors in the total duration.
Some examples of the duration in the new format:
* 364d 8h 42m 43s
* 5y 219d 2h 59m
* 2y
* 2h 1m 3s
**Background**
The [humantime](https://github.com/chronotope/humantime/blob/3f8526fcdf213cc082a14cc2bc14ac7f96bda510/src/duration.rs#L301) crate uses averaged units in the conversion to a human time, so for a duration spanning months, then the remaining hours part of the duration can get skewed unexpectedly (from the users perspective).
For instance, when a certificate is renewed using the Cumulocity Certificate Authority, the new certificate has a validity of 1 year (~365 days …
> feat: avoid using months when displaying certificate duration

- configuration/schema/tedge-alarm.schema.json
- configuration/schema/tedge-event.schema.json
- configuration/schema/tedge-measurement.schema.json
> docs: Add JSON schema for MEA MQTT messages

- docs/src/operate/c8y/apama.md
Update the Apama repository installation instructions to use the latest version (from 2026), and add guidance about finding the correct Debian version from the package.
<br/>
> docs: update Apama repository docs to use latest 2026 version

- configuration/package_manifests/nfpm.tedge.yaml
- tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
Two small changes
- Fix typo in the robot file name (diac -> diag)
- Include `template.sh.ignore` to the package
<br/>
> chore: add template.sh.ignore to package and fix typo

- docs/src/contribute/build.md
Update the build instructions in the contribution guide in the public docs.
Note: The reference to how to run the system tests is currently not mentioned for the moment due to being a bit more complicated to setup (and has additional requirements such as docker).
<br/>
> docs: update build instructions

- crates/extensions/c8y_mapper_ext/src/operations/convert.rs
- crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
- docs/src/references/agent/device-profiles.md
Change the default processing order of artifacts included in a device profile operation, where configuration is processed before software. The new order supports more use-cases out-of-the-box.
Technically this is a breaking change as it changed the behaviour, however we believe it will only positively impact users and remove common annoyances with the existing processing order.
**Old Processing Order**
* Firmware
* Software
* Configuration
**New Processing Order**
* Firmware
* Configuration
* Software
Below lists the advantages and disadvantages of the change:
**Advantages**
* Repositories can be configured (with credentials or proxy settings) before applications/containers are installed via software
* Configuration can be applied before the application/container starts the first time …
> feat: process configuration before software in device profile operations

- crates/core/tedge/src/cli/diag/collect.rs
- crates/core/tedge/src/cli/diag/logger.rs
- crates/core/tedge/src/cli/diag/mod.rs
- tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
The copy of the console output by `tedge diag collect` is now added as `summary.log` to a tarball archive.
#3646
> feat: tedge diag adds summary output to the archive

- docs/src/operate/security/cloud-authentication.md
- docs/src/start/connect-c8y.md
Improve the instructions for users when they're using thin-edge.io to communicate with a server which is using self-signed certificates.
The new one-liner only downloads the root certificate and not the full chain.
<br/>
> docs: add tip on how to download only the root certificate using openssl and awk

- crates/core/tedge_agent/src/entity_manager/server.rs
- crates/core/tedge_agent/src/entity_manager/tests.rs
- tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Include health status in the list of persistent topics that are cleared on entity deregister.
NOTE: measurement and event data are intentionally excluded to avoid unnecessarily fetching a huge volume of telemetry data on a deregistration attempt, especially since we don't expect any retained messages on these topics. That means, if a user accidentally publishes a retained message on these topics, it won't be cleared.
https://github.com/thin-edge/thin-edge.io/issues/3632
> fix: clear health status on entity deregister

- crates/core/c8y_api/src/http_proxy.rs
Add a timeout when trying to. connect to the local mqtt broker when fetching a jwt in the c8y-remote-access-plugin.
This prevents the c8y-remote-access-plugin from an infinite loop if it is misconfigured or does not have the correct credentials to connect to the local MQTT broker.
https://github.com/thin-edge/thin-edge.io/issues/3660
> fix: add connection timeout when connecting to the local broker

- crates/extensions/c8y_mapper_ext/src/availability/actor.rs
- crates/extensions/c8y_mapper_ext/src/availability/builder.rs
- crates/extensions/c8y_mapper_ext/src/availability/mod.rs
- crates/extensions/c8y_mapper_ext/src/inventory.rs
* at_id field is no longer required for the registration messages incoming to the availability actor. Update the error message and the comment accordingly.
* Remove todo, which was not planed to do.
* Some refactoring code for the better readability.
<br/>
> refactor: cleanup code and outdated comments from the availability actor

- crates/common/certificate/src/lib.rs
- crates/common/certificate/src/parse_root_certificate/mod.rs
- crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
- crates/core/tedge/src/cli/certificate/c8y/download.rs
- crates/core/tedge/src/cli/certificate/c8y/mod.rs
- crates/core/tedge/src/cli/certificate/c8y/renew.rs
- crates/core/tedge/src/cli/certificate/cli.rs
- crates/core/tedge/src/cli/certificate/create.rs
- crates/core/tedge/src/cli/certificate/create_csr.rs
- crates/core/tedge/src/cli/connect/command.rs
- crates/core/tedge/src/main.rs
- crates/extensions/tedge-p11-server/src/pkcs11/mod.rs
- crates/extensions/tedge-p11-server/src/service.rs
- crates/extensions/tedge-p11-server/src/signer.rs
- tests/RobotFramework/tests/pkcs11/private_key_storage.robot
This PR introduces support for `tedge cert renew c8y` when the private key is located on the HSM.
To generate a CSR, one needs to put the public key in the CSR (it will become a part of the certificate (SPKI)) and to sign the certificate using the private key to prove the ownership of it. Because the public key can be derived from the private key, and because we need to sign anyway, until this PR we just read the private key to do both these things.
Now, with an HSM, we can't read the private key, so instead for CSR creation with HSM being enabled, we read the public key from the currently used certificate and sign using the `TedgeP11Client`.
It's also perhaps possible to derive the public key from the public attributes of the private key in the HSM (that's what [gnutls seems to be …
> feat: `tedge cert renew c8y` using HSM

- crates/extensions/tedge_mqtt_ext/src/trie.rs
Address clippy warnings which were introduced in https://github.com/thin-edge/thin-edge.io/pull/3661.
```
warning: single-character string constant used as pattern
--> crates/extensions/tedge_mqtt_ext/src/trie.rs:211:44
|
211 |         let mut other_segs = other.0.split('/');
|                                            ^^^ help: consider using a `char`: `'/'`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
warning: single-character string constant used as pattern
--> crates/extensions/tedge_mqtt_ext/src/trie.rs:309:39
|
309 |         match topic_suffix.split_once("/") {
|                                       ^^^ help: consider using a `char`: `'/'`
|
= help: for further information visit …
```
> chore: fix clippy warnings

- crates/extensions/c8y_mapper_ext/src/converter.rs
Fix a flaky system test caused by duplicate operations being executed by the mapper.
The reason why the existing de-duplication didn't work is that the operation had been completed locally before the operation notification was received for a second time from Cumulocity. Since the command was no longer "active", the mapper totally ignored the fact the operation has already been executed.
This PR adds a new `recently_completed_commands` store to the mapper, which stores the completed command IDs for ~1 hour to cope with this race condition where the Cumulocity operation status takes some time to update.
- #3721
> fix: continue to de-duplicate incoming operations once operation is complete

- .github/workflows/build-workflow.yml
- .github/workflows/pull-request-checks.yml
- .github/workflows/release.yml
Update the runner to use ubuntu-24.04 for a more modern OS version that seems to have less issues when cross compiling C libraries (required in upcoming tedge flows feature which needs to compile the quickjs C library).
[ubuntu-24.04](https://github.com/actions/runner-images/blob/ubuntu22/20250720.1/images/ubuntu/Ubuntu2404-Readme.md) does not include cargo-audit, so it needs to be explicitly installed (which is better anyway).
<br/>
> ci: update to ubuntu-24.04 runner

- .github/workflows/pull-request-checks.yml
`cargo-udeps` is failing with:
```
error[E0275]: overflow evaluating the requirement `{async fn body of try_exists<&std::path::Path>()}: std::marker::Send`
|
= help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`c8y_mapper_ext`)
note: required because it appears within the type `impl std::future::Future<Output = Result<bool, std::io::Error>>`
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.0/src/fs/try_exists.rs:25:1
|
25 | pub async fn try_exists(path: impl AsRef<Path>) -> io::Result<bool> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because it's used within this `async` fn body
--> /home/runner/work/thin-edge.io/thin-edge.io/crates/common/tedge_utils/sr …
```
> ci: workaround cargo-udeps failure

- configuration/contrib/diag-plugins/07_mosquitto.sh
- tests/RobotFramework/tests/tedge/diag/predefined_plugins.robot
To aid with diagnosing mosquitto configuration related issues, the following files/folders are now included:
* `/etc/mosquitto/mosquitto.conf`
* `/etc/mosquitto/conf.d/`
* `/etc/tedge/mosquitto-conf/`
Also if the `tree` command is available, a full directory listing of the `/etc/mosquitto` folder is also included.
<br/>
> feat: include mosquitto configuration in diagnostic collection

- crates/extensions/tedge_mqtt_bridge/src/lib.rs
- crates/extensions/tedge_mqtt_bridge/src/mqtt_logging.rs
Adds logging for the packets sent and received by the built-in bridge. It logs connection, subscription and ping related packets. It doesn't log publish or acknowledge packets as this would be very noisy.
- #3459
> feat: log incoming and outgoing packets in built-in bridge

- crates/common/tedge_config/src/tedge_toml/models/proxy_url.rs
Fix a bug  when using port 80 within the`proxy.address` setting.
The parsing issue was caused by how`Url::parse()` parses well known ports like `80`.
Below shows the bug which is now resolved by switching to using [.port_or_known_default()](https://docs.rs/reqwest/latest/reqwest/struct.Url.html#method.port_or_known_default) instead of [.port()](https://docs.rs/reqwest/latest/reqwest/struct.Url.html#method.port).
```
Error: failed to set the configuration key: 'proxy.address' with value: https://127.0.0.1:80.
Caused by:
0: Failed to parse input
1: Invalid proxy URL: 127.0.0.1:80 is missing a port
2: 127.0.0.1:80 is missing a port
```
https://github.com/thin-edge/thin-edge.io/issues/3803
> fix: proxy port parsing issue when using port 80
